### ISSUE TITLE
Reference different branch in local repository

### ISSUE THREAD

**Issue by mxey** [earthly/earthly#1005]
I have a repo where I use Earthly where I'd like to have access to the artifacts of another branch. I can use the fully qualified target reference `gitlab.example.com/my/repo:branch+target` which makes Earthly clone that repo. But since I already am in that repo, it would be faster to just say `./:branch+target` and have Earthly check out the branch from the local repo. That does not work though.

**Comment by vladaionescu** [comment]
You could use the [builtin arg](https://docs.earthly.dev/docs/earthfile/builtin-args) `EARTHLY_TARGET_PROJECT` to form something like this

```
ARG EARTHLY_TARGET_PROJECT
BUILD $EARTHLY_TARGET_PROJECT:branch+target
```

**Comment by mxey** [comment]
> You could use the builtin arg EARTHLY_TARGET_PROJECT to form something like this

Would this make Earthly clone locally or is just shorthand to avoid repeating the repository reference?

Using it gives me this error, however:

```
    ARG EARTHLY_TARGET_PROJECT
    COPY $EARTHLY_TARGET_PROJECT:production+fullcode/src /from
```

```
            internal | --> GIT CLONE git@gitlab.example.com:my/repo.git
            internal | WARN: (GIT CLONE git@gitlab.example.com:my/repo.git) subdir not supported yet
            internal | --> docker-image://docker.io/alpine/git:v2.30.1
Error: failed to load cache key: subdir not supported yet
```

**Comment by vladaionescu** [comment]
It would actually clone that branch locally, within the buildkit cache.

@alexcb - any idea where this is coming from?

```
            internal | WARN: (GIT CLONE git@gitlab.example.com:my/repo.git) subdir not supported yet
```

**Comment by alexcb** [comment]
That's coming from within buildkit itself, under https://github.com/moby/buildkit/blame/477b1aab89dae85d31a48797f341d6bd7527fa5a/source/gitidentifier.go#L46-L48

It looks like this is already on buildkit's radar: https://github.com/moby/buildkit/issues/1684

**Comment by vladaionescu** [comment]
We do support subdirs in our project references from the Earthly side - underneath we slice the URL up to form git clone URL + project subdir. This should have worked.

@mxey - to help narrow it down, can you also try to issue this on the command line to see if it works:

```
earthly <insert-git-reference-here>:production+fullcode
```

Perhaps the config for the git URL needs tweaking?

I assume that the URLs in the output were redacted (given the `example.com`'s)? Perhaps you can show us your Earthly config? It's ok to redact, but if you can, don't redact out any slashes in the URLs - the issue may be related to those.

It might also help if you can give the output of this in that target:

```
ARG EARTHLY_TARGET_PROJECT
RUN echo $EARTHLY_TARGET_PROJECT
```

(Again, it's ok to redact if you need to, but keep the slashes)

**Comment by mxey** [comment]
> @mxey - to help narrow it down, can you also try to issue this on the command line to see if it works:
> earthly <insert-git-reference-here>:production+fullcode

works fine:

```
$ earthly --verbose gitlab.rz.babiel.com/provid/puppet-control:production+fullcode
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
            internal | --> GIT CLONE git@gitlab.rz.babiel.com:provid/puppet-control.git
            internal | --> docker-image://docker.io/alpine/git:v2.30.1
            internal | [          ] resolve docker.io/alpine/git:v2.30.1 ... 0%
            internal | adabd05d7a010695bc47bf5e96002eb682af3c48 refs/heads/production
            internal | Completed in 2.365956895s
            internal | [██████████] resolve docker.io/alpine/git:v2.30.1 ... 100%
            internal | Completed in 2.671453491s
            internal | *cached* --> GET GIT META gitlab.rz.babiel.com/provid/puppet-control:production
            internal | Completed in 30.945µs
             context | --> git context gitlab.rz.babiel.com/provid/puppet-control:production+fullcode
             context | Completed in 29.077µs
            internal | Initialized empty Git repository in /tmp/earthly/buildkit/runc-overlayfs/snapshots/snapshots/811/fs/.git/
             ongoing | internal (24 seconds ago)
            internal | From /tmp/earthly/buildkit/runc-overlayfs/snapshots/snapshots/547/fs
            internal |  * [new tag]         production -> production
            internal |  * [new tag]         production -> production
             ongoing | internal (34 seconds ago)
            internal | Note: switching to 'FETCH_HEAD'.
[…]
```

> It might also help if you can give the output of this in that target:

> ARG EARTHLY_TARGET_PROJECT
> RUN echo $EARTHLY_TARGET_PROJECT

When I tried this, $EARTHLY_TARGET_PROJECT looked wrong to me, so I printed a whole bunch of those builtin args:

```
catalog-diff:
    FROM +ruby-deps
    ARG EARTHLY_TARGET 
    ARG EARTHLY_TARGET_PROJECT
    ARG EARTHLY_TARGET_NAME
    ARG EARTHLY_TARGET_TAG
    ARG EARTHLY_GIT_ORIGIN_URL
    RUN echo EARTHLY_TARGET=$EARTHLY_TARGET
    RUN echo EARTHLY_TARGET_PROJECT=$EARTHLY_TARGET_PROJECT   
    RUN echo EARTHLY_TARGET_NAME=$EARTHLY_TARGET_NAME
    RUN echo EARTHLY_TARGET_TAG=$EARTHLY_TARGET_TAG 
    RUN echo EARTHLY_GIT_ORIGIN_URL=$EARTHLY_GIT_ORIGIN_URL
```

(trimmed for clarity)
```
EARTHLY_TARGET=gitlab.rz.babiel.com/provid/puppet-control:mag-earthly-all-dev-tasks+catalog-diff
EARTHLY_TARGET_PROJECT=gitlab.rz.babiel.com/provid/puppet-control:mag-earthly-all-dev-tasks
EARTHLY_TARGET_NAME=catalog-diff
EARTHLY_TARGET_TAG=mag-earthly-all-dev-tasks
EARTHLY_GIT_ORIGIN_URL=https://gitlab.rz.babiel.com/provid/puppet-control.git
```

As I understand it, $EARTHLY_TARGET_PROJECT should *not* include the branch name like this.

My `~/.earthly/config.yml`:

```
git:
    github.com:
        auth: https
global:
  cache_size_mb: 50000
```

I have this in my ~/.gitconfig, but I disabled it and it did not change Earthly's behaviour:

```
[url "ssh://git@gitlab.rz.babiel.com"]
        insteadOf = https://gitlab.rz.babiel.com
```

**Comment by mxey** [comment]
I took a quick look at the source code and to me it seems like [the tag is appended here](https://github.com/earthly/earthly/blob/6726a4a8cd41eb2c89c717a262bbba847b28538a/domain/reference.go#L158) when it should not be

**Comment by vladaionescu** [comment]
> As I understand it, $EARTHLY_TARGET_PROJECT should not include the branch name like this.

Yeah, I think you're right - that's the issue. Let me look into this a bit more.

**Comment by vladaionescu** [comment]
Decided in the end to add a new builtin for the project without the tag (`EARTHLY_TARGET_PROJECT_NO_TAG `) in #1011 . I'll update the docs too.

**Comment by vladaionescu** [comment]
This has now been released in `v0.5.14`. Let me know if this works as expected!

**Comment by mxey** [comment]
@vladaionescu  This works:

```
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    COPY $EARTHLY_TARGET_PROJECT_NO_TAG:production+fullcode/src /from
```

I am still not clear on whether this clones from the local directory or if it clones from the remote Git server. Is there a way to see what Earthly does exactly? To me it looks like it clones from the remote Git server. Might this be caused by having `.git` in my .earthignore? I generally don't want to send it as context because it's quite huge in this repo - and if I did, I could just check out from that instead of using the `GIT CLONE` instruction.

**Comment by vladaionescu** [comment]
> I am still not clear on whether this clones from the local directory or if it clones from the remote Git server. 

It clones from the remote git server.

> Might this be caused by having .git in my .earthignore?

No, it should have nothing to do with that.

Hmm.. if you really want another branch from the local repo specifically, then I don't see any other option other than copying the `.git` dir itself and manipulating it.

There may be alternative things you could do via [LOCALLY](https://docs.earthly.dev/docs/earthfile#locally-experimental) - like switching the current active branch - but that would leave your working directory on a different branch than the one you started on, which I imagine is not something you want.

**Comment by chandraaditya** [comment]
@vladaionescu would a feature like this ever be possible? It would be really useful for automatically detecting breaking changes. 

We use buf.build breaking to detect breaking changes for our photo files and currently the best option seems like copying the entire .git folder into the container and running the test, but this is slowing down the builds a lot and so would be useful if there was a way to specify the branch to get an artefact from.
