### ISSUE TITLE
Add a changelog file

### ISSUE THREAD

**Issue by azizk** [earthly/earthly#1018]
Hi!

Could you please add a CHANGELOG.md and possibly a BACKLOG.md to understand what's been happening between releases?

Thanks for the awesome project and all the efforts!

**Comment by vladaionescu** [comment]
Hi @azizk - we have changelogs in the release descriptions: https://github.com/earthly/earthly/releases

Does that work?

**Comment by azizk** [comment]
Yes, that works! Didn't think to look there. :sweat_smile: I always look for the changelog file when I visit a project. I couldn't imagine that a popular project wouldn't have it. Anyway, feel free to close this issue if you don't plan to add one. :+1:

**Comment by vladaionescu** [comment]
Sounds good - I added it to point to the releases page.
