### ISSUE TITLE
Using GIT CLONE, fails when checking out sub modules with Host key verification failed

### ISSUE THREAD

**Issue by pmembrey** [earthly/earthly#1024]
Hi guys,

I've got a repository that pulls in its own dependencies using submodules. This is still with my touch to sign key and the initial clone works fine. However when it gets to the stage of pulling the submodules, although I do the touch to sign bit, they then fail with `Host key verification failed.`.

If I just clone locally on my machine, the submodules get pulled without problem.

The repos are being cloned from github using `ssh`.

Thanks!

**Comment by pmembrey** [comment]
Is there anything I can do to help with this? If someone could point me in the right direction, I wouldn't mind taking a stab at it :)

**Comment by vladaionescu** [comment]
I believe that this is where submodules are handled in buildkit's Git source implementation: https://github.com/earthly/buildkit/blob/earthly-main/source/git/gitsource.go#L522 . Not sure what could be causing the issue.

**Comment by alexcb** [comment]
I wrote a test using submodules (under https://github.com/earthly/earthly/pull/1175/commits/48085427a5b29d85a75436be85280e767acfd74c ), but it's passing and doesn't replicate this issue. I'll need to dig a bit deeper for this.

I then re-wrote the test to use two differen sshd instances (one on port 22, the other on port 2222), both using different ssh keys, but that isn't replicating the issue.

@pmembrey in your case is github the only server you are interacting with? are they both public repos? or both private? or a mix?

**Comment by pmembrey** [comment]
@alexcb It's only with github. The repo is protected by my yubikey (but I don't think that is relevant for this), and as part of the check out it then pulls the sub modules. I get prompted to touch the yubikey which auths the first checkout, but when it tries to get a sub module, before it gets to auth, it rejects the server as unknown. The key it's shown though is the one for github in the source.

Let me try it again tomorrow, maybe there was weird condition I got into. Let me sanity check and get back to you :)

**Comment by pmembrey** [comment]
@alexcb I've just spent the day trying to reproduce the issue and I haven't had any luck. The exact same repo that was failing before now seems to be working. I tried pruning and doing a fresh build and it still worked fine.

I think it's probably best to close this out unless I hit it again. It's possible it got fixed by something in buildkit.

Sorry for the wild goose chase! :/

**Comment by vladaionescu** [comment]
Sounds good, no worries! Feel free to reopen if you encounter it again.
