### ISSUE TITLE
Earthly Nix package is broken

### ISSUE THREAD

**Issue by NobbZ** [earthly/earthly#1025]
When I run `earthly -VD +all` I get the following output. It is not relevant whether or not an `Earthfile` in the current folder exists. The error is the same:

```text
           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
      buildkitd-pull | Pulling buildkitd image...
      buildkitd-pull | Error: docker pull : exit status 1. Attempting to start buildkitd anyway...
Error stack trace:
github.com/earthly/earthly/buildkitd.Start
        github.com/earthly/earthly/buildkitd/buildkitd.go:295
github.com/earthly/earthly/buildkitd.MaybeStart
        github.com/earthly/earthly/buildkitd/buildkitd.go:135
github.com/earthly/earthly/buildkitd.NewClient
        github.com/earthly/earthly/buildkitd/buildkitd.go:62
main.(*earthlyApp).actionBuildImp
        github.com/earthly/earthly/cmd/earthly/main.go:2312
main.(*earthlyApp).actionBuild
        github.com/earthly/earthly/cmd/earthly/main.go:2245
github.com/urfave/cli/v2.(*App).RunContext
        github.com/urfave/cli/v2@v2.3.0/app.go:322
main.(*earthlyApp).run
        github.com/earthly/earthly/cmd/earthly/main.go:1202
main.main
        github.com/earthly/earthly/cmd/earthly/main.go:227
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
Error: build new buildkitd client: maybe start buildkitd: start: docker run : docker: invalid reference format.
See 'docker run --help'.
: exit status 125
Warning: timedout while sending analytics
```

```
$ earthly --version  # I think there is something wrong with my OS package, its build from https://github.com/NixOS/nixpkgs/blob/11f5b3279dffefb9c57cababe2e5cb627906b024/pkgs/development/tools/earthly/default.nix, so probably 0.5.13
earthly version - linux/amd64
$ docker version
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.15.10
 Git commit:        v19.03.12
 Built:             Tue May 25 02:11:37 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.10
  Git commit:       v19.03.12
  Built:            Tue Jan  1 00:00:00 1980
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="20.09.20210526.05f3800 (Nightingale)"
VERSION_CODENAME=nightingale
VERSION_ID="20.09.20210526.05f3800"
PRETTY_NAME="NixOS 20.09 (Nightingale)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"

```

**Comment by vladaionescu** [comment]
The OS package is definitely the issue here. In order to figure out what buildkit image to use, Earthly uses its own version by default. To override the buildkit image it uses you can try

```
earthly --buildkit-image=earthly/buildkitd:v0.5.13 +all
```

Let me know if that fixes the issue for you temporarily.

In parallel, I'll get in touch with the Nix package maintainers and figure out a way to fix the Nix package as it's missing some key build parameters: https://github.com/earthly/earthly/blob/main/Earthfile#L193

**Comment by vladaionescu** [comment]
I've written an email to @Mdsp9070. Copying here as well for reference:

> Hi Matheus,
> 
> I noticed that you added a Nix package for Earthly. Thank you for that!
> 
> A user of ours noticed that it doesn't work well and I think it's due to missing some key `go build` arguments such as `-X main.DefaultBuildkitdImage=...`. This user opened this issue in Earthly: https://github.com/earthly/earthly/issues/1025
> 
> To fix that, the `go build` command would need the following build tags: https://github.com/earthly/earthly/blob/main/Earthfile#L189 and the following ldflags: https://github.com/earthly/earthly/blob/main/Earthfile#L193. You would have to expand the variables though.
> 
> If you wanted to get those tags and ldflags from the Earthly build itself, you could also do
> 
> ```
> ❯ earthly --artifact 'github.com/earthly/earthly:v0.5.13+earthly/*' ./build-earthly/
> ...
> 
> ❯ cat build-earthly/ldflags
> -X main.DefaultBuildkitdImage=earthly/buildkitd:v0.5.13 -X main.Version=v0.5.13 -X main.GitSha=a7f082f8fade1badbee0a221c9a9da2317449e4c -linkmode external -extldflags -static
> 
> ❯ cat build-earthly/tags
> dfrunmount dfrunsecurity dfsecrets dfssh dfrunnetwork
> ```
> 
> Is that something you would be able to adjust in the Nix definition?
> 
> Cheers,
> Vlad.

**Comment by NobbZ** [comment]
Thank for your respone, passing the buildkit image via flag indeed works as a workaround.

I have opened a ticket on the nixos repository as well to track it there and rise awareness.

Adding some buildflags is usually a trivial change and if I had the time I'd do it myself even :D

**Comment by vladaionescu** [comment]
Seems that this is being addressed in https://github.com/NixOS/nixpkgs/pull/125530

**Comment by NobbZ** [comment]
Yes, it is. And with the final version of the PR I can indeed use `earthly` locally. Thank you for the pointers.

I will close this ticket now, as the problem is not `earthly`s fault.
