### ISSUE TITLE
log files being transfered via buildkit when running under verbose

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1030]
To help see why the transferring-files-from-localhost-into-buildkit operations could be taking so long, it would be useful to log what files are being copied and their filesizes.

**Comment by vladaionescu** [comment]
Maybe also list when something is skipped because it's on the ignore list, if possible

(to show that ignoring works)

**Comment by jazzdan** [comment]
Yeah now context transferring is my biggest timesink on my docker image builds, I'd love to be able to figure out where that time is going 🙏

**Comment by alexcb** [comment]
This was implemented in https://github.com/earthly/earthly/pull/1051
