### ISSUE TITLE
Be able to disable analytics with an environment variable

### ISSUE THREAD

**Issue by pmembrey** [earthly/earthly#1048]
Although I greatly appreciate the openness and clarity of the analytics that are getting reported and that there is a way to disable them, it would be great if this could be supported as a simple environment variable.

For example, I have a lot of projects that I am totally fine with sharing analytics for, and for some things we're looking to Open Source, I think it would only be fair to give back by sharing that information. That said, I have some projects where it is not appropriate for me to report that information (such as  certain corporate projects) despite the measures you have taken to anonymise the data.

If I could just add a special environment flag to the corporate CI, then all the builds that happen there will no longer report, but all the builds I do locally will still report metrics.

Given that there is already a config option for this (thank you for doing that!), I don't think adding it as an environmental variable would hurt, and would instead just highlight your commitment to transparency.

**Comment by vladaionescu** [comment]
Sounds good - another thing you can do until we support this could be

```bash
earthly config global.disable_analtyics true
```

In case that is easier for you to do in CI, for now.

**Comment by alexcb** [comment]
I opened up a PR for this under https://github.com/earthly/earthly/pull/1068

**Comment by alexcb** [comment]
This can now be done with:

    export EARTHLY_DISABLE_ANALYTICS=1
