### ISSUE TITLE
LOCALLY RUN documentation

### ISSUE THREAD

**Issue by idelvall** [earthly/earthly#1081]
Hi, after reading the docs,  it was not clear to me that `LOCALLY RUN` statements need to be split into different lines in order to take effect. Adding an example like this:
```
  ...
  LOCALLY
  RUN rm -rf ./build
  ...
```
in https://docs.earthly.dev/docs/earthfile#locally-experimental would make things easier.

**Comment by idelvall** [comment]
It would be nice also that 
`LOCALLY RUN rm -rf ./build` either is not a no-op (like it is right now), or the parser gives an error

**Comment by alexcb** [comment]
Thanks for the feedback @idelvall , I've expanded the description and created an example under https://github.com/earthly/earthly/pull/1082

**Comment by idelvall** [comment]
You are welcome. Another that was not expected to me was that this keyword, affects all the commands after it, and not only the following one
