### ISSUE TITLE
Brew depreciated warning

### ISSUE THREAD

**Issue by jndz2** [earthly/earthly#1094]
I get this warning during installation.

`Warning: earthly has been deprecated because it has an incompatible license!`

**Comment by alexcb** [comment]
We have been [forced to move out ](https://github.com/Homebrew/homebrew-core/pull/80842)of homebrew-core, and into our own [homebrew tap](https://github.com/earthly/homebrew-earthly). You can install the latest version with:

    brew install earthly/earthly/earthly

We will be updating our documentation this week.
