### ISSUE TITLE
Cannot seem to successfully use the exec form of RUN

### ISSUE THREAD

**Issue by rdw20170120** [earthly/earthly#1097]
I am adopting Earthly as my build tool.  I have written a simple Earthfile to create my own variant of an Ubuntu base image.  But I am consistently having trouble with `RUN`.  The shell form of `RUN` uses `/bin/sh` as documented and expected.  When I attempt to use the exec form of `RUN`, I still get `/bin/sh` even when I go to a lot of trouble to use `/bin/bash` instead.  I have searched and searched, but I find VERY FEW examples of using the exec form.  None of the examples have worked for me.  ALL of my `RUN` commands result is calling `/bin/sh`, which is defeating my attempts to use some features of Bash.  I have been certain that it was me that was messing it up, but now I am wondering.  Maybe it is as simple as a little documentation to cover it.
[Archive.zip](https://github.com/earthly/earthly/files/6805474/Archive.zip)

**Comment by agbell** [comment]
Hi @rdw20170120 ,
You are right that the exec form of Earthly is not very commonly used.  Perhaps we have a regression in its use. We will investigate this.

**Comment by agbell** [comment]
Looks like the exec form may indeed have a problem. Thanks for catching this!

 In the meantime putting `#!/bin/bash` in your bash scripts and using a standard run may be a simpler approach to your build.

**Comment by rdw20170120** [comment]
@agbell, thank you for taking a look at this.

I have converted all of my `RUN` commands to shell form.  In most of my cases, I have intentionally refactored my tasks into separate scripts.  For those, I invoke `RUN /bin/bash -c "SCRIPT ARG..."`.  I think that is getting me close enough for now.

I have already placed `#!/bin/bash` in my scripts, but they do not work in this use case.  Since the shell form of `RUN` invokes `/bin/sh`, that is the shell that executes them and the shebang is ignored.  The shebang is ONLY invoked when directly executing, as the exec form of `RUN` should do.

It occurs to me that I could perhaps work around this issue further by adding my own wrapper script.  I could have `RUN` invoke my wrapper script, which it will execute using `/bin/sh`.  I could pass my real script and its arguments to that wrapper.  That wrapper could then properly execute `/bin/bash` and ask it to execute my real script with its arguments.  Actually, it should just `exec` the real script which will allow the Linux execution engine to do its shebang magic.  If I encounter more issues, then I may resort to that.  I am hoping that this will be fixed sooner than that.

I have been doing a LOT of research into Docker best practices, and prominent among them is to ALWAYS use the exec forms of `RUN`, `CMD`, and `ENTRYPOINT`.  Yet my research also reveals almost NO examples of anyone doing that with `RUN`.  I am certain that is largely due to the near-impossibility of searching for statements in exec form versus shell form (because the difference is punctuation that you cannot search).  However, I believe that it is also real since even the examples from those recommending the best practice likewise fail to use the exec form!

I am hoping to change that by providing a **_production-ready_** complete implementation of various example implementations in a self-contained monorepo.

Thank you all here at Earthly for providing me with a tool worthy to build that upon!

Rob

**Comment by alexcb** [comment]
Hi @rdw20170120 

To expand on Adam's suggestion, would it be possible to setup your earthfile like this?

```
mytarget:
    FROM ubuntu:latest
    COPY myscript .
    RUN chmod +x myscript
    RUN ./myscript
```

Then consider `myscript`:

```
#!/bin/bash
echo "I am running under $SHELL"
```

When I run this with `earthly +mytarget`, I get:

```
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
       ubuntu:latest | --> Load metadata linux/amd64
             context | --> local context .
           +mytarget | --> FROM ubuntu:latest
           +mytarget | [██████████] resolve docker.io/library/ubuntu:latest@sha256:aba80b77e27148d99c034a987e7da3a287ed455390352663418c0f2ed40417fe ... 100%
             context | transferred 1 file(s) for context . (77 B, 1 file/dir stats)
           +mytarget | --> COPY myscript .
           +mytarget | --> RUN chmod +x myscript
           +mytarget | --> RUN ./myscript
           +mytarget | I am running under /bin/bash             <--------- bash is being used here
              output | --> exporting outputs
```

which shows that the script is being interupted by bash.

You're correct in noticing that behind the scenes it's wrapped by `/bin/sh -c ./myscript`; however the `sh` shell should detect the `#!/bin/bash` and execute it via bash.

Let us know if this helps,

Cheers,
Alex

**Comment by rdw20170120** [comment]
@alexcb,

Thank you for your insights.  I agree with you, but I am not getting that behavior.  Allow me please to provide some details (elided for brevity).

In my `Earthfile` I have:
```
FROM ubuntu:focal-20210609

ENV BO_ImgUserNonRoot=appuser
ENV BO_ImgDirWork=/workdir
ENV BO_ImgDirOut=/tmp/out

inject:
    FROM +base

    WORKDIR ${BO_ImgDirWork}

    # Inject my Bash scripts
    COPY . .
    RUN chmod --verbose a+rx *

    RUN ./execute_inject_as_root_user

    RUN ./capture_snapshot_as_root_user inject
    SAVE ARTIFACT ${BO_ImgDirOut}/inject AS LOCAL ./out/inject
```

Script `execute_inject_as_root_user` has this:
```
#/bin/bash
set -eux

main() {
    echo "Executing '$0' in directory '${PWD}'"

    [[ $(whoami) != "root" ]] && echo "MUST execute as 'root'" && exit 99

    # Create non-root user
    useradd --system --uid 5000 --user-group ${BO_ImgUserNonRoot}
    id ${BO_ImgUserNonRoot}
    groups ${BO_ImgUserNonRoot}

    # Create output directory
    mkdir --parents --verbose ${BO_ImgDirOut}
    chown --verbose ${BO_ImgUserNonRoot}:${BO_ImgUserNonRoot} ${BO_ImgDirOut}
    chmod --verbose a+rwx ${BO_ImgDirOut}

    return 0
}

main $@
```

Script `capture_snapshot_as_root_user` has this:
```
#/bin/bash
set -eux

main() {
    local _Tgt=$1

    echo "Executing '$0' in directory '${PWD}'"

    echo "SHELL is '${SHELL}'" >${_Dir}/SHELL.out
    ${SHELL} --version >>${_Dir}/SHELL.out

    [[ $(whoami) != "root" ]] && echo "MUST execute as 'root'" && exit 99

    local _Dir=${BO_ImgDirOut}/${_Tgt}
    mkdir --parents --verbose ${_Dir}

    env | sort >${_Dir}/ENV.out
    ls -Al / >${_Dir}/ls-ROOT.out

    [[ -n "${BO_ImgDirOut}" ]] && ls -AlR ${BO_ImgDirOut} >${_Dir}/ls-BO_ImgDirOut.out
    [[ -n "${BO_ImgDirWork}" ]] && ls -AlR ${BO_ImgDirWork} >${_Dir}/ls-BO_ImgDirWork.out

    return 0
}

main $@
```

When I build this with `earthly`, I get this output:
```
rob@Heka:~/repo/GitLab/WIP/private-mono/g0/image/Ubuntu/base$ earthly --no-cache +inject
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
ubuntu:focal-20210609 | --> Load metadata linux/amd64
               +base | --> FROM ubuntu:focal-20210609
             context | --> local context .
               +base | [          ] resolve docker.io/library/ubuntu:focal-20210609@sha256:aba80b77e27148d99c034a987e7da3a2[██████████] resolve docker.io/library/ubuntu:focal-20210609@sha256:aba80b77e27148d99c034a987e7da3a287ed455390352663418c0f2ed40417fe ... 100%
             context | transferred 8 file(s) for context . (6.9 kB, 8 file/dir stats)
               +base | [▎         ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 3%         [█         ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 11%        [███       ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 29%        [████▍     ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 44%        [██████▏   ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 62%        [███████▊  ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 77%        [█████████ ] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 91%        [██████████] sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 100%
               +base | [          ] extracting sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... [██████████] extracting sha256:c549ccf8d472c3bce9ce02e49c62b8f6cbc736ea2b8ba812a1ae9390c69d0b71 ... 100%
             +inject | --> WORKDIR /workdir
             +inject | --> COPY . .
             +inject | --> RUN chmod --verbose a+rx *
             +inject | mode of 'capture_snapshot_as_root_user' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'earthly.out' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'entrypoint' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'execute_build_as_nonroot_user' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'execute_build_as_root_user' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'execute_inject_as_root_user' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'execute_install_as_root_user' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | mode of 'install_Ubuntu_packages' changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
             +inject | --> RUN ./execute_inject_as_root_user
             +inject | + main
             +inject | + echo Executing './execute_inject_as_root_user' in directory '/workdir'
             +inject | Executing './execute_inject_as_root_user' in directory '/workdir'
             +inject | + whoami
             +inject | + [[ root != root ]]
             +inject | ./execute_inject_as_root_user: 11: [[: not found
             +inject | + useradd --system --uid 5000 --user-group appuser
             +inject | + id appuser
             +inject | uid=5000(appuser) gid=999(appuser) groups=999(appuser)
             +inject | + groups appuser
             +inject | appuser : appuser
             +inject | + mkdir --parents --verbose /tmp/out
             +inject | mkdir: created directory '/tmp/out'
             +inject | + chown --verbose appuser:appuser /tmp/out
             +inject | changed ownership of '/tmp/out' from root:root to appuser:appuser
             +inject | + chmod --verbose a+rwx /tmp/out
             +inject | mode of '/tmp/out' changed from 0755 (rwxr-xr-x) to 0777 (rwxrwxrwx)
             +inject | + [[ -z  ]]
             +inject | ./execute_inject_as_root_user: 24: [[: not found
             +inject | + [[ -z  ]]
             +inject | ./execute_inject_as_root_user: 25: [[: not found
             +inject | + [[ -z main ]]
             +inject | ./execute_inject_as_root_user: 26: [[: not found
             +inject | + [[ -z 6e1c804844c584573c582340de9a448a62dde533 ]]
             +inject | ./execute_inject_as_root_user: 27: [[: not found
             +inject | + [[ -z MeAtGitLab/refactorytechllc/private-mono/g0/image/Ubuntu/base ]]
             +inject | ./execute_inject_as_root_user: 28: [[: not found
             +inject | + [[ -z MeAtGitLab:refactorytechllc/private-mono.git ]]
             +inject | ./execute_inject_as_root_user: 29: [[: not found
             +inject | + [[ -z -main-6e1c804844c584573c582340de9a448a62dde533 ]]
             +inject | ./execute_inject_as_root_user: 30: [[: not found
             +inject | + return 0
             +inject | + :
             +inject | --> RUN ./capture_snapshot_as_root_user inject
             +inject | Executing './capture_snapshot_as_root_user' in directory '/workdir'
             +inject | + main inject
             +inject | + local _Tgt=inject
             +inject | + echo Executing './capture_snapshot_as_root_user' in directory '/workdir'
             +inject | ./capture_snapshot_as_root_user: 13: SHELL: parameter not set
             +inject | Command /bin/sh -c './capture_snapshot_as_root_user inject' failed with exit code 2
             +inject |
             +inject | ERROR: Command exited with non-zero code: RUN ./capture_snapshot_as_root_user inject
Repeating the output of the command that caused the failure
================================ FAILURE [main] ================================
             +inject *failed* | --> RUN ./capture_snapshot_as_root_user inject
             +inject *failed* | Executing './capture_snapshot_as_root_user' in directory '/workdir'
             +inject *failed* | + main inject
             +inject *failed* | + local _Tgt=inject
             +inject *failed* | + echo Executing './capture_snapshot_as_root_user' in directory '/workdir'
             +inject *failed* | ./capture_snapshot_as_root_user: 13: SHELL: parameter not set
             +inject *failed* | Command /bin/sh -c './capture_snapshot_as_root_user inject' failed with exit code 2
             +inject *failed* |              +inject *failed* | ERROR: Command exited with non-zero code: RUN ./capture_snapshot_as_root_user inject
Error: bkClient.Build: failed to solve: executor failed running [/bin/sh -c BO_DateRelease='' BO_DockerRepository='' BO_GitBranch=main BO_GitCommitHash=6e1c804844c584573c582340de9a448a62dde533 BO_GitSourcePath=MeAtGitLab/refactorytechllc/private-mono/g0/image/Ubuntu/base BO_GitUrl=MeAtGitLab:refactorytechllc/private-mono.git BO_ImgDirOut=/tmp/out BO_ImgDirWork=/workdir BO_ImgUserNonRoot=appuser BO_Release=-main-6e1c804844c584573c582340de9a448a62dde533 EARTHLY_GIT_HASH=6e1c804844c584573c582340de9a448a62dde533 EARTHLY_GIT_ORIGIN_URL=MeAtGitLab:refactorytechllc/private-mono.git EARTHLY_TARGET_PROJECT_NO_TAG=MeAtGitLab/refactorytechllc/private-mono/g0/image/Ubuntu/base EARTHLY_TARGET_TAG=main PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c './capture_snapshot_as_root_user inject']: exit code: 2
```

I think that I am following your suggestions here.  I have the proper shebangs.  My `RUN` statements are similar.  I am even running the same version of Ubuntu as you did.

But please notice the different behavior.  First we see ` ./execute_inject_as_root_user: 11: [[: not found` as well as repeats.  As you probably know, `[[` is a Bashism unknown to the Bourne shell.  We also see `./capture_snapshot_as_root_user: 13: SHELL: parameter not set`, which seems to further indicate that it is the Bourne shell rather than Bash that is executing.  A further symptom (not shown here) is that I previously had `set -euxo pipefail` and the Bourne shell would barf on the `pipefail` option.  I am forced to conclude that I am getting the Bourne shell, and it is failing to honor the shebang.  These scripts work as expected when I use the `RUN /bin/bash -c "SCRIPT ARG..."` syntax instead.

Of course, all of this helps illustrate the motivation for the best practice of avoid Bash for such work.  That is part of where I am heading, but I am not there yet.

So it seems that there is a bit more of something amiss here.  I am unclear what, though.  What do you think?

**Comment by rdw20170120** [comment]
Here is a discussion of the issue:  https://unix.stackexchange.com/questions/87560/does-the-shebang-determine-the-shell-which-runs-the-script

**Comment by rdw20170120** [comment]
By the way, when I use the troubleshooting advice in that article:
```
RUN readlink /proc/$$/exe
```
it then tells me:
```
/usr/bin/dash
```
I get the same result by executing that command in my script.

**Comment by MBH69** [comment]
Bugg

**Comment by rdw20170120** [comment]
By the way, in the Ubuntu image Bash is `/usr/bin/bash`.

**Comment by alexcb** [comment]
Your examples appear to be missing the `!` in your interpreter directive (`#/bin/bash`).

does changing it to `#!/bin/bash` fix the problem?

**Comment by rdw20170120** [comment]
Well, don't I have egg on my face!  Good catch, @alexcb!  Sorry for the trouble.  That did indeed fix it, and allowed me to make my code a bit cleaner.

As I mentioned above, the correct interpreter for the Ubuntu image is `/usr/bin/bash`.  So, now my scripts start with:
```
#!/usr/bin/bash
```
and my `Earthfile` now contains lines to execute those scripts that look like:
```
RUN ./script arg...
```
Thank you so much for catching this; apparently I needed a second pair of eyes.  I will have to figure out how to write a test to catch those.

This makes sense too.  When Earthly executes `RUN ./script arg...`, it translates it to `/bin/sh -c "./script arg..."`.  The `-c "..."` means that it will execute as a command, which means that it will get run through the Linux machinery that will interpret the shebang (unless the dumb programmer messes the shebang up!).  If we left off the `-c "..."`, then we have `/bin/sh ./script arg...` and the shell would execute the script directly *without* invoking the Linux machinery to interpret the shebang.  I got too close to it and confused myself, to the point of missing this crucial nuance.

I look forward to when you will have the exec form of `RUN` for me!  And I am going to start using a lot of `!`s everywhere, just in case.

**Comment by alexcb** [comment]
It's all good; thanks for pointing out that the exec form is broken (and has been for quite some time); let's leave this issue open until we have a fix in place for that.
