### ISSUE TITLE
enable git verbose mode when running earthly under verbose

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1102]
We had a case where a user was experiencing networking problems when performing a remote earthly build; however earthly only ever showed `Error: build target: build main: bkClient.Build: failed to solve: failed to load cache key: failed to fetch remote https://gitlab.com/alexcb/hello.git: exit status 128`

Upon further investigation it turned out that gitlab.com could not be reached from within the docker container:

```
$ docker run -it --entrypoint=sh  earthly/buildkitd:v0.5.18 
/ # ping gitlab.com
ping: bad address 'gitlab.com'
```

It would have saved a lot of debugging time if this message (or something similar) was bubbled up from git rather than the generic exit status 128 error.

**Comment by vladaionescu** [comment]
I believe that the way it is set is that a failure automatically makes the failing step verbose (e.g. an internal operation is not printed unless it fails). But within that failing step it seems that git isn't saying much. So really we could make git be verbose all the time, since usually the git step is anyway tucked away in an internal operation and its (verbose) output would be hidden by default.

**Comment by vladaionescu** [comment]
Remember to scrub credentials from the output when implementing this.

**Comment by alexcb** [comment]
>  believe that the way it is set is that a failure automatically makes the failing step verbose (e.g. an internal operation is not printed unless it fails)

here's an example of what we currently already have:

consider running `./earthly -V git.example.com/user/repo:main+foo`, this will display:

```
            internal | --> GIT CLONE https://git.example.com/user/repo.git
            internal | --> docker-image://docker.io/alpine/git:v2.30.1
            internal | [          ] resolve docker.io/alpine/git:v2.30.1 ... 0%
            internal | hint: Using 'master' as the name for the initial branch. This default branch name
            internal | hint: is subject to change. To configure the initial branch name to use in all
            internal | hint: of your new repositories, which will suppress this warning, call:
            internal | hint: 
            internal | hint: 	git config --global init.defaultBranch <name>
            internal | hint: 
            internal | hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
            internal | hint: 'development'. The just-created branch can be renamed via this command:
            internal | hint: 
            internal | hint: 	git branch -m <name>
            internal | Initialized empty Git repository in /tmp/earthly/buildkit/runc-overlayfs/snapshots/snapshots/7114/fs/
            internal | fatal: unable to access 'https://git.example.com/user/repo.git/': Could not resolve host: git.example.com
            internal | WARN: (GIT CLONE https://git.example.com/user/repo.git) failed to fetch remote https://git.example.com/user/repo.git: exit status 128
            internal | Completed in 114.426005ms
            internal | [██████████] resolve docker.io/alpine/git:v2.30.1 ... 100%
            internal | WARN: Canceled
            internal | Completed in 114.984399ms
```

which includes `fatal: unable to access 'https://git.example.com/user/repo.git/': Could not resolve host: git.example.com`. I think that's enough information to figure out what's the issue. Perhaps this wasn't the case when I initially opened this issue?
