### ISSUE TITLE
interactive debugger should not run (or display errors) when running in non-interactive session

### ISSUE THREAD

**Issue by jclangst** [earthly/earthly#1108]
Version: v0.5.18

In our CI environments, the Docker daemon exists on a separate host and we communicate over TCP. In this type of setup, every earthly command generates the following error message; however, functionality is NOT impaired.

`internal-term | Failed to connect to terminal: dial tcp 127.0.0.1:8373: connect: connection refused`

**Comment by alexcb** [comment]
Thanks for the report; it appears that any interactive RUN commands (or the interactive debugger) won't work with a non-local docker daemon. Fortunately in the context of CI there won't be an interactive commands which won't affect your use-case.

It's definitely something we'll want to fix, but it might be a lower priority.
