### ISSUE TITLE
Add shared cache option

### ISSUE THREAD

**Issue by xificurC** [earthly/earthly#1129]
Here's an updated proposal:

CACHE --id=my-shared-cache /target
RUN --mount type=cache,id=my-shared-cache,target=/target ...
The idea is that as long as the id matches, the cache would be shared across targets, regardless of where those targets exist: same Earthfile, or different Earthfile, completely different builds, etc. So presumably, even completely different projects could reuse the same cache mount.

---- original request below ----

real world use case: building a maven project. I want to reuse a .m2 cache in subsequent runs and across different images. This shouldn't break anything really and speed up my builds significantly. A `-v` flag like docker build has would do the trick, or any similar solution

**Comment by vladaionescu** [comment]
This could be problematic for two reasons:
- The cache might grow indefinitely and it's up to the user to GC it regularly
- It can be a source of inconsistency

In addition, the implementation ideally should not be based on mounting a local directory, because it would not have a good equivalent with the future remote Earthly capabilities.

That said, there are some relevant use-cases for this to help with speeding up builds and it has been requested a few times.

**Comment by xificurC** [comment]
Thanks for a quick response.

Running `mvn package` or any other maven command on a desktop reuses the `.m2` cache, for every project. If I put these projects in an `Earthfile`, I can't reproduce this behavior. Is that correct? If yes, this is a blocker for us right now.

> The cache might grow indefinitely and it's up to the user to GC it regularly

True, but isn't the problem the same with earthly caches? And since they aren't shared by default I can see it cluttering up the disk faster and making it harder to find the culprits, since they are spread across multiple project builds. Here I just have 1 `.m2` folder that in the direst case I can wipe out completely and let it refill only the necessary dependencies on the first run of each project.

> It can be a source of inconsistency

In the general case, yes.

> the implementation ideally should not be based on mounting a local directory, because it would not have a good equivalent with the future remote Earthly capabilities

Since I don't know what you mean I can't comment.

**Comment by vladaionescu** [comment]
We've put together a proposal that might address the need for this.

https://github.com/earthly/earthly/issues/1399

Please leave feedback and/or 👍  over there if it serves your needs. Also, I'm curious about specific use-cases where it might not and sharing an actual cache between targets is strictly needed.

**Comment by vladaionescu** [comment]
Some details above are a bit out of date. Here's an updated proposal:

```
CACHE --id=my-shared-cache /target
RUN --mount type=cache,id=my-shared-cache,target=/target ...
```

The idea is that as long as the `id` matches, the cache would be shared across targets, regardless of where those targets exist: same Earthfile, or different Earthfile, completely different builds, etc. So presumably, even completely different projects could reuse the same cache mount.

**Comment by vladaionescu** [comment]
This is now released as experimental in Earthly v0.7.20. You can enable this feature via `VERSION --global-cache 0.7` in your Earthfile.

**Comment by alexcb** [comment]
Just to note, if two targets use the same cache, they can not run concurrently, here's an example that shows this:

```
VERSION --global-cache 0.7

start:
  FROM alpine
  CACHE --id=cacheid /cache
  RUN echo initial-data > /cache/data

a:
  FROM alpine
  CACHE --id=cacheid /cache
  RUN set -x && echo "a start" >> /cache/data && sleep 10 && echo "a end" >> /cache/data && sleep 5 && cat /cache/data && echo "a has ended"

b:
  FROM alpine
  CACHE --id=cacheid /cache
  RUN set -x && echo "b start" >> /cache/data && sleep 10 && echo "b end" >> /cache/data && sleep 5 && cat /cache/data && echo "b has ended"

test:
  WAIT
    BUILD +start
  END
  BUILD +a
  BUILD +b
```

and the output:

```
$ earthly-v0.7.21 prune --reset && earthly-v0.7.21 +test
           buildkitd | Restarting buildkit daemon with reset command...
           buildkitd | ... Done
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

Streaming logs to https://cloud.earthly.dev/builds/d91e0708-94db-4586-9d2d-55654cdd1412

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata alpine linux/amd64
              +start | --> FROM alpine
              +start | [----------] 100% FROM alpine
              +start | --> RUN echo initial-data > /cache/data
                  +a | --> RUN set -x && echo "a start" >> /cache/data && sleep 10 && echo "a end" >> /cache/data && sleep 5 && cat /cache/data && echo "a has ended"
                  +b | --> RUN set -x && echo "b start" >> /cache/data && sleep 10 && echo "b end" >> /cache/data && sleep 5 && cat /cache/data && echo "b has ended"
                  +a | + echo 'a start'
                  +a | + sleep 10
                  +a | + echo 'a end'
                  +a | + sleep 5
                  +a | + cat /cache/data
                  +a | initial-data
                  +a | a start
                  +a | a end
                  +a | + echo 'a has ended'
                  +a | a has ended
                  +b | + echo 'b start'
                  +b | + sleep 10
                  +b | + echo 'b end'
                  +b | + sleep 5
                  +b | + cat /cache/data
                  +b | initial-data
                  +b | a start
                  +b | a end
                  +b | b start
                  +b | b end
                  +b | + echo 'b has ended'
                  +b | b has ended
              output | --> exporting outputs
```

**Comment by idelvall** [comment]
You missed that `--sharing=locked` is the default

```earthly
VERSION --global-cache 0.7

start:
  FROM alpine
  CACHE --sharing=shared --id=cacheid /cache
  RUN echo initial-data > /cache/data

a:
  FROM alpine
  CACHE --sharing=shared --id=cacheid /cache
  RUN set -x && echo "a start" >> /cache/data && sleep 10 && echo "a end" >> /cache/data && sleep 5 && cat /cache/data && echo "a has ended"

b:
  FROM alpine
  CACHE  --sharing=shared --id=cacheid /cache
  RUN set -x && echo "b start" >> /cache/data && sleep 10 && echo "b end" >> /cache/data && sleep 5 && cat /cache/data && echo "b has ended"

test:
  WAIT
    BUILD +start
  END
  BUILD +a
  BUILD +b
```
```
 earthly +test
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

Streaming logs to https://cloud.earthly.dev/builds/5050ee30-6088-48ed-a9e7-476813833b86

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata alpine linux/amd64
              +start | --> FROM alpine
              +start | [----------] 100% FROM alpine
              +start | --> RUN echo initial-data > /cache/data
                  +a | --> RUN set -x && echo "a start" >> /cache/data && sleep 10 && echo "a end" >> /cache/data && sleep 5 && cat /cache/data && echo "a has ended"
                  +b | --> RUN set -x && echo "b start" >> /cache/data && sleep 10 && echo "b end" >> /cache/data && sleep 5 && cat /cache/data && echo "b has ended"
                  +a | + echo 'a start'
                  +a | + sleep 10
                  +b | + echo 'b start'
                  +b | + sleep 10
                  +a | + echo 'a end'
                  +a | + sleep 5
                  +b | + echo 'b end'
                  +b | + sleep 5
                  +a | + cat /cache/data
                  +a | + echo 'a has ended'
                  +a | initial-data
                  +a | a start
                  +a | b start
                  +a | a end
                  +a | b end
                  +a | a has ended
                  +b | + cat /cache/data
                  +b | initial-data
                  +b | a start
                  +b | b start
                  +b | a end
                  +b | b end
                  +b | b has ended
                  +b | + echo 'b has ended'
              output | --> exporting outputs

 Push Summary ⏫ (disabled)
————————————————————————————————————————————————————————————————————————————————

To enable pushing use earthly --push

 Local Output Summary 🎁
————————————————————————————————————————————————————————————————————————————————



========================== 🌍 Earthly Build  ✅ SUCCESS ==========================

```
