### ISSUE TITLE
Add builtin arg for git timestamp and short hashes as a foundation to support reproducible builds

### ISSUE THREAD

**Issue by pmembrey** [earthly/earthly#1134]
Reproducible builds are a powerful tool in detecting a compromise in a build chain. Earthly already provides repeatable builds, making it perfect for supporting reproducible builds. A reproducible build is one where the artifacts are bit for bit identical when built on different machines / platforms.

More details about the project can be found here:

https://reproducible-builds.org/docs/source-date-epoch/

To make builds reproducible, we need to clamp the timestamp to a given value. This ensures filesystems and meta data for example always use the same date (`SOURCE_DATE_EPOCH` has been adding to a wide range of tools). When building software from `git`, it is customary to clamp the time to the time of the last commit.

Earthly already supports builtin args for `EARTHLY_GIT_HASH`. Adding support for `EARTHLY_GIT_COMMIT_TIMESTAMP` would be super useful.

**Comment by vladaionescu** [comment]
Seems like this has been addressed now. 👏
