### ISSUE TITLE
Use a path outside of /tmp for the cache if available

### ISSUE THREAD

**Issue by dmarti** [earthly/earthly#116]
On some systems, `/tmp` is a small tmpfs partition. This creates 2 problems for putting Earthly's cache there:

 * not enough space available for large builds 

 * contents are lost on reboot

Consider checking for the `/var/cache` directory and putting Eartlhy's cache there if it is available.

related issue: [Explore remote cache · Issue #11 · earthly/earthly](https://github.com/earthly/earthly/issues/11)

reference: [Features/tmp-on-tmpfs - Fedora Project Wiki](https://fedoraproject.org/wiki/Features/tmp-on-tmpfs)

**Comment by vladaionescu** [comment]
Good points.

A temporary workaround is to create a symbolic link from `/tmp/earthly` to some other location on the system.

**Comment by dmarti** [comment]
Yes, that's how I have it working, thank you.

**Comment by alexcb** [comment]
@dmarti the next release of earthly will allow this to be changed by creating a file under `~/.earthly/config.yaml` containing:
```
global:
  cache_path: "/path/to/earthly/cache"
```

We also changed it to default to `/var/cache/earthly` as you suggested. Thanks for reporting the issue.
