### ISSUE TITLE
Updating homebrew formula

### ISSUE THREAD

**Issue by MatthiasScholzTW** [earthly/earthly#1184]
Would it be possible to update the homebrew formula for Earthly:

- https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/earthly.rb

so I can test the solution for https://github.com/earthly/earthly/issues/1177? 🙏 

The current version available as homebrew is: `v0.5.17` latest release is: `v.5.23` (at the time writing this).

I tried to prepare a PR, but unfortunately I am missing the SHA256 for Catalina and Mojave builds.

**Comment by dchw** [comment]
We moved to our own tap. I think you can run `brew install earthly/earthly/earthly` to move to our new tap and upgrade.

**Comment by MatthiasScholzTW** [comment]
Ah interesting, I missed that...
Should the old formula be deleted?

Just pulled it using the tap. One thing noticeable on `Big Sur` the `Catalina` version is pulled. Maybe this is expected.

**Comment by dchw** [comment]
> Should the old formula be deleted?

I don't know. I _do_ know that the Homebrew team has disabled the recipe.
