### ISSUE TITLE
Cannot access internet inside `dind` container

### ISSUE THREAD

**Issue by volkanunsal** [earthly/earthly#1189]
I'm running into an interesting issue using earthly. I'm planning to run an integration test in container A that calls a selenium server in container B, and the selenium server is supposed to call back the container A, where there is a server process running. 

But I keep getting `ERR_CONNECTION_REFUSED` errors from the selenium web driver. They happen when the container B is trying to call container A, indicating that there is some kind of disconnectivity in the network.

Btw, this container is run on EC2, so I've had to add a couple of things to `/etc/resolv.conf` file to make it work.

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Not exactly sure if that would cause a complication, but I have noticed that inside the Earthly container domain name resolution doesn't work, and I can only access the other containers by name --- IP addresses still load. My guess is the user created bridge network is not properly configured?

This is what my Earthfile looks like:

```Dockerfile
FROM ruby:2.5-alpine3.10

WORKDIR /app

ARG SCOPE=amd64

demo-rb:
  COPY ./Gemfile /app
  RUN bundle
  SAVE IMAGE demo-rb:latest

host:
  FROM +demo-rb
  COPY "./start_server.sh" "/app"
  COPY "./perform_request.rb" "/app"
  COPY "./perform_request.sh" "/app"
  COPY "./config.ru" "/app"
  ENV APP_HOST http://host:50190
  EXPOSE 50190
  ENV SELENIUM_REMOTE_URL 'http://selenium:4444/wd/hub'
  ENTRYPOINT ["./perform_request.sh"]

integration:
  FROM earthly/dind:alpine
  COPY ./earthly.$SCOPE.yml /app/
  WITH DOCKER --compose /app/earthly.$SCOPE.yml --load test:latest=+host
    RUN docker run --rm --network test-network --network-alias host -P test
  END
```

I've created a reproduction of the issue [here](https://github.com/volkanunsal/sel).

Any feedback would be appreciated.

**Comment by vladaionescu** [comment]
Any thoughts @dchw?

**Comment by volkanunsal** [comment]
I solved this. Turned out to be a simple configuration issue on my end.
