### ISSUE TITLE
Earthly `--ci` mode should allow outputs in some cases

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1200]
Earthly `--ci` enables `--use-inline-cache`, `--save-inline-cache` and `--no-output`. It would be great if

- [ ] The `--no-output` part could be negated if the user chooses to (e.g. `--ci --output`)
- [ ] Output was automatically enabled when using `--artifact` or `--image` (e.g. `--ci --artifact +target/file.o ./` or `--image +target`)

**Comment by JosemyDuarte** [comment]
Hi Vlad! I would be happy to contribute to this one. I have opened a PR with my understanding of the requirements. Open to any feedback
