### ISSUE TITLE
Panic on launch if Earthly doesn't have permission to read .env 

### ISSUE THREAD

**Issue by indygriffiths** [earthly/earthly#1202]
OS: Ubuntu 18.04

The `FileExists` and `DirExists` functions within fileutil.go don't handle errors other than when a file cannot be found, meaning that you get a nice-looking panic if you try running Earthly if it doesn't have access to read `.env` in the current working directory.

```
$ stat .env
stat: cannot stat '.env': Permission denied

$ earthly
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcf8358]

goroutine 1 [running]:
github.com/earthly/earthly/util/fileutil.FileExists(0x11f535a, 0x4, 0xc00066c960)
	/earthly/util/fileutil/fileutil.go:17 +0x98
main.main()
	/earthly/cmd/earthly/main.go:208 +0x1f0
```

Depending on semantics these functions could return false if `err != nil` or the functions could return an error themselves and let the caller decide what to do. For my specific instance around `.env` an error could be ignored since it doesn't bother to pull in config if the file doesn't exist (or can't be read), but there could be other invocations where an error should be better-handled.

**Comment by indygriffiths** [comment]
This also comes up when attempting to find the Earthly config directory in `GetEarthlyDir`, which gets called when attempting to detect the presence of `config.yaml` vs `config.yml`. 

The function first looks for the `.earthly` folder from the `SUDO_USER` home directory if that envvar exists. In our case where Earthly is only be able to run from a specific user with no permissions to look at my home folder, using `sudo -u <earthly user> earthly` results in the same sort of panic due to a permission error.

**Comment by vladaionescu** [comment]
Makes sense - seems like something we should fix

**Comment by dbermond** [comment]
The tests fails to pass for me in earthly 0.5.23 when building the Arch Linux package on a chroot (which is the default way to build packages on Arch). In 0.5.22, the tests passes fine.

I think this is related to the current issue discussed here. Please correct me if I'm wrong.

Output:

```
--- FAIL: TestBuildArgMatrix (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55d63a3df21c]

goroutine 10 [running]:
testing.tRunner.func1.2({0x55d63a8a3460, 0x55d63b1ad4b0})
        testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        testing/testing.go:1212 +0x218
panic({0x55d63a8a3460, 0x55d63b1ad4b0})
        runtime/panic.go:1038 +0x215
github.com/earthly/earthly/util/fileutil.FileExists({0xc00010ec40, 0x0})
        github.com/earthly/earthly/util/fileutil/fileutil.go:17 +0x5c
github.com/earthly/earthly/cmd/earthly.defaultConfigPath()
        github.com/earthly/earthly/cmd/earthly/main.go:2942 +0xe7
github.com/earthly/earthly/cmd/earthly.newEarthlyApp({0x0, 0x0}, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x1, 0x0, ...})
        github.com/earthly/earthly/cmd/earthly/main.go:379 +0xc9c
github.com/earthly/earthly/cmd/earthly.TestBuildArgMatrix(0xc000602d00)
        github.com/earthly/earthly/cmd/earthly/settings_test.go:192 +0x9c7
testing.tRunner(0xc000602d00, 0x55d63a9f6090)
        testing/testing.go:1259 +0x102
created by testing.(*T).Run
        testing/testing.go:1306 +0x35a
FAIL    github.com/earthly/earthly/cmd/earthly  0.016s
```
