### ISSUE TITLE
extend bash autocompletion to include buildargs

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1215]
consider an Earthfile:

```
target:
    ARG foo
    echo "foo is $foo"
```

It would be nice to have earthly auto complete the args, e.g. earthly currently will extend `earthly +tar<tab><tab>` to `earthly +target`, it would be nice that a user could then hit `<tab><tab>` again and see `--foo` as an option (`earthly +target -<tab><tab>` would expand to `earthly +target --foo=`.)

**Comment by arajhansa** [comment]
I would like to give this issue a try.

**Comment by alexcb** [comment]
This has been released under `v0.6.0`.
