### ISSUE TITLE
Add example hyperlinks for other languages in Examples list in the Quickstart Section of README file

### ISSUE THREAD

**Issue by KKVANONYMOUS** [earthly/earthly#1246]
Currently, the Examples list in the [Quickstart Section](https://github.com/earthly/earthly#quick-start) of the README file contains hyperlinks to languages like Go, Java, Cpp, JS
It would be beneficial to add links to other languages such as C, Cobol, Python, Ruby, Rust, Scala to make the navigation easier.

@vladaionescu 
If you find this issue useful, I would be happy to work on this 😃

**Comment by rohitjmathew** [comment]
@alexcb this issue didn't have anyone assigned to it so I took it up to add a few examples but as @KKVANONYMOUS started the original issue I have also left a few examples out so he can also have a shot at contributing to hacktoberfest. Hope that's okay with everyone.

**Comment by PrerakMathur20** [comment]
Hello,
I noticed this issue is still open and there are a few links yet to be added, so if it's okay with the Maintainers and contributors, I'd like to work on this issue.

**Comment by vladaionescu** [comment]
Sorry, this is already taken. Please no more README updates.
