### ISSUE TITLE
VERSION statement shouldn't need to be consistent across all earthfiles

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1247]
In the example in https://github.com/earthly/earthly/issues/1243 I noticed that all files require the `--for-in` flag as part of `VERSION --for-in 0.5`. I would have thought that it is only necessary in the Earthfile actually making use of `FOR`. But I tried removing the `VERSION --for-in 0.5` in the other two files and I got the error saying that `FOR` is unsupported.

```
Error: build target: build main: bkClient.Build: failed to solve: ../Earthfile line 13:4 the FOR command is not supported in this version
in              github.com/earthly/earthly/examples/tests/import:main+INSTALL_WHLS (Earthfile line 7:4) --wheels=lib2
called from     github.com/earthly/earthly/examples/tests/import/lib1:main+build
```

**Comment by alexcb** [comment]
> I would have thought that it is only necessary in the Earthfile actually making use of FOR

definitely sounds like a bug.

**Comment by alexcb** [comment]
this has been fixed (not sure when -- there's no CHANGELOG item that references this ticket)

root earthfile:
```
VERSION 0.7
foo:
  FROM alpine
  FOR i IN $(echo hello world)
    RUN echo $i
  END
```

subdir/Earthfile
```
VERSION 0.5

test:
  FROM ..+foo
  RUN echo in 5
```

running `earthly +test` works as expected:

```
              alpine | --> Load metadata alpine linux/amd64
              ..+foo | --> FROM alpine
              ..+foo | [----------] 100% resolve docker.io/library/alpine@sha256:69665d02cb32192e52e07644d76bc6f25abeb5410edc1c7a81a10ba3f0efb90a
              ..+foo | --> FOR $(echo hello world)
              ..+foo | --> RUN echo $i
              ..+foo | hello
              ..+foo | --> RUN echo $i
              ..+foo | world
               +test | --> RUN echo in 5
               +test | in 5
```
