### ISSUE TITLE
Very slow image import/export during WITH DOCKER

### ISSUE THREAD

**Issue by konradmalik** [earthly/earthly#1268]
Hey,
Recently I started to use Earthly for some of my projects.
So far, the majority of stuff works great, but the biggest drawback seems to be performance.
Everything runs a little bit slower, which is expected and completely fine. However, the worst impact that we see is for `docker-compose` based integration tests.

Specifically, in the example below:
```
             context | transferred 1 file(s) for context /tmp/earthly-docker-load290768814 (72 MB, 1 file/dir stats)
             context | transferred 1 file(s) for context /tmp/earthly-docker-load850151696 (564 MB, 1 file/dir stats)
             context | transferred 1 file(s) for context /tmp/earthly-docker-load498375883 (623 MB, 1 file/dir stats)
             context | transferred 1 file(s) for context /tmp/earthly-docker-load533876533 (1.3 GB, 1 file/dir stats)
               +test | --> WITH DOCKER RUN --privileged docker run --network=pider-tests --entrypoint="" scraper ./wait-for-it.sh azurite:10000 -- poetry run python -m pytest --numprocesses $PYTEST_PARALLELISM --max-worker-restart 0 --verbose --cov=scraper tests
               +test | Loading images...
               +test | Loaded image: scraper:latest
               +test | Loaded image: mcr.microsoft.com/azure-storage/azurite:3.14.2
               +test | Loaded image: registry.gitlab.com/pider/detectron:0.0.6
               +test | Loaded image: registry.gitlab.com/pider/tohu:0.0.6
               +test | ...done
```
I have one image that is built via earthly and three others that need to be pulled and used in the docker-compose file I provided (dependencies for the integration test).
The problem is, that the import/export of all those images takes much longer (2, 3 times. Depending on the machine it may be 5-10 mins) than the running of the tests itself.
"Standard" approach with plain docker-compose is much, much faster.

This is the command I run for the reference:
```
    WITH DOCKER \
        --compose tests.yaml \
        --load scraper=+tests
        RUN docker run --network=pider-tests --entrypoint="" scraper \
            ./wait-for-it.sh azurite:10000 -- poetry run python -m \
            pytest --numprocesses $PYTEST_PARALLELISM --max-worker-restart 0 --verbose tests/integration
    END
```

Problems I noticed:
- seems like all the images are first loaded into the earthly buildkit context and then transferred (loaded) into the internal dind instance
- maybe the above could be optimized somehow, perhaps done in a one-step instead of two?
- images I use are pretty large (1.3 GB the biggest one), but I think this is by no means a "too large" image, and even bigger images are very common, so this will influence the majority of the users

Any ideas on how to debug, optimize or improve this?
I'll take all:
- workarounds (except running plain docker-compose commands just for the integration tests :) )
- suggestions where to look in earthly code and try to come up with some ideas/PRs

**Comment by vladaionescu** [comment]
Another thought for optimizing the image transfer:

Besides using a local registry for passing in the images to the inner Docker, we could additionally use the stargz snapshotter in the inner Docker, to lazily download bits and pieces from the loaded images as they are actually needed. Because the download operation is local, the lazy download should be almost unnoticeable. This should reduce the delay caused by loads+transfer of bytes to near zero. One wrinkle though... I'm not sure how re-tagging might work (when downloading from the local registry, the image will have a local address pre-pended to the image tag, which requires re-tagging to get it to the right image name as required by the user).

**Comment by vladaionescu** [comment]
The latest release of Earthly improves the performance a bit as it takes care of item 2 in the comment above. This is behind a feature flag as it's experimental, however: `VERSION --parallel-load 0.6`

**Comment by vladaionescu** [comment]
This has been GA'd some time ago.

**Comment by vladaionescu** [comment]
Item 1 is being GA'd in the next release. Item 2 has been GA'd for some time already.
