### ISSUE TITLE
Not able to run docker-in-docker from npm script

### ISSUE THREAD

**Issue by bjaanes** [earthly/earthly#1278]
I have an npm test that uses testcontainers-node to automatically spin up and tear down during tests (so there are no manual dependent steps to just run integration tests locally).

I have created a minimum reproducible example here: 
https://github.com/bjaanes/earthly-dind-reproduced-issue 

All the necessary code is in that repo, but I will copy some of the code for context in this issue:

Earthfile:
```
FROM earthly/dind:ubuntu

this-works:
    WITH DOCKER --pull hello-world
        RUN docker run hello-world
    END

this-does-not:
    COPY ./ ./
    RUN apt-get update -yq \
        && apt-get -yq install curl gnupg ca-certificates gcc g++ make \
        && curl -L https://deb.nodesource.com/setup_16.x | bash \
        && apt-get update -yq \
        && apt-get install -yq nodejs
    RUN npm i
    WITH DOCKER
        RUN npm test
    END
```

`WITH DOCKER` works just fine with the "hello-world" example, but this particular case does not. 
So this produces no errors:
```shell
$ earthly -P +this-works
```
But this one does:
```shell
$ earthly -P +this-does-not
```

I get the following error:
```
(HTTP code 500) server error - OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "a *:* rwm": write /sys/fs/cgroup/devices/docker/665963e797d624839a294a5023f68d4784ecbaf5b567323b91fea367d0de2467/devices.allow: operation not permitted: unknown
```

**Comment by bjaanes** [comment]
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 87
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-37-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.38GiB
 Name: gdevbox
 ID: YY2P:KGNI:442I:BMFF:4WKM:SN5J:WESH:GOFI:E5JD:3VKN:7UBN:Q4YZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bjaanes** [comment]
@dchw Any updates on this? Is it my setup that is causing this? I found a very temporary workaround for my npm project, but I am now facing the exact same problem for my java/maven based project that I want to move over to Earthly, but I am entirely blocked by this issue now.

**Comment by avasenin** [comment]
@dchw @vladaionescu facing the same issue. Any advice on how to run builds with test container integrated.

**Comment by vladaionescu** [comment]
Would you be able to provide your system information: Earthly version, OS version and output of `docker info`?

Also, if you can, it would help tremendously if you would be able to provide a minimal reproduction case.

**Comment by bjaanes** [comment]
@vladaionescu I assume you are asking avasenin? I have already provided both for this issue.

**Comment by vladaionescu** [comment]
BTW thanks for providing these @bjaanes. I'll take a look at this today. Haven't worked with testcontainers much. Though I suspect I should be able to also run that `npm test` command locally (outside of Earthly) with no issue, right?

**Comment by vladaionescu** [comment]
Hi @bjaanes - I played around with your example and it's working for me with the latest Earthly version. It's possible that this issue was fixed since you first opened this ticket (sorry for taking a long time to look at it). I made some small tweaks to your script BTW https://github.com/bjaanes/earthly-dind-reproduced-issue/pull/1

Let me know if this is working for you now!
