### ISSUE TITLE
Add Earthfile syntax highlighting to GitHub

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1292]
Here is the guide to add new languages: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language. I *think* that there are [enough Earthfiles out there](https://github.com/search?q=filename%3AEarthfile&type=code) for GitHub to allow this now.

We already have a TextMate grammar as part of the VScode syntax highlighting plugin. We could reuse that.

Details:

* The grammar and the samples can be released under MPL-2.0
* This repo has been created for the grammar itself: https://github.com/earthly/earthfile-grammar

**Comment by mccartney** [comment]
Half-way through the Github procedure, I've just hit an error message reported by Github's linguist/grammar-compiler. Details at: https://github.com/earthly/earthfile-grammar/pull/2 Please have a look.

**Comment by mccartney** [comment]
Still waiting...

**Comment by mccartney** [comment]
The PR to linguist got merged. I wonder what next. 
My hunch is that we need to wait (for some things to get deployed) and maybe it will start working?

**Comment by vladaionescu** [comment]
Awesome - yeah, I'll keep an eye out on GitHub. Maybe they have regular (weekly?) deploys or something.

**Comment by mccartney** [comment]
It started to work this week (yesterday or something)!

![image](https://user-images.githubusercontent.com/762437/146370500-f95e9761-7f89-4b19-80ac-6978444911c8.png)

**Comment by mccartney** [comment]
Last thing I can possibly see to be done here is - whether to remove https://github.com/earthly/earthly/tree/main/contrib/earthfile-syntax-highlighting (and point to https://github.com/earthly/earthfile-grammar).
Any thoughts from within the project?

**Comment by vladaionescu** [comment]
Woohoo!!

Yeah, we should do that. We can use earthly to copy things cross-repos perhaps.
