### ISSUE TITLE
Ignored files should be explicit

### ISSUE THREAD

**Issue by andrewsykim** [earthly/earthly#1294]
I'm currently using Earthly with some build scripts that require a clean git directory. However, when I run `COPY . .`, the Earthfile itself is not copied and I always end up with a dirty git directory since `.git` state is preserved on COPY.

The current implicit rules to ignore some files could be unexpected in some cases (like the one I mentioned above, although maybe this is not so normal). I think a simpler approach is to remove the implicit ignore rules and always require explicit files in `.earthlyignore`. If a user wants to remove the Earthfile from local context because edits to Earthfile should not result in misses in the cache layer, this should be done by updating `.earthlyignore` explicitly.

**Comment by vladaionescu** [comment]
Note a small gotcha: The `.earthlyignore` is not yet applied for remote targets. This is where [the relevant TODO exists](https://github.com/earthly/earthly/blob/main/buildcontext/git.go#L114).
