### ISSUE TITLE
ArchLinux: BuildKit with podman misses image name

### ISSUE THREAD

**Issue by ejiek** [earthly/earthly#1384]
I've tried building `v0.5.24` for Archlinux and running it with rooless podman.
Instructions from  #760.

Unfortunately a "hello world" 

```sh
earthly github.com/earthly/hello-world+hello
```
fails with:
```
           buildkitd | Starting buildkit daemon as a podman container (earthly-buildkitd)...
Error: build new buildkitd client: maybe start buildkitd: start: could not start buildkit: 1 error occurred:
	* command failed: podman run --privileged --env BUILDKIT_TCP_TRANSPORT_ENABLED=true --env BUILDKIT_TLS_ENABLED=false --env BUILDKIT_DEBUG=false --label dev.earthly.settingshash=d483bf34a69e34f --mount type=volume,source=earthly-cache,dst=/tmp/earthly --publish 127.0.0.1:8373:8373/tcp --publish 127.0.0.1:8372:8372/tcp -d --name earthly-buildkitd --log-opt : exit status 125: Error: requires at least 1 arg(s), only received 0: exit status 125
```

Looks like it misses image name for the `run` command.

As a dirty fix, I've added it through additional BuildKit arguments:
```yml
global:
    buildkit_additional_args: ["docker.io/earthly/buildkitd:v0.5.24"]
```

Now it works o.O

*ps. Do we need `--privileged` in this podman command? It seems to be formed before `docker info` rootless check*
*pps. I just don't understand the nature of this flag, seems to be unrelated to the podman rootless mode*

**Comment by dchw** [comment]
This is odd. You mentioned you are building it yourself? Try adding `-X main.DefaultBuildkitdImage=docker.io/earthly/buildkitd:v0.5.24`. We also have a couple other flags that need to be set in `-X main.Version` and `-X main.GitSha`.

To build it from source, you could bootstrap using an existing `earthly` binary to run the `+for-linux` target. This is what we do internally.

FWIW, we also have a dedicated flag you could use to set the image: `--buildkit-image docker.io/earthly/buildkitd:v0.5.24`.

> ps. Do we need --privileged in this podman command?

Yes. For all functionality to work correctly, we need to run it as privileged. Much of our functionality will work in rootless mode though; YMMV and we make no guarantees.

**Comment by tachiniererin** [comment]
I ran into this problem yesterday too, the earthly and earthly-git PKGBUILDs don't add the `-X main.Version` etc. when building it and that's why it fails to get the right buildkit image.

**Comment by dchw** [comment]
I suppose the PKGBUILD should be updated to build it like we do; using an existing Earthly binary to build the new one; if possible. I'll see about reaching out to the maintainer.

**Comment by ejiek** [comment]
I've tried adding mentioned flags to a local PKGBUILD.
It seems to work just fine.

Thanks for such a quick and informative response!

Updating AUR repo is out of this issue scope.
