### ISSUE TITLE
Fresh install earthly on 0.5.24 doesn't work iptables error

### ISSUE THREAD

**Issue by wesselvdv** [earthly/earthly#1397]
Installing a fresh earthly on Arch Linux `5.14.11-arch1-1` results in the following error from the buildkit container:

```
buildkitd: running [/sbin/iptables -t nat -C CNI-4398d9b7715348370ef20d09 -d 172.30.0.2/16 -j ACCEPT -m comment --comment name: "buildkitbuild" id: "4syseucn4xoji1p5q6disqk8h" --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load match `comment':No such file or directory
```

Seems to have something to do with an unsupported flag for the `iptables` command. Not sure if there's a workaround?

**Comment by wesselvdv** [comment]
Alright. I found the culprit. In order for this to work you need to have installed `iptables-nft` instead of `iptables`. After installing `iptables-nft` (using `yay iptables-nft` for example), and rebooting it works.

**Comment by wesselvdv** [comment]
Might be a good one to mention these requirements in the readme? (That `iptables-legacy` might not work.)

**Comment by dchw** [comment]
Odd. `iptables-nft` shouldn't be strictly required as a package; we have logic to try and detect which kernel module is in use here: https://github.com/earthly/earthly/blob/8a35665a010f5964c4af066f10c4d2b974ec9914/buildkitd/entrypoint.sh#L56-L100
 
If you can, I would love to see the logging output from starting the buildkitd container so I can improve our autodetection. In addition, you can manually specify the format by setting the `global.ip_tables` key:

```
❯ earthly config global.ip_tables --help
(string): Which iptables binary to use. Valid values are iptables-legacy or iptables-nft. Bypasses any autodetection.

❯ earthly config global.ip_tables iptables-legacy
```
