### ISSUE TITLE
Argument interpolation doesnt work correctly in `COPY`

### ISSUE THREAD

**Issue by Alphasite** [earthly/earthly#1407]
## Steps to reproduce
1. Define a local target as such:
   ```
    run:
        LOCALLY
        COPY +build-$USEROS/logbox build/logbox-$USEROS-amd64
        RUN ./build/logbox-$USEROS-amd64
    ```
1. Invoke the target: `earthly +run`

## What I expected

The target to run successfully

## What I got

Run failed:
```
Error: build target: build main: bkClient.Build: failed to solve: Earthfile line 60:4 copy artifact locally: apply build +build-: earthfile2llb for +build-: Earthfile line 0:0 target build- not found
in              +build-
in              +run
```
As variable interpolation doesn't appear to run correctly in the `COPY` step, so the `+build-` variable is used instead of `+build-darwin`.

**Comment by vladaionescu** [comment]
Oh, in order to use `USEROS` builtin variable you need to pre-declare it:

```
 run:
     LOCALLY
     ARG USEROS
     COPY +build-$USEROS/logbox build/logbox-$USEROS-amd64
     RUN ./build/logbox-$USEROS-amd64
```

BTW, please also note that `USEROS` is a very recent addition and is only available in the pre-released earthly `v0.6.0-rc2`.

**Comment by vladaionescu** [comment]
Please reopen if this did not fix the issue.

**Comment by Alphasite** [comment]
Oh sorry, i didn't realise it wasn't in the published builds, I did end up re-reading the docs and it still didn't work, so I assumed it was a bug, i hadn't realized it didn't exist in the version i was looking for.

Thanks for looking at this so promptly! (also tell Andrew I said hi)
