### ISSUE TITLE
saving artifacts from remote target to local directory fails with "build target: rm .: remove .: invalid argument"

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1422]
Running:

    earthly-v0.6.0-rc3 --artifact github.com/earthly/earthly+for-linux/* .

prodcues:

    Error: build target: rm .: remove .: invalid argument

However, running:

    earthly-v0.6.0-rc3 --artifact github.com/earthly/earthly+for-linux/* ./

works.

**Comment by vladaionescu** [comment]
Note that this should be saving the file to `$EARTHLYPATH` as per the original proposal https://github.com/earthly/earthly/issues/896

**Comment by sbs2001** [comment]
I created https://github.com/earthly/earthly/pull/1438 for fixing this
