### ISSUE TITLE
ARG default values cached when `--no-cache`

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#1431]
If an arg default is dynamic, running earthly with `--no-cache` should cause it to be reevaluated, but that doesn't seem to be the case.

Given:
```
cache-args:
    FROM alpine
    ARG timestamp="$(date +%s)"
    RUN echo $timestamp
```
Then run `earthly --no-cache +cache-args` several times and the `RUN` will be re-evaluated but the `timestamp` will remain the same due to caching. 

This feels very minor but is a bit confusing.

**Comment by Vignesh12041992** [comment]
@vladaionescu : Hi, we were not able to reproduce this issue. Have added the images for your reference. Please let me know if we are doing something wrong here.
![image](https://user-images.githubusercontent.com/83869903/182311706-505bf9c2-8ae5-4ebf-8326-f46bbd55879e.png)
![image](https://user-images.githubusercontent.com/83869903/182311838-73c5db26-f5c4-4b17-ad87-82354bd9748f.png)
![image](https://user-images.githubusercontent.com/83869903/182311978-19cc80b0-3948-4869-b0f0-671d5d821a2a.png)

**Comment by vladaionescu** [comment]
Thanks for testing - it seems that this has been fixed already.
