### ISSUE TITLE
ARG with a subshell does not work with LOCALLY

### ISSUE THREAD

**Issue by tyrken** [earthly/earthly#1437]
I'm trying to convert a Makefile which uses a number of `VAR:=$(shell some-command)` lines to set up constants it later uses.  I attempted to use `LOCALLY` to simulate this:

```
VERSION 0.6

LOCALLY
# FROM alpine
ARG FOO=$(echo ff)

all:
    RUN echo $FOO
```

... but the above errors saying `exec: "/bin/sh": stat /bin/sh: no such file or directory` on my Linux host, only working if I uncomment the `FROM alpine` instead of attempting to work LOCALLY.  ARG without a subshell, e.g. `ARG FOO=ff`, works fine either way.

More careful reading of the docs suggests LOCALLY only claims to support `RUN` commands, but ideally the error message should be a little clearer, if this is indeed what is meant to happen.

**Comment by alexcb** [comment]
Thanks for the bug report, it's something we should aim to support.

**Comment by renanvizza-prontmed** [comment]
Hey all, dunno if it's the same. 

But using on 0.5

```
BUILD --build-arg TAG="$(cat ./semver)" +job2
```

Used to work, and now it does not.

```
VERSION=0.6

semver:
...
  SAVE ARTIFACT /path/fileWithCurVer /semver

job1:
  FROM alpine:3.15
  BUILD +semver
  COPY +semver/semver ./
  BUILD +job2 --TAG="$(cat ./semver)"

job2:
  ARG TAG
  FROM alpine:3.15
  SAVE IMAGE --push docker-registry/myservice:$TAG

```

Thanks

**Comment by alexcb** [comment]
@renanvizza-prontmed that's definitely a regression; I opened up #1448 to track it. Thanks for reporting it.

**Comment by alexcb** [comment]
v0.6.1 will include better error messages for this; however, long term it's something we hope to support.

**Comment by mwopfner** [comment]
I think this but was solved with the `--shell-out-anywhere` feature, because the following earthfile works:
```
VERSION --shell-out-anywhere 0.6

all:
  LOCALLY
  # FROM alpine
  ARG FOO=$(echo ff)
  RUN echo $FOO
```
And of course `VERSION 0.7` also works.
