### ISSUE TITLE
--use-copy-include-patterns breaks absolute form of COPY

### ISSUE THREAD

**Issue by cehoffman** [earthly/earthly#1451]
The simplest example:

```
VERSION 0.5

mysql:
  FROM mysql:5.7
  COPY /files /
```

Updating this to the latest 0.6 breaks on the COPY, but removing the leading `/` from the COPY context works. Error is

`Error: build target: build main: bkClient.Build: failed to solve: failed to compute cache key: "/files": not found`

This is what is needed on 0.6 and differs from standard Docker experience.

```
VERSION 0.6

mysql:
  FROM mysql:5.7
  COPY files /
```

**Comment by vladaionescu** [comment]
I think this is an intended (maybe not properly documented) change. @alexcb can confirm?

We also want to support copying files outside of the current directory in the future: https://github.com/earthly/earthly/issues/1221#issuecomment-948838370. Possibly even files with an absolute path... which would be in conflict with this anyway.

**Comment by alexcb** [comment]
> I think this is an intended (maybe not properly documented) change. @alexcb can confirm?

Yes it is, this is one of the places where Earthfiles deviates from Dockerfiles. I'll update our docs on `COPY` to reflect this.

**Comment by cehoffman** [comment]
Makes sense. Thanks for improving the documentation.
