### ISSUE TITLE
Create builtin ARG EARTHLY_VERSION

### ISSUE THREAD

**Issue by cehoffman** [earthly/earthly#1452]
This would be useful for referencing the docker setup script to make an image suitable for use `WITH DOCKER`, e.g. `  DO github.com/earthly/lib:$EARTHLY_VERSION+INSTALL_DIND`

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/blob/main/variables/builtin.go#L18 is where we can add a new entry for `EARTHLY_VERSION`.

Perhaps we should also include `EARTHLY_BUILD_SHA`, which would point to the corresponding git sha that was used for the build?

Here are the relevant strings that are set at build time and would need to be propigated into `builtin.go`: https://github.com/earthly/earthly/blob/main/cmd/earthly/main.go#L168-L172
