### ISSUE TITLE
Inline Cache appears to be broken

### ISSUE THREAD

**Issue by sesgoe** [earthly/earthly#1466]
Hi all!

I asked a quick question in `#earthly` on slack and spoke with @alexcb about the Inline Cache seemingly not working, even for a very trivial `Earthfile`.

Here's the example Earthfile I'm using:
```
VERSION 0.6

earthly-test:
    FROM alpine

    RUN echo "hi"
    RUN echo "this is gonna get cached, I can feel it"

    SAVE IMAGE --push [REDACTED]
```

I am building the `+earthly-test` target locally like so:
`earthly --push +earthly-test`

The image is uploaded successfully, and the cache appears to upload successfully too.

To ensure no Earthly cache is present, I run:
`earthly prune`
`earthly --use-inline-cache +earthly-test` (can also run `earthly --ci +earthly-test` with the same results)

And the Earthly output suggests that the cache manifest has been loaded, but the stages are not cached.
```
cache | --> importing cache manifest from [REDACTED]
+earthly-test | --> FROM alpine
+earthly-test | [██████████] 100% resolve docker.io/library/alpine@sha256:2...
+earthly-test | [██████████] 100% sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
+earthly-test | [██████████] 100% extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
+earthly-test | --> RUN echo "hi"
+earthly-test | hi
+earthly-test | --> RUN echo "this is gonna get cached, I can feel it"
+earthly-test | this is gonna get cached, I can feel it
 output | --> exporting outputs
 ...
 ```
 
 The good news is that **explicit** caches still seem to work:

 ```
cache | --> importing cache manifest from [REDACTED]:cache
+earthly-test | --> FROM alpine
+earthly-test | [██████████] 100% resolve docker.io/library/alpine@sha256:21a3de...
+earthly-test | *cached* --> RUN echo "hi"
+earthly-test | *cached* --> RUN echo "this is gonna get cached, I can feel it"
output | --> exporting outputs
...
```

You can refer to the [slack thread](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1638382371239600) if you'd like to know what else I briefly tried.

**Comment by vladaionescu** [comment]
I believe you're missing `--save-inline-cache` in `earthly --push +earthly-test`. Without that there's no inline cache manifest uploaded.

This output

```
+earthly-test | [██████████] 100% resolve docker.io/library/alpine@sha256:2...
+earthly-test | [██████████] 100% sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
+earthly-test | [██████████] 100% extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
```

isn't actually the cache - it's just the pull of the `alpine` image.

Closing as I think this should fix your issue - but let us know if it doesn't!

**Comment by sesgoe** [comment]
This definitely seems to fix it!

and that output has this slightly above it:
```cache | --> importing cache manifest from [REDACTED]```

Which is why I guess I was confused.

The inline cache section doesn't really mention anything about **requiring** this flag:
https://docs.earthly.dev/docs/guides/shared-cache#how-to-use-inline-caching

So it might be worth a quick PR to add this information somewhere there. I think I can manage that!

Thanks for the help @vladaionescu! I absolutely adore this product.
