### ISSUE TITLE
comments don't work on FROM line

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#148]
```
debugger-docker:
	FROM busybox:latest # cant be FROM scratch because the args require sh to exist
```

produces the error:

```
buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: parse: invalid number of arguments for FROM: [busybox:latest # cant be FROM scratch because the args require sh to exist]
```

**Comment by alexcb** [comment]
The easy work around for the time being is to just put it on the line above, for example:

```
debugger-docker:
	# cant be FROM scratch because the args require sh to exist
	FROM busybox:latest
```

**Comment by vladaionescu** [comment]
Relevant area in the code: https://github.com/earthly/earthly/blob/master/earthfile2llb/parser/EarthLexer.g4#L95

**Comment by abennett** [comment]
New to ANTLR, but I am interested and started reading. Does the parser need to retain knowledge of comments or could they be discarded? Something like:
```g4
LINE_COMMENT   :'#' ~[\r\n]*      -> skip;
```
Would the omission of comments from the parser resolve this issue?

**Comment by vladaionescu** [comment]
They can be discarded, indeed. Though the more important aspect is making sure all the edge cases work as expected. Eg if `#` is in quotes or is escaped via `\#`, it should not count as a comment. It needs to integrate well with the definition of the `Atom`.

**Comment by vladaionescu** [comment]
This has been fixed, right @alexcb ?
