### ISSUE TITLE
Proposal: support path overrides for cloud secrets

### ISSUE THREAD

**Issue by andrewsykim** [earthly/earthly#1499]
Earthly has the ability to use secure cloud-based storage for build secrets, you can read more about it in the [docs](https://docs.earthly.dev/docs/guides/cloud-secrets). 

However, the feature currently only renders cloud paths within the Earthfile but does not allow overriding the paths using the --secret flag. Take this target for example:
```
target:
  RUN --secret MY_SECRET=+secrets/MY_SECRET echo "$MY_SECRET"
  RUN --secret MY_SECRET=+secrets/my-org/my-team/secret echo "$MY_SECRET"
```

It renders the following result assuming the secret value is `secret-value`:
```
$ earthly --no-cache --secret=MY_SECRET=+secrets/my-org/my-team/secret +secrets 
            +secrets | --> RUN echo "$MY_SECRET"
            +secrets | +secrets/my-org/my-team/secret
            +secrets | --> RUN echo "$MY_SECRET"
            +secrets | secret-value
```

Note that only the second RUN renders the right secret but the first RUN doesn't fetch cloud secrets but uses the value from --secret directly. It would be really nice if cloud-based paths can be provided through the `--secret` flag. This way you can specify a default secret value or a stub value and overwrite it as needed. You might want to use a different set of secrets locally vs on CI for example. 

By looking at some examples we already have, it does seem like this behavior is actually possible already by using build args. For example, you can leverage build arg for the secret path like this:
```
target:
   ARG SECRET_PATH
   RUN --secret MY_SECRET=$SECRET_PATH echo "$MY_SECRET"
```

And the caller of the target can pass in the desired cloud path using the SECRET_PATH build argument. While this technically works, it seems more intuitive and cleaner if it worked out of the box with the `--secret` flag.

**Comment by vladaionescu** [comment]
The additional issue with the build arg-based solution is that those build args need to be manually propagated all around the various targets that may be involved, which tends to be very verbose and error-prone.

Can you show what the proposed override would look like on the command line?

**Comment by andrewsykim** [comment]
> Can you show what the proposed override would look like on the command line?

I think my above example is what I would expect for the override, where specifying a cloud path via `--secret` renders the actual secret value instead of the path itself:

```
$ earthly --secret=MY_SECRET=+secrets/my-org/my-team/secret +secrets 
            +secrets | --> RUN echo "$MY_SECRET"
            +secrets | +secrets/my-org/my-team/secret  # <--- this should be "secret-value" instead
```

**Comment by alexcb** [comment]
To add to the original example:

> It renders the following result assuming the secret value is secret-value:

i.e. someone has previously run the command `earthly secrets set /my-org/my-team/secret secret-value`

---

There's a similar command to get secrets:

```
earthly secrets get /my-org/my-team/secret secret-value

# or use -n to skip the trailing newline
earthly secrets get -n /my-org/my-team/secret secret-value
```

So it's therefore technically possible to do:

    earthly --secret=MY_SECRET="$(earthly secrets get -n +secrets/my-org/my-team/secret)" +secrets

However I agree that it would be useful if earthly detected the secret value started with `+secrets/` and performed this lookup automatically (without forcing the user to pre-fetch it via a subshell)

Some minor questions:

 - Would the same lookup logic apply to:
     - `.env` files?
     - env variables? e.g. `MY_SECRET=+secrets/my-org/my-team/secret earthly --secret=MY_SECRET +secrets`
 - How would we allow (the unlikely event where) a user passing in a secret starting with `+secrets/`

**Comment by vladaionescu** [comment]
>  where specifying a cloud path via --secret renders the actual secret value instead of the path itself

I think there needs to be a way in which Earthly can unambiguously determine that the user passed in a cloud secrets path and not a value. The syntax you mentioned is already in use for providing the value of the secret. Perhaps there can be two distinct flavors of that somehow.

**Comment by andrewsykim** [comment]
I think that would work as well -- i'd be happy with any solution that allows the cloud secret path to be overwritten from the default value in the Earthfile.

**Comment by andrewsykim** [comment]
> Perhaps there can be two distinct flavors of that somehow.

Although I do feel like the `+secrets/` prefix feels distinct enough for us to determine if values should result in a cloud lookup. And if a user ever did have a secret valued +secret they can escape the +?

**Comment by alexcb** [comment]
> Although I do feel like the +secrets/ prefix feels distinct enough for us

I agree.

In the very unlikely case that someone wants to pass a secret value that starts with `+secrets/`, **I propose that we allow the user to encode this as: `value:+secrets/...`**. Instead if we had `\+` escaping, we then have to worry about escaling `\` and `+` throughout the entire secret (which I think is the much more likely case).

**Comment by alexcb** [comment]
Now that we have the concept of a `PROJECT`, it's possible to clone a project and override the secrets in the new cloned project.

If this feature is still required, please open a new issue and we will re-evaluate it.
