### ISSUE TITLE
Feature request: RUN --with-git go mod download

### ISSUE THREAD

**Issue by mirho** [earthly/earthly#1511]
**From Karol Lassak on the Earthly Slack Community**

Quick.. or maybe more complicated question..
Earthy have configuration for git, but its used only in 2 places (resolving external earthly targets + GIT command), do you thing it would be feasible to add support for it in other places?
like run?
I would like to do something like that
RUN --with-git go mod download
I know I can pass my own credentials.. but that actually forces users to configure credentials twice..

**Comment by vladaionescu** [comment]
I believe this is already available via `RUN --ssh`.

**Comment by alexcb** [comment]
`RUN --ssh` falls short when someone needs to use https-based credentials for git, in that case they'll need to configure them both in `~/.earthly/config.yml` and pass them through via build-args.

`RUN --with-git-https-credentials` might offer some syntactic sugar for such a case. But it introduce an easier attack-vector compared to ssh-based.
