### ISSUE TITLE
allow importing build args/env vars from file

### ISSUE THREAD

**Issue by ido-namely** [earthly/earthly#1515]
Hello,
I noticed that when changing the value of a global arg, it invalidates cache for targets that do not reference it/depend on it.
For example:
1. Earthfile:
```
ARG FOO
hello:
    RUN echo "hello world"
```

2. `earthly +hello --FOO=bar`
```
...
              alpine | --> Load metadata linux/amd64
              +hello | FOO=bar
              +hello | --> FROM alpine
              +hello | [██████████] 100% resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
              +hello | FOO=bar
              +hello | --> RUN echo "hello world"
              +hello | hello world
              output | --> exporting outputs
```

3. `earthly +hello --FOO=baz`
```
...
              alpine | --> Load metadata linux/amd64
              +hello | FOO=baz
              +hello | --> FROM alpine
              +hello | [██████████] 100% resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
              +hello | FOO=baz
              +hello | --> RUN echo "hello world"
              +hello | hello world
              output | --> exporting outputs
```

Now, I’m guessing this is because the global args are set in a hidden `base` target that all other targets depend on, 
and I’m also guessing that the args cannot be differentiated according to whether they are referenced or not because they are auto exported as env vars as well, which means any command might be using it.
Is that right?

The reason I ask is that I’m interested in being able to set default values in one place for multiple args (preferably at the top of the Earthfile) even though some args won’t be used by all targets.

I wonder if it can become possible to set the args in one place while still expecting for caches to work for targets that do not expect to use a changed arg?

If not, the 2nd best option I can think of is to be able to pass an env var file to the earthly command, so that default values can still be managed in one place (this would mean of course that I would need to define the ARG in each target that wishes to use it, unlike the global arg approach). 

I've noticed there is an option to either set `$EARTHLY_BUILD_ARGS` as one string of key/value pairs or to set the env vars in a `.env`. However, I'd like to be to do something like 
`earthly  --env-file my_vars.env +my_target` (similar to the existing `docker run` option), since the other options do not allow me to set the values in an explicit file while still invoking earthly in one command.

Would love to hear your thoughts on this.
Thanks!

**Comment by vladaionescu** [comment]
> Now, I’m guessing this is because the global args are set in a hidden base target that all other targets depend on,
and I’m also guessing that the args cannot be differentiated according to whether they are referenced or not because they are auto exported as env vars as well, which means any command might be using it.
Is that right?

Yes, exactly!

> earthly --env-file my_vars.env +my_target

I think this makes sense and should be doable.

**Comment by ido-namely** [comment]
Thaks @vladaionescu ,
I decided to try do contribute myself - https://github.com/earthly/earthly/pull/1518
