### ISSUE TITLE
Ability to iterate over an arg

### ISSUE THREAD

**Issue by tzilist** [earthly/earthly#1516]
I'm not sure if this is possible at the moment, however, it would be nice to do something akin to

```
build:
    BUILD +docker --libs=lib1 --libs=lib2

docker:
  ARG libs
   FOR lib in ${libs}
     echo ${lib}
   END
```

Is this possible to do right?

**Comment by vladaionescu** [comment]
Yeah it should. Check out https://docs.earthly.dev/docs/earthfile#for

I believe you need to do

```
BUILD +docker --libs="lib1 lib2"
```

Otherwise, it should work pretty much as you described it.
