### ISSUE TITLE
Seccomp profile in Earthly image

### ISSUE THREAD

**Issue by cdunster** [earthly/earthly#1529]
Hey, I'm trying to use [cargo-tarpaulin](https://crates.io/crates/cargo-tarpaulin) inside Earthly in my Rust project but I am getting an error:

> ERROR cargo_tarpaulin: Failed to run tests: ASLR disable failed: EPERM: Operation not permitted

Looking at this [cargo-tarpaulin issue](https://github.com/xd009642/tarpaulin/issues/146) it seems that I need to set the docker seccomp profile to allow this opperation.

So, my question is; how can I set this option for the docker image used by Earthly?

I thought it would be something like adding this section to my Earthly config `~/.earthly/config.yml`
```yaml
global:
  buildkit_additional_args: ["--security-opt", "seccomp=unconfined"]
```
but this didn't change anything.

Any help is greatly appreciated, thanks!

**Comment by vladaionescu** [comment]
Wondering if you've tried `RUN --privileged`? (You'd also need to run earthly with `earthly --allow-privileged` or `earthly -P` for short)

**Comment by cdunster** [comment]
> Wondering if you've tried `RUN --privileged`? (You'd also need to run earthly with `earthly --allow-privileged` or `earthly -P` for short)

@vladaionescu, awesome! That worked, thanks. I saw that and assumed that it was for `sudo`-esque commands and so didn't think it would work, looking back I should have just tried it.

Thanks again and keep up the great work.
