### ISSUE TITLE
`IF` statement does not execute properly in a non-root container

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#1547]
The inverse is actually easier to state: that the `IF` statement only works in root-run containers.  It just seemed better to phrase it as a bug (that is doesn't work as expected/desired).

This appears fairly straightforward, so I won't go into too much detail.

Minimal reproduction (with 0.6.2):
```
FROM alpine
RUN adduser --system peon
USER peon

as-non-root:
    RUN whoami
    IF [ -f /etc/passwd ]
        RUN echo "got file as peon"
    END

as-root:
    USER root
    RUN whoami
    IF [ -f /etc/passwd ]
        RUN echo "got file as root"
    END
```
Executing the `as-root` target succeeds (and echos) as expected.  I would expect the behavior for the `as-non-root` target to be identical.  However:
```
$ earthly +as-non-root 

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)


 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata linux/amd64
               +base | --> FROM alpine
               +base | [██████████] 100% resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
               +base | *cached* --> RUN adduser --system peon
        +as-non-root | --> RUN whoami
        +as-non-root | peon
        +as-non-root | --> IF [ -f /etc/passwd ]
        +as-non-root | /bin/sh: can't create /run/exit_code: Permission denied
        +as-non-root | Command /bin/sh -c '[ -f /etc/passwd ] ; echo $? >'"'"'/run/exit_code'"'"'' failed with exit code 1
        +as-non-root | 
        +as-non-root | ERROR: Command exited with non-zero code: IF [ -f /etc/passwd ]

============================ ❌ FAILURE [2. Build 🔧] ============================

Repeating the output of the command that caused the failure
        +as-non-root *failed* | --> IF [ -f /etc/passwd ]
        +as-non-root *failed* | /bin/sh: can't create /run/exit_code: Permission denied
        +as-non-root *failed* | Command /bin/sh -c '[ -f /etc/passwd ] ; echo $? >'"'"'/run/exit_code'"'"'' failed with exit code 1
        +as-non-root *failed* |         +as-non-root *failed* | ERROR: Command exited with non-zero code: IF [ -f /etc/passwd ]
Error: build target: build main: bkClient.Build: failed to solve: process "/bin/sh -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c '[ -f /etc/passwd ] ; echo $? >'\"'\"/run/exit_code\"'\"''" did not complete successfully: exit code: 1
```

It seems fairly obvious what's happening and why (i.e., https://github.com/earthly/earthly/blob/main/earthfile2llb/converter.go#L530), but will leave that for the actual devs to confirm.

That said, though this behavior is undesirable and unexpected... is it *really* a bug?  Or is my usage of a non-root container (for building) actually an anti-pattern in the Earthy world, thus more of a "we just never documented this behavior since nobody would actually do that"?

**Comment by alexcb** [comment]
This sounds like a bug, If we change `exitCodeFile = "/run/exit_code"` to `exitCodeFile = "/tmp/exit_code"`, I suspect it'll work (unless you go out of your way to change the permissions on `/tmp`).

As a work-around until this gets fixed, it's possible to do:

```Earthly
FROM alpine
RUN adduser --system peon
RUN touch /run/exit_code && chmod 666 /run/exit_code #  <--- ugly workaround
USER peon

as-non-root:
    RUN whoami
    IF [ -f /etc/passwd ]
        RUN echo "got file as peon"
    END
```

**Comment by rrjjvv** [comment]
Ironically (coincidentally?), I hit this when trying to use a combination of [this](https://github.com/earthly/earthly/issues/988#issuecomment-870504677) and [this](https://github.com/earthly/earthly/issues/988#issuecomment-871907012).  My original code was actually `IF [ -f /tmp/exit_code ]`.  At first I thought I hit some kind of weird symlinking issue (where `/tmp` was symlinked to `/run`, which couldn't be written to), then saw it was a coincidence that we chose the same name.

That said, perhaps it would be better for your solution to use `/tmp/.exit_code`, or some variation that is unlikely to correspond to a filename someone would create themselves?  It sounds like your fix would address my inability to use `IF`, but would actually break my script on accident.  My failed tests would write "1" to that file, but then you'd overwrite with "0" (since the file existence check would pass).  When reading that file back in, it would appear that my tests actually passed.  Or would that `IF` statement be writing to a layer that's not "visible" to my code?

**Comment by alexcb** [comment]
> (I don't know if I was looking at an old revision or if my eyes were just playing tricks on me, but it looks like the current commit uses a fairly unique name.)

Yeah initially I had it as `/tmp/exit_code`, then `/tmp/earthly_exit_code`, then ultimately `/tmp/earthly_if_statement_exit_code` :sweat_smile:
