### ISSUE TITLE
Use custom buildkit image

### ISSUE THREAD

**Issue by isavl** [earthly/earthly#1552]
Hello.

I want to use custom buildkit image not pre-builded like
```
BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:c86fdb0bbe33876c7445805808c34402d82cbb37+build
```

Is there any way to use custom buildkit image?

Can I change BUILDKIT_BASE_IMAGE variable from command line or config file?

**Comment by vladaionescu** [comment]
Hi @isavl - at runtime, you can use `earthly --buildkit-image=...` or `EARTHLY_BUILDKIT_IMAGE` to cause Earthly to use a different buildkit for the daemon. Note, however, that Earthly uses a modified version of buildkit - so it wouldn't work to use an official buildkit for it.

If you want to rebuild earthly+buildkit with a different buildkit base image that is not an Earthly target (our build doesn't support this) you could temporarily modify this line of the Earthfile: https://github.com/earthly/earthly/blob/main/buildkitd/Earthfile#L16... or propagate that variable upwards in the main Earthfile to get access to it from the command-line.
