### ISSUE TITLE
autocompletion bug related to two directories one which is a prefix of the other.

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1558]
https://github.com/earthly/earthly/tree/acb/autocompletion-bug reproduces the bug which needs to be fixed.

To reproduce: checkout the above branch, then run `./earthly -P ./tests/autocompletion+test-targets-in-two-directories-prefix`

**Comment by shahpratikr** [comment]
@alexcb I couldn't find this branch in the repository. Could you please share any other steps to reproduce this?

**Comment by alexcb** [comment]
Thanks for looking into this; it turns out it was fixed in 7851ca08d5b1ef375d792c02935eed22fa3e2f83 but this ticket was never closed.
