### ISSUE TITLE
Capturing command output in ARG via $(...) causes "defined multiple times" error

### ISSUE THREAD

**Issue by tyrken** [earthly/earthly#1572]
The following cut-down Earthfile should repro this bug, which is that when building the "all" target via `earthly +all` I get "Error: build target: build main: bkClient.Build: failed to solve: image foo/bar:latest-dev is defined multiple times for the same default platform".

```earthly
VERSION 0.6
FROM alpine
WORKDIR /code

# Commenting out below DATESTR line avoids bug
ARG DATESTR=$(date)

ARG REPO=foo/bar
ARG TAG=latest

dev:
  SAVE IMAGE $REPO:$TAG-dev

prod:
  SAVE IMAGE $REPO:$TAG

all:
    BUILD +dev
    BUILD +prod
```

The bug was introduced in v0.6.3 (v0.6.2 works), originally I thought this was the same as #1565 as the workaround to set `conversion_parallelism` to 0 also avoids the bug, as does commenting out the `ARG DATESTR=$(date)` line.

Later I was suspicious it wasn't the same bug, and I've just tested `prerelease-9da18fb74108b1bf6e5c630d31c38a8fad571f38` built after #1565 was solved & still get my problem.  I'm using Ubuntu 20.04.3.

**Comment by vladaionescu** [comment]
Thanks for the detailed report!

**Comment by vladaionescu** [comment]
This is now fixed and will be available in the next release.
