### ISSUE TITLE
Buildkitd's `GIT_URL_INSTEAD_OF` variable set from an unrelated setting

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#1574]
This seemed obvious enough that I didn't think it warranted a reproduction:

https://github.com/earthly/earthly/blob/961d3c55e08e57591ee1e3761bd51534a4a857d7/buildkitd/buildkitd.go#L427-L428

I assume the value of `settings.GitURLInsteadOf` is what is *supposed* to be applied.

I didn't actually experience an issue because of this.  I was going through the source trying to answer a question of mine (totally unrelated to this setting) and spotted this.  Viewing the diff that introduced it (#1224) suggests a simple copy/paste accident.

**Comment by vladaionescu** [comment]
Good catch - `GIT_URL_INSTEAD_OF` is a deprecated feature (it's done a bit differently now). This is done differently now.

I guess now we know nobody is using this anymore as we haven't heard of anyone complaining.

**Comment by vladaionescu** [comment]
Thanks for reporting it!

**Comment by alexcb** [comment]
@vladaionescu do you think this warrants fixing, or should we just remove it entirely?

@rrjjvv does https://docs.earthly.dev/docs/guides/auth#git-authentication achieve what you are after?

**Comment by vladaionescu** [comment]
I think we can remove it altogether. It's been like that for quite a while.

**Comment by rrjjvv** [comment]
@alexcb I should have been clearer in my report.  I was not actually impacted by this; I was just reading the source and it was "obviously" wrong, so I wanted to report it before somebody actually ran into it.  (I actually do have a question around git auth, though it shouldn't be at all related to this report; I'll likely bring up in Slack at some point.  And my reason for looking at that code had nothing to do with git auth either.)

**Comment by alexcb** [comment]
perfect, we'll remove it then: https://github.com/earthly/earthly/pull/1609
