### ISSUE TITLE
Cannot access localhost from build step

### ISSUE THREAD

**Issue by wataruian** [earthly/earthly#1603]
Hi!

I am having issue accessing localhost when building from Earthfile, I tried curl to test the endpoint:
`curl -GET 127.0.0.1:5000/v2/_catalog` resulting in `curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused`

But I can access it directly from host and gets the result from the endpoint:
`{"repositories":[]}`

My `docker run` command from host:
```
docker run -d --restart=always -p 5000:5000 registry:2
```

My earthly config:
```
global:
  buildkit_additional_config: |
    [registry."localhost:5000"]
      http = true
      insecure = true
```

Am I missing something? This is just a minimal setup, but why would localhost be unaccessible from the build step?

Thanks in advance!

**Comment by alexcb** [comment]
All commands that are evaluated in a `RUN` are containerised, so `localhost` within the context of a `RUN` resolves to the container and not the host.

Are you able to pass your actual IP into the RUN statement via an arg?

**Comment by wataruian** [comment]
Will try that one! Thanks!

**Comment by wataruian** [comment]
@alexcb This one works. Thanks!

But what about if I want to name my local registry with a hostname, is it possible to update the `/etc/hosts` file from inside earthly? I am trying to update it within the build step but was not able to do so, due to permission issue even when root user is used.

My use case:
1. I have local k8s dev setup (`k3d`) that I am pulling from the local registry that I assigned a domain name for it. I updated my /etc/hosts for this:

My host file from my local machine:
```
127.0.0.1   local.registry.myhost
```

So in earthly this would be like, assuming my host IP is `192.168.1.9` :
```
192.168.1.9  local.registry.myhost
```

2. Similar to k8s setup, I have docker-compose dev setup that pulls from a named host

3. I know that I can do this by using the IP as the local registry host name. So that it will both work on earthly and my use case. But domain name is kinda neat looking instead of the host's IP (pardon my OCD).

4. With this, I can simulate our whole CI/CD process locally without having to refactor lines of code to adjust and pass the host IP when pushing/caching/etc images from the (CI registry/local registry)

Any help is appreciated.

Thanks in advance!

**Comment by wataruian** [comment]
Update: 

I see that there's a proposal for updating /etc/hosts in https://github.com/earthly/earthly/issues/1168 and the current work around. Any plans to push this?

Thanks!

**Comment by wataruian** [comment]
Update: The solution I mentioned regarding adding the host IP to `/etc/hosts` does not seem to work.

Adding `192.168.1.9  local.registry.myhost` to /etc/hosts still resolves to `127.0.0.1`. Why is that?

**Comment by alexcb** [comment]
> Any plans to push this?

possibly; unfortunately it's not a high-priority at the time. PRs would be accepted but it doesn't seem like a trivial change. I suspect we'll want to mimic what docker build --add-host does.

> Why not from inside earthly container?

buildkit mounts it as a read-only file

**Comment by wataruian** [comment]
I see. Closing this. Thanks!
