### ISSUE TITLE
Improve docs for build arg syntax in COPY

### ISSUE THREAD

**Issue by andyli** [earthly/earthly#1605]
```earthly
VERSION 0.6
FROM busybox

file:
    ARG --required NAME
    RUN touch "$NAME"
    SAVE ARTIFACT "$NAME"

# this causes `combining artifacts and build context arguments in a single COPY command is not allowed`
abc-failing:
    COPY +file/abc --NAME=abc .

# the following works fine
abc-ok:
    COPY --build-arg NAME=abc +file/abc .
```

**Comment by alexcb** [comment]
You will need to add parenthesis around it to make it work:

```Earthly
VERSION 0.6
FROM busybox

file:
    ARG --required NAME
    RUN touch "$NAME"
    SAVE ARTIFACT "$NAME"

abc-failing:
    COPY (+file/abc --NAME=abc) .
```

But it's an interesting idea to see if we could make them optional.

**Comment by andyli** [comment]
Ahha. Now you mentioned it I can see that there are parenthesis in the doc.

I would be nicer if the doc about `--<build-arg-key>=<build-arg-value>` can mention the required use of parenthesis.

**Comment by alexcb** [comment]
> It would be nicer if the doc about `--<build-arg-key>=<build-arg-value>` can mention the required use of parenthesis.

Excellent feedback!

We just added a section under the COPY's examples subsection: https://docs.earthly.dev/docs/earthfile#examples
