### ISSUE TITLE
Using remote, non-earthly buildkit instance

### ISSUE THREAD

**Issue by heavelock** [earthly/earthly#1619]
Hi!

I'm working on changing the structure of CI that our team is using and migrate it to wider, k8s hosted setup.
Said k8s setup is using non-root images for running everything and builds are done within centralized, remote buildkit that is not earthly.

Does earthly support such settings or using earthly/buildkit is the only supported building backend?

**Comment by alexcb** [comment]
earthly requires `earthly/buildkit`, which contains additional code that is not in the upstream `moby/buildkit` codebase. Whenever possible we submit generic bugfixes and features to the upstream codebase, but there's some features that are only in our fork.

**Comment by heavelock** [comment]
So there are rather no plans to make possible usage of the generic buildkit?

**Comment by vladaionescu** [comment]
Correct, we don't plan to support generic buildkit for now.

We might support running `earthly/buildkit` in rootless mode in the future, but in experiments so far we've had trouble getting `WITH DOCKER` working in rootless.

**Comment by heavelock** [comment]
Okay, thanks for your answers! I will close it for now not to pollute your issue tracker. Cheers!

**Comment by guitcastro** [comment]
Which features the `earthly/buildkit` have that are not at the upstream? I think worth to document it, because the documentation is not clear about it. I had the same doubt.
