### ISSUE TITLE
Is it possible to add multiple tags to saved images?

### ISSUE THREAD

**Issue by ovesh** [earthly/earthly#1652]
I'd like to use `SAVE IMAGE` and set multiple tags on the image, then push all the tags.

What's the simplest way to achieve that?

**Comment by vladaionescu** [comment]
Hi @ovesh - you can either do

```Earthly
SAVE IMAGE image1:latest image2:something image3:somethingelse
```

or

```Earthly
SAVE IMAGE image1:latest
SAVE IMAGE image2:something
SAVE IMAGE image3:somethingelse
```

**Comment by jrodrigv** [comment]
@vladaionescu I'd suggest to document this option because It is not obvious reading the docs

**Comment by vladaionescu** [comment]
Makes sense - thanks for the suggestion! https://github.com/earthly/earthly/pull/1964
