### ISSUE TITLE
Set environment variable from command stdout

### ISSUE THREAD

**Issue by idelvall** [earthly/earthly#1700]
Hi,
I need to build a docker image that is inside a monorepo with lots of images. The image to build is identified by a script (based on git diff), not coming from the user.

I am struggling to see how once identified the Dockerfile to build, I can pass such value to `FROM DOCKERFILE -f`

Is there a way to set an environment variable from the execution of a command? Something similar to what in bash would be `foo=$(bar)`....

Thanks guys

**Comment by vladaionescu** [comment]
Hey Nacho, you can try literally

```
ARG foo=$(bar)
FROM DOCKERFILE -f $foo
```

This functionality is not well documented it seems - we'll fix that.

**Comment by idelvall** [comment]
Thanks Vlad!
