### ISSUE TITLE
Provide an SVG Logo

### ISSUE THREAD

**Issue by brumhard** [earthly/earthly#1735]
Hi there,

This is just a nice to have thing, but there is an open issue at https://github.com/vscode-icons/vscode-icons/issues/2898 and it would be great if you could provide the earthly logo preferably as SVG.

**Comment by vladaionescu** [comment]
Hi @brumhard, here are SVG variants for the Earthly logo, although they are not square: https://drive.google.com/drive/folders/11svoJGaxkJ1i85bvSA5ww-UgfTEAdY2L?usp=sharing

**Comment by brumhard** [comment]
@vladaionescu thank you very much, I guess you could just crop the SVG to only include the logo, but maybe the guys at vscode-icons can help with that 👍🏻

**Comment by svg153** [comment]
Hi @vladaionescu 

Here are the fixed logos. As my friend [Ana](https://anaboria.wixsite.com/portfolio) told me, there were some problems with some layers. If you need more information I can tell her to write more details.

- The [32x32 svg icon](https://github.com/vscode-icons/vscode-icons/blob/8d7f62ff18141e8c41eb2cef1a4379fbed19b14a/icons/file_type_earthly.svg) was provided in the https://github.com/vscode-icons/vscode-icons/pull/2953
- Here is the original logo with Earthly text: [earthly-logo-long.svg](https://user-images.githubusercontent.com/9192031/157791130-acf7f211-cf60-4e1f-82bd-bfce94d3777e.svg)
