### ISSUE TITLE
Failure to start due to container name overlap

### ISSUE THREAD

**Issue by abennett** [earthly/earthly#174]
After performing a successful `earth +earth-darwin` build, the `earthly-buildkitd` container is unable to start when attempting to update due to the reuse of the container name.
```
Error: buildkitd new client: buildkitd new client (own): maybe start buildkitd: start: docker run earthly/buildkitd:v0.2.2: docker: Error response from daemon: Conflict. The container name "/earthly-buildkitd" is already in use by container "48b57c80b6bd5778bf438a54de0e1e79db09e3cf8d629d9270bd953ee291c481". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by alexcb** [comment]
Thanks for the report @abennett ; can you check if the buildkitd container is currently running, or perhaps in an exited state? (i.e. does `docker ps -a | grep earthly-buildkitd` show any output?)

Does `docker logs earthly-buildkitd` show any errors in the container?

If it's currently running (or exited); you can remove it with `docker rm --force earthly-buildkitd`, then try re-running earth to see if it correctly restarts it.

We made a fix to have earth remove exited containers in https://github.com/earthly/earthly/issues/152 however this has not yet been released.

**Comment by abennett** [comment]
Welcome!

Understood. This wasn't blocking for me. I just wanted to report a potential bug. Seems like it's handled. 👍
