### ISSUE TITLE
`HOST` bug or expected behavior?

### ISSUE THREAD

**Issue by wataruian** [earthly/earthly#1743]
I've been following the experimental feature to add host in /etc/hosts for the duration of the build (`HOST`) and found something (bug or expected behavior?):

1. I can't seem to pass dynamic value to `HOST`, if I tried passing the ARG it really tries to add `${ARG_NAME}` in /etc/hosts, I tried even setting as ENV, still the same. But hardcoding the value is working
2. `SAVE IMAGE` does not seem to respect what is in /etc/hosts. So I am unable to push to the local registry, which when you try to do `curl` in `+success-access-host` is successful.

```
VERSION --use-host-command 0.6

FROM alpine:3.14

ARG IP="192.168.1.9"
ARG DOMAIN="mylocalhost.com"

success-set-host:
  HOST mylocalhost.com 192.168.1.9

failed-set-host:
  RUN echo ${DOMAIN}
  RUN echo ${IP}
  HOST ${DOMAIN} ${IP}

success-access-host:
  HOST mylocalhost.com 192.168.1.9
  RUN apk update && apk add curl && curl -GET mylocalhost.com:5000/v2/_catalog

failed-push:
  HOST mylocalhost.com 192.168.1.9
  SAVE IMAGE --insecure --push mylocalhost.com:5000/some-image:1.0
```

Any , idea how to achieve this?

Thanks!

**Comment by dchw** [comment]
Right now, the `HOST` keyword only accepts static values. It seems reasonable to incorporate this.

**Comment by wataruian** [comment]
Looks like this is the one I am needing for the long time (did not even know this existed): 
`earthly global.buildkit_additional_args ["--add-host", "yourdomain.com:127.0.0.1"]`

I am not sure if `HOST` interfering with buildkit hosts is a wanted/good thing though, if needed it can be easily done with (`--add-host` - Thanks @dchw). 

But `HOST` being able to accept variables for DOMAIN and IP makes sense.
