### ISSUE TITLE
Cannot `GIT CLONE` from (private) repo that is also configured with a "matcher"

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#1757]
We have a private, self-hosted git server.  After an initial learning curve, we've been using this server just fine when referencing remote targets hosted on this server (when paired with the appropriate matcher in our config).  Normally any `GIT CLONE` that we do is from public sources (e.g., github).  This is the first time I've had a need to `GIT CLONE` from our internal instance.  (The repo doesn't have an Earthfile, so is not a target.)  These errors are with `0.6.11`, but recent changelogs don't suggest this is a recent change in behavior.

---
The pertinent part of our config:
```
git:
    git.example.com:
        pattern: 'git.example.com/([^/]+)/([^/]+)'
        substitute: 'ssh://git.example.com:7777/$1/$2.git'
        auth: ssh
```

The domain is obviously fake (as is the port), but we *do* use a custom port (I see hints in the source suggesting that could be significant).

I can give full outputs if they're needed, but a condensed version of the variations I've tried, grouped by the errors that result:
```
# fails with "unsupported git protocol 5"
GIT CLONE git.example.com/some/repo .

# all fail with "makeCloneURL does not support gitMatcher substitution"
GIT CLONE ssh://git.example.com:7777/some/repo .
GIT CLONE ssh://git@git.example.com:7777/some/repo .
GIT CLONE git@git.example.com:7777/some/repo .

# fails with "panic: runtime error: index out of range [1] with length 1"
# I know where/why, so don't waste your time searching
GIT CLONE ssh://git.example.com/some/repo .
```

After seeing that there is support for `.netrc` (though not documented), I tried iterations using https; some failed with similar errors as above, some errors were unique, but none worked (but I won't elaborate, as SSH is the end-goal and don't want to distract from that).

I also tried changing the "name" of the matcher (leaving the values under it intact) after seeing that it's used as a lookup, but that failed for yet other reasons (probably not a surprise to you).

Out of my attempts, the middle three are all scenarios that I would expect to work.  So is the `makeCloneURL does not support gitMatcher substitution` error:
1. a design decision (there's some reason why this is considered "a bad thing")
2. a technical issue (where there are non-obvious downstream ramifications)
3. "nobody asked for it, so we didn't implement it"

---

There are three obvious workarounds I can think of:
1. create a CNAME dedicated to cloning
2. dropping down to a `RUN git clone`
3. make that repo a target by dropping in an Earthfile

The first is likely not an option for most people (and not one I'd do, though I have the ability).  The second is an anti-pattern, per your docs, but available to everybody.  The third is also an option for me (in this case), but maybe not for an average user.  (You might assume that if an entity is using earthly that they're "all-in", but we're nowhere near that point.)

Since I don't know if this is a bug, "feature" (that I can't yet appreciate), or something in-between, are there any options for me in the short term?  Ditto for long term (if this is a will-not-fix or can-not-fix)?

**Comment by alexcb** [comment]
#1830 updates our docs to mention earthly will fall back to searching `~/.netrc` for https-based authentication.

**Comment by alexcb** [comment]
It was indeed a bug, I expanded our test cases to ensure `GIT CLONE ...` works with explicit `ssh://` urls: https://github.com/earthly/earthly/pull/1829/files#diff-8577e8fcf662bda742d45886ab0093cff90f35d13decb7414d572e1cb26314c6R5-R9

I expect to do a release early next week, which will include this fix.
