### ISSUE TITLE
Intermittent failures with inconsistent graph state error

### ISSUE THREAD

**Issue by GMaxera** [earthly/earthly#1768]
We are running
earthly version v0.6.7 30a39d9b10c429e5a34cdd753652baf9966a3b63 linux/amd64; Ubuntu 18.04
for our build and CI tests and we are experiencing intermittent failures with the following error message:

Error: build target: build main: bkClient.Build: failed to solve: failed to get edge: inconsistent graph state

What could be the reasons for this kind of error?
How can we debug to get more information?
and more important, how can we avoid (or fix) it?

To add more context, we are using Jenkins and we see this error only on Jenkins.

**Comment by vladaionescu** [comment]
Hi @GMaxera - I would try the following things, in this order:

* Reset the cache `earthly prune --reset` and see if it goes away forever
* Identify if in your regular operation of Jenkins there are cases when Buildkit gets killed regularly
* Increase the [cache size](https://docs.earthly.dev/docs/earthly-config#cache_size_mb) (just in case some work gets GC'd too early)
* Update to the latest Earthly (in case some newer buildkit fixed this issue)

If the above fail, it might be worth running earthly in debug mode for a while `earthly --debug` and sharing the buildkit logs here after this happens again: `docker logs earthly-buildkitd`.

Curious if the above help with anything...

**Comment by alexcb** [comment]
merging this into #2454
