### ISSUE TITLE
`EARTHLY_GIT_SHORT_HASH` not available when building remote targets

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#1787]
At first I thought this might be undefined or even designed behavior.  While crafting a 'proper' report framed that way, I found a clue that leads me to believe this is a bug (likely of the oversight/accident variety).  I actually started drafting a hypothetical PR as I went along, but came to a decision point between "follow the pattern (increasing risk/overhead)" or "minimize footprint".  The answer wasn't obvious, so I stopped there.  I think a "full" bug report would be noise, so I'll streamline the typical "how to reproduce/what I tried".

Very high level description of how I got here:
1. In repo X there is a target ("alpha") that declares `EARTHLY_GIT_SHORT_HASH`, which is then passed to another local target ("beta", in repo X) as a required argument with a different (non-reserved) name.  This works fine when running earthly exclusively in/against repo X.
2. In the spirit of reuse, I have repo Y that references that references target "alpha" in repo X.  It fails due to `arg not supplied for required ARG` in target "beta".

At first I thought it might be by design and related to crossing git boundaries.  That was not the case, since doing the same build using Y to reference X that was locally cloned (and using "local" targets) worked exactly as expected and desired.  Suspecting it was something specific to remote targets (and not git boundaries), and after seeing the docs for `EARTHLY_SOURCE_DATE_EPOCH` (that it would return zero if it had no better answer), I suspected it wouldn't fail.  I assumed it would succeed due to getting `0` (and satisfying the required argument).  I was very surprised at seeing a real, non-zero value.  After looking at code, I spotted the omission, and after seeing that `EARTHLY_GIT_HASH` (full version) works, I was/am confident it's a bug.

---
This appears to be the one and only place it is set (and is done "just like" the full sha; no special feature flags or anything): https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/variables/builtin.go#L47-L48

With local targets (irrespective of git boundaries)
https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/buildcontext/resolver.go#L99

the short hash is 'always' grabbed
https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/util/gitutil/detectgit.go#L70-L75

But with remote targets
https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/buildcontext/resolver.go#L89
many of the git attributes are returned https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/buildcontext/git.go#L142-L149
the short hash being an exception.  The return structure itself supports it, but the data that populates it
https://github.com/earthly/earthly/blob/88f94c5ed342a0162c202f5ce666d8350bf3fcc4/buildcontext/git.go#L155
does not.

Since I couldn't anticipate what you'd consider the "best" (or at least acceptable) solution, and since they'd all be fairly easy for you folks, I thought it best to stop with this report.

**Comment by alexcb** [comment]
Thanks for the detailed bug report -- I opened #1790 with a fix (and introduced a test for it).

**Comment by rrjjvv** [comment]
Nice, thanks a bunch!

**Comment by alexcb** [comment]
This has been released under [v0.6.13](https://github.com/earthly/earthly/releases/tag/v0.6.13).
