### ISSUE TITLE
No-cache command line option seems to be ignored

### ISSUE THREAD

**Issue by oliverkenyon** [earthly/earthly#1804]
earthly version v0.5.23 darwin/amd64; macOS

We hit this issue in our build system for a web application, I've stripped the steps down to a small scenario that can be tested very quickly. I realize that the actual use-case doesn't make sense, but this is because it was taken from part of a larger system.

Steps to recreate:
1. Create an Earthfile with following content: .
```test:
  FROM cypress/browsers:node14.17.0-chrome91-ff89
  RUN echo 0 > exit_code
  RUN echo "compTest exit code:" && cat exit_code
  ARG successful_exit = $(grep -Fx 0 exit_code)
  IF [ "$successful_exit" != "0" ]
    RUN echo "CompTests had non-zero exit code" && exit 1
  END
```

2. Navigate to directory in standard MacOS terminal
3. Issue command `earthly prune --reset`
4. Issue command `earthly +test`
5. Issue command `earthly +test` again
6. Issue command `earthly --no-cache +test`

Expected:
Step 5 should use the cache, but step 6 should not

Actual:
Step 6 seems to ignore the --no-cache option and uses the cache anyway

Additional:
I also noticed while testing this, that initially Earthly would never cache anything, after running the prune command in step 3, the cache started working. I guess it may have been full or corrupt. It would be great if a warning could be issued here to help understand why the cache is not being used.

**Comment by adamgordonbell** [comment]
Hi @oliverkenyon,
Testing this on v0.6.13 and step 6 is re-run. So it seems this issue has been resolved. 
Have you tried updating to a newer release?
