### ISSUE TITLE
Credentials leaked in log output after running failed command

### ISSUE THREAD

**Issue by mattt** [earthly/earthly#1807]
When I run the `earthly` command locally for a target that fails, the logged error message contains information from that project's `.env` file:

```console
$ earthly --version
earthly version v0.6.12 42816638ab3904a83bb2a73a377c740e38d15232 darwin/amd64; macOS
$ cat .env
SECRET=sw0rdfish
$ earthly +some_target
Error: build target: build main: failed to solve: Earthfile line 44:8 apply BUILD +test: earthfile2llb for +some_target: infinite recursion detected for target +some_target
in github.com/mattt/<repo>:main+some_target --SECRET=sw0rdfish`
```

It looks like this could be solved by #1801.

Separate from that, you might also consider adding logic to automatically redact secrets in known formats, such as [GitHub PATs](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/) or [`secret-token` URIs](https://www.rfc-editor.org/rfc/rfc8959.txt).

**Comment by alexcb** [comment]
Good point regarding redaction, I opened #1809 to track it.

Additionally, we're working on a new proposal for a `.secrets` file under #1808 if you have any feedback.
