### ISSUE TITLE
Allow a user to supply a custom `secret_provider` program to lookup secrets

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1808]
## The current state of `.env`

Earthly currently provides support for an `.env` file which is used to augment environment variables prior to parsing the earthly command line arguments. For example one can run earthly under verbose mode by using `earthly --verbose ...`, `export EARTHLY_VERBOSE=true && earthly ...`, or by storing `EARTHLY_VERBOSE=true` in `.env`.

The `.env` file is also used to storing build args that are automatically provided to build targets. For example consider the target

```Earthfile
foo:
    ARG abc
    RUN echo "abc is '$abc'"
```

One can pass a value for `abc` via `earthly +foo --abc=123`, or by setting `abc=321` in an `.env` file and by running `earthly +foo` without any additional command line arguments.

The `.env` file can also store secrets in it, For example:

```Earthfile
foo:
    RUN --secret password echo "my password is '$password'"
```

which can be passed via `earthly --secret password=keepitsecret +foo` or by storing `password=keepitsecret` in an `.env` and by just running `earthly +foo`.

### Problems

 - The `.env` file doesn't allow users to specify if a key is a) an earthly command line flag, b) a build-arg, or c) a secret. This leads to problems like #1736 
 - Including secrets in a `.env` file means it is not possible for users to commit their `.env` file. (Even though there are mixed-opinions on committing `.env` files to git, earthly should be flexible and allow users to make that decision on their own)
 - (edge-case) It is not possible to use a build-arg and secret which have the same name.
 
#### Edge-case example
 ```Earthfile
foo:
    ARG token
    RUN --secret secrettoken=+secrets/token echo "secrettoken is $secrettoken; token is $token"
```
different values can be supplied with: `earthly --secret token=abc +foo --token=123`; however, only a single key can be supplied in an `.env`.

## Proposal
Create two new files: `.secrets` and `.args`, which will be formatted the same as `.env`. The files will be used to store secrets and build-args respectively.

Two additional cli flags will be created: `--earthlyargs`, and `--earthlysecrets`, which could allow users to specify different files.

To maintain backwards compatibility, earthly will parse the `.env` looking for [command line flags](https://github.com/earthly/earthly/blob/92da4c8a4a49b72d897af1f4b0ad948d0e6d5ec8/cmd/earthly/main.go#L365-L630), if any additional keys are found, earthly will display a warning and allow them to be used as a build-args or secrets.

### Credential Helpers

Some users may want to store secrets in a password manager (e.g. vault, [pass](https://formulae.brew.sh/formula/pass), [mac keychain](https://blog.koehntopp.info/2017/01/26/command-line-access-to-the-mac-keychain.html) etc).

This has been [requested via slack](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1645723916417289), but never made it into a github issue.

Supporting shelling-out (e.g. `mytoken=$(pass Email/zx2c4.com)`) is problematic since users would have to provide escaping for `\$` and `\\`. So we could provide a different `=` opporator such as:

 - `mytoken := pass Email/zx2c4.com`
 -  `mytoken ``= pass Email/zx2c4.com` (should only be a single backtick)
 -  `mytoken <- pass Email/zx2c4.com`
 - `mytoken exec pass Email/zx2c4.com`
 - `mytoken eval pass Email/zx2c4.com`
 - `mytoken $( pass Email/zx2c4.com`

#### Catch-all
Users could supply a catch-all program that takes the token to lookup as the first argument, which could be defined as:

- `* := pass $1`
- `* <- pass $1`

or maybe even without any wildcard-notation:
- `<- pass $1`

**Comment by mattt** [comment]
Overall, I'm 👎 on this particular approach. In the case of secrets, I think there are better patterns for storing secrets, like the credentials helpers described above or [what Rails does](https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html). As for `.args` / `.earthlyargs`, I still don't think I understand the naming or motivation behind that.

The current story of `.env` is imperfect, but simple. I think simplicity is one of Earthly's best selling points, and worry that this kind of change would be at odds with that.

**Comment by alexcb** [comment]
> think there are better patterns for storing secrets, like the credentials helpers described above or [what Rails does](https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html).

That's an interesting idea to support a built-in encryption pattern. One would still need to make sure the `config/master.key` file is kept secret.

We decided to punt on the shell-out option as we need to better figure out how to interface with systems like vault -- should we support some sort of secrets discoverability via some sort of vault-plugin? The other issue is determining how this would work with a team of developers who might have different configs.

One potential generic solution with what we currently have is: `earthly --earthlysecrets <(/path/to/script)`
where `/path/to/script` would be a script that prints out `key=value` pairs. This requires some bash-magic, which makes it hard (impossible?) to include in an `.env`. I'm unsure if there's a way around this, like a `--earthlysecrets-bin /path/to/script` which would remove the bash-magic dependency.

> As for .args / .earthlyargs, I still don't think I understand the naming or motivation behind that.

The idea behind calling it `.earthlyargs` is so the various `.earthlyargs`, `.earthlysecrets`, and `.earthlyignore` files would be grouped together when listing the directory (when sorted by name).

The other reason for introducing `.earthlyargs` over `.env` is due to the backwards compatibility issue. It's conceivable to keep build-args in `.env` and move secrets to `.earthlysecrets`.

> The current story of .env is imperfect, but it's simple. I think simplicity is one of Earthly's best selling points, and worry that this kind of change would be at odds with that.

It's a toss-up; as you mentioned `.env` is imperfect; I think we initially made a mistake by over-simplifying it which resulted in the mix of build-args and secrets being treated the same (which leads to potential security issues).

**Comment by mattt** [comment]
> > think there are better patterns for storing secrets, like the credentials helpers described above or [what Rails does](https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html).
> 
> That's an interesting idea to support a built-in encryption pattern. One would still need to make sure the `config/master.key` file is kept secret.

The CLI could help take care of that by adding the key file to `.gitignore` when it's created.

> The idea behind calling it `.earthlyargs` is so the various `.earthlyargs`, `.earthlysecrets`, and `.earthlyignore` files would be grouped together when listing the directory (when sorted by name).

Speaking purely in terms of my own aesthetic preferences: 

`.earthlyignore` is fine because it matches `.dockerignore` (and the `Earthfile` ⟷ `Dockerfile correspondence). But anything beyond that feels like clutter. It begs for consolidation within a single configuration file, or namespacing in an `.earthly` directory. But I don't really think Earthly has enough knobs yet to justify that amount of overhead.

> It's a toss-up; as you mentioned `.env` is imperfect; I think we initially made a mistake by over-simplifying it which resulted in the mix of build-args and secrets being treated the same (which leads to potential security issues).

I'd encourage you to consider other ways to addressing any security concerns before jumping to additional configuration. 

For example, what if we established the convention that any entries in `.env` with keys in `SCREAMING_SNAKE_CASE` are treated like a secret (i.e. values are scrubbed in logging statements) and anything else is treated like a build argument?

**Comment by alexcb** [comment]
> I'd encourage you to consider other ways to addressing any security concerns before jumping to additional configuration.

You've won us over! By saying `.env` is broken and improperly mixes secrets and build args, but then turning around and suggesting that we've fixed the issue by storing secrets in plain-text under `.earthlysecrets` seems just as broken as it's insecure-by-default.

We're going to re-evaluate the structure of the `.earthlysecrets` file and look into a credential helper as a secret provider instead. 

We're going to deliberately prevent storing any unencrypted data within the git repo scope to prevent the possibility of it ever being accidentally committed.

**Comment by alexcb** [comment]
I put together #1822 which allows users to set:

```
global:
    secret_provider: <user-supplied-secret-provider>
```
in `~/.earthly/config.yml`

where `user-supplied-secret-provider` is a user-supplied program that looks like:

```
#!/bin/sh
set -e
if [ "$1" = "somekey" ]; then
    echo -n "some value"
    exit 0
fi
exit 2 # no secret found, allow earthly to continue looking up under `.env`, or on the command line via `--secret ...`
```

Currently there's no reference to which earthfile is being targeted; however in the future we might allow a user to specify a Earthfile `PROJECT` name, which will be passed to the `secret_provider` via an env such as `$EARTHLY_PROJECT_NAME`.

**Comment by mattt** [comment]
@alexcb I'm not sure how relevant this is, but do you think Earthly could use Git Credential Manager in some way? (If not directly, then as a model for how to do credential management?) https://github.blog/2022-04-07-git-credential-manager-authentication-for-everyone/

**Comment by alexcb** [comment]
@mattt I just had a quick glance -- Are you asking about using it to retrieve credentials for cloning via https? or in a more generic key/value store? In the case of using it to lookup credentials for accessing a git server via https, that could be useful. It would be a nicer option than storing username/passwords in `~/.earthly/config.yml` or `~/.netrc`.

Perhaps it could line up with work required for #1818

**Comment by brumhard** [comment]
Hi, just wanted to give some feedback based on [my implementation of a Hashicorp vault secret provider](https://github.com/brumhard/earthly-secret-provider-vault).

Generally, I think the interface to implement a secret provider is great and easy to implement for any language.
Things I found:
- passing args to the secret provider in the earthly config could help to pass config options
- I added a new config file at ~/.earthly/vault.yml to configure the provider since I couldn't add anything to the main config file, args are not settable and env vars are not available. Maybe it would be nice to define some best practices on how to pass config.
- The env vars `EARTHLY_PROJECT_*` described in https://github.com/earthly/earthly/pull/1822 are currently not available
- Maybe it would be nice to just pass the whole env to the secret provider

**Comment by alexcb** [comment]
> I think for most providers flags and env vars (both provided in the config field and the global ones) should be enough, so I guess the need for separate config fields/ config file just for the secret provider is not too big.

I didn't full appreciate the fact that it's now possible to also set these environment variables per-directory via the `.env` file, and they'll also be propagated to the secret_provider :tada:
