### ISSUE TITLE
Question: How to run a pipeline in Bitbucket with Earthly?

### ISSUE THREAD

**Issue by roccotr** [earthly/earthly#1842]
Is the private repository in the Bitbucket pipeline supported?

Simple Earthly run command on the Bitbucket.org pipeline returns this error

### Earthfile
```
VERSION 0.6
FROM node:17.8.0-alpine3.14 

all:
    RUN echo "Hello world"
```

### ERROR

```
+ earthly +all
           bootstrap | Bootstrapping successful.
 1. Init 🚀

           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
Error: build new buildkitd client: maybe start buildkitd: start: could not start buildkit: 1 error occurred:
	* command failed: docker run --privileged --env BUILDKIT_DEBUG=false --env BUILDKIT_TCP_TRANSPORT_ENABLED=false --env BUILDKIT_TLS_ENABLED=false --env BUILDKIT_MAX_PARALLELISM=20 --env BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371 --label dev.earthly.settingshash=c919e39463a37848 --mount type=volume,source=earthly-cache,dst=/tmp/earthly --publish 127.0.0.1:8373:8373/tcp --publish 127.0.0.1:8371:8371/tcp -d --name earthly-buildkitd --userns host [docker.io/earthly/buildkitd:v0.6.12:](http://docker.io/earthly/buildkitd:v0.6.12) exit status 125: docker: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed.
See 'docker run --help'.: exit status 125
```
Is there a way to run Earthly in Bitbucket?

**Comment by alexcb** [comment]
https://jira.atlassian.com/browse/BCLOUD-13420?focusedCommentId=2247002&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2247002 makes it sound like they do not support running docker with the `--privileged` (which earthly requires in order to start the `earthly-buildkitd` container which is where earthly runs the `RUN` commands).

**Comment by darkvertex** [comment]
Note that the above holds true for Bitbucket Pipelines's **cloud** runners, but [on-prem runners](https://support.atlassian.com/bitbucket-cloud/docs/adding-a-new-runner-in-bitbucket/) supposedly can declare a "step" with:
```
securityContext:
  privileged: true
```
to run in a `--privileged` context.

On-prem runners also don't cost you any monthly build minutes at all, which is a nice bonus.
