### ISSUE TITLE
how can i run on real workdir?

### ISSUE THREAD

**Issue by fgsoftware1** [earthly/earthly#1867]
how can i run earthly on real workdir like this on docker(%cd%:path)

**Comment by alexcb** [comment]
I'm not entirely sure I understand the question.

If it's regarding using a volume mount, earthly doesn't support mounting a directory from the host under a volume on the container.

earthly does have a [`LOCALLY` command](https://docs.earthly.dev/docs/earthfile#locally), which allows one to run commands directly on the host (without using any containers).

Perhaps you can expand your example if it's not related to the two above items.

**Comment by fgsoftware1** [comment]
> I'm not entirely sure I understand the question.
> 
> If it's regarding using a volume mount, earthly doesn't support mounting a directory from the host under a volume on the container.
> 
> earthly does have a [`LOCALLY` command](https://docs.earthly.dev/docs/earthfile#locally), which allows one to run commands directly on the host (without using any containers).
> 
> Perhaps you can expand your example if it's not related to the two above items.

im running on windows and i need linux tools. is possible to use LOCALLY?

**Comment by fgsoftware1** [comment]
@alexcb or anything i can do to compile and copy output to host

**Comment by fgsoftware1** [comment]
> `SAVE ARTIFACT <file> AS LOCAL <output-location>` will save a file to your local system; see https://docs.earthly.dev/docs/earthfile#save-artifact for more details. This is also covered under https://docs.earthly.dev/basics/part-2-outputs

i already saw this but im confused which path is host and wich is virtual

**Comment by brandonSc** [comment]
In the example `SAVE ARTIFACT <file> AS LOCAL <output-location>` , `<file>` is a file you have available inside your Earthly target, which you would copy out to your host at the `<output-location>` .

**Comment by fgsoftware1** [comment]
thanks
