### ISSUE TITLE
[Feature] Add an Option to Squash Layers on SAVE IMAGE

### ISSUE THREAD

**Issue by SimonAdameit** [earthly/earthly#1872]
## Description

Add an option to squash images when using the `SAVE IMAGE` command. This can be useful e.g. for regularly building base images with security updates baked in, like:
```earthly
FROM fedora:latest
ARG --required tag
RUN dnf upgrade
SAVE IMAGE --push --squash my-org/fedora-base:$tag
```

## Existing Work:
- Docker does have an experimental `docker image build --squash` [option](https://docs.docker.com/engine/reference/commandline/image_build/). It does squash all *newly* built layers into a single new layer.

- The tool [`docker-squash`](https://github.com/goldmann/docker-squash) allows squashing already existing layers in a docker image.

**Comment by vladaionescu** [comment]
Hey @SimonAdameit, I think this is very similar https://github.com/earthly/earthly/issues/584. Please let us know if not.
