### ISSUE TITLE
Add support for abstracting the creation of multiple targets

### ISSUE THREAD

**Issue by gpoulin** [earthly/earthly#1883]
While both `COMMAND` and the ability to reference targets/artifacts/commands from external file allow for some composability and reuse of code, there's some limitation. One of the main limitation is that there's no way to abstract the creation of multiple targets. This is particularly useful when you have multiple projects with a really similar structure. For example, in every python project that I have, I will want a target that install the dependencies, a target that run the test, a target that build the final image, ... 

In GNU Make, this type of abstraction can be accomplished using the `include` statement. Here's a project that illustrate how this statement can be used to remove a lot of boilerplate and make project easier to maintain.

So a suggestion to overcome this issue would be to add an `INCLUDE` command that would work similarly to `include` in GNU Make. It would basically inline the definition of the `INCLUDE`d file within the caller file.

For example one could put in `github.com/org/earthly-libs/poetry`
```
VERSION 0.6

base-poetry:
  ARG PYTHON_VERSION=3.8
  ARG APP_NAME=app
  FROM python:${PYTHON_VERSION}-slim
  WORKDIR /opt/${APP_NAME}
  ENV POETRY_VIRTUALENVS_IN_PROJECT=true
  ENV PATH="/opt/${APP_NAME}/.venv/bin:${PATH}"

install-deps:
    FROM +base-poetry
    RUN pip install poetry
    COPY pyproject.toml ./
    COPY --if-exists poetry.lock ./
    RUN poetry install --no-dev
    SAVE ARTIFACT .venv .venv

update-deps:
    FROM +install-deps
    RUN poetry update
    SAVE ARTIFACT poetry.lock AS LOCAL poetry.lock

dev:
    FROM +install-deps
    RUN poetry install
    COPY ${APP_NAME} ${APP_NAME}
    COPY tests tests

pytest:
    FROM +dev
    RUN poetry run pytest

cmd:
    FROM +dev
    ARG CMD=python
    RUN --interactive ${CMD}

# target that include only the virtualenv and the app code
app:
    FROM +base-poetry
    COPY +deps/.venv .venv
    COPY ${APP_NAME} ${APP_NAME}
```

 Which could be used in `github.com/org/patate/Earthfile` like
```
ARG APP_NAME=patate
INCLUDE github.com/org/earthly-libs/poetry --APP_NAME=${patate}

serving:
    FROM +app
    ENTRYPOINT uvicorn ${APP_NAME}.main:app --host=0.0.0.0 --port=8080

server:
    LOCALLY
    WITH DOCKER --load serving=+serving
        RUN docker run --rm -p 127.0.0.1:8000:8000 serving
    END
```

The difference with `IMPORT` is that target would be:
  - Defined target can be called from earthly. e.g.: `earthly cmd` should be valid and start an interactive python shell
  - Use the build context of the caller
 
I'm not convinced that the `INCLUDE` command suggested here is the best solution to the problem I outlined, but I'm convinced that Earthly should address the limitation.

**Comment by brandonSc** [comment]
Relevant Slack thread https://app.slack.com/client/T01DL290UJ3/C01DL2928RM/thread/C01DL2928RM-1651847438.639279

**Comment by vladaionescu** [comment]
Hi @gpoulin, we thought about this quite a bit and arrived at this somewhat different solution: https://github.com/earthly/earthly/issues/1891. For this particular use-case, the idea would be to use UDCs that can then be referenced from a number of targets. I know that it doesn't look related at first, but the feature was designed actually for this use-case. Looking for any feedback you might have!

**Comment by vladaionescu** [comment]
> If I understand the proposal correctly, it wouldn't allow to create more than one target at the time, but it would make COMMAND more powerful in a way that would allow to have a one-liner for every target.

Yes, exactly!

**Comment by vladaionescu** [comment]
Closing in favor of `--pass-args` proposal.
