### ISSUE TITLE
Proposal: `--pass-args`

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1891]
### Background

In commands such as `FROM`, `COPY`, `WITH DOCKER --load`, `BUILD` etc, args are implicitly passed into the referenced target if the target is in the same Earthfile. Otherwise, args need to be explicitly passed in.

In the `DO` command, all args need to be passed in explicitly regardless of whether the UDC is in the same Earthfile or not.

### Problem

This sometimes creates highly verbose interactions where many `ARG`s need to be declared just to be passed along.

Here's an example use-case. We want to reuse some build logic across several sub-projects of a monorepo. A common location (`../..` below) defines some common logic for subprojects to use. And here's what each sub-project might do to reuse that logic.

```Earthfile
shell:
    ARG ENVIRONMENT
    ARG AWS_PROFILE
    DO ../..+TERRAFORM_SHELL_AWS --ENVIRONMENT=$ENVIRONMENT --AWS_PROFILE=$AWS_PROFILE

deploy:
    ARG ENVIRONMENT
    ARG AWS_PROFILE
    DO ../..+TERRAFORM_DEPLOY_AWS --ENVIRONMENT=$ENVIRONMENT --AWS_PROFILE=$AWS_PROFILE

destroy:
    ARG ENVIRONMENT
    ARG AWS_PROFILE
    DO ../..+TERRAFORM_DESTROY_AWS --ENVIRONMENT=$ENVIRONMENT --AWS_PROFILE=$AWS_PROFILE
```

Even though there are only two args in each call, this ends up being pretty verbose, which is especially noticeable if this needs to be repeated across 10-20 sub-projects. For more args, this can get really painful.

### Proposal

The proposal is the introduction of a new option `--pass-args` for `DO`, `FROM`, `COPY`, `BUILD`, and any other command referencing a target. This option automatically passes any overriding args passed from above, or any new args declared in the current scope into the target or UDC. This allows the example above to contract to the following...

```Earthfile
shell:
    DO --pass-args ../..+TERRAFORM_SHELL_AWS

deploy:
    DO --pass-args ../..+TERRAFORM_DEPLOY_AWS

destroy:
    DO --pass-args ../..+TERRAFORM_DESTROY_AWS
```

Because the individual UDCs declare their own `ARG`s, through `--pass-args`, those `ARG`s can be influenced through the targets shown above.

#### `INCLUDE ../../something.earthly`

Including text from a file to be inlined in the current file, thus allowing us to import a number of targets and their recipes.

This has the disadvantage of having yet another system for importing that is distinct from `IMPORT`, yet somewhat similar, but not quite. A new user would probably not be able to tell the difference between `IMPORT` and `INCLUDE` just by looking at them.

In addition, `INCLUDE` doesn't allow parameterization - or at least not without introducing yet more concepts.

#### `IMPORT ../.. AS root (+something, +something-else)`

While this option is pretty short to type, it makes `IMPORT` work in a way that is not quite the same as the current behavior of `IMPORT`. In the current behavior, `IMPORT` only aliases a path reference (`../..` will be known as `root` in this file), whereas adding `(+...)` also introduces new code in the Earthfile. This distinction is similar enough, but also different enough to cause confusion to someone who is new to the Earthly syntax.

#### `INLINE ../..+something`

```Earthfile
INLINE ../..+deploy
```

or even

```Earthfile
INLINE ../..+*
```

This has the disadvantage that it's not as parameterizable as the UDC solution, and also `INLINE` as a word sends the wrong message. The recipes of those targets aren't exactly inlined.

#### `FROM --current-context ../..+something`

```Earthfile
deploy:
   FROM --current-context ../..+deploy
```

This idea reuses the recipe of `../..+deploy`, however it uses the current directory as the context for `COPY ./...` commands. Although this is pretty close to what we want, there are some open issues:

1. ../..+deploy is only meant for being imported from with a totally different context. If we want that target to never be executed without the default context, we'd have to introduce more concepts to block that off.
2. It's unclear which context to use if `../..+deploy` references other targets of its own. Any arbitrary choice that we would make would be unclear to someone new coming along and just reading the Earthfiles.

These two issues are resolved by the proposal above, since UDCs cannot be called on their own, and there's never an ambiguity about which context a UDC uses - it's always the callers context.

### Tangential issues

* #1890 This is a distinct proposal, but somewhat related to the above, as it enables passing targets as `ARG`s.
* #1575 This makes args more efficient as they don't bust cache as much, and allows builtin args to be used without a pre-declaration

**Comment by gpoulin** [comment]
What would be the possible interaction with https://github.com/earthly/earthly/issues/1890 ? Would it allow to also pass target/artifact implicitly? For example:

a/Earthfile
```earthfile
DO_SOMETHING:
  COMMAND
  ARG --target deps
  FROM deps
  RUN echo something
```

b/Earthfile
```earthfile
FROM python:3.8-slim
deps:
  COPY requirement.txt requirement.txt
  RUN pip install -r requirement.txt

something:
  DO --pass-args ../b+DO_SOMETHING
```

**Comment by vladaionescu** [comment]
Not implicitly in this case. In the example you've shown, it needs to be more obvious that `+deps` will be passed along, to avoid unexpected magic - it should be obvious what happens when reading the code, even for Earthfile newbies. (So you still have to do `DO --pass-args ../b+DO_SOMETHING --deps=+deps` in this case)

But the behavior of passing args more easily via `--pass-args`, combined with allowing targets and UDCs to be parameters themselves (with no string attached), gives the user everything they need to create highly reusable components for a monorepo setup.

**Comment by rrjjvv** [comment]
Would autocomplete follow that pass-through when giving completions (i.e., would `earthly +shell --<TAB><TAB>` offer up the arguments defined in the downstream target, despite not being defined in `shell` itself)?

It occurred to me that I don't know when exactly args are "highlighted" in the build output, but whatever the conditions, they are useful.  Would the placement of that highlighted output change as a result of using `--pass-args`?

I assume this would work transitively (they would get passed through the entire call chain, as long as each instruction uses `--pass-args` itself)?

Those answers don't take away from the value of this proposal, but could influence when to use it.

**Comment by vladaionescu** [comment]
> Would autocomplete follow that pass-through when giving completions

Yeah, that would be nice.

> It occurred to me that I don't know when exactly args are "highlighted" in the build output, but whatever the conditions, they are useful. Would the placement of that highlighted output change as a result of using --pass-args?

Currently, they are highlighted when the value has been overridden. So the same could apply to args that have been overridden and then passed through.

> I assume this would work transitively

Yes

**Comment by vladaionescu** [comment]
More specifically, it has been under the feature flag `VERSION --pass-args 0.7`. It'll most likely be part of `VERSION 0.8`.

**Comment by mitre-tm** [comment]
> More specifically, it has been under the feature flag `VERSION --pass-args 0.7`. It'll most likely be part of `VERSION 0.8`.

Please add it to https://docs.earthly.dev/docs/earthfile/features#feature-flags
