### ISSUE TITLE
Ability to run Earthly on an M1 computer that uses a remote x86 Docker

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1895]
### Setup

* User has an M1 laptop
* User uses a remote Docker daemon, which is running on an x86

### Problem

User wants to run Earthly locally, but as Earthly attempts to start the buildkit daemon in Docker, it pulls the arm64 version of the image, instead of the x86 version of it. This causes a crash as buildkit cannot be emulated.

### What should happen instead

* Earthly should detect that the Docker daemon is running on x86 (which may be different than the current host's architecture) and thus use an x86 version of the Earthly image.
* Earthly builds run on this kind of setup should default to use platform x86, when no platform is specified (it's possible that the new platform logic behind a feature flag already does this)

**Comment by vladaionescu** [comment]
Possible workaround

* Start an x86 Buildkit daemon via Docker using the instructions here: https://docs.earthly.dev/ci-integration/remote-buildkit
* Point Earthly to that daemon by setting `EARTHLY_BUILDKIT_HOST` env var

**Comment by dchw** [comment]
We actually already expose this information, too! Its in this structure:

https://github.com/earthly/earthly/blob/b0e5a0f191b765a79f60d9b2d5c20652109343d9/util/containerutil/types.go#L53-L62

And you get it (regardless of frontend) with this method on a given frontend:

https://github.com/earthly/earthly/blob/b0e5a0f191b765a79f60d9b2d5c20652109343d9/util/containerutil/frontend.go#L21

Implementations:
* Docker: https://github.com/earthly/earthly/blob/b0e5a0f191b765a79f60d9b2d5c20652109343d9/util/containerutil/docker.go#L77-L112
* Podman: https://github.com/earthly/earthly/blob/b0e5a0f191b765a79f60d9b2d5c20652109343d9/util/containerutil/podman.go#L78-L131

**Comment by vladaionescu** [comment]
Oh great - that's really useful! I'll play with this this weekend.

**Comment by vladaionescu** [comment]
Note that interactive mode might not work immediately in this setup and more tinkering may be necessary. Also, we should test that local registry-based outputs still work fine in this case.

**Comment by r-LaForge** [comment]
Digging into the problem more I think @alexcb is correct.
We are using an[ incorrect assumption](https://github.com/earthly/earthly/blob/90d79633da0859cae5ee9a2170b93a06ce4fc2d6/util/containerutil/shell_shared.go#L302) when running the buildkit image.

 - We assume the frontend host is the same as the current machine's architecture.
 - We assume the message will contain "Unable to find image" if and only if it supports the frontend.

```
$ docker run --rm --platform fake/arch scratch
Unable to find image 'scratch:latest' locally
docker: Error response from daemon: 'scratch' is a reserved name.
See 'docker run --help'.
```
