### ISSUE TITLE
Does'nt work in Windows

### ISSUE THREAD

**Issue by cupen** [earthly/earthly#1901]
```
\> git clone https://github.com/earthly/earthly
\> cd earthly
\> earthly +base

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build new buildkitd client: maybe start buildkitd: start: could not start buildkit: 1 error occurred:
        * command failed: docker run --privileged --env BUILDKIT_DEBUG=false --env BUILDKIT_TCP_TRANSPORT_ENABLED=false --env BUILDKIT_TLS_ENABLED=false --env BUILDKIT_MAX_PARALLELISM=20 --env BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371 --label dev.earthly.settingshash=c919e39463a37848 --mount type=volume,source=earthly-cache,dst=/tmp/earthly --publish 127.0.0.1:8373:8373/tcp --publish 127.0.0.1:8371:8371/tcp --platform linux/amd64 -d --name earthly-buildkitd : exit status 125: docker: invalid reference format.
See 'docker run --help'.: exit status 125
```
My docker desktop:
![image](https://user-images.githubusercontent.com/1221615/170509650-5e0d5f8b-8ba5-4793-9e92-c492d7c89352.png)

**Comment by adamgordonbell** [comment]
@cupen What version of Earthly are you running?

```
earthly --version
```

Are you able to startup buildkit yourself:

```
docker run --privileged --platform linux/amd64 -d --name earthly-buildkitd

```

**Comment by cupen** [comment]
@adamgordonbell  Hello, sorry for delay.
My earthly is build from  source@master.  Just `go build cmd/earthly`.

I'll try  it  after hours.
```
docker run --privileged --platform linux/amd64 -d --name earthly-buildkitd
```

BTW: I use earthly in Windows powershell, not WSL.

**Comment by adamgordonbell** [comment]
> BTW: I use earthly in Windows powershell, not WSL.

Right now, I believe Earthly needs to be run in WSL2 on windows. See here for more details: https://earthly.dev/get-earthly

**Comment by cupen** [comment]
> > BTW: I use earthly in Windows powershell, not WSL.
> 
> Right now, I believe Earthly needs to be run in WSL2 on windows. See here for more details: https://earthly.dev/get-earthly

Yes, it works in WSL2. Thanks.
