### ISSUE TITLE
Proposal: Build build target to a Dockerfile

### ISSUE THREAD

**Issue by ryuheechul** [earthly/earthly#1906]
First of all, thanks for the fantastic tool!
I've used it [only once](https://github.com/ryuheechul/eb-sqs-imdsv2/blob/main/Earthfile) so far and already quite impressed by how versatile and easy to learn and use.
_Who knew Makefile and Dockerfile needed a much improved child, brilliant idea!_

During my usage, thanks to Earthfile, of course I didn't need a Dockerfile on local (earthly running) environment but eventually I need a Dockerfile for the target environment (since I have a very little control of what I can do when build Docker image in AWS Elastic Beanstalk).

This time I just solved it in a not DRY way, which is duplicating
https://github.com/ryuheechul/eb-sqs-imdsv2/blob/e3b99e5512059cf046d16a1408c1b55b1a2e960b/Earthfile#L10
to https://github.com/ryuheechul/eb-sqs-imdsv2/blob/e3b99e5512059cf046d16a1408c1b55b1a2e960b/gen-docker-files.sh#L49-L61.

It would be great to have a feature that a target can be used to generate a Dockerfile via Earthly (think of it as rendering a Dockerfile instead of building an image) to avoid duplication cases like this one.

I don't think I was able to find this feature from the guide and reference.
If such feature already do exist, please let me know and kindly close the issue :)

**Comment by alexcb** [comment]
I'm not sure that's a feature that's realistically possible for earthly to implement (earthly provides features that exceed the capabilities of dockerfiles).

I'm curious why you can't simply use earthly to push an image to a remote registry? e.g. add a `SAVE IMAGE myuser/myimage:mytag` to your `dev:` target, then run `earthly --push +dev` (where `myuser` is your dockerhub user).

If you absolutely must use a dockerfile, is it possible to first perform an `earthly --push +dev`, then use a dummy dockerfile such as:

```Dockerfile
FROM myuser/myimage:mytag
```

**Comment by ryuheechul** [comment]
> I'm not sure that's a feature that's realistically possible for earthly to implement (earthly provides features that exceed the capabilities of dockerfiles).

I haven't given much thought about implementation and naively thinking that whatever possible could be rendered and that might be good enough but this might be a lazy thinking from my end.


> I'm curious why you can't simply use earthly to push an image to a remote registry? e.g. add a `SAVE IMAGE myuser/myimage:mytag` to your `dev:` target, then run `earthly --push +dev` (where `myuser` is your dockerhub user).

It's not about can or can't (in fact the Earthfile I referred also provides an option to build and push (for both amd and arm) as well). However I like the idea of preferring to bypass registry when it's possible and make sense. (For example, the image is a part of demo purpose and there is no "single" maintainer for the registry or don't want to force people to push images to registry or not assuming which target platform to be used, etc).

(I'm not debating if this is good or bad but simply trying to give you some use cases that I can think of)

> If you absolutely must use a dockerfile, is it possible to first perform an `earthly --push +dev`, then use a dummy dockerfile such as:
> 
> ```Dockerfile
> 
> FROM myuser/myimage:mytag
> 
> ```

It is a way to it, however, if not for actually building, just pointing to a image at docker-compose (in case of Elastic Beanstalk) would be sufficient. (That's the behavior of the repo in case of pushing method is selected)

**Comment by alexcb** [comment]
Thanks for the idea, but ultimately this is not a feature we can implement due to the required effort.
