### ISSUE TITLE
Proposal: EVAL

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1909]
We've been discussing this possibility for a while, but we never opened a tracking issue until now.

`EVAL <earthly-command>`

For example, the following is not possible without the eval (because the commands themselves cannot be args, and also because arg expansion cannot include multiple command parameters):

```Earthly
ARG cmd=COPY
ARG params=+src/src ./dest/
EVAL $cmd $params
```

This would evaluate and execute the Earthly command `COPY +src/src ./dest/`

Useful for when the command, or multiple options of the command are args. Works similar to bash eval.

**Comment by gpoulin** [comment]
Would that overlap with `BUILD`?

**Comment by vladaionescu** [comment]
No, because `BUILD` is only meant to trigger the build of a target, whereas `EVAL` is meant to trigger any arbitrary Earthly command. I've added an example to the description to make it a bit more clear about the intention behind `EVAL`.

**Comment by mwopfner** [comment]
I think this is related to #1077 where the keyword `EVAL` is also used in the same way but in a wider context.

**Comment by alexcb** [comment]
closing in favour of #1077 (might also be better to improve UDCs instead)
