### ISSUE TITLE
TextMate bundle causes IntelliJ IDEA to hang

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#1952]
I'd like to start by saying thanks for working on Earthly. It's very easy to use, and incredibly powerful.

I've installed Earthly's TextMate bundle by doing the following:

1. `git clone https://github.com/earthly/earthly`
2. Open IntelliJ, go to Settings -> Editor -> TextMate Bundles
3. Navigate to [`/contrib/earthfile-syntax-highlighting` ](https://github.com/earthly/earthly/tree/main/contrib/earthfile-syntax-highlighting) where I cloned the repo

<img width="778" alt="Screen Shot 2022-06-21 at 6 28 52 PM" src="https://user-images.githubusercontent.com/3904778/174925600-f19bf4a4-3db2-44b5-9457-7e2ecdc49ea0.png">

# Reproduction Steps

IntelliJ will consistently hang when pressing `<Enter>` at the end of a line. Minimum reproducible example:
```Dockerfile
VERSION 0.6
FROM alpine
WORKDIR /workspace
```

Put your cursor at the end of the the `WORKDIR /workspace` line. IntelliJ will hang forever.

![2022-06-21 18 44 13](https://user-images.githubusercontent.com/3904778/174925544-aa099a57-627e-412c-a541-61b60080fb70.gif)

This does not occur when I disable the TextMate bundle.

# Versions

- IntelliJ Build #IU-221.5921.22, built on June 21, 2022
- [TextMate Bundles](https://www.jetbrains.com/help/idea/textmate.html) 221.5921.22

Here are logs and diagnostic data generated by IntelliJ:

* [idea-logs-20220621-184740485990115615265798.zip](https://github.com/earthly/earthly/files/8953808/idea-logs-20220621-184740485990115615265798.zip)

**Comment by sharyar** [comment]
I am facing the exact same issue!
