### ISSUE TITLE
Strange behavior with `SAVE ARTIFACT`

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#1960]
I’m seeing some strange behavior with `SAVE ARTIFACT` . I’m trying to save an artifact both locally and to be used by other Earthfiles.

```
VERSION 0.6
FROM amazon/aws-cli:latest

COPY --if-exists ./cache/ /root/.aws/
COPY aws_config /root/.aws/config

dev.login:
    IF --no-cache ! aws sts get-caller-identity
      RUN --no-cache aws sso login
      SAVE ARTIFACT /root/.aws /aws AS LOCAL ./cache
    END
```

When I run `earthly+dev.login` in my `aws` project this works fine. The `cache` directory gets created.
https://ci.earthly.dev/logs?logId=cf8cd11f-c3cd-4e06-a77d-435859e4ad0c

When I run another target in another directory, I get an error:

```
build:
    ARG only
    FROM +init
    COPY ../aws+dev.login/aws /root/.aws/
    <truncated>
```
https://ci.earthly.dev/logs?logId=91ecbe9b-89e4-4acd-8693-1a7ae9194a2f

The `build` target works if I delete the `cache` directory and then run the `build` target again.

Is this a bug?

**Comment by brandonSc** [comment]
Hi @shepherdjerred - I'm trying to narrow it down to a minimal example that reproduces it. This is what I have tried:

`./Earthfile`
```earthly
VERSION 0.6

dev.login:
    FROM alpine
    WORKDIR /root
    RUN mkdir .aws
    RUN echo "configuration" > .aws/config
    SAVE ARTIFACT /root/.aws /aws AS LOCAL ./cache
```

`./inner/Earthfile`
```earthly
VERSION 0.6

build:
    FROM alpine
    COPY ..+dev.login/aws /root/aws
    RUN --no-cache cat /root/aws/*
```

If I run `earthly ./inner+build` it seems to work with or without the `./cache` directory existing. 

Is this example similar to what you are trying to do with copying your artifact? Maybe there's some other step in your Earthfile that's interfering with it?

**Comment by shepherdjerred** [comment]
Thanks for looking into this. I'll try to make a minimum example tomorrow.

**Comment by brandonSc** [comment]
Hi @shepherdjerred , apologies for not seeing your follow-up message from a little while ago. Appreciate the thorough test script and logs you attached. I'll take a closer look into this today and see if I can track down the issue.

**Comment by shepherdjerred** [comment]
Thank you for looking into it! I ran into a strange issue yesterday that may be related. If I can reproduce I'll attach details.

**Comment by shepherdjerred** [comment]
Okay, this is the best example I can come up with:

```earthfile
VERSION 0.6
FROM alpine

login:
    COPY +dev.login/aws /root/.aws
    SAVE ARTIFACT /root/.aws/credentials /credentials

dev.login:
  COPY --if-exists ./cache/ /root/.aws/
  RUN mkdir -p /root/.aws/ && touch /root/.aws/myfile
  SAVE ARTIFACT /root/.aws /aws AS LOCAL ./cache
```

`+dev.login` will create `./cache`.`+login` will not create `./cache`.

![2022-08-11 11 15 27](https://user-images.githubusercontent.com/3904778/184210604-5652a941-8f55-4b2a-b0b4-f4022c8d82ce.gif)

**Comment by brandonSc** [comment]
In your previous example, you have a target like this:

```earthly
create:
  IF --no-cache ! [ -e "/root/artifact" ]
    RUN --no-cache echo $(date) > /root/artifact
    SAVE ARTIFACT /root/artifact /artifact AS LOCAL ./artifact
  END
```

Is there any issue with moving the `SAVE ARTIFACT` to after the `IF` statement, like so?
```earthly
create:
  IF --no-cache ! [ -e "/root/artifact" ]
    RUN --no-cache echo $(date) > /root/artifact
  END
  SAVE ARTIFACT /root/artifact /artifact AS LOCAL ./artifact
```

**Comment by brandonSc** [comment]
And in your most recent example, are you expecting that since `+login` performs a `COPY` from `+dev.login`, that the `cache` would be outputted locally?

That might be a common point of confusion, but the local output only happens if you call the target that contains it directly. We have some docs [buried here](https://docs.earthly.dev/docs/earthfile#build) which show an example of doing a `BUILD` to force the local output.

**Comment by shepherdjerred** [comment]
Ah. That does seem to be the issue that I'm running into. The BUILD workaround isn't great because I'd have to run that before every target that requires AWS credentials... It seems like Earthly doesn't really handle this use case well.

**Comment by brandonSc** [comment]
Yeah, we use AWS quite a bit internally in Earthfiles here as well, and getting the auth setup right can be tricky. We actually ended up leveraging our own [Cloud Secrets](https://docs.earthly.dev/earthly-cloud/cloud-secrets) feature to store credentials, tokens, etc which makes it a bit different than how you're doing it with local artifacts. 

In your case though, one thing you could try, if you find the extra BUILD call annoying, is wrap it up in a UDC. Something like:

```earthly
LOGIN:
  COMMAND
  ARG dest
  BUILD +dev.login
  COPY +dev.login/aws $dest

login:
    DO +LOGIN --dest=/root.aws
    SAVE ARTIFACT /root/.aws/credentials /credentials
```

**Comment by shepherdjerred** [comment]
Oh, that UDC could work. Thanks for the tip

**Comment by shepherdjerred** [comment]
Ah! My solution was a bit convoluted, but I was finally able to get it working. Thanks for the help!
