### ISSUE TITLE
Support (or document usage of) Kaniko 

### ISSUE THREAD

**Issue by rubin55** [earthly/earthly#1967]
We're exploring Earthly. We're running on a GitLab environment which we don't fully control. One of the limitations of that environment is that they don't allow `dind`. We therefore use a custom `kaniko` image to build our docker images in GitLab.

The [CI Integration guide's GitLab example section](https://docs.earthly.dev/ci-integration/vendor-specific-guides/gitlab-integration) shows how to get started on GitLab with `dind`; is it technically possible to use `kaniko`? (note, I'm unsure if you're mostly using `dind` for building and pushing images, or if you're using it in a much broader sense that Kaniko couldn't cover).

Or is there another way to use earthly without requiring privileged containers?

**Comment by adamgordonbell** [comment]
Hi @rubin55, 

We are tracking this in #1144. Please give it a thumbs up as this is how we prioritize features. 

The issue is that buildkit needs to run in a privileged mode. `kaniko` could indeed be a possible solution to that. 

Remote build kits are also a solution to this.
