### ISSUE TITLE
Docker containers built with earthly don't run on Google Cloud Run

### ISSUE THREAD

**Issue by MinmoTech** [earthly/earthly#1975]
Hey!

As stated in the title, containers built with earthly don't run on [Google Cloud Run](https://cloud.google.com/run/) even if they run locally.

I assume this is because Cloud Run require the Docker Image Manifest V2 and don't support the OCI Image Format. [Source](https://cloud.google.com/run/docs/container-contract)

I made a minimal repo that has a Dockerfile and an Earthfile, the build with the Dockerfile runs on Google Cloud Run, the build with the Earthfile does not:
https://github.com/MinmoTech/earthly-ktor-google-cloud-run-test

Thanks for any kind of support!

**Comment by vladaionescu** [comment]
Hi @MinmoTech - can you also provide some information about the exact commands you use? What Earthly flags do you use and how do you push the image somewhere such that it gets to Google Cloud Run?

**Comment by MinmoTech** [comment]
Sure!
But it's very basic:
I build with `earthly +docker` (so no earthly flags), tag the image with `docker tag ktor-docker-sample:latest us-central1-docker.pkg.dev/<project-id>/<registry-name>/ktor-docker-sample:latest` and I push to google artifact registry with `docker push us-central1-docker.pkg.dev/<project-id>/<registry-name>/ktor-docker-sample:latest` (this requires setting up docker auth with `gcloud auth configure-docker us-central1-docker.pkg.dev` I believe).

I then select the image in google artifact registry and press "Deploy to Cloud Run" and then keep the defaults and deploy it.

**Comment by vladaionescu** [comment]
Great, thanks for those steps - very useful! We'll play around with Cloud Run from our end and hopefully, reproduce and then address the issue.

**Comment by vladaionescu** [comment]
Oh and also, another thing to try is to push from Earthly itself via `SAVE IMAGE --push`. Earthly uses the same auth configured via Docker, so hopefully, it should just work.
