### ISSUE TITLE
Builds that need interaction aren't able to export artifacts

### ISSUE THREAD

**Issue by pmembrey** [earthly/earthly#1980]
I've recently been working on getting OpenWRT building inside Earthly. One of the issues I've found is that often when the kernel is configured, it will prompt for user input to select new config items. If it detects that the terminal is not interactive, it exits with an error. This often won't get picked up until the firmware build is complete (which can take many hours) because errors are often ignored during development (this means your firmware doesn't fail just because one application can't be built - but if that thing is your kernel...)

Earthly does support `--interactive` which resolves the config issue nicely and makes it possible to interact with the build. Unfortunately the --`interactive` step must be the last step in a build target. In my case this means that once the firmware is built, I can't get it out of the container as an artifact as `SAVE` cannot be used after `--interactive`.

A workaround is to do something like:

```
RUN --interactive ./my_buid.sh && bash
```

This will drop you at a shell prompt and you can use `scp` or whatever to copy out the files you want. Obviously that's not ideal, but it does make it usable.

**Comment by vladaionescu** [comment]
This would be possible with `--interactive-keep`, however `SAVE ARTIFACT` is currently not allowed after `RUN --interactive-keep`. We should lift this limitation.

**Comment by pmembrey** [comment]
Yeah, if saving the image itself is okay, I imagine exporting the artefacts should be too. The `&& bash` workaround is, well, working, but I'd be happy to give this a test too :)

**Comment by adamgordonbell** [comment]
Fixed in https://github.com/earthly/earthly/issues/1980 @pmembrey!

I have a router running OpenWRT between me and the internet, so interested to see how this build goes.

**Comment by pmembrey** [comment]
Awesome!

I'm doing a test build at the moment, but once that completes, I'll pull the latest version of Earthly, and give it a run through :)
