### ISSUE TITLE
`EXPOSE` parse problem

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#1986]
The docs for `EXPOSE` say that it mirrors `EXPOSE` in docker and that is not true in at least one specific case.

All the following work in a dockerfile:
```
EXPOSE 8080:8080
EXPOSE 8080
EXPOSE 8080 8080
```
and all result (in my testing) with the following result in the image config:
```
$ docker inspect ktor2 | jq '.[].Config.ExposedPorts'
{
  "8080/tcp": {}
}
```
In Earthly, both of these
```
EXPOSE 8080
EXPOSE 8080 8080
```
give this:
```
docker inspect ktor-docker-sample | jq '.[].Config.ExposedPorts'
{
  "8080": {}
}
```
(note missing `tcp`, I'm unsure if that is an issue)

And :
```
EXPOSE 8080:8080
```
sets: 
```
{
  "8080:8080": {}
}
``` 
which is certainly wrong. 

See ticket #1975

**Comment by shahpratikr** [comment]
@alexcb can you please review PR https://github.com/earthly/earthly/pull/2083?
