### ISSUE TITLE
Q: How to access host's docker.sock on the step?

### ISSUE THREAD

**Issue by ismailbaskin** [earthly/earthly#2092]
I want to create a new container image in the host's local registry using [ko](https://github.com/google/ko). But it fails with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock` message. Is there way to bind host's docker.sock with using earhtly cli command?

**Comment by alexcb** [comment]
from https://docs.earthly.dev/docs/guides/docker-in-earthly

> It is currently not possible to mount /var/run/docker.sock in order to use the host Docker daemon. This goes against Earthly's principles of keeping execution repeatable. Mounting the Docker socket may cause builds to depend on the host Daemon state (e.g. pre-cached images) in ways that may not be obvious or easy to reproduce if the build were executed in another environment.

Perhaps you can experiment using `WITH DOCKER` to build your image, then export it to a tar.gz, then load it in via a `LOCALLY` target (which will run on your host, and thus have access).

**Comment by ismailbaskin** [comment]
Thank you @alexcb . 

I got the idea however, this makes it practically impossible to use applications that do not use Dockerfile, such as [ko ](https://github.com/google/ko) and [jib](https://github.com/GoogleContainerTools/jib), with Earthly. At best, it requires us to sacrifice the local build experience Earthly offers.
