### ISSUE TITLE
Build fail after upgrading to version 0.6.22 with EARTHLY_DOCKER_LOAD_REGISTRY: unbound variable

### ISSUE THREAD

**Issue by guitcastro** [earthly/earthly#2158]
Hello,

I just update from version 0.6.21 to version 0.6.22 and my build is not failing with:

`/var/earthly/dockerd-wrapper.sh: line 178: EARTHLY_DOCKER_LOAD_REGISTRY: unbound variable`

I am using remote-buildkit, and seems that is [caused by this commit.](https://github.com/earthly/earthly/commit/1ce574b0d7b2a69ca62fb689d11df4e9bd2a5e7d).

For now I am just using the 0.6.21.

**Comment by alexcb** [comment]
It's not obvious what's causing this issue; line 178 https://github.com/earthly/earthly/blob/1c8bcfbab64b9b52302ef63c897e6b989b88a794/buildkitd/dockerd-wrapper.sh#L178 doesn't reference `EARTHLY_DOCKER_LOAD_REGISTRY`, which seems odd.

Are there any more details you can share about how you are running your remote buildkit? or steps to reproduce the error?

**Comment by vladaionescu** [comment]
I suspect that your remote buildkit is on a different version? Can you confirm the version of your remote buildkit?

**Comment by guitcastro** [comment]
@vladaionescu You are right, upgrading to earthly/buildkitd:v0.6.22 fix the issue
