### ISSUE TITLE
Feature request: Allow using FROM DOCKERFILE with a generated Dockerfile and build context

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#219]
CC @zenyui

Proposed syntax

```Dockerfile
target-which-generates-dockerfile:
  ...
  RUN ... > ./my-docker-dir/Dockerfile
  SAVE ARTIFACT ./my-docker-dir

image:
  FROM DOCKERFILE +target-which-generates-dockerfile/my-docker-dir
  SAVE IMAGE ...
```

**Comment by zenyui** [comment]
For some added context, I'm using the [sbt-native-packager](https://www.scala-sbt.org/sbt-native-packager/formats/docker.html#tasks) in my scala/akka projects, which stages the necessary jars and generates a dockerfile for me.

**Comment by vladaionescu** [comment]
This will go out in the next release, @zenyui. We're targeting early next week.
