### ISSUE TITLE
Expose `--ci` status to targets

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#2261]
A very common pattern in my Earthfile is to check whether or not I'm in a CI environment. This is useful in so many scenarios:

- Should I pull AWS credentials from the command line with `--secrets`, or run `aws login` in Earthly
- Should I automatically fix linter errors (e.g. Prettier), or should I fail the build
- Should I write out files for CI, or echo certain extra data (e.g. for GitHub actions)?

I currently solve this by adding a `dev` argument to most of my targets. It'd be so much nicer if I could use the status of the `--ci` flag. It'd remove a lot of ARG declarations, and I wouldn't have to pass the value down to each target that I'm calling.

I'd love to see these two things:

- Expose the status of `--ci`, e.g. as a `$ci` variable
- Add some easy way of checking. `IF [ "$ci" = "true" ]` is okay, but something like `IF --ci` would be amazing

**Comment by alexcb** [comment]
This sounds somewhat similar to the `EARTHLY_PUSH` arg that gets set to `true` whenever the `--push` cli flag is given (e.g. `earthly --push +target`).

seems easy enough to implement a similar arg for `EARTHLY_CI`.

**Comment by alexcb** [comment]
If you (or someone else) wants to attempt implementing this, 1d9b9ab0310a3ff008b89401f87ee6350caaafe3 shows how `EARTHLY_CI` was implemented, and could be used as a rough guide to which parts of the codebase would need to be changed.

**Comment by shepherdjerred** [comment]
Awesome! I'll try to find some time, it looks like it would be relatively straightforward.

**Comment by shepherdjerred** [comment]
Wow thanks @miles170, this will really simplify my Earthfiles!
