### ISSUE TITLE
Allow targets to create secrets

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#2262]
I have a project that uses Pulumi and AWS to create infrastructure. Pulumi gives long-lived access tokens, whereas AWS gives short-lived (<24 hour) tokens.

I've created targets to run `aws login` and `pulumi login` which interactively prompt the user to login and stores these tokens. In CI I know the tokens ahead of time (or I have some other way to fetch the tokens outside of Earthly), so I can pass these values in via Earthly secrets.

This is not great for a few reasons:
- There's a lot of code dedicated to checking if I'm in development or in CI
- These credentials get saved in layers which means I can't safely take advantage of caching

I'd love there to be a way to dynamically set the value of Earthly secrets.

I'm not set on the implementation below, but it's one idea of how it could work.

For example:

```earthfile
# Regular use of secrets in a target, nothing special
up:
  RUN --secret_provider=AWS_SECRETS aws s3 create "my bucket"

AWS_SECRETS:
  SECRET_PROVIDER
  FROM aws
  RUN aws login
  # Earthly will capture stdout and save it as a secret named AWS_ACCESS_KEY_ID
  RUN --capture-secret=AWS_ACCESS_KEY_ID echo $AWS_ACCESS_KEY_ID
  RUN --capture-secret=AWS_SECRET_ACCESS_KEY echo $AWS_SECRET_ACCESS_KEY
```

```
# Earthly uses the AWS_SECRETS provider
earthly +up

# Earthly prefers the CLI secrets
earthly --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY +up
```

**Comment by vladaionescu** [comment]
This looks very similar to what is presented in https://github.com/earthly/earthly/issues/1298. Great minds think alike?

**Comment by shepherdjerred** [comment]
The implementation looks different (namely theirs is more thought out than the one I whipped up in 5 minutes), but the intent looks the same!

Any similar mechanism that lets me unify development and CI is good enough for me.

**Comment by vladaionescu** [comment]
Sounds good - I'll mark this as duplicate.
