### ISSUE TITLE
Allow log lines to be printed without target name

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#2268]
Earthly currently prefixes output with the name of the target, e.g.

```
                 +run | --> FROM ubuntu:jammy
```

This is extremely useful, but it is sometimes useful to print text without this prefix.

My use case is for outputting [annotations with GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions). GitHub Actions scans stdout for certain patterns which can be used to create annotations in pull requests, e.g. alerting a user that a certain line is not formatted correctly.

For example, `::error file=app.js,line=1::Missing semicolon` renders a comment on line 1 of app.js.

This doesn't work currently because Earthly prefixes lines.

It would be nice to define commands that shouldn't have the target name, e.g. `RUN --plain-output echo "::error file=app.js,line=1::Missing semicolon"`

**Comment by endigma** [comment]
Elaborating on this concept, perhaps a full "low output" mode:

- remove indenting on task related output
- omit fancy ascii table stuff (===========... :x: FAILURE [2. Build :wrench: ] ====== to [FAIL] Build for example
- write over docker output from `+base` and `+context` to remove it from final output
- replace 
```
 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————
```

with 

```
[RUN] Init
...
[RUN] Build
...
```

or something, perhaps the running build part can be omitted entirely and just use each target as the top level header

overall, I'd like to see something more like:
```
task: [deps] go mod download
task: [test] go test ./...
--- FAIL: Test (0.00s)
    main_test.go:10: 
                Error Trace:    /tmp/tmp.vx0AyCGwzF/part1/main_test.go:10
                Error:          Not equal: 
                                expected: true
                                actual  : false
                Test:           Test
FAIL
FAIL    part1   0.002s
FAIL
task: Failed to run task "test": exit status 1
```

or 

```
[INFO] Ready to run 2 tasks: deps and test.
[INFO] Running task deps…
[INFO] Running task test…
--- FAIL: Test (0.00s)
    main_test.go:10: 
                Error Trace:    /scratch/main_test.go:10
                Error:          Not equal: 
                                expected: true
                                actual  : false
                Test:           Test
FAIL
FAIL    part1   0.002s
FAIL
[ERROR] Command failed.
```

available as an alternative writer for earthly output

**Comment by shepherdjerred** [comment]
I think this has been complete with https://github.com/earthly/earthly/issues/3713
