### ISSUE TITLE
Improve docker image tagging

### ISSUE THREAD

**Issue by jume-dev** [earthly/earthly#2303]
Hello there,
we use [renovate](https://github.com/renovatebot/renovate) for updating our earthly images for our pipelines, but we'd like to pin it somehow to the official release.

Sadly, the docker hub repository contains what seems like to be the [nightly build or something](https://hub.docker.com/r/earthly/earthly/tags).

Would be great, if the label format could distinguish between the stable releases and the latest builds :)

**Comment by vladaionescu** [comment]
You can use `v0.6.27` as a stable version. The long version numbers are indeed pre-releases.

We should probably improve this, but perhaps a distinction is `v0.<any-number-above-1000>.*` is pre-release, whereas `v*.<any-number-below-1000>.*` is stable.

**Comment by alexcb** [comment]
#2142 appears to have resurfaced.

**Comment by idodod** [comment]
Hi @jume-dev ,
I believe this issue has been resolved. I think you should be only getting stable updates from this repo by default.
BTW Renovate allows use to limit the type of releases you get by using [allowedVersions](https://docs.renovatebot.com/configuration-options/#allowedversions).
So for example you can set a package rule to only get semver versions from earthly/earthly
