### ISSUE TITLE
Platform discrepancy with docker

### ISSUE THREAD

**Issue by ovesh** [earthly/earthly#2311]
I recently switched to working with an M1 mac. I have an Earthly target that started failing because of issues related to platform. I am specifying `--platform linux/x86_64` and getting some other errors. The same build with raw docker works.

I looked into those errors and I think it's because Earthly replaces `linux/x86_64` with `linux/amd64`. It's using `containerd/platforms.Normalize()` to do the normalization. I get the same errors if I run the raw docker build with `--platform linux/amd64`.

I think the fix should be to either _not_ normalize platform names (or give an option to avoid the normalization), or to make an explicit exception for `x86_64`.

**Comment by ovesh** [comment]
I'm happy to contribute the change if the maintainers agree on an approach.

**Comment by vladaionescu** [comment]
Hi @ovesh - we normalize the string, such that the build is more consistent (e.g. if a developer provides `--platform=linux/x86_64` vs another providing `--platform=linux/amd64`, it should behave the same).

If I were to guess, I believe that the Dockerfile build you're mentioning probably uses the builtin variable `$TARGETARCH` to perform some manual download of a binary (via `wget` or `curl`), where the platform is specified in the URL. If that's the case they may have been relying on the specific string `x86_64`.

One way to do that in Earthly might be to use an IF statement:

```Earthfile
ARG TARGETARCH
IF [ "$TARGETARCH" = "amd64" ]
  RUN wget <url-for-amd64-binary>
ELSE IF [ "$TARGETARCH" = "arm64" ]
  RUN wget <url-for-arm64-binary>
ELSE
  RUN false
END
```

Hope this helps!

**Comment by ovesh** [comment]
> I believe that the Dockerfile build you're mentioning probably uses the builtin variable $TARGETARCH

Nope. The way if affects me specifically is that python is failing to find a wheel (matching on arch) and tries to build one.

Is there a downside to allowing to skip normalization of the platform string? If this is opt-in then users should know what they're doing.

**Comment by vladaionescu** [comment]
> matching on arch

Any idea how python does that kind of matching? I don't really understand how the arch difference is seen by python in this case, if it's not via that builtin variable that I mentioned.

> Is there a downside to allowing to skip normalization of the platform string? If this is opt-in then users should know what they're doing.

The downside is that it makes builds less repeatable, and Earthly's goal, in general, is to make builds behave as similarly as possible across different environments.

I think that this kind of setting creates more variability in the way the Earthfile might be interpreted. So to avoid that, it would have to be a setting within the Earthfile itself. Not sure how that should be represented. Any thoughts?

One idea might be to expose the un-normalized platform as a different built-in ARG. But then, there's always the option of passing a regular arg for that too, if the user wanted, without having to make the Earthfile language more complex.

I guess it all depends on how exactly python is making that detection exactly.

**Comment by ovesh** [comment]
I take this back. I haven't been able to reproduce again and I think my diagnosis was incorrect.
