### ISSUE TITLE
Publish vscode syntax highlighting extension to Open VSX

### ISSUE THREAD

**Issue by jbalonso** [earthly/earthly#2312]
As a user of `code-server` (from the folks at coder.com), I would like to be able to use the Earthly VSCode extension, but it is currently not published in the [open-vsx registry](https://open-vsx.org/).

**Comment by felpeyu** [comment]
Here it goes @jbalonso!
https://open-vsx.org/extension/earthly/earthfile-syntax-highlighting

**Comment by jbalonso** [comment]
Awesome! I note, though, that it was published as version `0.0.0`, which might not be what you intended.
