### ISSUE TITLE
SAVE ARTIFACT AS LOCAL doesn't always save the artifact

### ISSUE THREAD

**Issue by benbenbenbenbenben** [earthly/earthly#2429]
I have a situation where a build seems to randomly drop artifacts.

I'm unable to share the actual Earthfile, but it has been happening for a while (including in v0.6.29 and the previous release).

It seems that it only happens when an artifact is saved by a target that is called by another target, roughly 5%-10% of the time in the particular Earthfile where it is happening. For what it may be worth said Earthfile has a little over 10 targets.

```Earthfile
# roughly the scenario that exhibits the behaviour
npm-package:
    RUN npm pack
    # this local file may not exist after a successful build
    SAVE ARTIFACT some-package-*.tgz AS LOCAL ./artifacts
npm-install-test:
    # this COPY into a target always works
    COPY +npm-package/some-package-*tgz /deps
    RUN npm i *.tgz
make-archive:
    RUN some zip command
    # this local file may not exist after a successful build
    SAVE ARTIFACT file.zip AS LOCAL ./artifacts
test:
   RUN npm test
   SAVE ARTIFACT *.xml AS LOCAL ./artifacts
end-to-end:
    BUILD +npm-package
    BUILD +make-archive
    BUILD +test
```

I haven't been able to reproduce this building a target directly (i.e. earthly +npm-package) but when I select +end-to-end it occasionally drops one or more files.

Interestingly the missing files, when referenced by other targets, are available, they just don't show up in the output.

Could it be that AS LOCAL files need to be re-saved in jobs that also reference them later in a build?

**Comment by vladaionescu** [comment]
Only targets referenced via a `BUILD` chain have local outputs. See ["What is being output and pushed"](https://docs.earthly.dev/docs/earthfile#description-6)

**Comment by benbenbenbenbenben** [comment]
> Only targets referenced via a `BUILD` chain have local outputs. See ["What is being output and pushed"](https://docs.earthly.dev/docs/earthfile#description-6)

Yeah I understand that, because that's exactly what I'm reporting doesn't work. The targets *are* referenced by a BUILD command, and they still fail to output.
