### ISSUE TITLE
Have a git commit date in addition to the git author date

### ISSUE THREAD

**Issue by jadinm** [earthly/earthly#2432]
Earthly provides a `EARTHLY_GIT_COMMIT_TIMESTAMP` to make builds that depends on commit which is quite nice

However, to each commit, there are actually two timestamp:
- a author date (what `EARTHLY_GIT_COMMIT_TIMESTAMP` is actually pointing to): when someone first creates a commit with `git commit`
- a commit date: the last edit of the commit (either through `git rebase` or `git commit --amend`)

In our workflow that relies on rebasing branches, this would be useful to have access to both timestamps

**Comment by vladaionescu** [comment]
Makes sense. Perhaps the one we have right now should be renamed to `EARTHLY_GIT_COMMIT_AUTHOR_TIMESTAMP` and the new one could take the name `EARTHLY_GIT_COMMIT_TIMESTAMP`?
