### ISSUE TITLE
COPY --if-exists +target/file works strange

### ISSUE THREAD

**Issue by backdround** [earthly/earthly#2541]
version: `earthly version 0.6.30 743687991d227f2f7e2e6ba11a90f443b4f99c67 linux/amd64; Arch Linux`
___
### Problem:
```Earthfile
COPY --if-exists +get-file/file ./file
```
doesn't copy a file even if target `+get-file` saves it as artifact.

___
### Full example:
```Earthfile
VERSION 0.6
FROM alpine:latest

get-file:
  RUN echo "hi" > ./file
  SAVE ARTIFACT ./file ./file

main:
  COPY --if-exists +get-file/file ./file
  RUN --no-cache cat ./file
  # cat: can't open './file': No such file or directory
```

**Comment by alexcb** [comment]
thanks for the report and repro-case -- I see the same thing here.
