### ISSUE TITLE
Git clone default ssh user should be git

### ISSUE THREAD

**Issue by EamonKeane** [earthly/earthly#2547]
Just leaving this here as it took a bit of debugging. It appears that if `earthly.config.$domain.auth.user` is left blank, the user used by `GIT CLONE` on Macos at least defaults to the logged in user (e.g. `eamonkeane`). This then attempts to clone using `ssh://eamonkeane@....`. 

This fails because the user (at least for gitlab and github) needs to be `ssh://git@...` or else the clone fails with permission denied.

https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

This occurs despite explicitly stating the user in the clone url e.g. `GIT CLONE ssh://git@...`. In the background the underlying command issued is `git clone ssh://eamonkeane`.

As a suggestion, the default user should be `git` if not specified in the earthly config.

**Comment by alexcb** [comment]
The decision to use the current user was chosen to be consistent with how `git` works; for example:

```
$ git clone github.com:earthly/earthly.git
Cloning into 'earthly'...
alex@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

however once you do `git clone github.com:earthly/earthly.git`, it works.

I agree it might be a bit of a surprise, but deviating from how `git` works would also be a surprise. Hopefully this ticket can be helpful for those who come across this issue.
