### ISSUE TITLE
Wrong date modified from SAVE ARTIFACT

### ISSUE THREAD

**Issue by ginkcode** [earthly/earthly#2663]
All of files or folders copied from SAVE ARTIFACT do not have correct date modified.

```
VERSION 0.6

build-base:
    FROM node:16-alpine
    WORKDIR /usr/src/app
    COPY package.json yarn.lock ./
    RUN yarn install
    COPY . ./
    RUN yarn build:prod
    RUN ls -lah /usr/src/app/dist
    SAVE ARTIFACT /usr/src/app/dist

build-prod:
    FROM nginx:alpine
    COPY +build-base/dist /usr/share/nginx/html/
    EXPOSE 80
    SAVE IMAGE demo-image:latest
```

Results from `ls -lah` still correct, which is the created time in `build-base`. But in the final image from `build-prod`, all files inside `/usr/share/nginx/html/` are reset to `16 Apr 2020 12:00:00`

**Comment by ginkcode** [comment]
Any investigation or suggestion to fix it please?
This bug causes an issue with cache on browser because the date modified is always used as `last-modified` header. Which gives browser info to know which file should be reloaded.

**Comment by alexcb** [comment]
This behaviour is intentional (to promote cache-reuse), if you want the timestamp to persist, use `--keep-ts`, described under the options of https://docs.earthly.dev/docs/earthfile#save-artifact and under https://docs.earthly.dev/docs/earthfile#copy

**Comment by stellarpower** [comment]
I think it would help for the documentation to add a note about this - there is a hint box below the main description. As the behaviour is unusual, I feel needing to read about the specific arguments to understand that this happens by default makes this easy to miss. When I am looking at documentation, I am going to read the description for each instruction, and then only go through the arguments if I feel I need to refine the behaviour of the command I am running, so I think it would be goo to mention this in the general description of the SAVE ARTIFACTS command
