### ISSUE TITLE
Gitlab sub group IMPORT does not work

### ISSUE THREAD

**Issue by EamonKeane** [earthly/earthly#2691]
I'm trying to `IMPORT` from a project in gitlab which is part of a sub-group (three slashes in the url, not the normal two for `org/repo`.).

This works fine:

```yaml
VERSION 0.6
IMPORT gitlab.com/earthly-technologies/earthly-demo:main
build:
    BUILD earthly-demo+build
```

While this doesn't work (at least in my case, I haven't got a public example on gitlab).
```yaml
VERSION 0.6
IMPORT gitlab.com/earthly-technologies/public-demos/earthly-demo:main
build:
    BUILD earthly-demo+build
```

The error is similar to this:
` failed to fetch remote gitlab.com/earthly-technologies/public-demos.git`

Which indicates that it's only expecting two slashes in the url (like the demo examples only show github with two slashes).

**Comment by vladaionescu** [comment]
I believe that this limitation can be worked around via some config. I've asked @alexcb to look into adding some docs on how to do this.

**Comment by alexcb** [comment]
I added an example specific to gitlab under #2814

**Comment by EamonKeane** [comment]
Thanks @alexcb that works!

**Comment by alexcb** [comment]
awesome! thanks for the extra test coverage :)
