### ISSUE TITLE
Request: provide way to silence/minimize warning around new `.env` behavior

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#2696]
Obviously this is specific to `0.7`.  The rationale for the change makes sense, as does the warning.  However, that warning causes a whole lot of unnecessary log noise even when you're doing things 'properly'.  An `.env` file is used by a number of tools.

I'm not sure if enumerating all of the file entries was a design choice, but if there was only one warning, I would have probably been too lazy to create this request.  But my 18-line `.env` file (not used for earthly) results in lots of noise that I "can't" eliminate.

I tried a `touch .arg` in the hopes that maybe the presence of `.arg` or `.secret` would eliminate the warnings, but it didn't.  I would think that the presence of one of those files (with non-zero length) would indicate someone is aware of the behavior change and is actively doing the new way (and that an existing `.env` is used by other tools).  Similarly, I think an empty file would indicate "yes, I've read the warning, and my empty `.arg` proves it, so you can stop bugging me about my `.env` that's used by my other tools".

Thoughts?

**Comment by alexcb** [comment]
good idea; #2713 will silence the warnings when either `.env` or `.secrets` exists.

**Comment by alexcb** [comment]
we'll get this released next week.
