### ISSUE TITLE
EARTHLY_GIT_(REF|BRANCH) built in ARG

### ISSUE THREAD

**Issue by wburningham** [earthly/earthly#2735]
Would it be possible to include an `EARTHLY_GIT_(REF|BRANCH)` built-in ARG similar to to `EARTHLY_GIT_HASH`?

**Comment by alexcb** [comment]
We would welcome a PR that implements these; take a look at #2462 for some inspiration.

**Comment by wburningham** [comment]
Thanks. I’ll take a look at that pull request.

**Comment by taytzehao** [comment]
@alexcb ,what should this ref|branch be representing?

**Comment by alexcb** [comment]
> @alexcb ,what should this ref|branch be representing?

`git rev-parse --abbrev-ref HEAD`

**Comment by miles170** [comment]
> > @alexcb ,what should this ref|branch be representing?
> 
> `git rev-parse --abbrev-ref HEAD`

`EARTHLY_GIT_BRANCH` has already implemented `git rev-parse --abbrev-ref HEAD`, what should `EARTHLY_GIT_REF` represent?
