### ISSUE TITLE
Proposal: Non-ARG variables

### ISSUE THREAD

**Issue by nelsam** [earthly/earthly#2808]
# Problem statement

As a developer writing complicated targets in an Earthfile
I want to define variables that are not controlled by user flags
So that I can write cleaner Earthfile code without causing confusion to CLI users of my targets.

# Description

With the advent of both `earthly doc` (which in the near future will document `ARG`s that are available to a target) and `SET`, we're coming up on a source of notable confusion:

1. Engineers often like to use variables to keep code clean
2. `ARG` is currently the only method of creating variables
3. All `ARG`s will show up as flags in `earthly doc` output
4. `SET` can be used to override CLI flags from end users

If I were writing an `Earthfile` using `VERSION --arg-scope-and-set 0.7`, there's a good chance that I'd have a few `ARG`s that I'm using for cleaner code, not for end users to actually use as flags. `SET` makes this even more tempting, because I don't have to risk a user overriding my variable from the CLI. For example:

```Earthfile
VERSION --arg-scope-and-set 0.7
FROM alpine

# test-golden runs a golden test
test-golden:
    ARG --required goldenFile
    ARG expected
    SET expected=$(cat $goldenFile)
    ARG actual
    SET actual=$(someIntegrationCommand)
    IF $actual != $expected
        RUN "golden test failed! diff:"
        RUN diff $actual $expected
        RUN exit 1
    END
```

In this scenario, the end user would see the following output from `earthly doc`:

```
TARGETS:
  +test-golden --goldenFile [--expected] [--actual]
      test-golden runs a golden test
```

When the end user calls the target using `earthly +test-golden --goldenFile=somefile.golden --expected=$(cat updatedOutput.txt)`, the user's `--expected` flag will be completely ignored, to the point that earthly will even use cached output from previous runs. If I were an end user, this would be quite confusing.

# Proposal

A new command, e.g. `LET` or `VAR`, which defines a variable that does not get overridden by user input and does not show up in `earthly doc` output, but otherwise works the same as `ARG`.

Thus, the example changes to:

```Earthfile
VERSION --arg-scope-and-set 0.7
FROM alpine

test-golden:
    ARG --required goldenFile
    LET expected=$(cat $goldenFile)
    LET actual=$(someIntegrationCommand)
    IF $actual != $expected
        RUN "golden test failed! diff:"
        RUN diff $actual $expected
        RUN exit 1
    END
```

Since I don't have to worry about end users trying to override my `expected` and `actual`, I no longer need to use `SET` to override CLI flags. And since `LET` does not impact `earthly doc` output, the end users will never think that they can pass `--expected` to the target and get it unexpectedly overridden.

Note that it is still on the author of the `Earthfile` to actually _use_ `LET` instead of `ARG` - this doesn't _prevent_ an engineer from creating confusing targets. It just provides a tool for engineers to author cleaner and clearer targets.

**Comment by mwopfner** [comment]
Having `LET`/`VAR` would be great for all the points mentioned. 

Would this replace `SET` for `ARG` so that `ARG`s could not be overridden?
And how to override a `LET` variable? Do I need `SET` for this?

If this proposal is implemented I actually think we do not/should not have `SET` for `ARG`s

**Comment by nelsam** [comment]
@mwopfner just as a heads up for you: we discussed this this morning and have decided to roll this change into the `--arg-scope-and-set` feature and also not allow `SET` for `ARG`s, as you suggested. I'll be working on it this week.

Thanks for the suggestion!

**Comment by mwopfner** [comment]
@nelsam I'm glad I could help. 
Thanks for your great work you do with earthly.
