### ISSUE TITLE
Auth Issue in Air Gapped Environment

### ISSUE THREAD

**Issue by donmstewart** [earthly/earthly#2827]
Earthly v0.7.2

We are trying to run our builds in an air-gapped environment but it is failing with the Earthly Auth call 

```
retrying http request due to unexpected error Get "https://api.earthly.dev/api/v0/account/auth-challenge": dial tcp: lookup api.earthly.dev: i/o timeout
```

Is this possible as currently there is no way for these machines to get to the internet.

**Comment by alexcb** [comment]
As a short-term work-around, any chance setting `SSH_AUTH_SOCK=""` prevents this?

**Comment by alexcb** [comment]
extra context: performing a `earthly account logout` should in theory disable the ssh-based auto-login; however, it appears it may not actually be working.

**Comment by mologie** [comment]
Unfortunately neither `earthly account logout` nor setting SSH_AUTH_SOCK to an empty value silence the errors or remove the delay for me on macOS.

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/pull/3034 implements a fix for this.

Once it's released a user can run earthly account logout, or touch ~/.earthly/do-not-login-automatically which will disable the auto-login functionality.
