### ISSUE TITLE
Feature: Assertions

### ISSUE THREAD

**Issue by Itxaka** [earthly/earthly#2881]
Sometimes when building big stuff, especially when its multiplatform, I find myself wondering if everything is correct in my earthfile. Were the proper files copied somewhere? did this FROM pick the proper arch or version?

Usually when testing big changes to my earthfile I manually add several things to check and exit if something is wrong like:

```
IF [ ! -e /some/file ]
	exit 1
END
```

I found that once an earthfile is big enough or has a lot of targets, any changes that I introduce can lead to issues in my final build. As our test env results in several ISOs being build, along with several OCI artifacts and those require heavy and long testing, I would find myself more happy if there was something to test during my build that everything is on its place in a more ...shorter way.

Something like

```
ASSERT [ -e /some/file ]
```

So I could introduce it in critical places to verify that my changes are not breaking everywhere. Kind of what c++ does with the assert?

Also I could do with a plugin system to extend Earthfiles with custom keywords so I could implement this and more myself :D

**Comment by Itxaka** [comment]
That is a good point, but my main issue with that is that those RUN will get into the final layer, won't they? While the IF won't, which gives a cleaner layers in the final image.

**Comment by nelsam** [comment]
Ah, fair point. You can still use the `IF` in the user-defined command though.

```
VERSION 0.7
FROM alpine:3.15

ASSERT:
    COMMAND
    ARG --required test
    IF ! test $test
        RUN exit 1
    END

foo:
    RUN echo "foo" > foo.txt
    DO +ASSERT --test="-e foo.txt"
    SAVE IMAGE foo

bar:
    RUN echo "foo" > foo.txt
    SAVE IMAGE bar
```

^^^ when I run `earthly +foo` and `earthly +bar`, `docker image ls` shows the same `IMAGE ID` for both of those.
