### ISSUE TITLE
Secret ids allowed in `--secret` are not allowed in `.secret` files

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#2883]
Given
```Earthfile
VERSION 0.7
FROM alpine

test:
    RUN --mount=type=secret,id=super-secret,target=secret cat secret
```
one can use a hyphenated secret id from the command line just fine
```
$ echo 'oops' > hush && earthly --secret-file super-secret=hush +test
<snip>
              alpine | --> Load metadata alpine linux/amd64
               +base | --> FROM alpine
               +base | [----------] 100% resolve docker.io/library/alpine@sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126
               +test | --> RUN cat secret
               +test | oops
              output | --> exporting outputs
<snip>
========================== 🌍 Earthly Build  ✅ SUCCESS ==========================
```
but doing the equivalent with a `.secret` file fails
```
$ echo 'oops' > hush && echo 'super-secret=hush' > .secret && earthly +test
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: read .secret: unexpected character "-" in variable name near "super-secret=hush\n"
```

I've only tried in `0.7.4`, but I doubt it's new.  I know I've used hyphenated ids (from the CLI) ever since I started using earthly.  I know this is the first time I've tried using them in `.secret` files.  I'm not sure if I ever tried in `.env` files (pre-`0.7.x`), but probably not.  My hunch is that it's not a technical limitation, but that secrets used to be treated similar to args, which in turn are treated similar to environment variables (and if I recall correctly, POSIX doesn't guarantee support for hyphens).

Nearly all of the earthly docs use underscores, but there is at least one place where a hyphen is used, which implies it's not disallowed: https://github.com/earthly/earthly/blob/efc0c582b4dfb380106cb5977a9abd898c80cb69/docs/earthfile/earthfile.md?plain=1#L245

**Comment by rrjjvv** [comment]
I realized shortly after posting that the title claims this impacts `--secret`, though my reproduction uses `--secret-file`.  I am very confident this is applicable to `--secret`, but I can edit my reproduction if you want.

Furthermore, after executing my reproduction to use only underscores, I see that fixing the issue (to allow names with hyphens in the `.secret` file), while needed, won't actually fix my original issue.  If the issue (as stated) were to be fixed, the result that would be output is `hush` (the name of the file), rather than `oops` (the _content_ of the file, which is what I really wanted).  I may file a separate issue/request for that.

**Comment by alexcb** [comment]
I think it's best to display a warning in this case, and eventually we will turn it into an error if a users passes in a secret that doesn't conform to the existing ARG naming scheme -- a name that is a valid shell environment variable (i.e. `[a-zA-Z][a-zA-Z0-9_]*`)
