### ISSUE TITLE
Way to disable reading .env file

### ISSUE THREAD

**Issue by justin-calleja** [earthly/earthly#2890]
`earthly` version I'm using:

```txt
earthly version v0.7.4 a1c46ca2b75f21a4948fd53b5464de5a2bd90372 darwin/arm64; macOS 13.2 homebrew
```

### Issue:

When I run `earthly` to run a task in a directory with a `.env` file in it - I get log messages like this one:

> unexpected env "SOME_ENV_VAR": as of v0.7.0, --build-arg values must be defined in .arg (and --secret values in .secret)

I cannot remove the `.env` file as it's being used elsewhere but I have no  way of telling `earthly` not to use it.

### Work-around

As suggested by @adamgordonbell  on Slack, one work-around is to use the `cli` arg `env-file-path`. E.g. this works (avoids picking up the `.env` file):

```sh
earthly --env-file-path=.mytmp/.envEmpty -P +tmp
```

but it requires adding an empty file to point to.

It would be nice to have a cli option / env var to disable picking up `.env` file or just not pick it up by default if it's no longer the preferred way of doing things.

Thank you

**Comment by alexcb** [comment]
This has been addressed in #2713

```
touch .arg
```

will silence these messages.

We may eventually remove this warning in some time; however the `.arg` and `.secret` files are a fairly new addition, so we want to keep this warning in place to give people time to transition.
