### ISSUE TITLE
Recommended user for self-hosted Actions installation?

### ISSUE THREAD

**Issue by dtanner** [earthly/earthly#2891]
I'm administering GitHub Actions self-hosted runners, and the runners are currently configured to run as a non-root user.  This causes the `setup-earthly` action to fail because `/home/ghactions/actions-runner/_work/_temp/03189a7c-2269-457e-bf2b-da9bfee49dae.sh: line 1: /usr/local/bin/earthly: Permission denied`

By default, Runners aren't allowed to be installed as root.  I don't know why this is specifically. I do see it's _possible_ to install runners as root using the `RUNNER_ALLOW_RUNASROOT` env variable.  These are ephemeral runner VMs so no security concerns from that perspective.

Is there a suggested technique advised for earthly? i.e. Is it feasible to install earthly as a non-root user, or do you recommend installing the runners as root?  Thanks.

**Comment by alexcb** [comment]
you could try modifying the installation found on https://earthly.dev/get-earthly : 

```
sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
```

to use a different location?

**Comment by dtanner** [comment]
AFAIK the location doesn't matter; it's that the instructions indicate installing it as root.  I don't know if that's a hard requirement, or if things should work fine installing it as the Actions user.?

**Comment by alexcb** [comment]
earthly can run without root; however it will attempt to create a privileged docker container. Some users are running earthly with rootless podman; however features like `WITH DOCKER` might not work in those cases.

**Comment by dtanner** [comment]
ok thanks - i'll give it a whirl.
