### ISSUE TITLE
[BUG] Starting from v0.7, all ARG parameters are invalid

### ISSUE THREAD

**Issue by mritd** [earthly/earthly#2899]
I recently upgraded Earthfile to v0.7, most of my Earthfile relies on ARGs to generate dynamic parameters; 
but after the upgrade all ARG configurations are invalid, I tried everything in the documentation and still can't get it to work.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/13043245/234209866-3899c7c0-f8a4-4515-b5e0-e56f3ae2a49f.png">

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/13043245/234209990-afd653e6-45ee-467a-b181-759169892ea4.png">

**Comment by alexcb** [comment]
can you submit a smaller reproduction case in text (that can be copy and pasted).
