### ISSUE TITLE
Appending to ENV idiom should work that same as Docker Files

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#290]
https://docs.earthly.dev/earthfile#description-15 mentions that ENV should work the same was as dockerfiles. This is not the case when attempting to append to ENV values such as the following example:

```
FROM python:3
test:
  ENV PATH=/hello/bin:$PATH
  RUN echo path is $PATH
```

Here the $PATH  in `ENV PATH=/hello/bin:$PATH` is expected to be build argument which is not what someone experienced with dockerfiles would expect.  

My suggestion would be to only treat $PATH as a build argument if it is defined as one with the `ARG` command.

**Comment by vladaionescu** [comment]
Not sure what you mean here. Do you mean that your host system's `$PATH` is used? Can you explain in the format 1. what is expected to happen and 2. what happens instead?

**Comment by jimmykarily** [comment]
Just in case someone else also stumbles on this, [the fix](https://github.com/earthly/earthly/commit/33fd94971cd9a45aded9bf53b556882a266df431) relies on `ENV` to be set on the base image. If not it will still not work. E.g.

```
VERSION 0.6

test:
  FROM opensuse/tumbleweed

  RUN echo $PATH
  ENV PATH=$PATH:/go
  RUN echo $PATH
```
produces:

```
...
               +test | --> RUN echo $PATH
               +test | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
               +test | --> RUN echo $PATH
               +test | :/go
...
```

Replacing the base image with `FROM ubuntu:jammy` makes it work:

```
               +test | --> RUN echo $PATH
               +test | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
               +test | --> RUN echo $PATH
               +test | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go
```

The difference is that `ubuntu:jammy` image has this:

```
      "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ],
```
while `opensuse:tumbleweed`:

```
      "Env": null,
```

Maybe this is a shortcoming inherited from Dockerfile (https://github.com/moby/moby/issues/29110), not sure.

**Comment by alexcb** [comment]
It sounds like we need to force a shell out to evaluate the value inside the container.

Perhaps this should be a fall-back heuristic for cases when the env doesn't exist in the image config (but instead is generated by the executing `/bin/sh` inside the image).

e.g.

```
VERSION 0.7

test:
  FROM opensuse/tumbleweed

  RUN echo $PATH
  ENV PATH=$(echo $PATH:/go)
  RUN echo $PATH
```

(or `VERSION --shell-out-anywhere 0.6`)

produces

```
 opensuse/tumbleweed | --> Load metadata opensuse/tumbleweed linux/amd64
               +test | --> FROM opensuse/tumbleweed
               +test | [----------] 100% resolve docker.io/opensuse/tumbleweed@sha256:3a1a6ad0ad5950674c2a958b34ec46d440e043b4c236cf0baeaf473b63f542bf
               +test | --> RUN echo $PATH
               +test | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
               +test | --> expandargs echo $PATH:/go
               +test | --> RUN echo $PATH
               +test | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go
              output | --> exporting outputs
```
