### ISSUE TITLE
create script to install docker-in-docker

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#291]
Currently the `WITH DOCKER` feature requires a user to use the existing `docker:dind` image.

It would be nice if a user could use whatever image they want, and when the RUN command starts under a WITH DOCKER layer, earth would attempt to install dind if it's not detected.

**Comment by agbell** [comment]
Partial solution for alpine:
https://github.com/earthly/earthly-example-scala/tree/dind-alpine/AlpineJDK

**Comment by alexcb** [comment]
This has been implemented.
