### ISSUE TITLE
support for git-lfs

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#2921]
earthly does not correctly pull in large files which are tracked via [git-lfs](https://git-lfs.com/).

Consider a repo setup as:

```
git init --initial-branch=main .
echo foo > small-file
git add small-file
git -c commit.gpgsign=false commit -m 'a small regular file'
git remote add origin git@example.com:user/repo.git
git push --set-upstream origin main

git lfs install
echo "pretend-this-is-really-big" > large-file
git lfs track large-file
git add large-file

git -c commit.gpgsign=false commit -m 'a large file tracked in lfs'
git push

cat>Earthfile<<EOF
VERSION 0.7
small:
  FROM alpine
  COPY small-file .
  RUN --no-cache cat small-file

large:
  FROM alpine
  COPY large-file .
  RUN --no-cache cat large-file
EOF

git add Earthfile
git -c commit.gpgsign=false commit -m 'test earthfile'
git push
```

When you run `earthly example.com/user/repo+large`, you will incorrectly get:

```
hack/hack/hack+large | --> RUN --no-cache cat large-file
hack/hack/hack+large | version https://git-lfs.github.com/spec/v1
hack/hack/hack+large | oid sha256:d83792ea398308233d1b957ec27653705f6a6254751d9ff68727042be6e3df56
hack/hack/hack+large | size 27
hack/hack/hack+large | Completed in 92.498343ms
```

Rather than the expected:

```
hack/hack/hack+large | --> RUN --no-cache cat large-file
hack/hack/hack+large | pretend-this-is-really-big                   <-- expected real contents
hack/hack/hack+large | Completed in 92.498343ms
```

This occurs because buildkit is performing a basic `git clone git@example.com:user/repo.git` rather than a `git lfs clone git@example.com:user/repo.git`.

**Comment by alexcb** [comment]
Here's a more complete example that replicates the issue; note that a self-hosted repo is used as github charges for lfs.

```
#!/bin/sh
set -e

TESTPATH=/tmp/my-lfs-test
IP=192.168.0.115   #  <---- CHANGE THIS AS REQUIRED

rm -rf "$TESTPATH"
mkdir "$TESTPATH"
cd "$TESTPATH"

git init --bare --initial-branch=main my-lfs-repo.git

mkdir "$TESTPATH/create-the-initial-repo"
cd "$TESTPATH/create-the-initial-repo"

git init --initial-branch=main .
echo foo > small-file
git add small-file
git -c commit.gpgsign=false commit -m 'a small regular file'
git remote add origin "file://$TESTPATH/my-lfs-repo.git"
git push --set-upstream origin main

git lfs install
echo "pretend-this-is-really-big" > large-file
git lfs track large-file
git add large-file

git -c commit.gpgsign=false commit -m 'a large file tracked in lfs'
git push

cat>Earthfile<<EOF
VERSION 0.7
small:
  FROM alpine
  COPY small-file .
  RUN --no-cache cat small-file

large:
  FROM alpine
  COPY large-file .
  RUN --no-cache cat large-file
EOF

git add Earthfile
git -c commit.gpgsign=false commit -m 'test earthfile'
git push

mkdir "$TESTPATH/test-clone-local"
cd "$TESTPATH/test-clone-local"
git clone "file://$TESTPATH/my-lfs-repo.git" .
test "$(cat large-file | head -n 1)" = "version https://git-lfs.github.com/spec/v1" # note this isn't the real contents

mkdir "$TESTPATH/test-clone-local-with-lfs-clone"
cd "$TESTPATH/test-clone-local-with-lfs-clone"
git lfs clone "file://$TESTPATH/my-lfs-repo.git" . # note we are calling "git lfs clone", and not "git clone"
test "$(cat large-file)" = "pretend-this-is-really-big"

mkdir "$TESTPATH/test-clone-remote"
cd "$TESTPATH/test-clone-remote"
git clone "$IP:$TESTPATH/my-lfs-repo.git" .

echo make sure the following is in your ~/.earthly/config.yml
cat<<EOF
git:
    hackhackhack:
        pattern: 'hack/hack/hack'
        substitute: 'ssh://$USER@$IP:22$TESTPATH/my-lfs-repo.git'
        auth: ssh
EOF

earthly-v0.7.4 --no-cache --verbose hack/hack/hack+small
earthly-v0.7.4 --no-cache --verbose hack/hack/hack+large
```

**Comment by alexcb** [comment]
I also tried creating a custom git image:

```
VERSION 0.7

gitlfs:
  ARG VERSION=v2.36.3
  FROM alpine/git:$VERSION
  RUN apk add git-lfs
  SAVE IMAGE --push earthly/alpine-git-lfs:$VERSION
```

and according to the docs, as long as git-lfs is installed, a `git clone ...` should automatically fetch the large files; however this did not work.

I also tried a hackier version:

```
VERSION 0.7

gitlfs:
  ARG VERSION=v2.36.3
  FROM alpine/git:$VERSION
  RUN apk add git-lfs
  RUN mv /usr/bin/git /usr/bin/real-git
  COPY fake-git /usr/bin/git
  SAVE IMAGE --push earthly/alpine-git-lfs:$VERSION-wrapper
```

along with the fake-git script:

```
#!/bin/sh
set -e
if [ "$1" = "clone" ]; then
  exec /usr/bin/real-git lfs $@
fi
exec /usr/bin/real-git $@
```

but unfortunately, these didn't provide a work-around. We will have to investigate further.

**Comment by vladaionescu** [comment]
Note that the git image is only used by Earthly for additional operations *after* the clone, like detecting git metadata, branch name, etc. The clone is still being done by the Buildkit container. Perhaps a simple test could be to add the git-lfs package to the Buildkit container to see if the large files magically show up.

**Comment by alexcb** [comment]
idea: create a new `GitLFSFactory` under `util/llbutil/llbfactory/`, which could make use of `WithInclude(patterns []string)`, which would communicate to buildkit that a `git lfs pull` will have to occur. Currently there's a `LocalFactory` which is called whenever earthly is running based on a local context, and the include patterns is passed to fsutils -- maybe some of this API could be re-used?

**Comment by alexcb** [comment]
v0 will simply take a `--include=<path>` from the cli (e.g. earthly --git-lfs-pull-include="large-file-from-lfs,other-large-file-from-lfs" example.com/user/repo+test`).

However for v1, we hope to figure out what files to include via the contents of the `COPY` commands; however doing this efficiently will take some work. e.g. consider:

```
test:
  FROM alpine
  ARG EARTHLY_GIT_AUTHOR
  RUN echo "running under repo which was last changed by $EARTHLY_GIT_AUTHOR"
  COPY large-file-from-lfs .
  RUN echo the file is $(cat large-file-from-lfs | wc -l) lines long
  COPY other-large-file-from-lfs .
  RUN diff large-file-from-lfs other-large-file-from-lfs
```

The `ARG` that must be populated based on git, followed by different `COPYs`.

Under v0, I had to include the `--include=<path>` value under the buildkit cache key; otherwise it would sometimes use a cached version of the repo which didn't include the pull. But now I worry that the first `ARG` will cause 1 clone, then the two other `COPY`s will cause two more clones, resulting in 3 total clones when someone runs: earthly [example.com/user/repo+test](http://example.com/user/repo+test).
