### ISSUE TITLE
--push cmd line argument tries to push SAVE IMAGE step not marked with --push flag

### ISSUE THREAD

**Issue by gavvvr** [earthly/earthly#2923]
Hi. I am using the most recent earthly v0.7.4

Consider the following minimal `Earthfile`:

```earthfile
VERSION 0.7
FROM alpine
WORKDIR /workdir

build:
    RUN echo hello > file.txt
    SAVE IMAGE hello:latest
```

The `earthly --push +build` will fail with the following error(even though `--push` IMO should not make any difference for `+build` target):

```
              output | [          ]   0% pushing layers
             ongoing | output (5 seconds ago)
              output | [----------] 100% pushing layers
              output | WARN: The command 'exporting outputs' failed: server message: insufficient_scope: authorization failed
             ongoing | Waiting on Buildkit... (Utilization: unknown other builds, 0/20 op load)
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to run Build function: failed to SAVE IMAGE: server message: insufficient_scope: authorization failed
```

The error says that the push failed. Earthly just tried to push `hello:latest` to dockerhub. If I prefix `hello:latest` with my dockerhub username, the push will succeed.

---

The reason why I assume the `--push` cmd line argument should not make any effect in this case, is because based on the [`earthly` cmd line reference](https://docs.earthly.dev/v/earthly-0.7/docs/earthly-command#earthly):

> `--push` ... Instructs Earthly to push __any docker images declared with the `--push`__ flag to remote docker registries and to run any `RUN --push` commands.

But my `SAVE IMAGE` step is not marked with `--push` flag.

The [`SAVE IMAGE` reference](https://docs.earthly.dev/v/earthly-0.6/docs/earthfile#save-image) also confirms my assumption:

> __The `--push` options marks the image to be pushed to an external registry__ after it has been loaded within the docker daemon available on the host.
> ... __The actual push is not executed by default. Add the `--push` flag to the earthly invocation to enable pushing.__

**Comment by alexcb** [comment]
I was able to replicate this too (using both `VERSION 0.6` and `VERSION 0.7`); definitely a bug.
