### ISSUE TITLE
Syntax highlighting fails when string contains +

### ISSUE THREAD

**Issue by bearbytes** [earthly/earthly#295]
The syntax highlighting in Earthfiles gets broken when a `+xyz` is encountered within a string anywhere in an earthfile.

![image](https://user-images.githubusercontent.com/15155173/92895327-afdcd100-f41b-11ea-9fba-9347554cccd0.png)

This is due to `+xyz` being incorrectly identified as a recipe name. I think this should not happen within quoted strings.

**Comment by vladaionescu** [comment]
Thanks, this looks like a valid issue. We'll take a look.

**Comment by vladaionescu** [comment]
This is fixed and will go out in the next release (likely this week).
