### ISSUE TITLE
earthly should strive to be deterministic

### ISSUE THREAD

**Issue by dudicoco** [earthly/earthly#2983]
Currently, non-deterministic builds can be produced by earthly, see the following example:
```
VERSION 0.7
FROM node:13.10.1-alpine3.11
WORKDIR /js-example

deps:
    COPY package.json ./
    RUN npm install
    SAVE ARTIFACT package.json AS LOCAL ./package.json

build:
    FROM +deps
    COPY src src
    RUN mkdir -p ./dist && cp ./src/index.html ./dist/
    RUN npx webpack
    SAVE ARTIFACT dist /dist AS LOCAL dist
```

Without a `package-lock.json` file, deleting the cache and rerunning the build could produce different results due to changes in dependencies.

Another issue is cache invalidation, per the [tutorial](https://docs.earthly.dev/basics/part-3-adding-dependencies-with-caching#caching) cache invalidation could occur due to inefficient ordering of commands.

These two issues can cause the build system to be unreliable, especially when working with a large monorepo at scale as it's the end user's responsibility to configure the earthfile correctly rather than the build system's responsibility to ensure that users cannot make such mistakes.

Bazel for example "boxes in" what the user can do via rules, thus providing a higher guarantee of deterministic builds and efficient caching.

Earthly could provide a different syntax than the standard Dockerfile syntax in order to provide a high guarantee that builds are deterministic rather than relying on the user to configure the file correctly.

**Comment by alexcb** [comment]
Can you clarify where this example comes from? The example under https://github.com/earthly/earthly/blob/main/docs/basics/part-4-args.md#more-examples , for instance, copies both `package.json` and `package.json.lock`.

**Comment by dudicoco** [comment]
@alexcb I've deliberately removed `package-lock.json` to show possible user errors which can cause non-deterministic builds.
This issue is not relation to documentation but to how Earthly can guarantee reproducible builds.

**Comment by alexcb** [comment]
We can't realistically support every possible language or package manager. We have deliberately chosen to be language agnostic  and instead leave it up to the user to be explicit about which files they want to copy over.
