### ISSUE TITLE
Possible to use with https://depot.dev/ ?

### ISSUE THREAD

**Issue by endigma** [earthly/earthly#2993]
Depot is a remote docker build system, it supports remote caching and works well in multiple CI providers. It would be nice if we could use depot with earthly as it's already in our toolchain.

**Comment by alexcb** [comment]
Unfortunately earthly uses a [fork of buildkit](https://github.com/earthly/buildkit); therefore it's not possible to guarantee all features will work with a standard remote buildkit instance. We do, however, offer our own remote workers, which we refer to as [satellites](https://docs.earthly.dev/earthly-cloud/satellites).
