### ISSUE TITLE
Feature Request: Option to export containers as OCI-compliant Nydus Images

### ISSUE THREAD

**Issue by vyas-n** [earthly/earthly#2997]
Nydus is an OCI-compliant image format that's currently proposed to accelerate image distribution across many hosts.

It's a standard that is currently compatible with containerd, OCI registries and the Dragonfly image distribution system.

Buildkit currently has support for exporting containers using the Nydus format (https://github.com/moby/buildkit/blob/master/docs/nydus.md) and I'd like for earthly to have an option to do so as well.

The flag in buildkit is implemented as a `compression` type. I'm uncertain if that makes it harder or easier for Earthly to support it.

**Comment by mwopfner** [comment]
I think this is related to #1666 where the export of other buildkit supported types is proposed.

**Comment by vyas-n** [comment]
@mwopfner, my bad that ticket does cover this use case.

I'll close this in favor of the other one.
