### ISSUE TITLE
[release] improve our documentation version string substition regex

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3006]
Note that our current regexes do not update these files:

```
$ grep -RI 0\\.7\\.0 docs/
docs/basics/part-8a-using-earthly-in-your-current-ci.md:        version: v0.7.0
docs/ci-integration/guides/gh-actions-integration.md:        version: v0.7.0
```

Rather than regexes, we should create a simple program that updates our docs automatically; unfortunately gitbook does not make it possible to render docs using a variable.

**Comment by alexcb** [comment]
idea: run the program to update versions to an arbitrary number such as `0.999.888`, then do a grep for `0.7.[0-9]`, and if any old versions were left un-migrated, raise an error.

**Comment by alexcb** [comment]
I think this was covered by @idodod in #3280

**Comment by idodod** [comment]
Yes!, I'll keep this open until I update the docs that refer to previous docker tags
