### ISSUE TITLE
runc run failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe

### ISSUE THREAD

**Issue by idelvall** [earthly/earthly#3014]
_A community member reported this:_

i’m trying to build a simple base image and got the following error:
`runc run failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe`
the target is very simple:
```
FROM cgr.dev/chainguard/wolfi-base:latest
RUN apk add --no-cache ca-certificates
```
```
earthly version v0.7.8 83add94bc251b22935fb492c08cd516556f03f7c darwin/arm64; macOS 13.4
Docker version 23.0.6, build ef23cbc [Docker Desktop for MacOS Apple Silicon] 
```
running with verbose i see these too:
```
earthfile2llb group error: async force execution for +runtimebase: unlazy force execution: process "/bin/sh -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt /usr/bin/earth_debugger /bin/sh -c 'apk add --no-cache ca-certificates'" did not complete successfully: exit code: 1
```
and it builds fine with docker with a Dockerfile. any ideas?

**Comment by idelvall** [comment]
Apparently this was the solution he found:

ok, managed to fix the above finally, if anyone experience the same, here is how to fix it:
```
$ docker stop earthly-buildkitd
$ docker builder prune -a
$ docker system prune -a
$ earthly bootstrap
```
just but careful with the prune commands those are purging every conatiner image, volume, etc! (for me was totally fine on this dev machine)

**Comment by tylfin** [comment]
I ran into a similar issue w/ Docker Desktop for Mac and the commands above didn't resolve, realized I had Rosetta switched on:

> Use Rosetta for x86/amd64 emulation on Apple Silicon

Turning this setting off resolved it for me.

**Comment by idelvall** [comment]
Thanks for the info @tylfin !
