### ISSUE TITLE
docs: badly rendered Markdown link in GitHub Actions guide

### ISSUE THREAD

**Issue by gvwilson** [earthly/earthly#3028]
**What went wrong?**
1. Go to https://docs.earthly.dev/ci-integration/vendor-specific-guides/gh-actions-integration
2. Link in first sentence is rendering as Markdown source rather than as hyperlink.

**What should have happened?**

Link should render as link.

**Other Helpful Information**

![Screenshot 2023-06-15 at 3 29 10 PM](https://github.com/earthly/earthly/assets/911566/e5e0d31d-f9fb-4826-89ba-b417247b20c7)

**Comment by alexcb** [comment]
Thanks for pointing that out :raised_hands:
