### ISSUE TITLE
earthly does not use docker registry cloud credentials when building a remote target or from a CI Runner 

### ISSUE THREAD

**Issue by idodod** [earthly/earthly#3058]
**What went wrong?**

When building a remote target, either locally or when running a pipeline from a CI Runner, earthly/buildkit does not use docker registry auth credentials set by `earthly registry setup` for a specific project.

1. Set docker credentials for a project using `earthly registry --org <org_name> --project <project_name> setup --username <user> --password-stdin`

2. Build a remote target from an Earthfile which reference the same org/project, for example:
if the following Earthfile is in `https://github.com/my-org/my-project/blob/main/Earthfile`
```Earthfile
VERSION 0.7

PROJECT my-org/my-project

FROM alpine

hello:
    RUN --no-cache echo hello
```
Run: `earthly -V github.com/my-org/my-project+hello`

**What should have happened?**

earthly/buildkit should authenticate to the docker credentials set in cloud secret at paths:
 `my-org/my-project/std/registry/registry-<docker-host>/username`
 `my-org/my-project/std/registry/registry-<docker-host>/password`

When running locally (like in this example) the auth fallsback to the local docker login info (the credentials set by `docker login`).
Potentially for a CI Runner if the credentials are set without specifying the org and project, the credentials would probably be used (though I haven't tried it to confirm)

**Other Helpful Information**

Because it is hard to tell whether earthly actually uses the credentials, it might be helpful to purposely set the wrong credentials with `earthly registry setup`, this way if the command fails with auth error, we can tell it was trying to use the auth credentials from the cloud secret in order to login to the docker registry

**Comment by nelsam** [comment]
fixed in #3059
