### ISSUE TITLE
warn if cache is too small

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3072]
once #3068 is complete, add a warning for systems that have an earthly cache size of 10GB or less.

The warning should include a line that can be copy/pasted, which a user can use to increase the size.

**Comment by alexcb** [comment]
here's a few code locations that could be useful:

https://github.com/earthly/earthly/blob/0d62a6f4fa19ba905a33469f0667e5c497dd13c0/buildkitd/buildkitd.go#L852 is where we can print a warning if it's too small

here's a commit where earthly-specific data was added to the `WorkerRecord` message / struct: https://github.com/alexcb/buildkit/commit/04bab2d652bea77688beb7d454abdc6b8a75907d

**Comment by mikejholly** [comment]
https://github.com/earthly/earthly/pull/3733
