### ISSUE TITLE
Quoting issues with `RUN` and "shell-out" executions

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#3131]
**What went wrong?**

Attempting to pass a single double-quote to commands in some shell scenarios fail in various ways.  For example, trying to remove quotes from strings via `tr -d '"'` or `tr -d "\""`, which should be functionally equivalent, fail in their own ways.  I don't know if this is restricted to passing a single double-quote; I did not explicitly try scenarios with single single-quotes.

Below are the different variations.  Since the first two are lexer issues, they had to be broken into separate files to illustrate.  (When they are in the same file as the others, depending where they are physically located, they sometimes execute, but with very wrong results.)

Summary:

|  | `'"'` | `"\""` |
| - | --- | ------ |
| `RUN` (earthly) | shell error | works |
| `ARG` shell-out | lex error | lex error |
| `RUN` (Dockerfile) | works | works |

```Earthfile
VERSION 0.7
FROM alpine

run-plain:
    RUN echo run | tr -d '"'
```
```
$ earthly +run-plain
Error: build target: build main: failed to solve: resolve build context for target +run-plain: lexer error: Earthfile
syntax error: line 5:26: token recognition error at: '"'

'
```

```Earthfile
VERSION 0.7
FROM alpine

arg-plain:
    ARG val=$(echo run | tr -d '"')
    RUN echo $val
```
```
$ earthly +arg-plain
Error: build target: build main: failed to solve: resolve build context for target +arg-plain: lexer error: Earthfile
syntax error: line 5:32: token recognition error at: '"')
    RUN echo $val
'
```

```Earthfile
VERSION 0.7
FROM alpine

# This variant works correctly
run-esc:
    RUN echo single | tr -d "\""

# The shell-out form should also work, but fails at runtime
arg-esc:
    ARG val=$(echo single | tr -d "\"")
    RUN echo $val

# The same constructs work fine when not parsed by earthly itself
doc-plain:
    FROM DOCKERFILE -f +dockerfiles/Dockerfile.plain .

doc-esc:
    FROM DOCKERFILE -f +dockerfiles/Dockerfile.esc .


dockerfiles:
    WORKDIR work
    RUN echo "
FROM alpine
RUN echo run | tr -d '\"'
" > Dockerfile.plain

    RUN echo "
FROM alpine
RUN echo run | tr -d \"\\\"\"
" > Dockerfile.esc
    SAVE ARTIFACT *
```
```
$ earthly +arg-esc
            +arg-esc | --> expandargs echo single | tr -d """
            +arg-esc | /bin/sh: syntax error: unterminated quoted string
            +arg-esc | ERROR Earthfile line 11:4
            +arg-esc |       The command
            +arg-esc |           expandargs echo single | tr -d """
            +arg-esc |       did not complete successfully. Exit code 2
```

**What should have happened?**

All of those examples should result in the string being output unchanged.  As this is a quoting issue, it is intentional that the strings do not contain quotes (i.e, the `tr` is a no-op); I wanted to minimize any quotes to help pinpoint the issue.

The only workaround I'm aware of is to avoid the use of single quotation marks.  In my scenario, rather than "remove quotes", I "removed anything that I don't explicitly want", e.g. replacing `tr -d '"'` with `tr -c -d '[:alnum:]'`.

**Other Helpful Information**

These were reproduced with `v0.7.12`.  I found it hard to believe I had never used this construct before, so spot-checked some of those scenarios with other versions (even back to `v0.6.x`), wondering if the new `earthly doc` changes were responsible.  I did not run all of those scenarios in all the versions.  The combinations I did try all yielded identical behavior.

EDIT:
---
After looking at my dockerfile example, I had a thought... when doing those multi-line `ARG` or `RUN` commands, it's now second nature to think of those as "earthly quotes", not "shell quotes", thus require another level of escaping.  I guess that's not specific to the multi-line construct.  With that change in thinking, I can get all four scenarios to work:
```Earthfile
VERSION 0.7
FROM alpine

run-plain:
    RUN echo '"run"away' | tr -d '\"'

arg-plain:
    ARG val=$(echo '"run"away' | tr -d '\"')
    RUN echo $val

run-esc:
    RUN echo '"run"away' | tr -d "\\\""
    # Original case, which works without the escaping... why?
    RUN echo '"run"away' | tr -d "\""

arg-esc:
    ARG val=$(echo '"run"away' | tr -d "\\\"")
    RUN echo $val
```

So this may be more of a documentation issue, not a bug... but the discrepancy in the "escaped" scenario doesn't make sense to me.  But one would typically expect that you can literally copy/paste a `RUN` from a Dockerfile and have it work in an Earthfile (and is exactly what led to this report).

**Comment by weaversam8** [comment]
Here's another example from the Earthly Slack:

> Hmm, weird bug. The following fails the lexer:
> `RUN 'echo "message'`
> but the following passes:
> `RUN 'echo "message"'`
