### ISSUE TITLE
Earthly is not respecting proxy variables, causing 5-second delay startup trying to talk to api.earthly.dev

### ISSUE THREAD

**Issue by gblewis1** [earthly/earthly#3135]
**What went wrong?**
Whenever I run earthly to build a target on my corporate network machine (Linux x86_64), it is spending about 5 seconds trying to ping the API during Init. I have traced this delay to the `func (c *Client) WhoAmI(ctx context.Context) (string, string, bool, error)` function, specifically inside `c.ping(ctx)`. The primary difference between the corporate network machine and an Internet-connected machine is that the corporate network blocks all outside IP access and forces http/https requests through a proxy. 

I have verified that when I take the machine off the corporate VPN and run earthly on an Internet network, the Init phase does not hang for 5 seconds here. It looks like earthly is not respecting my http/https proxy environment variables when trying to connect to https://api.earthly.dev.

**What should have happened?**
I would like to see a way to disable the call to api.earthly.dev, and also to have Earthly respect the proxy variables when trying to connect. I have not yet found any workarounds to this.

**Comment by alexcb** [comment]
> I would like to see a way to disable the call to api.earthly.dev

This already exists, you need to set `EARTHLY_DISABLE_ANALYTICS=1` (or `DO_NOT_TRACK=1`); it's documented under `--help` and also in our CHANGELOG.

We even have a test for it: https://github.com/earthly/earthly/blob/main/tests/do-not-track/Earthfile#L25-L33

It does seem odd that the proxy envs aren't being used though -- I'll leave this issue open for users who require a proxy connection; thanks for reporting this.

**Comment by gblewis1** [comment]
> > I would like to see a way to disable the call to api.earthly.dev
> 
> This already exists, you need to set `EARTHLY_DISABLE_ANALYTICS=1` (or `DO_NOT_TRACK=1`); it's documented under `--help` and also in our CHANGELOG.
> 
> We even have a test for it: https://github.com/earthly/earthly/blob/main/tests/do-not-track/Earthfile#L25-L33
> 
> It does seem odd that the proxy envs aren't being used though -- I'll leave this issue open for users who require a proxy connection; thanks for reporting this.

Even with `EARTHLY_DISABLE_ANALYTICS=1` or `DO_NOT_TRACK=1`, earthly is still calling `func (c *Client) WhoAmI(ctx context.Context) (string, string, bool, error)` which calls the ping to api.earthly.dev, which causes the 5 second pause. I looked through the code and I don't see anything that disables that WhoAmI call based on  disableAnalytics.

**Comment by ben-krieger** [comment]
Generally this is problem where an `*http.Client` is created without the `Proxy` field set to the value of `http.ProxyFromEnvironment`, which is what `http.DefaultClient` uses.

Therefore, the fix is probably just:

```diff
diff --git a/cloud/http.go b/cloud/http.go
index 82bf3ba6..c5e5f8fe 100644
--- a/cloud/http.go
+++ b/cloud/http.go
@@ -206,6 +206,7 @@ func (c *Client) doCallImp(ctx context.Context, r request, method, url, reqID st
 			DialContext: (&net.Dialer{
 				Timeout: c.serverConnTimeout,
 			}).DialContext,
+			Proxy: http.ProxyFromEnvironment,
 		},
 	}
```

**Comment by alexcb** [comment]
This has been fixed, but we don't currently have a test. I opened #3153 to track testing.
