### ISSUE TITLE
cgroup "operation not supported" errors on Rocky 9

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#3139]
_Note: I believe I know the problem as well as the solution; both are specific to buildkit.  I decided to file an issue in this project to aid others who might hit this._

**What went wrong?**
A subset of builds fail with (for example) `failed to capture provenance: read /sys/fs/cgroup/buildkit/pd1m0t9pkvrdzy4rolqkfxma6/memory.pressure: operation not supported`.

There are probably other ways to trigger this error, but a shell-out `ARG` was the first thing I found that would reproduce it 100% of the time.  This happens with `v0.7.12` on Rocky 9.  I suspect the issue is new and OS-specific.

```Earthfile
VERSION 0.7

foo:
    FROM alpine
    ARG val=$(grep "^ID=" /etc/os-release)
    RUN echo "val=$val"
```
```
# earthly --version 
earthly version v0.7.12 ce5e243a950f18da3d64c9a969ce18969a65d946 linux/amd64; Rocky Linux 9.2 (Blue Onyx)

# earthly --no-cache +foo
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata alpine linux/amd64
                +foo | --> FROM alpine
                +foo | [----------] 100% resolve docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
                +foo | --> expandargs grep "^ID=" /etc/os-release
Error: build target: build main: failed to solve: Earthfile line 5:4 failed to expand ARG $(grep "^ID=" /etc/os-release): failed to process "$(grep \"^ID=\" /etc/os-release)": non constant build arg read request: failed to capture provenance: read /sys/fs/cgroup/buildkit/pd1m0t9pkvrdzy4rolqkfxma6/memory.pressure: operation not supported
in		+foo
```

**What should have happened?**

The target should have executed without error and (in this specific case) output "rocky".

Workarounds:
1. use patched buildkit (see below)
2. use a kernel [without PSI support, or with PSI enabled](https://facebookmicrosites.github.io/psi/docs/overview#prerequisites)
3. avoid shell-out `ARG` (though it's unlikely this is only feature that triggers the behavior)

**Other Helpful Information**

I believe the earthly version that incorporated https://github.com/moby/buildkit/pull/3860 would be the first version impacted.  Though the scenario is very different from mine, [one specific comment](https://github.com/moby/buildkit/issues/3997#issuecomment-1624007105) got my attention.  That is exactly the configuration on this Rocky 9 host ("supported but disabled").

After creating a new buildkit image with https://github.com/moby/buildkit/pull/3999 applied, the minimal reproduction build above and my actual build work just fine.

I assumed it would be overkill to file another issue in the buildkit project.  Similarly, I didn't think it would be helpful to create a buildkit PR for one single commit from upstream, when you folks do that regularly.  But if either one of those helps, I'd be happy to do so.

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/releases/tag/v0.7.14 has been released which includes a buildkit update (and allows us to remove our own cgroup v2 init code).
