### ISSUE TITLE
The version number is not identified in the Earthfile of the REAMDE file for each language under examples.

### ISSUE THREAD

**Issue by pekuecoder** [earthly/earthly#3149]
Currently, the version number is not identified in the Earthfile of the REAMDE file for each language under examples. Of course, there are complete Earthfile files in each language. However, if you only refer to the Readme file to build your own Earthfile, you will encounter problems when using it. (like me 😊 )

@alexcb
If you find this issue useful, I would be happy to work on this. 😄

**Comment by pekuecoder** [comment]
Of course, like here: [earthly/examples/go/README.md](https://github.com/earthly/earthly/blob/main/examples/go/README.md)
The Earthfile it displays starts with `FROM`.

**Comment by alexcb** [comment]
thanks! I opened #3152 to fix them. I did some grepping to see if there were any others -- I only found two caess.

**Comment by pekuecoder** [comment]
I only see these two cases so far.
Thanks for your reply, I'll close this issue. 😄

**Comment by pekuecoder** [comment]
I only see these two cases so far.
Thanks for your reply, I'll close this issue. 😄
