### ISSUE TITLE
`earthly secret set --stdin foo` should display message saying waiting for EOF when running interactively

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3160]
It's not obvious to all users that `earthly secret set --stdin foo` waits for an EOF rather than a newline.

If earthly is run via an interactive tty, we should display a message reminding users how the `--stdin` mode works.

(note that we must wait for an EOF rather than a newline because some secrets contain newlines)

**Comment by vladaionescu** [comment]
Could we maybe have `--stdin` (uses new-line) and `--stdin-eof` (uses eof) as separate options? Although secrets could indeed contain new lines, it's pretty rare.

**Comment by alexcb** [comment]
it might be more intuitive if we simply treated a missing value as a prompt to interactively ask for a value.

```
$ earthly secret set foo
secret: <cursor>
```

Then we could use the `promptPassword()` code from https://github.com/earthly/earthly/blob/567e70d88685732a4ffc136d2c02e4d109888680/cmd/earthly/account_cmds.go#L307-L324

**Comment by alexcb** [comment]
I'm worried about breaking the existing functionality of `--stdin`; encryption keys (e.g. private keys used by ssh and gpg) tend to have new lines.

**Comment by idodod** [comment]
Addressed in #3196
