### ISSUE TITLE
Build all earthly/dind variants for linux/arm64 

### ISSUE THREAD

**Issue by krinoid** [earthly/earthly#3174]
**Use case**
Lately, I've started getting issues when using Earthly on the M1 CPU/ARM architecture, for targets that previously worked without issues (I suspect that https://github.com/earthly/earthly/pull/3163 might have triggered the issue). After investigation, I've realized that the problem is that the base image I've been using, `earthly/dind:alpine`, has no `linux/arm64` build: https://hub.docker.com/r/earthly/dind/tags, so that Earthly is attempting to do a multi-platform build. This fails when trying to use `WITH DOCKER`, one of the error is e.g.: "failed to create NAT chain DOCKER" (related issue: https://github.com/earthly/earthly/issues/2873). As far as I understand, Docker-in-Docker has to run on the same architecture as the host.

**Expected Behavior**
After switching to `earthly/dind:latest` (which has a native `linux/arm64` image) my builds/targets succeed again. It's a different Alpine version that I've used (which is a issue for some of my targets), so I'm proposing that all `earthly/dind:latest` images should have builds for `linux/arm64` (along with `linux/amd64`).

Related issues:
- https://github.com/earthly/earthly/issues/2873
- https://github.com/earthly/earthly/issues/1748
- https://github.com/earthly/earthly/pull/3163
- https://github.com/earthly/earthly/issues/3164
- https://github.com/earthly/earthly/issues/1907

**Comment by alexcb** [comment]
As a work-around, is it possible to switch to using the latest version of earthly (v0.7.15), and use the `earthly/dind:alpine-3.18` instead?

Unfortunately, there's some rather tight coupling between the version of earthly and the version of the earthly/dind image. If an older version of earthly uses latest version of docker compose (which under `alpine-3.18` is Docker Compose version v2.17.3) it will error with "project name must not be empty".

The `earthly/dind:alpine` image was initially updated; however once we discovered this issue it was incorrectly rolled-back only as an amd64 image.

We're currently working on restoring the old image, but will still have to figure out a better plan for this tight coupling.

One potential solution (once the old arm64 image is restored), is an Earthfile such as:

```Earthfile
VERSION 0.7

dind:
  FROM earthly/dind:alpine #alpine-3.18
  ARG EARTHLY_VERSION
  ARG SMALLEST_VERSION="$(echo -e "$EARTHLY_VERSION\nv0.7.15" | sort -V | head -n 1)"
  IF [ "$SMALLEST_VERSION" = "v0.7.15" ]
    # earthly is at v0.7.15 or newer, and must use the more recent dind:alpine-3.18 image
    FROM earthly/dind:alpine-3.18
  END

test:
  FROM +dind
  WITH DOCKER
    RUN docker --version # old versions of earthly will get 20.10.14, and newer will get 23.0.6
  END
```

**Comment by alexcb** [comment]
@krinoid I just rebuilt the old version of our `alpine` tag, the digest isn't the same as the original one; however, it appears to be running the older versions of docker and docker-compose:

```
alex@surfperch:~/gh/earthly/earthly/examples/go$ docker run --rm earthly/dind:alpine /bin/sh -c 'docker version'
error during connect: Get "http://docker:2375/v1.24/version": dial tcp: lookup docker on 192.168.0.1:53: no such host
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:45:09 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
alex@surfperch:~/gh/earthly/earthly/examples/go$ docker run --rm earthly/dind:alpine /bin/sh -c 'docker-compose version'
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.9.17
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

Would you be able to confirm if this "new" image is working for you on earthly v0.7.12 or older?

**Comment by alexcb** [comment]
#3178 updates our image tagging scheme to include the distro and docker versions.

**Comment by krinoid** [comment]
Thanks, @alexcb, things are working on my side! Appreciate such a quick resolution. I think that a couple of other issues might get fixed by this change as well (some of them linked in my initial report, and a couple of more that I've encountered during my investigation and lost).
