### ISSUE TITLE
CLI flag --ci has obsolete documentation

### ISSUE THREAD

**Issue by mcheshkov** [earthly/earthly#3213]
**Does existing documentation exist?**
[Build options for aerthly command](https://docs.earthly.dev/docs/earthly-command#build-options), `--ci` flag part

**Request**

Documentation states that `--ci` implies `--use-inline-cache --save-inline-cache`
But since version 0.7.0 it does not: https://github.com/earthly/earthly/blob/main/CHANGELOG.md#v070---2023-02-21

**Comment by alexcb** [comment]
@dchw thanks for getting that merged.

I just merged it into our `docs-0.7` branch so they end up getting published:

```
git merge main
Updating 8dfe0cf4..c8a044a4
```
