### ISSUE TITLE
extend `--pass-args` to always be enabled

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3228]
The `BUILD --pass-args +foo` command is tedious in some use-cases; users should be able to enable this for all `BUILD`, `FROM`, etc commands exactly once per Earthfile.

One idea is to create a new feature flag `--always-pass-args` which will always pass args to external Earthfile, essentially always applying the `--pass-args` flag to all `BUILD`, `FROM`, `COPY`, etc commands.

For example:

```
VERSION --always-pass-args 0.7

all:
    BUILD ./tests+foo
    BUILD ./tests+bar
    BUILD ./tests+baz
```

would be equivalent to

```
VERSION --pass-args 0.7 # note that the existing `--pass-args` feature is still very new and not enabled by default in 0.7

all:
    BUILD --pass-args ./tests+foo
    BUILD --pass-args ./tests+bar
    BUILD --pass-args ./tests+baz
```

The on concern is: if this new `--always-pass-args` feature will never be enabled by default in a later version, is it apporpriate to include it in the `VERSION` command, or should it be better to have a new command for this, e.g. `CONFIGURE --always-pass-args`

**Comment by vladaionescu** [comment]
I think that global options like this make things harder to understand. If you copy-paste a snippet of a build and move it to a different earthfile, it'll behave differently and it might not be very obvious why.

**Comment by alexcb** [comment]
@rrjjvv will be updating this request -- I didn't capture his idea.
