### ISSUE TITLE
Proposal: WITH DOCKER-COMPOSE

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#324]
### Background

A common pattern of integration testing and e2e testing is to have something like

```Dockerfile
RUN apk add docker-compose
WITH DOCKER
  DOCKER PULL img1
  DOCKER PULL img2
  DOCKER PULL img3
  ...
  DOCKER LOAD +custom-img img13
  RUN docker-compose up -d && \
    (perform testing) && \
    docker-compose down
END
```

### Proposal

The proposal is to simplify this as

```Dockerfile
WITH DOCKER-COMPOSE
  DOCKER LOAD +custom-img img13
  RUN (perform testing)
END
```

Behind the scenes, this command ensures the following:

* docker-compose utility is available
* `DOCKER PULL` is performed for all the images specified in the compose spec AND not specified in any `DOCKER LOAD` line
* The run command is wrapped by `docker-compose up -d` and `docker-compose down`

### Extra options

The following additional options could be specified:

```
WITH DOCKER-COMPOSE [-f compose-file.yml...] [service-name...]
  ...
END
```

* `-f ...` works the same as `docker-compose -f ...`, including having the ability to string together multiple specs.
* `service-name` works the same as the `docker-compose up service-name`, including being able to list more than one service

### Benefits

The core benefit is reducing the brittleness of the `DOCKER PULL` statements. If an image tag is changed in a docker-compose.yml, the user might forget to update the `DOCKER PULL` statement, causing inefficiencies that are not easy to spot.

The other benefits are secondary.

### Alternative proposal

Another option might be to only change the `DOCKER PULL` command to accept a docker-compose specification. eg

```Dockerfile
WITH DOCKER
  DOCKER PULL --compose docker-compose.yml
  DOCKER LOAD +custom-img img13
  RUN docker-compose up -d && \
    (perform testing) && \
    docker-compose down
END
```

Although a little more verbose, this has the benefit of reusing more of the existing syntax, making it less surprising (magical) to the user as to what exactly takes place behind the scenes.

**Comment by agbell** [comment]
I support the proposal. 

It removes the need not just for the `DOCKER PULL` but also for starting and stopping docker-compose.

**Comment by alexcb** [comment]
I like the idea; I'm unsure about the connection between the docker-compose and docker load spanning multiple lines.

What if we could combine them with:

```
WITH DOCKER-COMPOSE --image img13=+custom-img
    RUN ...
END
```

although that might become problematic if there's too many images to load, which could then end up with wrapping lines like:

```
WITH DOCKER-COMPOSE \
        --image img13=+custom-img \
        --image img9=+custom-img9
    RUN ...
END
```

**Comment by vladaionescu** [comment]
### Updated proposal

```Dockerfile
WITH DOCKER \
    --compose docker-compose.yml \
    --compose anotehr.yml \
    --service myserv1 \
    --service myserv2 \
    --load img23:latest=+custom-img \
    --pull some-img:latest \
    --run image:latest
  RUN docker-compose -f docker-compose.yml -f test.yml up test-name
END
```

This means that DOCKER LOAD and DOCKER PULL would have to go through a deprecation cycle. However, this syntax makes most logical sense. Because the load and the compose would interact with each other (eg if an image is loaded, it should not be pulled) and therefore it makes more sense if the instructions are part of the same command.

### Alternative considered
```
WITH DOCKER
  DOCKER-COMPOSE up the.yaml
  DOCKER RUN image:latest
  DOCKER LOAD +custom-img img13
  RUN docker run
    (perform testing) && \
    docker-compose down
END
```

This has the drawback that the difference between `DOCKER RUN` and `RUN docker run` would not be obvious to the user.
