### ISSUE TITLE
Adding earthly metadata to created images

### ISSUE THREAD

**Issue by idelvall** [earthly/earthly#3247]
As of today, images generated by Earthly cannot be differentiated from others. It would be nice for earthly to add some metadata in the image, so downstream tools were be able to known when a image has been generated by Earthly and under which version.

**Comment by jmgilman** [comment]
I would suggest labels, given that they are typically used for "finding" specific images. Additionally, it would also be nice to record the original target used to build the image. The goal being the ability to detect what images (if any) a particular target created.

**Comment by alexcb** [comment]
I'm not sure adding extra `LABEL`s to a user's image without them requesting it is a good idea or not -- does docker do this in any places?

**Comment by idelvall** [comment]
Feedback received! Let me know your thoughts on the PR
