### ISSUE TITLE
`earthly account login --token <token>` should ignore SSH_AUTH_SOCK (but doesnt)

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3284]
If I try to run `earthly account login --token <token>`, 1Password prompts me to allow use of my SSH key.

After I approve it, the Earthly command exits with `Error: failed to login: failed executing ping request: failed refreshing expired auth token: agent: failed to sign challenge`.

_Originally posted by @Nezteb in https://github.com/earthly/earthly/issues/3179#issuecomment-1731861993_

**Comment by alexcb** [comment]
@nezteb can you try running `SSH_AUTH_SOCK="" earthly account login --token <token>` -- does that prevent the key from being used?

(technically earthly will never read your private key, when I say "used", i'm referring to earthly requesting the ssh-agent to sign a challenge..... this is irrelevant to this ticket, but just wanted to mention our stance on never loading your private key into earthly's memory space)

**Comment by Nezteb** [comment]
> can you try running `SSH_AUTH_SOCK="" earthly account login --token <token>`

That works!

```
❯ SSH_AUTH_SOCK="" earthly account login --token <token> && earthly org select <org>
Logged in as "<email>" using token auth
Log sharing is enabled by default. If you would like to disable it, run:

        earthly config global.disable_log_sharing true
Updated selected org in /Users/noah/.earthly/config.yml
```

**Comment by alexcb** [comment]
we'll need to get this fixed -- the `<token>` should take precedence over ssh-based login.

extra note: When we fix this, we should also **test that once the JWT expires, the <token> still takes precedence**.
