### ISSUE TITLE
WITH DOCKER raises gpg: cannot open '/dev/tty': No such device or address

### ISSUE THREAD

**Issue by antoniomdk** [earthly/earthly#3288]
**What went wrong?**

WITH DOCKER cannot be used in certain Debian-based images because lack of a TTY device:

```
gpg: cannot open '/dev/tty': No such device or address
```

I wonder if it'd be a good idea to add the --yes and --batch options to this line: 

`curl -fsSL "https://download.docker.com/linux/$distro/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg`

 in docker-auto-install.sh.

Currently I'm using the following workaround:

```
base-image:
    FROM my-debian:latest

    RUN mkdir -p $HOME/.gnupg && \
        echo "yes" >> $HOME/.gnupg/gpg.conf && \
        echo "batch" >> $HOME/.gnupg/gpg.conf && \
        chmod 600 $HOME/.gnupg/gpg.conf

    WITH DOCKER
        RUN echo ""
    END

    SAVE IMAGE my-debian-dind:latest

test:
    FROM +base-image
    WITH DOCKER
        RUN docker ps
    END
```

**Comment by alexcb** [comment]
> certain Debian-based images

we should check if this exists in `earthly/dind:ubuntu-23.04-docker-24.0.5-1` too.

**Comment by antoniomdk** [comment]
I have found the issue with debian bookworm, alpine works fine.

**Comment by alexcb** [comment]
> I have found the issue with debian bookworm, alpine works fine.

I just tried

```
VERSION 0.7
test:
    FROM debian:bookworm
    WITH DOCKER
        RUN docker ps
    END
```

which did not replicate the issue -- can you share an Earthfile that replicates the problem?

**Comment by antoniomdk** [comment]
I'm using a custom image based on debian that another team from my company maintains, it is not just the base OS. Unfortunately, I can't share that dockerfile

**Comment by hongkongkiwi** [comment]
Why don't you just use the --no-tty option for gpg? That worked for me.

**Comment by alexcb** [comment]
> Why don't you just use the --no-tty option for gpg?

thanks for the suggestion! #3324
