### ISSUE TITLE
Feature request: Syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#331]
We already have a [TextMate grammar](https://github.com/earthly/earthly/blob/master/contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json) for VS Code syntax highlighting. Wondering if it's easy to port that into the right format for Sublime Text.

**Comment by vishnugt** [comment]
Can I take this and try to create syntax highlighting for Sublime Text?

**Comment by zedtux** [comment]
FYI [I've opened an issue](https://github.com/asbjornenge/Docker.tmbundle/issues/32) on [the Dockerfile Syntax Highlighting sublime plugin](https://packagecontrol.io/packages/Dockerfile%20Syntax%20Highlighting), the only sublime text plugin for Dockerfile syntax highlighting asking to support `Earthfile`.

There's not so much to get it covering Earthfiles.

**Comment by vishnugt** [comment]
Instead of having `Earthfile `syntax as part of `Dockerfile `Syntax plugin, I think it makes sense for `Earthfile` to have it's own separate sublime plugin and syntax definition package file which users can copy for syntax highlighting.

@vladaionescu any thoughts on this?

**Comment by zedtux** [comment]
It sounds like duplicating something existing to just add few rules.

I'm really not against it, but I'm not sure if the Earthly people want to maintain all the Dockerfile syntax highlighting (as `Earthfile` syntax is like 80% the one from `Dockerfile`).
To me, it make more sens they contribute with the `Earthfile` syntax only part.

In the end, I just want it to work, no matter how 😉.

**Comment by agbell** [comment]
Great effort @zedtux in opening that issue!  I think our own syntax highlighting would make sense though, in this case.

**Comment by vladaionescu** [comment]
I've assigned this to you @vishnugt. Thanks for taking a look into this.

**Comment by vladaionescu** [comment]
I'll keep this open to also track the publishing of the package via [these instructions](https://packagecontrol.io/docs/submitting_a_package).

**Comment by vishnugt** [comment]
I'll take this as well, I've replied to this in the original PR #364

**Comment by vladaionescu** [comment]
Here you go @vishnugt https://github.com/earthly/sublimetext-earthly-syntax

**Comment by vladaionescu** [comment]
FTR - PR by @vishnugt for package control repo: https://github.com/wbond/package_control_channel/pull/8060

**Comment by vladaionescu** [comment]
Seems that the ST2 syntax needs to be converted to ST3 syntax according to https://github.com/wbond/package_control_channel/pull/8060#issuecomment-743804904. (Apparently there's an automated process for the translation - it just needs to be used from an ST3 installation).

Any contributions here are welcome!

**Comment by vishnugt** [comment]
![image](https://user-images.githubusercontent.com/7014475/103703453-96b0ef00-4fcd-11eb-8437-9a6a09b72a61.png)

Package control PR merged.  The package is now available in Sublime 🎉 
All further changes can be done in our repo itself

**Comment by vladaionescu** [comment]
Yaaaay!! Thanks for shepherding this through, @vishnugt!

For installation instructions, would something along the lines of this be accurate? https://www.storybench.org/install-babel-packages-sublime-text-3/ (been a while since I used ST2/3).

**Comment by vishnugt** [comment]
Yeah, pretty much, we don't need that "Activate" part mentioned that in the wiki. Once the package is installed, it will automatically pick up the EarthFiles and will do syntax highlighting by default.


Steps:
1.  Press Ctrl+Shift+P, it will bring up a menu, select ”Install Package control".
2.  Press Ctrl+Shift+P again, you should see additional options, select "Package Control: Install Package" and search for "Earthly" and click on it to install.

And you are done, now earthly files will have its syntax highlighted by default.

**Comment by vladaionescu** [comment]
Installation instructions updated. This is now complete.

Many thanks for bringing this to life, @vishnugt !! :raised_hands: :rocket: :100:
