### ISSUE TITLE
`CACHE --no-persist`

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#3327]
**What existing functionality needs improvement?**

One key difference between `RUN --mount type=cache` and `CACHE` is that `CACHE` additionally persists the contents of the cache into the final image. This is useful in certain cases, but sometimes it just degrades performance, because the final image becomes larger, and also copying the files from the cache volume takes time.

Allow for the contents of the `CACHE` directory to not be persisted into the final image via a new flag.

One issue with this proposal: the name `--no-persist` isn't immediately suggestive. If a new user sees this for the first time, they wouldn't know what it means without reading the docs. Can we come up with a better name?

**Expected Behavior**

`CACHE --no-persist` creates a cache volume that does not carry over to other targets via persisting the contents into the final image.

**Comment by alexcb** [comment]
done in #3510

example:

```
VERSION --cache-persist-option 0.7

test:
  FROM alpine
  ARG CACHE_BUSTER
  CACHE /the-cache
  RUN date >> /the-cache/data
  RUN cat /the-cache/data | wc -l
  SAVE IMAGE ctest
```

```
$ earthly-v0.7.22 +test --CACHE_BUSTER=$RANDOM
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

Streaming logs to https://cloud.earthly.dev/builds/b15f67ff-50a4-4f20-b85d-40185e0030da

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata alpine linux/amd64
               +test | CACHE_BUSTER=28858
               +test | --> FROM alpine
               +test | [----------] 100% FROM alpine
               +test | CACHE_BUSTER=28858
               +test | --> RUN date >> /the-cache/data
               +test | CACHE_BUSTER=28858
               +test | --> RUN cat /the-cache/data | wc -l
               +test | 4                                                       <----- NOTE the data is increasing here
              output | --> exporting outputs
              output | [----------] 100% exporting outputs
              output | --> exporting outputs
```

but it's not exported:

```
$ docker run --rm ctest /bin/sh -c 'ls -la /the-cache'
ls: /the-cache: No such file or directory
```

if however `CACHE --persist` is used, it is:

```
$ docker run --rm ctest /bin/sh -c 'ls -la /the-cache'
total 12
drwxr-xr-x    2 root     root          4096 Dec  1 19:37 .
drwxr-xr-x    1 root     root          4096 Dec  1 19:37 ..
-rw-r--r--    1 root     root           145 Dec  1 19:37 data
```
