### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by Leward** [earthly/earthly#333]
Hi, I find this project interesting and am considering participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/). 

Do you plan on labelling issues to be picked up as well a label issues which would be good for somebody contributing for the first to the project?

**Comment by agbell** [comment]
Hi @Leward 

We have a label 'good first issue'.  We only have one issue labeled that right now (#322 ).  However, we can try to identify some more if necessary .  Also jump on gitter to ask questions or ping me adam at earthlly.dev and I can try to enable your hackober efforts.
