### ISSUE TITLE
expand autocomplete to work with user home directories

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#334]
Currently if you type `earth ~<tab><tab>` this auto completes to `earth ~/`, instead it should auto complete to list all available users (e.g. ~/, ~adam, ~alex, ~corey, ~vlad).

Here's the relevant section of the code that needs to be expanded to list other users:

https://github.com/earthly/earthly/blob/master/autocomplete/complete.go#L106-L109

This will also have to be able to do autocompletion so when you type `earth ~a<tab><tab>`, it'll only display users starting with an a (e.g. ~adam, ~alex)

**Comment by avasapollo** [comment]
hi there,
is this can be ok for you?
```

func lookupUsers(prefix string) ([]string, error) {
	u, err := user.Current()
	if err != nil {
		return nil, err
	}

	lPath := strings.Split(u.HomeDir, "/")
	if len(lPath) < 1 {
		return nil, errors.New("users not found")
	}

	directoryList, err := ioutil.ReadDir(fmt.Sprintf("/%s", lPath[1]))
	if err != nil {
		return nil, err
	}
	var res []string
	for _, s := range directoryList {
		if prefix != "" && !strings.HasPrefix(s.Name(), prefix) {
			continue
		}

		if !s.IsDir() {
			continue
		}

		u, err := user.Lookup(s.Name())
		if err != nil {
			continue
		}
		res = append(res, fmt.Sprintf("~%s", u.Username))
	}
	return res, nil
}

```

**Comment by alexcb** [comment]
Thanks for taking a look at this @avasapollo ; it looks like a great so far.

I think that'll work with the initial auto-completion work for say ~user, but we might also need to handle the case for searching `~user/some/pat<tab><tab>` because right now it assumes it'll only ever be `~/` under https://github.com/earthly/earthly/blob/master/autocomplete/complete.go#L112-L119

**Comment by avasapollo** [comment]
Hey there I ll take a look tomorrow 😉

**Comment by alexcb** [comment]
Assuming you're running linux and you've checked out earthly to `/path/to/earthly`,
you can compile it with `earth +for-linux` then under bash you can change the autocomplete entry to use the build binary with:
`complete -o nospace -C '/path/to/earthly/build/linux/amd64/earth' earth`

(otherwise if you're under macOS, you can use +for-darwin to build the macOS version)

This will help testing the autocompletion code does what is expected.

thanks again for taking a look and trying out earthly :)

**Comment by avasapollo** [comment]
hey there, it's seems that I don't have permission to push the branch 
![Screenshot from 2020-09-30 10-51-52](https://user-images.githubusercontent.com/22316360/94670983-2f6b0b00-030b-11eb-9683-6e5e7072e2e7.png)

**Comment by agbell** [comment]
Hi @avasapollo,
You'll need to fork the repo, push your branch on the fork and raise a PR from the fork. See this guide https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by avasapollo** [comment]
Hey @agbell, thanks to let me know :).
I added some tests to see if it works on my machine. I think that I can implement the tests and use the current user if you want.
Let me know if you like the implementation

**Comment by agbell** [comment]
That's awesome!  I'll let @alexcb review it, as this is his area of expertise. Are you interested in an earthly sticker as a thankyou?

**Comment by avasapollo** [comment]
:) sure thanks

**Comment by avasapollo** [comment]
Ciao @alexcb , I still see the PR on hacktoberfest in review and not in accepted, can you do anything for that? Thanks

**Comment by alexcb** [comment]
@avasapollo that's odd. I just added a `hacktoberfest-accepted` label to the PR. Let's see if that makes it work? otherwise we'll try to figure out some other way.

**Comment by avasapollo** [comment]
The state is still the same maybe just need time I ll check next week thanks have good weekend

**Comment by avasapollo** [comment]
Ciao @alexcb sorry to annoying you but the PR is still in review, do you know how to change the state to accepted ?

**Comment by alexcb** [comment]
that's odd, if I look at https://github.com/earthly/earthly/pull/349 I see it as accepted. Is there a different place to look?

![image](https://user-images.githubusercontent.com/1806823/96031241-f2763c80-0e11-11eb-9a00-e4ae130815eb.png)

**Comment by avasapollo** [comment]
I read something probably it is just because a maintainer as to accept
