### ISSUE TITLE
Build fails with "build target: build main: failed to solve: Internal: rpc error"

### ISSUE THREAD

**Issue by mologie** [earthly/earthly#3361]
**What went wrong?**

Builds randomly fail with
```
_unknown *failed* | build target: build main: failed to solve: Internal: rpc error: code = Internal desc = rpc error: code = Internal desc = header list size to send violates the maximum size (1048896 bytes) set by server
```

This happens at the very end of the build after `[----------] 100% exporting outputs`. Everything up until that point works normally.

I do not have a clear method to reproduce this or even narrow down the issue yet, so any pointers would be appreciated. Running my Earthfiles locally on macOS with Docker Desktop instead of a Linux VM did not produce the error yet, so I'm hesitant to blame the input, but rather the environment.

**What should have happened?**
The error should not happen. Retrying a few times usually makes it disappear, only to reappear with the next build.

**Other Helpful Information**

This happens with the latest Earthly release v0.7.20, and Docker 20.10.23 under Fedora CoreOS 38.

The issue started to appear after upgrading from v0.7.13 to v0.7.19.

Earthly args used are `--ci --use-inline-cache --save-inline-cache`.

The earthly-buildkitd container prints a very similar error as last message:
```
time="2023-10-09T21:04:14Z" level=info msg="response completed" go.version=go1.20.8 http.request.host="127.0.0.1:8371" http.request.id=efcc6a91-1ee5-4f3f-8ade-17e2db9fb262 http.request.method=GET http.request.remoteaddr="172.17.0.1:56862" http.request.uri="/v2/sess-3j6y4mgbdes8kozs59zd5q6l6/pullping/blobs/sha256:d74ec9eb5877d62243a0977a7bede2dfa5d3c8405cd19bd4c723f1c6f3c0becd" http.request.useragent="docker/20.10.23 go/go1.20rc3 git-commit/%{shortcommit_moby} kernel/6.4.15-200.fc38.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype=application/octet-stream http.response.duration=1.977633893s http.response.status=200 http.response.written=459120774
time="2023-10-09T21:08:28Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Internal desc = rpc error: code = Internal desc = rpc error: code = Internal desc = header list size to send violates the maximum size (1048896 bytes) set by server" revision=af796f0cb8ff6cf53fdebd543ff1e7cd173c00a1 version=v0.7.20
```

**Comment by mologie** [comment]
There is a ticket with related error message at #1016, where the author's logs show this buildkit error:

```
time="2021-06-01T12:49:02Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Internal desc = received 68586-bytes data exceeding the limit 65535 bytes\n"
```

Judging from my error I guess the limit was bumped from 64 KiB to 1 MiB, but that's still not sufficient.

**Comment by alexcb** [comment]
> I guess the limit was bumped from 64 KiB to 1 MiB

That's correct!

We'll need to know what messages are exceeding that, simply bumping this limit beyond 1MB seems like a wrong solution -- instead we need to figure out if we can break them up into smaller messages, but we'll need to come up with a reproduction case.

are you able to provide more information regarding your Earthfile?

is it producing lots of logs?

is it for all targets, or just some targets in your Earthfile?

Are you using features like `TRY` / `FINALLY` ? does it have a `SAVE ARTIFACT` in it?

**Comment by mologie** [comment]
> is it producing lots of logs?
Yes (tens of thousands of lines when rebuilding without cache), but I have Earthfiles that produce much more output without issues.

> is it for all targets, or just some targets in your Earthfile?
Just one target, see next answer

> Are you using features like TRY / FINALLY ? does it have a SAVE ARTIFACT in it?
Yes to both, and that is the target that is causing issues! No other target uses TRY/FINALLY + SAVE ARTIFACT. I did not realize this at first. There is a test job, which dumps test output to a log file and, on failure, tails the last 100 lines from it. The whole file is always passed to SAVE ARTIFACT via FINALLY, and it can become very large.

The size is not deterministic due to randomized testing, so I guess that explains why it only sometimes exceeds 1 MiB.

Given we've probably narrowed it down already: Shall I try to construct some synthetic test that causes the issue via TRY/FINALLY + SAVE ARTIFACT, or is this information sufficient already? Thank you!

**Comment by alexcb** [comment]
If you could come up with a concise Earthfile, that would be a big help. Maybe try using a command like `dd` to produce a large file?

**Comment by mologie** [comment]
While trying to reproduce from a clean state I reset the affected machine's Earthly cache, and ever since, I am unable to reproduce the issue. The build machine has since processed ~50 builds and wrote 80 GiB of artifacts, but is just churning along nicely.

So there's apparently another factor of having /something/ in the Earthly cache that's written by Earthly 0.7.x-0.7.13, and then updating to 0.7.19+, and using TRY/FINALLY with SAVE ARTIFACTS on top. It might also be that the cache simply has to fill up again over a few weeks.

All synthetic Earthfiles that I tried to think of that used dd in TRY/FINALLY, large amount of log output distributed over roughly the build time, failed to reproduce it (just like the original build would no longer reproduce it).

Regardless I can't reproduce this anymore (while 3 of 4 builds failed before), so I'd close this for now until (if at all) the issue appears again.
