### ISSUE TITLE
Cannot log in with ed25519 ssh keys

### ISSUE THREAD

**Issue by robarnold** [earthly/earthly#3366]
**What went wrong?**
I try to run `earthly account login` in the sample devcontainer and get this error:
`Error: failed to login: failed executing ping request: failed refreshing expired auth token: agent: failed to sign challenge`

This error is deterministic. Looking at the logs of my ssh agent (1Password), I saw this line with a matching timestamp to running `earthly`:
`Error handling sign request: Key(expected Ed25519 signing but found an RSA algorithm)`

**What should have happened?**
The login process should have been able to sign the challenge with my ssh key (which is on my earthly account).

No known workaround other than just not using ed25519 keys. The [instructions on GitHub for creating ssh keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) defaults to ed25519 keys and refers to systems using RSA keys as "legacy", so switching to RSA does not seem like a good solution.

**Other Helpful Information**
Earthly's ssh login code asks the agent to sign the key but assumes that the key is an RSA key, so [it uses an RSA-specific flag in the signing request](https://github.com/earthly/earthly/blob/main/cloud/auth.go#L542C86-L542C86). Reading [this IETF spec on ssh agents](https://www.ietf.org/archive/id/draft-miller-ssh-agent-10.html#name-private-key-operations) it looks like 1Password is correctly refusing to sign the challenge data because the RSA flags are not valid for the key type (ed25519).

I think the change to Earthly shouldn't be too involved - it likely just needs to pass 0 for the flags when signing with non-RSA keys. I think #2246 meant to address this use case.

**Comment by vladaionescu** [comment]
Can you confirm the Earthly version you're using?

I thought we fixed this some time ago. CC @alexcb

**Comment by robarnold** [comment]
Thanks for the quick reply! Running `earthly--version` gives me this:
```
earthly version v0.7.20 9600f376026c11d23eb43fc68ad716d6ae4cca2e linux/amd64; Ubuntu 20.04.6 LTS (Focal Fossa)
```

**Comment by alexcb** [comment]
> I thought we fixed this some time ago. CC @alexcb

This bug is unrelated. We previous added support for ed25519 keys; however it was only tested against OpenSSH which is a bit more liberal (or open :laughing: ) in the challenges it will sign.

in the meanwhile, I would suggest to either use OpenSSH's agent, or set `SSH_AUTH_SOCK=""` and use password-based login with earthly.

@robarnold I appreciate the detailed bug report (and especially pointing out the offending argument we have hardcoded)

**Comment by alexcb** [comment]
I created a very dumb ssh-agent proxy in https://github.com/alexcb/ssh-auth-verbose-forwarder/blob/main/proxy/agent.go

and printed out some logs:

```
Extension session-bind@openssh.com [0 0 0 51 0 0 0 11 115 115 104 45 101 100 50 53 53 49 57 0 0 0 32 240 84 218 44 78 198 213 209 221 99 129 112 204 174 215 54 113 217 210 163 201 21 154 159 213 85 3 3 95 192 89 72 0 0 0 32 245 56 139 84 82 42 108 114 180 181 72 7 102 157 238 85 61 224 33 44 23 5 229 199 232 107 80 85 140 180 64 233 0 0 0 83 0 0 0 11 115 115 104 45 101 100 50 53 53 49 57 0 0 0 64 13 169 230 137 26 6 155 152 54 200 105 29 125 159 242 183 181 72 133 221 137 226 154 18 54 224 50 54 203 185 153 155 228 129 56 139 238 103 97 137 9 248 35 230 225 185 129 217 113 53 251 220 48 139 210 175 55 69 159 87 211 231 96 10 0]
List()
SignWithFlags ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGwP3hY4GcZzeJIVY26Cq60+3cHqsdn8W9OtYYQYXPyy [0 0 0 32 245 56 139 84 82 42 108 114 180 181 72 7 102 157 238 85 61 224 33 44 23 5 229 199 232 107 80 85 140 180 64 233 50 0 0 0 4 97 108 101 120 0 0 0 14 115 115 104 45 99 111 110 110 101 99 116 105 111 110 0 0 0 9 112 117 98 108 105 99 107 101 121 1 0 0 0 11 115 115 104 45 101 100 50 53 53 49 57 0 0 0 51 0 0 0 11 115 115 104 45 101 100 50 53 53 49 57 0 0 0 32 108 15 222 22 56 25 198 115 120 146 21 99 110 130 171 173 62 221 193 234 177 217 252 91 211 173 97 132 24 92 252 178] 0
```

which correspond to me sshing with a temporary ed25519 key to a server.

it appears that the flag value is set to 0 when a ec25519 key is used; this matches up with what the specs says:

> [3.6.1. ](https://www.ietf.org/archive/id/draft-miller-ssh-agent-10.html#section-3.6.1)[Signature flags](https://www.ietf.org/archive/id/draft-miller-ssh-agent-10.html#name-signature-flags)
Two flags are currently defined for signature request messages: SSH_AGENT_RSA_SHA2_256 and SSH_AGENT_RSA_SHA2_512. These two flags are only valid for "ssh-rsa" keys and request that the agent return a signature using the "rsa-sha2-256" or "rsa-sha2-512" signature methods respectively. These signature schemes are defined in [[RFC8332](https://www.ietf.org/archive/id/draft-miller-ssh-agent-10.html#RFC8332)].

I'll see if we can set this to 0 in earthly.
