### ISSUE TITLE
Document .earthignore

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#337]
It has the same syntax as `.dockerignore`. Current limitation is that it doesn't work for remote targets, however.

**Comment by kichloo** [comment]
@vladaionescu I would like to take up this issue and can fix it using some help. Kindly assign it to me. Also, is it a part of Hacktoberfest?

**Comment by vladaionescu** [comment]
Hi @kichloo - we don't want to give this out as it'll probably require more time to guide than addressing it on our end. We're very religious about the consistency of the docs :-)

**Comment by kichloo** [comment]
@vladaionescu Ok. But is there any way a beginner can participate, majorly in documentation or something of thus sort?

**Comment by alexcb** [comment]
https://docs.earthly.dev/docs/earthfile/earthlyignore
