### ISSUE TITLE
Enhancement request: Consider using go-vendor

### ISSUE THREAD

**Issue by xgqt** [earthly/earthly#3408]
Hello!

I'm writing as a Earthly user but also as the maintainer of Earthly Gentoo package.

Currently in Gentoo if a go package does not provide vendored go deps we have to create it ourselves.
Please see: https://wiki.gentoo.org/wiki/Writing_go_Ebuilds#Packaging_the_dependencies

It would speed up greatly earthly package maintainership and testing if Earthly provided vendor in the repo.

For reference project using go-vendor see: https://github.com/containers/podman-tui

Thanks a lot in advance.

**Comment by alexcb** [comment]
for reference, here's the gentoo ebuild script: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-containers/earthly/earthly-0.7.20.ebuild

**Comment by alexcb** [comment]
see #3411 for why we decided against vendoring.
