### ISSUE TITLE
Add example rust application to examples

### ISSUE THREAD

**Issue by agbell** [earthly/earthly#341]
We need an example rust application added to the examples folder:
https://github.com/earthly/earthly/tree/master/examples

An example Earthfile should also be included which can build and produce a docker file of the example. 

The [Go example](https://github.com/earthly/earthly/tree/master/examples/go) can serve as a reference point for how to structure an example.

**Comment by vbhv007** [comment]
Hey, Can I pick this up under hacktoberfest?

**Comment by agbell** [comment]
Hey @vbhv007, you certainly can.

**Comment by agarwalBinay18** [comment]
can I work on this issue?

**Comment by agbell** [comment]
You can @agarwalBinay18

**Comment by vbhv007** [comment]
Hey @agbell  
I tried running the python example and I'm getting this error

`Error: new file stream build.earth: open build.earth: no such file or directory`

Is this some known issue, I couldn't find anything on the internet

**Comment by agbell** [comment]
Hi @vbhv007, that is strange.    What command are you running?  Try earth +build in the python folder. It runs as part of the build, so I believe it should be working.   Also, make sure you have the latest version of earthly.

**Comment by vbhv007** [comment]
Yup, I think it was a version issue, working with v0.3.8

**Comment by kevinkjt2000** [comment]
Is this done already?

**Comment by agbell** [comment]
Hey @kevinkjt2000, I believe it is. Good catch.
