### ISSUE TITLE
Ruby on rails example

### ISSUE THREAD

**Issue by agbell** [earthly/earthly#344]
We need an example rails application added to the examples folder:
https://github.com/earthly/earthly/tree/master/examples

An example Earthfile should also be included which can build, test, and produce a docker file of the example. 

The [Go example](https://github.com/earthly/earthly/tree/master/examples/go) can serve as a reference point for how to structure an example.

**Comment by RajivSah** [comment]
Can I take this?

**Comment by agbell** [comment]
Hi @RajivSah, you certainly can.  Let me know if you have any questions or jump on our Gitter channel:
https://gitter.im/earthly-room/community

**Comment by RajivSah** [comment]
Thanks.

**Comment by RajivSah** [comment]
Wouldn't setting up new rails app in the example folder create multiple files as the new rails project contains a lot of files?

**Comment by zedtux** [comment]
Well, for Python, there's no featured framework, why would it be for Ruby?

I guess @agbell meant Ruby, not Rails.

**Comment by agbell** [comment]
Hi @zedtux and @RajivSah ,
I was thinking an actual ruby on rails example.  I also put a ticket in for a django example.  The problem we are trying to solve here is somebody has a rails project and is considering using early to run the tests and containerize it, we want to give them an example that they can work off of.  I think a small ruby example would also be useful.

**Comment by zedtux** [comment]
@RajivSah will you do both, Ruby or Rails?

**Comment by RajivSah** [comment]
The ruby example has been merged, I am working on rails as well.

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.

**Comment by RajivSah** [comment]
> I would like to work on this issue.

You can take it if you want.

**Comment by Gauravsaha-97** [comment]
@RajivSah Created a PR

**Comment by zedtux** [comment]
@Gauravsaha-97 I believe you messed up with your PR #371 as it contains the same code (The C example) than the PR #369.

Can you please double check?

**Comment by Gauravsaha-97** [comment]
Actually, I messed up with the commit message. The code in the two PRs are
different. I dont know how to edit the commit message.

**Comment by zedtux** [comment]
Okay, sorry, you're right. The PR #371 has both Ruby and C examples because its branch is a child of #369.

Have look at [Changing a commit message](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message) from Github's documentation.

**Comment by Gauravsaha-97** [comment]
I have changed the commit message.
