### ISSUE TITLE
allow turning off fail-fast behavior

### ISSUE THREAD

**Issue by mitre-tm** [earthly/earthly#3452]
**Use case**

Analogous to [GitHub Actions fail-fast: false](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast). This could help to find more errors at a time.

**Expected Behavior**

Analogous to [GitHub Actions fail-fast: false](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast).

It would be a CLI argument, ex: `--do-not-fail-fast` or `--fail-fast false`.

**Comment by alexcb** [comment]
duplicate of #607
