### ISSUE TITLE
docker-compose not available on latest earthly/dind:ubuntu images but it  was available in earthly/dind:ubuntu-

### ISSUE THREAD

**Issue by jrodrigv** [earthly/earthly#3458]
**What went wrong?**
I can do this with the older ubuntu tag:
```
dummy-with-docker-compose:
    FROM earthly/dind:ubuntu-
    WITH DOCKER
        RUN docker-compose info
    END
```
However using the newer images like: earthly/dind:ubuntu-23.04-docker-24.0.5-1

The output is:

> +dummy-with-docker-compose *failed* | --> WITH DOCKER RUN --privileged docker-compose info
> +dummy-with-docker-compose *failed* | Starting dockerd with data root /var/earthly/dind/fe5e66bc350c368ce8c60e3033d40565e0aa6db75fe61f10f564ca9f37488469/tmp.wT4MRSaceT
> +dummy-with-docker-compose *failed* | /bin/sh: 1: docker-compose: not found

**What should have happened?**
It would be ideal to have full access to docker-compose cli for special escenarios like this:
```
RUN --privileged mkdir logs && \
           export VERSION=ci && \
           docker-compose -f ${COMPOSE} up --build  --exit-code-from host-instrument-mock
```

**Comment by idodod** [comment]
Hi @jrodrigv ,
In the newer image `docker-compose` command changed to `docker compose`.
We will update our docs/examples to make it clearer when using the new tags.

**Comment by jrodrigv** [comment]
Thanks you! I didn't about the command name change
