### ISSUE TITLE
Contribute Earthfile to other open-source projects

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#351]
As part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), you may contribute Earthfiles to other open-source projects. Please check with maintainer of the project first.

**Comment by kichloo** [comment]
Hi @vladaionescu, I am a beginner and would like to take up this issue. Please assign it to me.

**Comment by agbell** [comment]
Hi @kichloo,
This is more of an open-ended ticket, that can be taken by many people.  It is adding an earthfile based build to any open source project.

**Comment by kichloo** [comment]
@agbell Oh! I am interested in taking this up, so can you explain how to go about this issue, meaning the steps?

**Comment by agbell** [comment]
Hi @kichloo, Earthly is a build tool. If there were an open-source project that you worked on that used make files for building you could open a PR to add an earthfile, that could be used instead.  
You could add an earthfile to this project of yours for instance: 
https://github.com/kichloo/kubectl-who-can
