### ISSUE TITLE
Go Integration Test Example

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#352]
We have a simple go example being built by earthly here:
https://github.com/earthly/earthly/tree/master/examples/go

It would be nice to have a second, more detailed go example, that included unit tests and integration tests and build targets for each of these.  It would be more similar to this example https://github.com/earthly/earthly/blob/master/examples/integration-test/Earthfile but in go.

**Comment by ShubhamPalriwala** [comment]
Hey, I'd like to take this issue up !

**Comment by vladaionescu** [comment]
Sold

**Comment by ShubhamPalriwala** [comment]
Hey @vladaionescu so basically you want me to write a similar example in Go like the one you mentioned right ?
Or you want me to write some easy to understand Golang code which helps users understand the syntax?

**Comment by agbell** [comment]
Hi @ShubhamPalriwala,
Imagine a potential user of earthly that has a go service that talks to a data store (say redis) and has unit tests and integration tests (that is tests that test pushing and pulling data out of the store).  

We want to create an example that shows how they could use earthly to build, unit test, integration test and dockerize a similar project.   So the example can be quite simple but should have those components and build targets for them in the Earthfile. In this way it serves to show how they could use earthly for their project.

**Comment by JosemyDuarte** [comment]
Hi all! I have just opened a PR building on top of the current Golang example some unit-test and integration tests as described by @adamgordonbell. Any suggestion will be appreciated.
