### ISSUE TITLE
Mount caches should include `build-args` in key by default

### ISSUE THREAD

**Issue by xv-ian-c** [earthly/earthly#3549]
**What went wrong?**

Using http://github.com/earthly/lib/rust I have a target which uses `ARG debian=bookworm` and `FROM rust:1.74.0-$debian`, roughly:

```
VERSION --global-cache 0.7
ARG --global debian=bookworm
+build
    FROM rust:1.74.0-$debian
    COPY --keep-ts --dir Cargo.toml Cargo.lock .
    DO rust-udc+CARGO --args="build --release" --output="$release/app$"
    SAVE ARTIFACT --keep-ts ./target/release/app AS LOCAL artifacts
```

I expected `earthly +build` to produce me a bookworm compatible binary and `earthly +build --debian=bullseye` to produce me a bullseye compatible binary.

However I find that in the latter case I get a binary which depends on symbols in bookworm's libc, i.e. it was actually built in a bookworm environment.

This is because within the lib/rust there is:

```
RUN --mount=type=cache,mode=0777,id=$cache_id,sharing=shared,target=$CARGO_HOME \
    --mount=type=cache,mode=0777,target=target ... cargo $args...
 ```

and that `target=target` cache is shared between the two invocations of the `build` target even though the build args differed.

**What should have happened?**

My built artifacts should accurately reflect the difference in build args.

I think this implies that the key used for `--mount=type=cache,mode=0777,target=target` should include not just the `target` but also the build args.

I can workaround by using cargo's `--target-dir` to add `$debian` into the path:

```
+build
    ARG debian=bookworm
    FROM rust:1.74.0-$debian
    COPY --keep-ts --dir Cargo.toml Cargo.lock .
    DO rust-udc+CARGO --args="build --target-dir=target/$debian --release" --output="$debian/$release/app$"
    SAVE ARTIFACT --keep-ts ./target/$debian/release/app AS LOCAL artifacts
```

**Comment by idelvall** [comment]
Notice that manually changing the `FROM` image to another (without using an arg), would still make it fail, since no arguments would be involved any more.

**Comment by idelvall** [comment]
Recently changed: https://github.com/earthly/earthly/commit/8d8eaa573fddec8463fa77d320fed466ad199071

**Comment by idelvall** [comment]
closing due to https://github.com/earthly/earthly/commit/8d8eaa573fddec8463fa77d320fed466ad199071
