### ISSUE TITLE
C Example

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#357]
We need an example c application added to the examples folder:
https://github.com/earthly/earthly/tree/master/examples

An example Earthfile should also be included which can build and produce a docker file of the example.

The Go example can serve as a reference point for how to structure an example.

**Comment by kzuri** [comment]
Hello @agbell, I would like to take up this issue. 😄

**Comment by vladaionescu** [comment]
Sold

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.

**Comment by AnshMishra2001** [comment]
Can I work on this issue, pls?

**Comment by alexcb** [comment]
Go for it @AnshMishra2001 , if it's possible we would really like to see an example that makes use of the cunit library for an example of performing unittesting of a simple function. A suggestion could be to write a program that implements a fibonacci function along with a second program that uses cunit to test that function.

**Comment by sea-grass** [comment]
Since there hasn't been any activity on this issue in a while, is it okay if I pick this up?

**Comment by vladaionescu** [comment]
Sure @sea-grass - feel free. Seems that many people offered but nobody has shown anything yet.

**Comment by sea-grass** [comment]
Thanks! I just created a PR that adds a C example: https://github.com/earthly/earthly/pull/1235. Let me know if there's someone I should tag as a reviewer.

**Comment by vladaionescu** [comment]
Awesome! Added @alexcb as reviewer.
