### ISSUE TITLE
Syntax highlighting for Intellij

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#359]
We already have a [TextMate grammar](https://github.com/earthly/earthly/blob/master/contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json). We should port it / recreate it for intellij syntax highlighting.

**Comment by baspalinckx** [comment]
Hi @agbell Would love to help, but doesn't Intellij support TextMate out of the box? https://www.jetbrains.com/help/idea/textmate.html

**Comment by vladaionescu** [comment]
Indeed - it's a task of mostly repackaging as an IntelliJ plugin and making sure that everything works as expected @baspalinckx

**Comment by notmeta** [comment]
A workaround (for now) I've found is you can actually select the `contrib/eathfile-syntax-highlighting` directory as a TextMate bundle: https://www.jetbrains.com/help/idea/textmate.html

The only problem is it does not recognise files named `Earthfile`, only `*.Earthfile`, I suspect this is a problem with IntelliJ's plugin as I've tried messing about with no success (such as adding an explicit 'Earthfile' `fileType` entry).

**Comment by ingwarsw** [comment]
@notmeta For me your workaround works for plain `Earthfile` files as a charm.. and I did not had to do anything special..

**Comment by sharyar** [comment]
This does not work @notmeta as that textmate bundle causes pycharm to freeze every-time I try to edit an earthly file. Is there any other solution that anyone has discovered so far?

**Comment by ingwarsw** [comment]
Actually I dropped using syntax cause I had a lot of freezes also..

**Comment by felpeyu** [comment]
Plugin available in the IntelliJ marketplace!
![image](https://user-images.githubusercontent.com/114394155/201369669-34de7727-e66c-4ec3-a8db-7ee64e5b000c.png)
