### ISSUE TITLE
Vim Syntax Highlighting Support

### ISSUE THREAD

**Issue by agbell** [earthly/earthly#360]
We already have a [TextMate grammar](https://github.com/earthly/earthly/blob/master/contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json) for VS Code syntax highlighting. 

We need one for [VIM](https://vim.fandom.com/wiki/Creating_your_own_syntax_files)

**Comment by abhisht51** [comment]
Hi, can you please elaborate on how to get started on this? Since it has a good first issue, I would want to contribute to this.

**Comment by agbell** [comment]
Hi abhist51,
A good place to get started would be to find vim syntax highlighting for docker files and adjust it so that is cover earthfiles.  Comparing it to the linked TextMate grammar may help.

**Comment by HexF** [comment]
Hi,
@abhisht51 have you made a start on it, or do you think I could do it?
If not, I should have a PR in the next few hours.

**Comment by abhisht51** [comment]
I am a little busy right now so please feel free to commit.
