### ISSUE TITLE
An earth command that turns Dockerfiles into Earthfiles

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#361]
Although Earthly supports Dockerfiles via `FROM DOCKERFILE`, there are many cases where translating the build to Earthly is beneficial, in order to have access to all the Earthly features.

Some of the key things that this conversion should do:

* Dockerfile multi-stage builds are turned into Earthly multi-target builds
* Single-stage builds are turned into a single-target Earthfile
* Any Dockerfile command that is not supported is passed on as a commented out command (eg `SHELL`) and display a warning
* COPY --from are turned into `SAVE ARTIFACT` and `COPY +target/artifact`
* We don't need to support the new Dockerfile experimental syntaxes in the first version

Ideally this reuses the same Dockerfile parser that Buildkit uses.

Suggested command usage: `earth docker-to-earth -o ./Earthfile ./Dockerfile` or `cat ./Dockerfile | earth docker-to-earth - >./Earthfile`

Credit to @dchw for the idea.

**Comment by avats-dev** [comment]
Hi @vladaionescu , I am willing to work on this. I know a bit about docker (still learning it). Can you guide me how to resolve this? Thanks.

**Comment by vladaionescu** [comment]
Hi @avats-dev - this issue requires significant experience with Dockerfiles unfortunately.

**Comment by vladaionescu** [comment]
Hey @26tanishabanik - can you provide a very basic prototype first?

**Comment by alexcb** [comment]
It seems like this has been done already:

```
$ earthly docker2earthly --help
NAME:
   earthly docker2earthly - Convert a Dockerfile into Earthfile

USAGE:
   earthly docker2earthly [command options] [arguments...]

DESCRIPTION:
   Converts an existing dockerfile into an Earthfile

OPTIONS:
   --dockerfile value  Path to dockerfile input, or - for stdin (default: "Dockerfile")
   --earthfile value   Path to Earthfile output, or - for stdout (default: "Earthfile")
   --tag value         Name and tag for the built image; formatted as 'name:tag'
   --help, -h          show help (default: false)
```

we even have a test for it: https://github.com/earthly/earthly/blob/7a7ebb9bb8d999e9140b1e51c03ed9ff78c64c31/tests/docker2earth/test.sh
