### ISSUE TITLE
The auto-skip feature cannot handle symlinks

### ISSUE THREAD

**Issue by madsnedergaard** [earthly/earthly#3631]
**What went wrong?**

I am getting an error where Earthly cannot determine the hash due to a symlink (at least I think that is what is causing it).

![Screenshot 2023-12-20 at 13 46 02](https://github.com/earthly/earthly/assets/3296643/a1854aa8-043f-4606-bd33-04609fcada85)

> unable to calculate hash for +test-projects: unable to determine hash
failed to hash file contrib/electricitymap: read contrib/electricitymap/contrib/parsers: is a directory

Here is how the Earthfiles involved look:
```
# app-backend Earthfile
src-files:
  FROM +deps
  COPY ../../contrib+src-files/* /contrib
  COPY src ./src

# contrib Earthfile
src-files:
  COPY electricitymap ./electricitymap
  COPY parsers ./parsers
  SAVE ARTIFACT .
```

And here is the specific symlink that is causing problems:

![Screenshot 2023-12-20 at 13 49 08](https://github.com/earthly/earthly/assets/3296643/7ff168f2-ee38-4c3f-bda7-c964b92d41a0)
https://github.com/electricitymaps/electricitymaps-contrib/blob/master/electricitymap/contrib/parsers

**What should have happened?**

It should not crash, but instead follow the symlink.

**Other information**
- Using xlarge satellite with `0.7.23`
- Running on GitHub Actions

Interestingly, this job also returned an `inconsistent graph state` error (#2454), but I don't know if it's related or just a coincidence:

> _unknown *failed* | build target: build main: failed to solve: async force execution for ./projects/app-backend+src-files: unlazy force execution: failed to get edge: inconsistent graph state

**Comment by mikejholly** [comment]
Hey @madsnedergaard. Thanks for the report. Since this repo is public, would you mind sharing a link (or branch) to the problem Earthfile? And is the target working without auto-skip? I'm having trouble getting `COPY` to work with symlinks in general for a repro case. Thanks.

**Comment by mikejholly** [comment]
Would you also mind upgrading your CLI to https://github.com/earthly/earthly/releases/tag/v0.7.23? It looks like you may be using an older version. I'm using v0.7.23 and the auto-skip hashing appears to work. However, `COPY`-ing a symlink only works when the symlink is nested inside another directory.

**Comment by mikejholly** [comment]
Related: https://github.com/earthly/earthly/issues/3646

**Comment by madsnedergaard** [comment]
Sorry for the late reply, I was trying to reproduce the problem in [a new repo](https://github.com/electricitymaps/earthly-auto-skip-bug-repro), but it works fine - so it might definitely be related to the CLI version update that I missed! I somehow thought it wouldn't matter when the satellite was running latest version :)

**Comment by mikejholly** [comment]
@madsnedergaard Great to hear! Thanks for checking. I'll go ahead and close this issue for now. If you see the problem again, please reopen it.
