### ISSUE TITLE
GitHub Actions badge in the README is broken as it points to unknown workflow name

### ISSUE THREAD

**Issue by mbrukman** [earthly/earthly#3659]
The README badge:

https://github.com/earthly/earthly/blob/642e0fd3eb7db27406655405d2bae7ca9c9f55b8/README.md?plain=1#L10

has the following components:

* image: https://github.com/earthly/earthly/workflows/GitHub%20Actions%20CI/badge.svg
* URL: https://github.com/earthly/earthly/actions?query=workflow%3A%22GitHub+Actions+CI%22+branch%3Amain

There are 2 issues here:

1. the image is broken, and
2. clicking on the image shows no results:

   > No results matched your search.

This is probably because there is no workflow with the literal name of "GitHub Actions CI", but there are dozens of other workflows, so it should probably be updated in both places (the image and the target URL) to match the name of an existing workflow whose status belongs in the README.

**Comment by AkintolaRichard** [comment]
Hi @idodod 
I would love to help fix this issue, but I would need your guidance on solving the issue.
