### ISSUE TITLE
Part 1 of documentation fails - is this even maintained ? 

### ISSUE THREAD

**Issue by Glagnar** [earthly/earthly#3675]
**Does existing documentation exist?**
https://docs.earthly.dev/basics/part-1-a-simple-earthfile
it states I should the the command
```bash
earthly --artifact github.com/earthly/earthly/examples/tutorial/go:main+part1/part1 ./part1
```

**Request**
Failed due to:
```bash
Error: resolve build context for target github.com/earthly/earthly/examples/tutorial/go:main+part1: 1 validation issues.
- Earthfile version is invalid, supported versions are 0.5, 0.6, or 0.7
```

**Comment by vladaionescu** [comment]
Hi Glagnar - we actually upgraded our examples for our upcoming release 0.8, and this seems to be breaking things for 0.7.

Can you try `earthly --artifact github.com/earthly/earthly/examples/tutorial/go:main-0.7+part1/part1 ./part1`

**Comment by Glagnar** [comment]
Thank you @vladaionescu this works. Great work, look forward to testing earthly.
I hope you have a chance to test the documentation against the working code in the future, as this can be quite frustrating.

**Comment by vladaionescu** [comment]
Indeed - that would be fantastic
