### ISSUE TITLE
Auto-skip performance issue 

### ISSUE THREAD

**Issue by mikejholly** [earthly/earthly#3691]
**What went wrong?**

Auto-skip hash calculation is sometimes taking multiple minutes (sometimes over 10m!) for unknown reasons. 

**What should have happened?**

The hash calculation shouldn't be taking longer than a few seconds. 

**Other Helpful Information**

![image](https://github.com/earthly/earthly/assets/332408/3087a7b9-19c3-4425-9ae1-935adc0a7b5c)

Reported by Mads here: https://earthlycommunity.slack.com/archives/C01DL2928RM/p1704795622712029

**Comment by madsnedergaard** [comment]
> How many files are being copied? 

Quite a lot, but I don't know the exact number - is there an easy way to get that number with Earthly?

> What OS are you using?

MacOS, but same problem when running on Linux in GitHub Actions.

> Is it possible to create a simple reproduction case in a public repo?

I'll make an attempt!

**Comment by madsnedergaard** [comment]
Alright, I was able to reproduce the problem over here: https://github.com/madsnedergaard/earthly-repro
Before adding contrib folder, the execution time was averaging around 30s, but after adding a contrib target to all libs it jumped to 1m30s. I have then removed **a lot** of files from the contrib folder, so the target is now copying only 4 files (60kb) instead of thousands of files and hundreds of megabytes. This made the average execution fall to 60s, which still seems very high and enough to reproduce the problem.

The contrib folder is a submodule of https://github.com/electricitymaps/electricitymaps-contrib, but in the reproduction case I have just copied it over and deleted the majority of files.


![Screenshot 2024-01-11 at 12 36 45](https://github.com/earthly/earthly/assets/3296643/ec3c0aef-2597-43ef-8bc8-bdfd46413cfd)

**Comment by madsnedergaard** [comment]
Interestingly, running without `--auto-skip` and with `--no-cache`, the build only takes around 15-20 seconds:
![Screenshot 2024-01-11 at 12 40 50](https://github.com/earthly/earthly/assets/3296643/88b0829d-5341-41a3-9d5c-a25c85a68700).

Here are the logs, so you can see what is going on in the builds without `--auto-skip`:
- Normal logs: https://cloud.earthly.dev/builds/9174a328-0329-4e5b-872e-b9d90ffe96ff
- Verbose logs: https://cloud.earthly.dev/builds/23bfd35a-c764-4747-b97f-948c303bd2ba

**Comment by mikejholly** [comment]
@madsnedergaard thanks so much for creating that repro case! That will help me a lot. :partying_face:

**Comment by madsnedergaard** [comment]
Happy to help, and I'm still very excited about the feature! :)
Let me know if there's anything else I can do

**Comment by mikejholly** [comment]
@madsnedergaard would it be possible to build from this branch and run a test? https://github.com/earthly/earthly/pull/3700

You should be able to clone this repo and build for Mac using `[+for-darwin](https://github.com/earthly/earthly/blob/main/Earthfile#L608)`. That will output `./build/darwin`.

In my test, the repro case is now finishing in 1s. Hopefully, you see similar results :slightly_smiling_face:

**Comment by madsnedergaard** [comment]
Waaaay faster now on repro case! 😍 
![Screenshot 2024-01-12 at 09 22 11](https://github.com/earthly/earthly/assets/3296643/2d7a51d7-677c-4245-ac49-63d8b3f5bd3a)

For some reason I cannot build with the binary on our main repository, although the exact same binary works just fine on the repro repo 🤔 
![Screenshot 2024-01-12 at 09 59 46](https://github.com/earthly/earthly/assets/3296643/c1522e99-ce00-4a86-a96a-618cb6e05046)
![Screenshot 2024-01-12 at 10 00 00](https://github.com/earthly/earthly/assets/3296643/58de0460-f479-4b0e-b37e-722d331b4577)

**Comment by mikejholly** [comment]
Nice, I'm glad that it's a lot faster. We'll probably merge this PR.

I'm not sure why that crash is happening, but I bet that removing `--auto-skip` will cause a crash in `earthly-repro` as well. This is because `--auto-skip` runs won't contact BuildKit if the build can be skipped.  

I'll look into why that build is failing. It may have to do with how Earthly was built.

**Comment by mikejholly** [comment]
@madsnedergaard can you repro that crash and then run `docker logs earthly-dev-buildkitd`. Hopefully, that will show some extra info.

**Comment by mikejholly** [comment]
@brandonSc helped me out by confirming that the patch led to a significant speedup. 

```
❯ time moonly --auto-skip -V +test-libs
            frontend | Running command: docker info
            frontend | Running command: docker info --format={{.SecurityOptions}}
            frontend | Running command: docker info --format={{.DockerRootDir}}
            frontend | docker-shell frontend initialized.
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           auto-skip | targets visited: 84; targets hashed: 28; target cache hits: 56
           auto-skip | hash calculation took 2.472388333s
           auto-skip | unable to detect all git metadata: returned error exit status 128: : Could not auto-detect or parse Git tags
           auto-skip | Target github.com/madsnedergaard/earthly-repro+test-libs (hash 2d08643b7736d54c901332a0b00bfb15103fab42) has already been run. Skipping.

========================== 🌍 Earthly Build  ✅ SUCCESS ==========================

moonly --auto-skip -V +test-libs  1.69s user 1.62s system 80% cpu 4.094 total
```

**Comment by madsnedergaard** [comment]
> Actually, this error may be to do with using `+for-darwin` rather than `+for-darwin-m1`. Can you try that? We also have `+for-own` which is meant to handle the OS flavor automatically.

I did use `for-dawin-m1`, and the binary worked for one repository but not the other.
Anyway, happy that the change is merged and I'm eagerly awaiting a new release so we can try it in production :)
