### ISSUE TITLE
add a flag to disable failing fast

### ISSUE THREAD

**Issue by mitre-tm** [earthly/earthly#3709]
**Use case**

Earthly could have feature a [fail-fast: false](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) equivalent behavior, e.g., via a CLI flag. That would allow maximizing the amount of information conveyed by each single execution.

Imagine we have 10 targets, each checking one aspect. Instead of fail 1, fix 1, fail 3, fix 3, fail 7, fix 7, we could have fail 1,3,7, fix 1,3,7. Batching. Saves developer time. If makes sense for independent checks, not so much for builds or deploys.

Related: [Slack Thread](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1705094118990009)

**Comment by alexcb** [comment]
duplicate of #607
