### ISSUE TITLE
SAVE IMAGE connection refused

### ISSUE THREAD

**Issue by mikejholly** [earthly/earthly#3736]
**What went wrong?**

A user reported the following error when he attempted to run a build with a `SAVE IMAGE` on Jenkins CI with Linux.

```
[2024-01-22T23:20:34.964Z]               output | --> exporting outputs
[2024-01-22T23:20:47.159Z]               output | [----------] 100% exporting outputs[K
[2024-01-22T23:20:55.244Z] Error: pull ping error: pull ping response: rpc error: code = Unknown desc = image pull: 1 error occurred:
[2024-01-22T23:20:55.244Z] 	* command failed: docker pull 127.0.0.1:35137/sess-jwd728vcbn4ni32eu360wnxmi/pullping:img-0: exit status 1: Error response from daemon: Get "http://127.0.0.1:35137/v2/": dial tcp 127.0.0.1:35137: connect: connection refused: exit status 1
```

**What should have happened?**

The build should have been completed as usual.

**Other Helpful Information**

https://earthlycommunity.slack.com/archives/C01DL2928RM/p1705973717313219

**Comment by mikejholly** [comment]
Workaround:

**Comment by mikejholly** [comment]
It looks as though the registry proxy is failing after startup. If it fails on start-up, the build should fall back to tar-based image transfer.

https://github.com/earthly/earthly/blob/main/builder/builder.go#L198

**Comment by mikejholly** [comment]
This message in a user's logs indicates that the proxy started correctly. 

```
registry-proxy | Starting registry proxy on 127.0.0.1:33849
```

**Comment by mikejholly** [comment]
It turns out the user was running Earthly in a Docker container. 

Here's how to reproduce:

```
docker run --privileged -e NO_BUILDKIT=1 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/workspace -v earthly-tmp:/tmp/earthly:rw  -it docker.io/earthly/earthly -V +for-linux
```

Excerpt:
```
Error: pull ping error: pull ping response: rpc error: code = Unknown desc = image pull: 1 error occurred:
	* command failed: docker pull 127.0.0.1:34133/sess-kx4b26mhnc5s3ewlbj57ozoah/pullping:img-0: exit status 1: Error response from daemon: Get "http://127.0.0.1:34133/v2/": dial tcp 127.0.0.1:34133: connect: connection refused: exit status 1

```

**Comment by mikejholly** [comment]
Another workaround would be to use `--network=host` when running the container.

We could also expose the registry port and allow the port value to be manually specified.

**Comment by rrjjvv** [comment]
I think I ran into this in v0.8.3 (a version after the 'fix'), but after looking at the linked PRs, I don't think it's a regression but a misleading/incomplete changelog description.  This is only 'fixed' for users running (or deriving from) Earthly's published image, correct?  For users that add the earthly binary to their own images, they will still have to apply one of the workarounds in this issue, correct?
