### ISSUE TITLE
Caching "earthly-cache" volume between builds

### ISSUE THREAD

**Issue by zedtux** [earthly/earthly#375]
I'm trying to figure what's the path to be cached by Gitlab in order to speed up the earth builds.

Can you please tell me, if you know it, what path should I pass to the cache `paths` attribute in order to get the `earthly-cache` container volume cached on Gitlab CI?

**Comment by zedtux** [comment]
Sounds harder than just adding a path to the cache ...

As of now, I've explored the use of `docker export` and `docker import` without success ... I can't restore the `earthly-cache` volume 🤔

**Comment by vladaionescu** [comment]
Hi @zedtux - we've experimented in the past with exporting such a volume and the performance was not very good. We currently don't have an officially supported Earthly way of exporting / importing the cache.

We have on our roadmap to provide shared caching over the next 6-9 months, however.

**Comment by zedtux** [comment]
Thank you for your comment @vladaionescu 👍

**Comment by TriplEight** [comment]
You can set it up in the gitlab-docker-runner settings. Set the persistent volume in runner's host fs.
Then, do not use the Gitlab's `cache`. Instead, put your cache to that mount.

**Comment by zedtux** [comment]
> You can set it up in the gitlab-docker-runner settings.

Wouldn't this implies to have my own server running it? I'm actually using Gitlab.com.

**Comment by TriplEight** [comment]
> Wouldn't this implies to have my own server running it? I'm actually using Gitlab.com.

Yes, for that you have to run at least your own gitlab-runner

**Comment by zedtux** [comment]
Thank you anyway for your comment.

**Comment by vladaionescu** [comment]
Issue to follow:

* https://github.com/earthly/earthly/issues/11
* https://github.com/earthly/earthly/issues/574
