### ISSUE TITLE
Adding issue labeller and greeting Github actions

### ISSUE THREAD

**Issue by bislara** [earthly/earthly#376]
__What should we do?__

Add issue labeller action to add relevant labels to the issues once created. 
Add GitHub action to greet a first-time contributor for an issue or a PR.

__Why should we do it?__
Adding labelled would help to understand whats the issue is about. 
Adding greeting action will encourage the first time contributors to contribute more and more

**Comment by vladaionescu** [comment]
Thanks - we're not interested in doing these at this time.
