### ISSUE TITLE
Iptables missing from earthly/dind:alpine-3.19

### ISSUE THREAD

**Issue by kukkok3** [earthly/earthly#3784]
**What went wrong?**

Running a target using the latest `earthly/dind:alpine-3.19` with `WITH DOCKER` fails with
```
ERROR: dockerd crashed on startup
........
........
 level=warning msg="failed to find iptables" error="exec: \"iptables\": executable file not found in $PATH"
```
I'm running WSL version: 2.0.9.0 Ubuntu 20.04.6 LTS

To reproduce run:
```
hello:
        FROM earthly/dind:alpine-3.19-docker-25.0.2-r0-20240206002608
        WITH DOCKER --pull hello-world
            RUN docker run hello-world
        END
```

**What should have happened?**

**Workaround:**
Use  FROM earthly/dind:alpine-3.18

**Comment by alexcb** [comment]
thanks for the report; perhaps it's WSL related? I can't replicate it under linux (ubuntu 23.10, amd64, cgroups v2)

**Comment by ingwarsw** [comment]
We had exactly the same issue..
What helped was changing to
```
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
```

Any more info that could help with fixing it in long run? Cause its happing from release to release..

**Comment by ingwarsw** [comment]
On CI

Using `dind:alpine`
```
00:01:08.510   earthly/dind:alpine | --> Load metadata earthly/dind:alpine linux/amd64
...
00:01:09.025     +integration-test | --> RUN --privileged iptables --list
00:01:09.282     +integration-test | iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
00:01:09.282     +integration-test | ERROR Earthfile line 111:4
00:01:09.282     +integration-test |       The command
00:01:09.282     +integration-test |           RUN --privileged iptables --list
```

`alpine-3.19`

```
00:01:08.854    e/dind:alpine-3.19 | --> Load metadata earthly/dind:alpine-3.19 linux/amd64
00:01:09.633     +integration-test | --> RUN --privileged iptables --list
00:01:09.891     +integration-test | iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
00:01:09.891     +integration-test | ERROR Earthfile line 111:4
00:01:09.891     +integration-test |       The command
00:01:09.891     +integration-test |           RUN --privileged iptables --list
```

**Comment by alexcb** [comment]
it looks like alpine 3.19 contains a different version of iptables compared to 3.18

```
$ docker run --rm earthly/dind:alpine-3.19-docker-25.0.2-r0 ls -la /sbin/iptables
lrwxrwxrwx    1 root     root            17 Feb  5 21:59 /sbin/iptables -> xtables-nft-multi
```

vs

```
$ docker run --rm earthly/dind:alpine-3.18-docker-23.0.6-r4 ls -la /sbin/iptables
lrwxrwxrwx    1 root     root            20 Aug  9 18:18 /sbin/iptables -> xtables-legacy-multi
```

**Comment by kukkok3** [comment]
Thanks for looking into this, yes the problem seems to be related to WSL.
I think what happens is that when earthly detects that it is running on WSL, it tries to switch to iptables-legacy ([here](https://github.com/earthly/earthly/blob/10a75b0d04f87f5062e98bbe4d7b1831cbf3c3ad/buildkitd/dockerd-wrapper.sh#L125)), but as you found out, in the latest alpine, there is no iptables-legacy anymore and it fails. Installing iptables-legacy does the trick
`hello:  
        FROM earthly/dind:alpine-3.19-docker-25.0.2-r0-20240206002608  
        RUN apk update && apk add iptables-legacy  
        WITH DOCKER --pull hello-world  
            RUN docker run hello-world  
        END`

**Comment by ingwarsw** [comment]
@kukkok3 Its not about the WSL..
For us it fails on linux.

Problem is that iptables on container needs to work well with iptables modules installed on OS level.
If they are not matching its bad..

We have talked yesterday with @alexcb on slack and final conclusion was to:
- install both iptables versions (nft and legacy)
- at runtime choose proper one in a way thats now done for [buildkitd entrypoint](https://github.com/earthly/earthly/blob/b1c02a8fdb7119191f0cdd313a013d4b2edb12bc/buildkitd/entrypoint.sh#L67-L110)

**Comment by idodod** [comment]
I believe this issue has been address. Feel free to reopen if you feel otherwise.

Please note that it is encouraged to use the tag that includes both the alpine & the docker versions.
Newer versions will be released at a more rapid pace (maintained in [earthly/dind](https://github.com/earthly/dind))
