### ISSUE TITLE
earthly/dind release process needs improvement

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3786]
currently there's no easy way to only release a single dind image (e.g. only alpine), to do so, I had to manually comment out code:

```
@@ -664,16 +664,16 @@ all-dind:
         --platform=linux/amd64 \
         --platform=linux/arm64 \
         +dind-alpine --DATETIME=$DATETIME
-    BUILD \
-        --pass-args \
-        --platform=linux/amd64 \
-        --platform=linux/arm64 \
-        +dind-ubuntu-20.04 --DATETIME=$DATETIME
-    BUILD \
-        --pass-args \
-        --platform=linux/amd64 \
-        --platform=linux/arm64 \
-        +dind-ubuntu-23.04 --DATETIME=$DATETIME
+    #BUILD \
+    #    --pass-args \
+    #    --platform=linux/amd64 \
+    #    --platform=linux/arm64 \
+    #    +dind-ubuntu-20.04 --DATETIME=$DATETIME
+    #BUILD \
+    #    --pass-args \
+    #    --platform=linux/amd64 \
+    #    --platform=linux/arm64 \
+    #    +dind-ubuntu-23.04 --DATETIME=$DATETIME
 
 # all builds all of the following:
 # - Buildkitd for both linux amd64 and linux arm64
```

furthermore, the `alpine-3.19` tag was never created (but out tutorials reference them), to get unstuck, I had to manually add it in:

```
@@ -574,7 +574,7 @@ dind:
       SAVE IMAGE --push --cache-from=earthly/dind:$OS_IMAGE-main $DOCKERHUB_USER/dind:$OS_IMAGE
     END
     ARG DATETIME="$(date --utc +%Y%m%d%H%M%S)" # note this must be overriden when building a multi-platform image (otherwise the values wont match)
-    SAVE IMAGE --push --cache-from=earthly/dind:$OS_IMAGE-main $DOCKERHUB_USER/dind:$TAG "$DOCKERHUB_USER/dind:$TAG-$DATETIME"
+    SAVE IMAGE --push --cache-from=earthly/dind:$OS_IMAGE-main $DOCKERHUB_USER/dind:alpine-3.19 $DOCKERHUB_USER/dind:$TAG "$DOCKERHUB_USER/dind:$TAG-$DATETIME"
```

## What would be nicer ##

It would be nice to be able to first build and push a tag such as `alpine-3.19-docker-25.0.2-r0-20240206171222`, then we could do some testing with it.

Next, we need a way to create new tags (e.g. `alpine-3.19-docker-25.0.2-r0` and `alpine-3.19`) which would _point_ to the existing tag that contains the timestamp. (note point here denotes the same image digests)

If something were to go wrong, we could use the same re-tagging command to perform a fall-back where we could point an existing tag such as `alpine-3.19` to an older version. (there should never be a need to re-build or push any container layers for a rollback)

**Comment by alexcb** [comment]
we should create some sort of proposal for the changes we want to see in this before jumping into implementing it.

**Comment by idodod** [comment]
The release process is now automated in http://github/earthly/dind
