### ISSUE TITLE
earthly/dind `alpine` tag docs is now outdated

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3793]
**Does existing documentation exist?**
https://hub.docker.com/r/earthly/dind

**Request**
the `alpine` tag was updated to 3.19, which doesn't reflect the docs.

now that we encourage users to pin to specific versions, I think we should revisit using having `alpine` and `ubuntu` point to the latest versions, and update our docs to reflect this.

**Comment by idodod** [comment]
The docs were updated to use the latest release of alpine/ubuntu:20-04/ubuntu:23-04
The dockerhub readme also suggets using one of the explicit versions
