### ISSUE TITLE
EARTHLY_GIT_AUTHOR contains only the email address

### ISSUE THREAD

**Issue by brettdh** [earthly/earthly#3822]
**What went wrong?**
The builtin `EARTHLY_GIT_AUTHOR` env variable is [documented](https://docs.earthly.dev/docs/earthfile/builtin-args#git-related-args) to contain `Author Name <email@example.com>`

1. Create the `Earthfile` below in a directory with a `.git` directory with at least one commit that has an author
2. Run `earthly +test`
3. Compare the output with that of `git show -s --pretty='%an <%ae>'`

```Earthfile
VERSION 0.8

test:
  LOCALLY
  ARG EARTHLY_GIT_AUTHOR
  RUN echo "EARTHLY_GIT_AUTHOR: ${EARTHLY_GIT_AUTHOR}"
```

Repro'd with `LOCALLY` for simplicity, but it's also reproducible with `FROM`.

**What should have happened?**
- The value of `EARTHLY_GIT_AUTHOR` should match the documentation (`Author Name <email@example.com>`)
- Additionally, it would be nice to have separate env vars for the author's name and email.

I'm planning to use a `LOCALLY` target to gather any git info that's not captured by `EARTHLY_` builtins (or which has an issue like this one), write it to a file, `SAVE ARTIFACT`, and `COPY` the artifact into another target.

**Other Helpful Information**

```
➜ earthly --version
earthly version v0.8.2 f991e7fc9261892afe82fe5b20a8952eed14514a darwin/arm64; macOS 13.4 homebrew
```

Output of the commands above, with the `Earthfile` above:

```
➜ earthly +test
<snip>
               +test | darwin/arm64
               +test | --> RUN echo "EARTHLY_GIT_AUTHOR: ${EARTHLY_GIT_AUTHOR}"
               +test | EARTHLY_GIT_AUTHOR: brett.higgins@example.com
              output | --> exporting outputs

➜ git show -s --pretty='%an <%ae>'
Brett Higgins <brett.higgins@example.com>
```

**Comment by idodod** [comment]
will be included in next releases (v0.8.8)
