### ISSUE TITLE
Is possible to pass dynamic flags to `WITH DOCKER`?

### ISSUE THREAD

**Issue by wataruian** [earthly/earthly#3837]
When using `WITH_DOCKER`, is it possible to pass dynamic flags to the command?

Something like this:
```
WITH DOCKER --compose docker-compose.yaml --service service1 --service service2
  // some command
END
```

Where the number of `--service` flags can vary based on the `ARG` supplied. Something like `--SERVICES="service1 service2"`

I tried constructing the flags using `FOR` to loop the values and assign it via `LET/SET` like this:
```
LET buildArgs = ""
FOR service IN $SERVICES
  SET buildArgs = "$buildArgs --service $service"
END
 ```
 The constructed `$buildArgs` looks like this: `--service service1 --service service2` and I am passing it to `WITH DOCKER` via:
 ```
 WITH DOCKER --compose docker-compose.yaml $buildArgs
   // some command
END
```

But is failing: `invalid WITH DOCKER arguments [${buildArgs}]`

Is there a way/hack to achieve dynamic services in docker-compose?

**Comment by alexcb** [comment]
The entire script run will be cached assuming none of the dependencies of the `WITH DOCKER` command change.

Perhaps earthly will some day support arrays, but it's not on our immediate roadmap.
