### ISSUE TITLE
Earthly behaving differently on Travis-CI than locally

### ISSUE THREAD

**Issue by zedtux** [earthly/earthly#385]
I have a case of a Ruby gem I'm working on, that should run against RethinkDB but [it fails on Travis CI](https://travis-ci.com/github/zedtux/database_cleaner-nobrainer/jobs/395988761) because Travis doesn't know how to install RethinkDB anymore.

I then immediately think of Earthly!

I made [my Earthlyfile](https://github.com/zedtux/database_cleaner-nobrainer/blob/master/Earthfile) that works locally, my RSpec tests are passing all is fine!

I obviously want know to run them on Travis so that I made [a .travis-ci.yml file](https://github.com/zedtux/database_cleaner-nobrainer/blob/master/.travis.yml) that simply installs the latest available version on Earthly and run the same command I'm running locally: `earth -P +rspec`.

While all work fine locally, it is failing on Travis.

I tried first with the `--no-cache` flag, but no luck.

Then I stopped and removed the `earthly-buildkitd` container, and deleted the `earthly-cache` docker volume and ran the command again.
While I was seeing the same output than on Travis CI, tests are still passing while they are failing on Travis.

I tried all I could think of and I continue to search what is going wrong here, but can someone help me please?

I'm ready to try anything.

**Comment by vladaionescu** [comment]
Hi @zedtux - I suspect there's an issue in Travis with `--network=host`. Can you try setting that to the composer network instead? The network name is usually the name of the compose project, which by default is the name of the directory in which the docker-compose file exists. So `--network=<name-of-dir>` would work. That should work both locally and in Travis (hopefully!).

**Comment by zedtux** [comment]
Looking at the Travis-CI output closely, I found that [the created network is named `default_default`](https://travis-ci.com/github/zedtux/database_cleaner-nobrainer/builds/188450675#L799).
Is that the name I should use?

**Comment by alexcb** [comment]
I'm not sure if it helps, but I tried running the tests locally on my machine with both:

```
earth -P -i github.com/zedtux/database_cleaner-nobrainer+rspec
```

and

```
git clone github.com/zedtux/database_cleaner-nobrainer
cd database_cleaner-nobrainer
earth -P -i +rspec
```

and in both cases I see the similar error as shown in travis:

```
github.com/zedtux/database_cleaner-nobrainer:master+rspec | fatal: not a git repository (or any of the parent directories): .git
github.com/zedtux/database_cleaner-nobrainer:master+rspec | bundler: failed to load command: rake (/usr/local/bin/rake)
github.com/zedtux/database_cleaner-nobrainer:master+rspec | Bundler::GitError: The git source https://github.com/DatabaseCleaner/database_cleaner is not yet checked out. Please run `bundle install` before trying to start your application
```

I used the `-i` interactive debugger mode which dropped me into a shell and I can see two containers in a failed state:

```
/ # docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS                           PORTS                                                         NAMES
954caa8f987b        zedtux/database_cleaner-nobrainer:latest   "bundle exec rake"       About a minute ago   Exited (1) About a minute ago                                                                  youthful_bassi
b22b94fe1c38        zedtux/database_cleaner-nobrainer:latest   "bundle exec rake"       About a minute ago   Exited (10) About a minute ago                                                                 default_adapter_1
9e2e3cd28df7        rethinkdb:2.4-buster-slim                  "rethinkdb --bind all"   About a minute ago   Up About a minute                0.0.0.0:8080->8080/tcp, 0.0.0.0:28015->28015/tcp, 29015/tcp   default_rethinkdb_1
```

with a couple different error messages in them:

```
/ # docker logs youthful_bassi
fatal: not a git repository (or any of the parent directories): .git
bundler: failed to load command: rake (/usr/local/bin/rake)
Bundler::GitError: The git source https://github.com/DatabaseCleaner/database_cleaner is not yet checked out. Please run `bundle install` before trying to start your application
  /usr/local/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:241:in `allowed_in_path'
  /usr/local/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:198:in `find_local_revision'
  /usr/local/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:68:in `revision'
  /usr/local/lib/ruby/2.7.0/bundler/source/git.rb:226:in `revision'
  /usr/local/lib/ruby/2.7.0/bundler/source/git.rb:93:in `install_path'
  /usr/local/lib/ruby/2.7.0/bundler/source/path.rb:131:in `expanded_path'
  /usr/local/lib/ruby/2.7.0/bundler/source/path.rb:168:in `load_spec_files'
  /usr/local/lib/ruby/2.7.0/bundler/source/git.rb:201:in `load_spec_files'
  /usr/local/lib/ruby/2.7.0/bundler/source/path.rb:105:in `local_specs'
  /usr/local/lib/ruby/2.7.0/bundler/source/git.rb:168:in `specs'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:764:in `block in converge_locked_specs'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:750:in `each'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:750:in `converge_locked_specs'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:247:in `resolve'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
  /usr/local/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
  /usr/local/lib/ruby/2.7.0/bundler.rb:149:in `setup'
  /usr/local/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
  /usr/local/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
  /usr/local/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
  /usr/local/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
/ # docker logs default_adapter_1
Could not locate Gemfile or .bundle/ directory
```

**Comment by zedtux** [comment]
Thank you @alexcb for your comment !

I also tried on Gitlab CI and [it fails too](https://gitlab.com/zedtux/database_cleaner-nobrainer/-/jobs/776218625).

So why is it passing locally ... 🤔 ?

**Comment by alexcb** [comment]
Just thinking out lout.... Are you working out of a clean git repo? can you try checking out a new copy into a different directory and see if the tests pass in that one or not?

**Comment by zedtux** [comment]
I first made it with a `Dockerfile` and a `docker-compose` files and when I saw the issue on Travis I've switched to Earthly.

Thinking of a potential conflict/collision between the `Dockerfile` generated image and the `Earthfile` one, I tried to delete all the images, and tried again but tests are passing.

I'm now giving a try to your idea.

**Comment by zedtux** [comment]
Oh !! Removing the local project folder and cloning it again made it failing locally! Thank you @alexcb !

**Comment by alexcb** [comment]
Awesome! (we'll not awesome that your tests are failing, but awesome to hear you can reproduce it).

I'll close this ticket, but please re-open it if you run into any other inconsistencies between local vs CI.

Cheers!

**Comment by zedtux** [comment]
So what happened? Do you know it?

**Comment by alexcb** [comment]
it sounds like you have some local files that are not checked into git?

**Comment by zedtux** [comment]
Not that I know, sorry.

BTW tests passed now on Travis CI and on Gitlab CI.

**Comment by vladaionescu** [comment]
Awesome! Let us know if you run into any other issues
