### ISSUE TITLE
Regression: COPY --if-exists + wildcard is broken in v0.8

### ISSUE THREAD

**Issue by idelvall** [earthly/earthly#3875]
The following command fails in `v.0.8.x` but works in `v0.7.23`

```
earthly --no-cache +build
```
```
VERSION 0.7

build:
 FROM alpine
 COPY --if-exists non_existing_folder/* /
```

**Comment by mikejholly** [comment]
[This PR](https://github.com/earthly/earthly/pull/3652) may have introduced a regression with the wildcard case.

**Comment by idelvall** [comment]
Thanks Mike!
