### ISSUE TITLE
Git features should just work

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#388]
Earthly by default assumes SSH-based auth for GitHub and GitLab. This works well for many developers, but not for all. Also, in many CI environments SSH-based auth is not configured and Earthly does not work right away.

There should be some way for Earthly to either infer default settings or have a way to try out one approach and switch to the other in case of failure.

Also related issue: https://github.com/earthly/earthly/issues/387

**Comment by BjoernAkAManf** [comment]
Just a small suggestion: Maybe try if ssh_agent is running or if any keys are registered within it? That is definitely not foolproof, but would prevent most new environments to be problematic.
