### ISSUE TITLE
autoskip - targets which should be rerun are skipped as cached

### ISSUE THREAD

**Issue by idodod** [earthly/earthly#3895]
**What went wrong?**

While using the go docker image as the base image to build and run tests for go applications, I noticed that after upgrading the go version, the targets that build & test are still skipped even though I expected those targets to run with the new go version.

common/Earthfile
```Earthfile
VERSION 0.8

ARG GOLANG_VERSION=1.21-alpine
FROM golang:$GOLANG_VERSION
```

some-service/Earthfile
```Earthfile
FROM ../common+base
RUN apk add --update --no-cache build-base ca-certificates curl
WORKDIR /app

deps:
    #COPY go files
    COPY go.mod go.sum ./
    RUN go mod download
```

Earthfile:
```Earthfile
build-services:
    BUILD --autoskip ./some-service+deps
```

`earthly --autoskip +build-services`

**What should have happened?**

Autoskip should have detected that the base image changed and rerun the target

**Other Helpful Information**

**Comment by mikejholly** [comment]
I was able to reproduce this with:

```
VERSION --build-auto-skip 0.8

ARG VERSION=3.18.6
FROM alpine:$VERSION

parent:
    RUN cat /etc/os-release

expand-args-from:
    BUILD --auto-skip +parent
```
