### ISSUE TITLE
Self-hosted satellite questions

### ISSUE THREAD

**Issue by wataruian** [earthly/earthly#3898]
Hi! I've set up my self-hosted satellites on a k8s cluster and it works fine. 

Now I want to set up mTLS for security reasons.

I've found out that it is possible on satellites too (I've done it before with the self-hosted remote buildkit) from this [PR](https://github.com/earthly/earthly/pull/3622)

Any docs/guides on how to implement this?

Also, is it possible to set up pull-through cache with the self-hosted satellites? (I've seen from the docs that Cloud Satellites does not support this yet)

Thanks!

**Comment by brandonSc** [comment]
Hi @wataruian - glad to hear that the new self-hosted satellites are working well for you so far! 

They do actually use mTLS by default, and will generate and configure certificates when they are launched. It's mentioned briefly at the top of the [docs](https://docs.earthly.dev/earthly-cloud/satellites/self-hosted), but perhaps we should elaborate more on it.

As for pull-through cache - I think it should be possible, however, I have not tried it yet myself. You may need to pass the TOML config to buildkit (similar to the [pull-through cache docs](https://docs.earthly.dev/ci-integration/pull-through-cache#configuring-earthly-to-use-the-cache)) using the `EARTHLY_ADDITIONAL_BUILDKIT_CONFIG` environment variable at the satellite container.

**Comment by brandonSc** [comment]
That's awesome, good to know that the pull-through cache works!

I would remove any TLS-related configurations from the satellite and earthly-cli. They should figure it out on their own. Having TLS work out of the box was an important feature for self-hosted satellites.

If you're still getting registration issues, you can send me your satellite and org names and I can bring up the error to help debug (you can send that to me privately via email if you prefer).
