### ISSUE TITLE
`WITH DOCKER --load +target` image name inference is not documented

### ISSUE THREAD

**Issue by glehmann** [earthly/earthly#3917]
In the documentation for `WITH DOCKER` at https://docs.earthly.dev/docs/earthfile#with-docker, `--load` is of the form `--load <image-name>=<target-ref>`. In the examples however we can find some cases where the image name is not provided — `--load +foo`. Indeed this form is supported, if a `SAVE IMAGE` exists in the referenced target.

This should be documented :-)

**Comment by idodod** [comment]
updated docs.
Thanks for reporting the issue @glehmann !
