### ISSUE TITLE
update explicit-cache with note saying attributes are now supported

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3918]
**Does existing documentation exist?**
https://docs.earthly.dev/docs/caching/caching-via-registry#explicit-cache-advanced

**Request**
[#3714](https://github.com/earthly/earthly/issues/3714) and [#3868](https://github.com/earthly/earthly/issues/3868) are now fixed; however we should document that this new feature exists.

For example, users can now run:

```
earthly --remote-cache=harbor.company.team/earthly-cache/test:cache,image-manifest=true,oci-mediatypes=true +example
```

for cases where their registry requires additional attributes to be set.

**Comment by idodod** [comment]
addressed in #3920
