### ISSUE TITLE
insecure-registries not work, still pull image use https in build stage

### ISSUE THREAD

**Issue by rmGFW** [earthly/earthly#3925]
**What went wrong?**

VERSION 0.8
FROM my-self-hosted-registry/xxximage
WORKDIR /go-workdir

 +build | in               xxxxxx:main+base
Error: Earthfile line 5:0 apply FROM: apply build +base: earthfile2llb for +base: Earthfile line 2:0 apply FROM my-self-hosted-registry/xxximage: resolve image config for my-self-hosted-registry/xxximage: failed to do request: Head "https://my-self-hosted-registry/v2/xxximage/manifests/latest": dial tcp 100.64.0.17:443: connect: connection refused

this seems a docker buildkit bug , https://github.com/docker/buildx/issues/1642
but i dont know how to solve this in earthly

**Comment by alexcb** [comment]
Do you have any special config under ~/.earthly/config.yml?

Can you clarify what port and protocol (http vs https) your registry is using?

**Comment by rmGFW** [comment]
> Do you have any special config under ~/.earthly/config.yml?
> 
> Can you clarify what port and protocol (http vs https) your registry is using?

non special config under ~/.earthly , there is no config.yaml under the folder

my self-hosted registry only listen in 80, server http protocol , the https is not supported

**Comment by alexcb** [comment]
> non special config under ~/.earthly , there is no config.yaml under the folder

see https://docs.earthly.dev/docs/guides/configuring-registries/self-signed#insecure-registries for details on setting it up. Please re-open this ticket if it doesn't work.

**Comment by rmGFW** [comment]
<img width="919" alt="image" src="https://github.com/earthly/earthly/assets/66858140/c797c575-e86d-4b51-be8d-b3c275a1c925">
i already put this config in under the  ~/.earthly/config.yml and kill docker container of earthly and run earthly bootstrap , but it still not working

**Comment by alexcb** [comment]
you're screenshot doesn't show `http = true`, which is needed to connect to a regular http server (without it, https will be used)

**Comment by rmGFW** [comment]
> you're screenshot doesn't show `http = true`, which is needed to connect to a regular http server (without it, https will be used)

Actually, there is, sorry ,my screenshot is not complete
<img width="400" alt="image" src="https://github.com/earthly/earthly/assets/66858140/b2beb05d-e19b-4b27-bb49-4edba517b2f4">
<img width="1060" alt="image" src="https://github.com/earthly/earthly/assets/66858140/c79e0159-7c40-4d26-b306-2ef6115898b0">

**Comment by alexcb** [comment]
We have a test that makes use of an http-based registry under https://github.com/earthly/earthly/blob/4ac1b1249aeae62f83aebde28a932eb5ef76bef6/tests/remote-cache/Earthfile#L9

it sets:

```
ARG --global REGISTRY_CONFIG="
[registry.\"$REGISTRY\"]
  http = true
"
```

without an `insecure = true`

can you try omitting it?

If that doesn't work, can you also try setting the port in the config? e.g.

```
[registry."example.com:80"]
  http = true
```

**Comment by rmGFW** [comment]
i have tried, but still not working

**Comment by rmGFW** [comment]
it works ,  i delete the two black space char at the front of http = true ,then it works
