### ISSUE TITLE
Rust Build fails hard when Cargo.toml inherits from workspace config

### ISSUE THREAD

**Issue by marvin-hansen** [earthly/earthly#3928]
## What went wrong?

I wanted to build a shared lib in a Rust mono-repo as a test to see how good Earthly works for Rust. 

The shared lib has zero internal dependencies, and only a few external dependencies. 

However, the build failed because Earthly cannot parse the Cargo.toml that inherits values from the workspace. 

## Can you reproduce it? If so, please list the steps to reproduce the issue. 

1) Create a new folder, ie rust-bug
2) Copy the attached workspace cargo and renamed to Cargo.toml
3) Create a new lib crate called common
4) Replace the Cargo.toml with the attached workspace cargo toml
5) Put in the attached Earthfile 

Run:
earthly +install - Should pass
earthly +source -  Should pass

earthly +build - hard fail See error log. 
 
## Earthfile

 See attachments. 

## **What should have happened?**

An actual build would be great... 

## **Have you found any workarounds?**

Obviously, you could copy&paste all workspace declaration in the Cargo.toml file. 

Here is the catch, I have over 30 (!) crates and every week new get added so this is basically non-maintainable and basically defies the logic of a workspace declaration. 

## **Other Helpful Information**

Error Logs and all config files attached. 

The error message is really clear:

   +build *failed* |   error inheriting `edition` from workspace root manifest's `workspace.package.edition`

I think what's happening is that the Cargo file gets parsed *after* it has been moved into the build container where the Workspace Cargo.file doesn't exists. 

Two possible solutions:

1) Pre-parse the workspace Cargo.toml and if there are workspace declarations, resolve them before copying the Cargo.toml into the build container. 

2) When a workspace config has been detected, just copy the workspace Cargo.toml into the build container and then resolve workspace declarations accordingly. 

Either way, this must be solved because any large Rust project leans on workspace declarations for mete-data, dependencies, or both. I really baffled that hasn't been brought up before 

## Files / Attachments: 
[error.txt](https://github.com/earthly/earthly/files/14681903/error.txt)

[Crate-Cargo.toml.txt](https://github.com/earthly/earthly/files/14681919/Crate-Cargo.toml.txt)

[Workspace-Cargo.toml.txt](https://github.com/earthly/earthly/files/14681932/Workspace-Cargo.toml.txt)

**Comment by idodod** [comment]
CC: @idelvall

**Comment by marvin-hansen** [comment]
Solved.

**Comment by alexcb** [comment]
> Solved.

Was there an issue with earthly, or just an Earthfile or lib issue? It's not clear what was solved, but I'll close this issue. Feel free to add addition context or re-open it if there's an outstanding issue.

**Comment by marvin-hansen** [comment]
I’ve Migrated my entire Rust monorepo to  Bazel and build all images with
the Dockerless rules_oca.

https://codilime.com/blog/bazel-build-system-build-containerized-applications/
