### ISSUE TITLE
buildkit_additional_config not working

### ISSUE THREAD

**Issue by rmGFW** [earthly/earthly#3929]
this is re-open for issue https://github.com/earthly/earthly/issues/3925

i have tried add buildkit_additional_config for set my self-hosted registry to use insecure http 
and i have stop the buildkit docker container and run bootstrap again , already enter the buildkit container check the `/etc/buildkitd.toml` ,  the config is there ,but in the build stage ,it still use https
<img width="1060" alt="image" src="https://github.com/earthly/earthly/assets/66858140/1f1a1ec1-ed3b-4b3f-b8ce-bcb8ac7bb0b3">

by the way ,i install earthly by brew install , and my mac chip is apple silicon

**Comment by alexcb** [comment]
Let's move this back to the original issue (#3925), which I have reopened
