### ISSUE TITLE
how can i load local image 

### ISSUE THREAD

**Issue by rmGFW** [earthly/earthly#3990]
VERSION 0.8
FROM local-image

build:
   ....

---
i want use local image ,but it will pull the local-image then failed

**Comment by Nasfame** [comment]
If u do have dockerfile: then do:

```
dockerfile:
  FROM DOCKERFILE .
  SAVE IMAGE hive:dockerfile
```

If not possible, try to create a dockerfile with the local image specified 

```
FROM local-image
```

I presume this should work in ur system:

```
VERSION 0.8
FROM local-image
```

But make sure u do : `earthly --no-sat +[recipeName]`

**Comment by Nasfame** [comment]
I think its more consistent to use a dockerfile.

**Comment by alexcb** [comment]
duplicate of #1412
