### ISSUE TITLE
SAVE ARTIFACT option to not fail if file does not exist

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#402]
Example use-case: Terraform creating a backup file only if changes are made. We want that backup file to be exported locally. But sometimes the file does not exist.

Perhaps this could be in the form of a flag. Eg `SAVE ARTIFACT --no-fail`. Or something along these lines.

CC @dchw

**Comment by alexcb** [comment]
`SAVE ARTIFACT --if-exists` implements this.
