### ISSUE TITLE
SAVE ARTIFACT after RUN --push

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#403]
In some cases, saving locally the a resulting log file or state file is useful after a `RUN --push` command. Example use-case: saving a backup file after applying a terraform change.

One possible issue with this is that other targets would not be able to COPY such an artifact. So it would only have the effect of saving locally. This might not be obvious to the user, however. The syntax / design of this needs more thinking.

```
RUN --push ....
SAVE ARTIFACT something AS LOCAL something
```

CC @dchw

**Comment by Hritam-stark** [comment]
good

**Comment by alexcb** [comment]
This is now possible with `WAIT` / `END` blocks in `VERSION 0.7`.
