### ISSUE TITLE
Allow access to host docker

### ISSUE THREAD

**Issue by iirekm** [earthly/earthly#4043]
### Use case

There are many usecases for this:
- using Gradle (very slow because daemon is started every time under earthly) - I just ran into this trouble, not a problem in CI, but veeery annoying issue for everyday Java or Android development
- running integration tests requiring some docker containers to start on rootless Docker (`WITH DOCKER` doesn't work)
- running integration tests where the used services take some time to start (e.g. e2e tests of large system with e.g. dozens of microservices) - it's easiest to just start the services on host
- debugging broken integration tests (e.g. being able to connect to a failing database from IDE or a database tool) - again, it's easiest to just start the databases on host
- interoperability with tools like devcontainers or devpod, which again: require long running containers on host

Current workaround:
- connect to host with SSH
- use same file paths as on host, so docker mounts everything correctly, also file references in error messages become clickable in IDE again
- pass the host and cwd with e.g. `earthly ... --host=192.168.0... --cwd=$(pwd)`

I guess the current behavior is because of reproducibility issues, but this option could be accessible with some flag (e.g. `--local` or `--fast`).

### Expected Behavior

Access to host docker should be allowed for the reasons above.

**Comment by alexcb** [comment]
It's possible to do with with [LOCALLY](https://docs.earthly.dev/docs/earthfile#locally) and `WITH DOCKER`.
