### ISSUE TITLE
CMD including env variable does not dynamically work

### ISSUE THREAD

**Issue by danielschlegel** [earthly/earthly#4071]
### What went wrong?

When i create a docker container with a Dockerfile that contains a command including a ENV variable the env variable does not get replaced on docker run. With plain docker this works but not with earthly.

```
docker build -t repro -<<'EOF'
FROM alpine
ENV FOOBAR=fish
CMD echo $FOOBAR
EOF

docker run docker.io/library/repro
# -> fish
docker run -e FOOBAR=cat docker.io/library/repro
# -> cat
```

```
# Earthfile
VERSION 0.8

build:
  FROM alpine
  ENV MSG="I want to get overridden"
  CMD echo "This is your message: $MSG"
  SAVE IMAGE command-with-env-variable
```
```
earthly +build
docker run -e MSG=test command-with-env-variable 
This is your message: I want to get overridden
```

### What should have happened?

Running the docker image i expect it to replace the MSG in the command.

### What earthly version?

earthly version v0.8.8 2718b793272cf8f80fa61071b41fec8469a7427b darwin/arm64; macOS 14.4.1 homebrew

**Comment by rrjjvv** [comment]
If you change your line to either use single quotes
```
CMD echo 'This is your message: $MSG'
```
or escape the dollar sign:
```
CMD echo "This is your message: \$MSG"
```
you should get the desired result.

**Comment by danielschlegel** [comment]
Thanks a lot for this fast answer and solution! That helped.
