### ISSUE TITLE
Artifacts of intermediate targets not stored

### ISSUE THREAD

**Issue by idsvandermolen** [earthly/earthly#4100]
### What went wrong?

It seems `SAVE ARTIFACT` and `SAVE IMAGE` are only effective when you directly call the target that has the statement. 

# Test 1
If you have this Earthfile:
```Earthfile
VERSION 0.8

docker:
    FROM ubuntu:22.04
    SAVE IMAGE earthly-test:latest

build:
    FROM +docker
    COPY --dir input ./
    SAVE ARTIFACT input AS LOCAL output

all:
    BUILD +build
```
There are a few issues here, when calling some commands.
command | image created? | output directory created?
--- | --- | ---
`earthly +all` | no | yes
`earthly +build` | no | yes
`earthly +docker` | yes | no

Note that the output directory is also created when calling `+all`

# Test 2
If we add another intermediate target like this:
```Earthfile
VERSION 0.8

docker:
    FROM ubuntu:22.04
    SAVE IMAGE earthly-test:latest

build:
    FROM +docker
    COPY --dir input ./
    SAVE ARTIFACT input AS LOCAL output

tests:
    FROM +build

all:
    BUILD +tests
```
Then we get this:
command | image created? | output directory created?
--- | --- | ---
`earthly +all` | no | no
`earthly +tests` | no | no
`earthly +build` | no | yes
`earthly +docker` | yes | no

Note that the output directory is _not_ created when calling `+tests` or `+all`, which did work in previous test.

Running `earthly` with `--no-cache` yields the same result.

### What should have happened?

The expected outcome would be that Earthly creates the artifacts also consistently when there is a target in a "chain" with a `SAVE` statement.

### What earthly version?

earthly version v0.8.9 a2fc61ee6e00ed5b8ad09bd06c59451534e2541e darwin/arm64; macOS 14.1 homebrew

### Other Helpful Information

Of course it is still possible we misunderstand Earthly behaviour or are misreading the documentation.

**Comment by eliottwiener-gridunity** [comment]
I believe this is the expected behavior, although I also find it somewhat counterintuitive.

Here is where the docs explain this:

https://docs.earthly.dev/docs/earthfile#save-image

>As of [VERSION 0.6](https://docs.earthly.dev/docs/earthfile#version), images are only saved [if they are connected to the initial target through a chain of BUILD commands](https://docs.earthly.dev/docs/earthfile#what-is-being-output-and-pushed).

https://docs.earthly.dev/docs/earthfile#save-artifact

>As of [VERSION 0.6](https://docs.earthly.dev/docs/earthfile#version), local artifacts are only saved [if they are connected to the initial target through a chain of BUILD commands](https://docs.earthly.dev/docs/earthfile#what-is-being-output-and-pushed).

So the explanation is that `BUILD` will cause images and artifacts to be saved in the sub-target, whereas `FROM` will not.

**Comment by idsvandermolen** [comment]
Perhaps. Note that the url linked in the docs "[if they are connected to the initial target through a chain of BUILD commands](https://docs.earthly.dev/docs/earthfile#what-is-being-output-and-pushed)" is broken and apparently needs to point at the section in the [BUILD](https://docs.earthly.dev/docs/earthfile#build) command.
I'll read that section and try to figure out if it makes sense. However, at first glance as "Test 2" shows, just adding another intermediate target (`tests`) changes the behaviour in (IMO) unexpected ways

**Comment by idsvandermolen** [comment]
I think this section in [FROM](https://docs.earthly.dev/docs/earthfile#from) probably makes it clearer:
> The FROM command does not mark any saved images or artifacts of the referenced target for output, nor does it mark any push commands of the referenced target for pushing. For that, please use [BUILD](https://docs.earthly.dev/docs/earthfile#build).

**Comment by idsvandermolen** [comment]
Actually the docs still don't make it clear to me how to adjust the tests described above to make it work and have both outputs. What I expect is to setup a chain of dependencies and (just like using a `Makefile`) when one of the targets inputs (either a dependent target or input from `COPY`) change, the corresponding outputs would be re-generated.

**Comment by idsvandermolen** [comment]
Changing the Earthfile to this seems to work:
```Earthfile
VERSION 0.8

docker:
    FROM ubuntu:22.04
    SAVE IMAGE earthly-test:latest

build:
    BUILD +docker
    FROM +docker
    COPY --dir input ./
    SAVE ARTIFACT input AS LOCAL output

tests:
    BUILD +build

all:
    BUILD +tests
```
Which generates all outputs when invoking targets `build`,`tests` and `all`. Though it is not really clear to me if this is the way one should implement it. First I tried to have only a `BUILD +docker` in `build` target, but then you get this error:
```
copy classical: the first command has to be FROM, FROM DOCKERFILE, LOCALLY, ARG, BUILD or IMPORT
```

**Comment by alexcb** [comment]
> Note that the url linked in the docs "[if they are connected to the initial target through a chain of BUILD commands](https://docs.earthly.dev/docs/earthfile#what-is-being-output-and-pushed)" is broken and apparently needs to point at the section in the [BUILD](https://docs.earthly.dev/docs/earthfile#build) command.

I had a look to see if this could be fixed, but unfortunately the anchor has disappeared. The docs are hosted via gitbook, which makes it difficult to fix these sorts of issues which come from bugs (or feature changes) in gitbook.

**Comment by alexcb** [comment]
> Though the examples there still use FROM and SAVE ARTIFACT in on target, suggesting it still would work correctly.

The `SAVE ARTIFACT` is required here to allow for a `COPY` to reference it; Note that `SAVE ARTIFACT <path>` is different from `SAVE ARTIFACT <PATH> AS LOCAL <output>`. It's only the `AS LOCAL <output>` portion that requires chaining of BUILD commands.

**Comment by alexcb** [comment]
> Though it is not really clear to me if this is the way one should implement it

```
build:
    BUILD +docker
    FROM +docker
```

is how it's intended to be used. The `BUILD +docker` occurs asyncronously and doesn't affect the target where it is defined.

If you really want to get into the weeds, you can also create a function to do both, e.g.

```
VERSION 0.8

BUILD_AND_FROM:
    FUNCTION
	ARG target
	BUILD --pass-args $target
	FROM --pass-args $target

docker:
    FROM ubuntu:22.04
    SAVE IMAGE earthly-test:latest

build:
    DO +BUILD_AND_FROM --target=+docker
    COPY --dir input ./
    SAVE ARTIFACT input AS LOCAL output

tests:
    BUILD +build

all:
    BUILD +tests
```
