### ISSUE TITLE
how to create a Java class

### ISSUE THREAD

**Issue by damir2407** [earthly/earthly#4293]
### Question

how to create a Java class? please give me some tips

**Comment by damir2407** [comment]
> ### Question
> how to create a Java class? please give me some tips



> ### Question
> how to create a Java class? please give me some tips

Just create it

**Comment by damir2407** [comment]
dsada

**Comment by damir2407** [comment]
dada

**Comment by vladaionescu** [comment]
Closing as irrelevant for Earthly

**Comment by damir2407** [comment]
sry i thought i issued it in my space))))
just testing one feature
