### ISSUE TITLE
"Error: invalid number of args" can you please explain me why?

### ISSUE THREAD

**Issue by zedtux** [earthly/earthly#430]
Hello awesome team of Earthly!

I have a weird error here with version 0.3.10:

```
$ earth --secret CI \ --secret BOT_EMAIL \ --secret BOT_NAME \ --secret GIT_REMOTE_URL \ --secret SSH_PRIVATE_KEY \ --allow-privileged \ +run
...
Error: invalid number of args
```

Can you please tell me why ?

**Comment by agbell** [comment]
Hi @zedtux ,
That is unexpected?  Are there linebreaks that you have omitted and if so does it work on a single line? I can try to reproduce it tomorrow morning.

**Comment by vladaionescu** [comment]
I have the same suspicion - if the line breaks aren't actually there, then `\ ` could be interpreted as the space character ` `, leading to things like `\ --secret` to be interpreted as

```
 --secret
```
(notice the space in front), which is not a flag, and therefore it's an arg, leading to "number of args" error.

**Comment by zedtux** [comment]
Thank you guys for your comments.

You can see [my .gitlab-ci.yml file over here](https://gitlab.com/zedtux/wow-psh/-/blob/2c41d67e0c36c25204e3ae8d6fbd0f4568de698a/.gitlab-ci.yml#L41-46) and [the pipeline output where it fails here](https://gitlab.com/zedtux/wow-psh/-/jobs/798112060).

**Comment by zedtux** [comment]
Hey @vladaionescu you actually guessed it well !

Removing spaces works:

```
$ earth --secret CI \--secret BOT_EMAIL \--secret BOT_NAME \--secret GIT_REMOTE_URL \--secret SSH_PRIVATE_KEY \--allow-privileged \+run
buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Warning: DOCKER LOAD is deprecated. Please use WITH DOCKER --load registry.gitlab.com/zedtux/wow-psh:latest=+dev instead
...
```

**Comment by vladaionescu** [comment]
Great! Closing this.
