### ISSUE TITLE
Does not work if any elements of the current directory path are symlinks

### ISSUE THREAD

**Issue by tobyjwebb** [earthly/earthly#449]
When I run the earth command, and the directory I am in has a symlink in it, I get the following error:
```shell
$ earth +docker
buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: resolve build context for target +docker: Unexpected non-relative path within git dir
```
(I'm using the `Go` example from here: [a simple earthfile](https://docs.earthly.dev/guides/basics#a-simple-earthfile))

I store my repositories in a `REPOS` directory, let's call it `$HOME/Work/company/foo/bar/REPOS`, and I have a symlink to it in `$HOME/REPOS`. If I run the `earth` command from `$HOME/REPOS`, then I get the error, but if run from the destination directory, the command works correctly.

OS: Linux (Pop!_OS 20.10)
```shell
$ earth --version
earth version v0.3.10
```

**Comment by alexcb** [comment]
Thanks for the bug report @tobyjwebb 

We'll get the patch out in our next release, until then you can make use of our latest pre-release version located in the earth script in the root of our repo: https://github.com/earthly/earthly/blob/master/earth
