### ISSUE TITLE
Move vim syntax files into separate repository

### ISSUE THREAD

**Issue by slurps-mad-rips** [earthly/earthly#470]
Most vim syntax plugins are setup in such a way that you can easily use them with a plugin manager.

A few examples:
 * https://github.com/rust-lang/rust.vim
 * https://github.com/octol/vim-cpp-enhanced-highlight
 * https://github.com/plasticboy/vim-markdown

While I understand wanting to keep things colocated, I'd rather not have to clone all of earthly just to get a few syntax files 😅 

Considering the sublime syntax files are in a separate repo, I reckon this wouldn't be too much of a precedence to do. 🙂

**Comment by alexcb** [comment]
Thanks for the suggestion, I've created a new repo at https://github.com/earthly/earthly.vim which can now be installed via vim-plug.

If you use a different plugin manager, we would definitely appreciate a PR to the readme with installation notes.

One thing to note is that we use `main` as our default branch in git.
