### ISSUE TITLE
Generalised credential mounting and default env var passthrough

### ISSUE THREAD

**Issue by eganjs** [earthly/earthly#489]
Hi, I am trying to use dvc (https://dvc.org) as part of my build, it basically enables version control for large files. I've currently got files stored on a private S3 bucket which dvc uses as it's "remote". The problem is I need my AWS credentials available at build time. I know I can pass in secrets, however I think this is far more inconvenient than it needs to be.

Ideally there would be a way I could temporarily mount `~/.aws` and passthrough the `AWS_PROFILE` env var. I know I can use the env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, but as said above I feel this could be made far more convenient.

e.g.
```
# by default pasthrough AWS_PROFILE, equivalent to '--secret AWS_PROFILE=$AWS_PROFILE'
SECRET AWS_PROFILE=AWS_PROFILE

# mount ~/.aws to /root/.aws for use in this RUN
RUN --mount=type=cred,src=~/.aws,dest=/root/.aws --secret=AWS_PROFILE=+secrets/AWS_PROFILE dvc pull
```

I think default passthrough gets the 80%, but I'm not sure everything supports using env vars for credentials and normally requires additional manual set up to put into env vars.

**Comment by dchw** [comment]
Thanks for the issue! As I also use AWS credentials extensively within Earthly targets, I also feel your pain. Right now, we settle for passing them in as secrets using the `--secret AWS_ACCESS_KEY_ID` style as well.

If you absolutley need a config file in the interim, one option might be to add a parent target:

```
credentials:
    FROM amazon/aws-cli 
    RUN aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
```

**Comment by dchw** [comment]
Thanks for the issue!

As I also use AWS credentials extensively within Earthly targets, I also feel your pain and agree we could do better. Right now, we settle for passing them in as secrets using the `--secret AWS_ACCESS_KEY_ID` style as well. its cumbersome, but has also been supported everywhere we need it so far.

If you absolutely need a config file in the interim, one option might be to add a parent target:

```
credentials:
    FROM amazon/aws-cli 
    RUN aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
    ...
    SAVE ARTIFACT .aws

build-step:
   ...
   COPY +credentials/credentials .aws/credentials
   ...
```

Admittedly, its a bit of a workaround. We do something similar to get our credentials via `aws sts assume-role` for later targets.

**Comment by vladaionescu** [comment]
> Admittedly, its a bit of a workaround.

A note regarding the workaround above is that the secrets end up in your cache and if you output images, they may also end up in image layers. This may or may not be acceptable depending on the specifics of how they are used.

In any case, we plan to support this particular use-case properly with some upcoming features. We'll update with progress.

**Comment by eganjs** [comment]
After digging around a bit more I've found general purpose mounting exists experimentally [here](https://github.com/earthly/earthly/blob/c7cfad609859fc29f7bd1b82899e9f4cb1ec9228/earthfile2llb/runmount.go#L127) and can be used like so `--mount=type=bind-experimental,target=/bind,source=/bind-test`
I also found the test `earth -P ./examples/tests+host-bind-test` which demonstrates it in action, however I've been unable to reproduce usage of it outside of this test, even using the test's own [Earthfile](https://github.com/earthly/earthly/blob/c7cfad609859fc29f7bd1b82899e9f4cb1ec9228/examples/tests/host-bind.earth)

Obviously this functionality is experimental but perhaps someone could offer some guidance as to whether I am making an simple mistake :smile:  ?

My set up:
`run.sh`:
```
#!/usr/bin/env bash

# set up
sudo mkdir /bind-test
sudo chown -R eganjs:eganjs /bind-test
echo "a" > /bind-test/a.txt

# run earthly
earth -P +test

# check output
test -f /bind-test/b.txt && echo "b.txt exists" || echo "b.txt not present"
ls -al /bind-test
cat /bind-test/b.txt

# cleanup
sudo rm -rf /bind-test
```

`Earthfile`:
```
FROM alpine:3.11

test:
    RUN --mount=type=bind-experimental,target=/bind,source=/bind-test \
        ls -al /bind && test -f /bind/a.txt
    RUN --mount=type=bind-experimental,target=/bind,source=/bind-test \
        echo "hello b" > /bind/b.txt
```

Output:
```
$ ./run.sh
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
         alpine:3.11 | --> Load metadata
               +base | --> FROM alpine:3.11
               +base | resolve docker.io/library/alpine:3.11@sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54 100%
               +test | --> RUN ls -al /bind && test -f /bind/a.txt
               +test | container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/bind-test" to rootfs at "/bind" caused: stat /bind-test: no such file or directory
               +test | ERROR: Command exited with non-zero code: RUN ls -al /bind && test -f /bind/a.txt
Repeating the output of the command that caused the failure
=========================== FAILURE ===========================
               +test *failed* | --> RUN ls -al /bind && test -f /bind/a.txt
               +test *failed* | container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/bind-test" to rootfs at "/bind" caused: stat /bind-test: no such file or directory
               +test *failed* | ERROR: Command exited with non-zero code: RUN ls -al /bind && test -f /bind/a.txt
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c  /usr/bin/earth_debugger /bin/sh -c 'ls -al /bind && test -f /bind/a.txt']: buildkit-runc did not terminate successfully
b.txt not present
total 12
drwxr-xr-x.  2 eganjs eganjs 4096 Nov  9 18:03 .
dr-xr-xr-x. 19 root   root   4096 Nov  9 18:03 ..
-rw-rw-r--.  1 eganjs eganjs    2 Nov  9 18:03 a.txt
cat: /bind-test/b.txt: No such file or directory
```

**Comment by vladaionescu** [comment]
Hi @eganjs - we actually don't plan on making that a full user-facing feature. Currently it mounts things from within the `earthly-buildkitd` container into the build container. So probably not very useful to you.

We're on the fence with offering host path mounts into the build because it can be a source of inconsistent builds (the same reason also BuildKit does not offer it). However, I think the AWS use-case is very valid and we will either implement first-class support for loading in AWS config in Earthly or have another way of loading AWS credentials... or both.

**Comment by eganjs** [comment]
@vladaionescu thanks for clarifying, I think host path mounts is a feature I would still like see, albeit, perhaps naively.
I look forward to seeing official integration for aws credentials!

In the meanwhile, I've put together a slightly more sensible approach than I was using beforehand. I've written a wrapper file that I'm committing to repositories where I use earthly. The script does the following:
- Downloads the latest or a pinned version of earthly if it does not already exist.
- Forwards your aws credentials as secrets into earthly.

Script link: https://github.com/eganjs/wrappers

Obviously use this at your own risk, there is very little/no error handling and it assumes you have aws credentials, but I thought I would at least share my interim solution in case others are facing a similar challenge :smiley:

**Comment by vladaionescu** [comment]
Hi @eganjs, I have opened the following issues for tracking two separate solutions for this (we will likely implement both):

* https://github.com/earthly/earthly/issues/578
* https://github.com/earthly/earthly/issues/579

I will close this issue in favor of the other two.
