### ISSUE TITLE
Bug: Earthly fails when run in an empty git repository

### ISSUE THREAD

**Issue by JensRantil** [earthly/earthly#490]
I just executed `git init` and then
```bash
$ earth +test
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = resolve build context for target +test: detect git hash: exit status 128
```
The "git hash" made me guess it had to do with the empty git repository. I added a small readme file and made my first commit, and then `earth +test` passed.

Expected:
 * Either that I would get a nicer error message; or
 * that Earthly works in an empty git repository. (preferred)

**Comment by vladaionescu** [comment]
Ah indeed - we should make this gracefully handle the situation. This should be an easy fix.
