### ISSUE TITLE
How can a build be reproducible when container references are not immutable?

### ISSUE THREAD

**Issue by joshuagl** [earthly/earthly#492]
The [introduction](https://docs.earthly.dev/) claims:

> your builds run the same on your laptop as they run in CI or on your colleague's laptop

however, so far as I can tell from a brief skim of the documentation and examples, this can _only_ be guaranteed to be true if they run at the same time. 

Take "[A simple example (for Go)](https://github.com/earthly/earthly#a-simple-example-for-go)" from the earthly README.md, the first two lines seem to me to be non-reproducible (inline comments expand on this):

```Dockerfile
# Earthfile
FROM golang:1.13-alpine3.11 # tag is not immutable, may resolve to different image on next build
RUN apk --update --no-cache add git # package manager database is not static, may get different package version
```

For the first line, it would be good to support referencing container images by digest and advocate for that through documentation and examples. Earthly could even inform when there is an updated version of the container image available.

For the second line, however, short of using Debian and [snapshot.debian.org](https://snapshot.debian.org/) I don't know what can be done.

**Comment by vladaionescu** [comment]
Hi @joshuagl - you're right. It's not reproducible like, for example [a Bazel build](https://github.com/earthly/earthly#how-is-earthly-different-from-bazel). It's just more reproducible than most popular build tools (eg Makefile, bash scripts etc). The word "reproducible" is a stretch - any ideas for a better word / description?

**Comment by joshuagl** [comment]
If the goal is to ensure that a build is self-contained and isolated from the host (such that, i.e the presence or absence of libraries and binaries on the host does not affect the build), you might find the term "hermetic" a better fit.

For a more complete definition of Hermetic Builds, see chapter 8 of Google's SRE book: https://landing.google.com/sre/sre-book/chapters/release-engineering/

**Comment by vladaionescu** [comment]
I think "hermetic" could also be misinterpreted, because the meaning of the word comes from being "airtight" or "completely isolated" - which is not quite the case.

Perhaps "repeatable" or "consistent"?

CC @agbell

**Comment by joshuagl** [comment]
Repeatable could work. It's is a term I have used, and seen used, to refer to build processes that are not strictly reproducible but make replicating build results across the and systems more reliable.
