### ISSUE TITLE
Support for watch mode

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#495]
Many build tools made for frontend support a watch mode - a mode in which every code change immediately updates a running development server - thus the user can see updates to the site in real-time.

Docker + watch mode traditionally has been a DIY project, many engineers preferring to just run outside of containers so they wouldn't have to deal with the setup. Challenge is that source code needs to be mounted as a volume and some ports need to be exposed on the host so that eg a browser can connect to them.

This feature has been requested by a number of users - the latest one being Dan Miller over Slack.

**Comment by alexcb** [comment]
duplicate of #1052
