### ISSUE TITLE
Build performance metrics

### ISSUE THREAD

**Issue by jazzdan** [earthly/earthly#496]
When I'm writing an Earthfile for a project I'm always on the look out for what the biggest build bottlenecks are. Should I break out that build script in to smaller targets? Should I optimize that Dockerfile by using a smaller base image?

If Earthly could show me a detailed breakdown of how long each of my build steps take that would help me figure out what's important to focus on. As of right now I have to rely on timing each step with my eyeballs, and it can be really hard to tell when there are multiple builds happening in parallel.

**Comment by vladaionescu** [comment]
This should be relatively easy - BuildKit already exposes some of this data. We just need to take it and report it to the user neatly.
