### ISSUE TITLE
parser failure: nil pointer dereference

### ISSUE THREAD

**Issue by jazzdan** [earthly/earthly#498]
Repro steps:

```
$ earth --version
earth version v0.3.12
$ git clone https://github.com/jazzdan/earthly-nil-pointer.git
$ cd earthly-nil-pointer
$ cat Earthfile
FROM node:14.15.0
WORKDIR /usr/build

src:
    COPY package.json package-lock.json ./
    RUN npm install --production
    COPY . .

standalone-experiment-setup:
    FROM +src
    RUN mv src/build/Dockerfile.standalone Dockerfile

standalone-experiment:
    FROM DOCKERFILE +standalone-experiment-setup/
    SAVE IMAGE recordreplay-standalone
$ earth +standalone-experiment
        buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
        node:14.15.0 | --> Load metadata
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = parser failure: runtime error: invalid memory address or nil pointer dereference
```

I think I ran in to this before and it was some typo, but as of right now I'm still looking for what caused it so I figured I'd report it. :)

**Comment by vladaionescu** [comment]
Thanks for the repro Earthfile - I'll take a look

**Comment by vladaionescu** [comment]
BTW - I see a few COPY commands - any chance that you could share the files that are being copied so that I have a fully working reproduction of the issue?

**Comment by jazzdan** [comment]
@vladaionescu I don't think it matters in this case because even if I run that Earthfile in an empty directory (Like my [linked repro case](https://github.com/jazzdan/earthly-nil-pointer.git)) I get the same error.

Maybe I can reduce the repro case further, let me see

**Comment by jazzdan** [comment]
@vladaionescu I reduced it further to:

```Earthfile
FROM node:14.15.0
WORKDIR /usr/build

foo:
    RUN touch Dockerfile

bar:
    FROM DOCKERFILE +foo/
```

**Comment by jazzdan** [comment]
Then `earth +bar` :)

Hmm maybe the issue is that I didn't save the output of `foo` as an artifact?

**Comment by vladaionescu** [comment]
Yes... exactly!

We should improve that error

**Comment by vladaionescu** [comment]
Thanks for the report, @jazzdan - improved error message coming in the next release!
