### ISSUE TITLE
SAVE ARTIFACT AS LOCAL overwrites local directory

### ISSUE THREAD

**Issue by jazzdan** [earthly/earthly#512]
If I have an Earthfile like this:

```
SAVE ARTIFACT foo/ AS LOCAL foo/
```

Everything in my local `foo/` gets wiped out and replaced with whatever was in the container's `foo/`. There are definitely situations where this is what I want to happen, but there also situations where I want to merge the two, the equivalent of  `cp foo/* foo/`.

For example, if I have two rules like this:

```
foo:
  RUN touch foo/a
  RUN touch foo/b
  SAVE ARTIFACT foo/ AS LOCAL foo/

bar:
  RUN touch foo/c
  RUN touch foo/d
  SAVE ARTIFACT foo/ AS LOCAL foo/
```

And I run `earth +foo` then `earth +bar` I'll end up with a directory that only has `foo/c` and `foo/d` in it, when what I really want is `a`, `b`, `c` and `d`.

I know I could do this by saving each file in `foo/` as its own artifact, but this gets tedious and seems less forwards compatible (if some build step changes and it starts outputting more files, we might forget to save them as additional artifacts).

Not sure what the right solution here is, maybe some additional syntax to be able to copy the semantics of `cp foo/* foo/`?

**Comment by vladaionescu** [comment]
FTR - copying response from Slack.

I believe this is intended behavior - as the artifact is declared as being the entire directory - so it completely replaces the destination to make it exactly the same. You should be able to use `SAVE ARTIFACT foo/* AS LOCAL foo/` - then the artifacts are a collection of files which should be placed in the destination together with anything that's already in there.

**Comment by jazzdan** [comment]
Yep, that works great. Thanks! I'll close this for now.
