### ISSUE TITLE
WITH DOCKER clean up problem 

### ISSUE THREAD

**Issue by agbell** [earthly/earthly#515]
### Scenario:
Earthly froze on pulling an image so I had to kill it.  

The next run I got this:
```
 +integration-test *failed* | docker: Error response from daemon: Conflict. The container name “/postgres” is already in use by container “95a63fd7159b7b21e9ef265cc59bdf8cb4bd0df11a076f481b7e03bfa04fa66a”. You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by vladaionescu** [comment]
Seems that this is an issue with dind ID cleanup - when Earthly is killed, it doesn't have the opportunity to cleanup after itself. Consistent hashing used for the dind ID (necessary for cache consistency) means that the build uses the same dind dir as before and given that it's not cleaned up, the same docker state as before.
