### ISSUE TITLE
Proposal: option for no caching from a particular target

### ISSUE THREAD

**Issue by parnham** [earthly/earthly#520]
The `--no-cache` option forces `earth` to start entirely from scratch, however in some cases you may just want to force no caching from a particular target layer - especially if the earlier layers take a long time to build.

Perhaps something along the lines of 
```
earth [--no-cache-from <target-ref>] <target-ref>
```

So using https://github.com/emergent-design/libentity/blob/master/Earthfile as an example:
```
$ earth --no-cache-from +build +package
```
In this case the cached layers for `+base` and `+code` will still be used.

**Comment by vladaionescu** [comment]
Hi @parnham - we're planning to add a `RUN --no-cache` flag in the future. I know it's not exactly what you're asking for - in your use-case, it would require that you (temporarily) edit your Earthfile. Curious, however, if this would cover your needs.

Alternatively, another way to do what you're asking for might be a flag which uses no cache only for the final target, but does use for everything else. For example: `earth --no-cache-final +something`. This, together the ability to specify multiple targets (another future feature) `earth --no-cache-final +build +package` should be very similar to your suggestion.

**Comment by parnham** [comment]
The `RUN --no-cache` would work since it could be placed precisely at the point you want to invalidate and that would cascade throughout the remainder of the build.
I'll close this proposal since your suggestion is a viable alternative, thanks.
