### ISSUE TITLE
Support multi-platform builds

### ISSUE THREAD

**Issue by LuaxY** [earthly/earthly#536]
Is it possible to support multi-platform (e.g. amd64, arm64, arm v7) image build with `docker buildx` feature?
With docker command, by using compatible builder, we can now provide `--platform` flag to specify target platform.

`docker [buildx] build --platform linux/amd64,linux/arm64,linux/arm/v7 .`

https://docs.docker.com/buildx/working-with-buildx/

**Comment by agbell** [comment]
Hi @LuaxY, I believe this should be possible and should be a feature we add.  Thank you for submitting it.

**Comment by vladaionescu** [comment]
Experimental support for multi-platform builds is available in `v0.4.3`. Here is a simple example: https://github.com/earthly/earthly/blob/main/examples/multiplatform/Earthfile .

If you try this feature out, I'd be very curious about your experience with it - either here or on our Slack.

**Comment by LuaxY** [comment]
Tested on my project, work perfectly, big thanks!!

Question about local artifacts, example:

`main.go`
```go
package main

import "fmt"

func main() {
	fmt.Println("test")
}
```

`Earthfile`
```Dockerfile
FROM golang:1.15-alpine
RUN apk --update --no-cache add git
WORKDIR /mailtrap

all:
  BUILD \
    --platform=linux/amd64 \
    --platform=linux/arm64 \
    --platform=linux/arm/v7 \
    --platform=linux/arm/v6 \
    +build

build:
  COPY main.go main.go
  RUN go build -o build/test main.go
  SAVE ARTIFACT build/test AS LOCAL build/test
```

This will build binary for each platform but also override the local artifcat

```
+build | Artifact test:master+build/test as local build/test
+build | Artifact test:master+build/test as local build/test
+build | Artifact test:master+build/test as local build/test
+build | Artifact test:master+build/test as local build/test
```

The final binary is the last platform stage to finish the `SAVE ARTIFACT`

```
$ file build/test 
build/test: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, [...]
```

This is the intended behavior? or there is a way to control the artifact name depending the platform?

**Comment by vladaionescu** [comment]
Great!

There are four new built-in args available, which you can use for this:

* `TARGETPLATFORM`
* `TARGETOS`
* `TARGETARCH`
* `TARGETVARIANT`

You need to predeclare them before using them:

```
ARG TARGETPLATFORM
RUN echo "The platform is $TARGETPLATFORM"
```

So in your example, you could have

```
build:
  COPY main.go main.go
  RUN go build -o build/test main.go
  ARG TARGETPLATFORM
  SAVE ARTIFACT build/test AS LOCAL build/$TARGETPLATFORM/test
```

**Comment by LuaxY** [comment]
Perfect thank you!

**Comment by bhansconnect** [comment]
Is there a way to remerge a build split by platform instead of propagating it through all dependant builds?
Ex:
```
get-dep-linux-arm64:
    # Download/setup arm64 version of dep

get-dep-linux-amd64:
    # Download/setup amd64 version of dep

build-app:
    # ideally I would want this to pick the right version of get dep. And just say something like:
    FROM +get-dep
```
Instead, i believe with the current setup, i would need to make build-app-linux-arm64 and build-app-linux-amd64

**Comment by vladaionescu** [comment]
You should have get-dep defined in a single target. You can use builtin args like [`TARGETPLATFORM`](https://docs.earthly.dev/earthfile/builtin-args) if you need to do a bash conditional. In the future we plan on having a built-in [`IF` command](https://github.com/earthly/earthly/issues/779).

After that, you can reference `FROM +get-dep` and it'll use the same platform `build-app` is being built as.

**Comment by bhansconnect** [comment]
Yeah, I saw the if proposal, it would definitely solve my issue.

Frankly all I need to do to solve my specific issue is to map targetplatform.
Essentially:
amd64 -> x86_64
arm64 -> aarch64
etc
And then I would be able to just directly download the file and extract the file.
Probably will just make a small bash script with that if to deal with the conversion.

**Comment by n-rodriguez** [comment]
> wondering what you mean by "dynamically"

From a ruby script :`earthly --platform ... + build`

**Comment by vladaionescu** [comment]
Got it - yeah makes sense. We should support that. Mind opening a new issue about it?
