### ISSUE TITLE
Passing arg TAG to all builds

### ISSUE THREAD

**Issue by tafax** [earthly/earthly#545]
Hi,
I'm trying to set up a monorepo project. This is the structure:
```
root
---/frontend
---/backend
```

Earthfile on root
```
# Earthfile

FROM alpine:3.11

all:
    ARG TAG
    BUILD --build-arg TAG=$TAG ./backend+build
    BUILD --build-arg TAG=$TAG ./frontend+build
```

Earthfile on frontend
```
# Earthfile

build:
    ARG TAG
    FROM DOCKERFILE .
    SAVE IMAGE "frontend:$TAG"
```

Earthfile on backend
```
# Earthfile

build:
    ARG TAG
    FROM DOCKERFILE .
    SAVE IMAGE "backend:$TAG"
```

What I'm trying to do is passing a TAG from the command line. It allows me to calculate the tag and then build my artifacts independently. I run earthly with:
```
earth --build-arg TAG=v0.0.1 +all
```

The error I get:
```
internal | ERROR: (earthly exporting to oci image format) failed to parse nima/frontend:: invalid reference format
Repeating the output of the command that caused the failure
=========================== FAILURE ===========================
            internal *failed* | --> earthly exporting to oci image format
            internal *failed* | [no output]
            internal *failed* | ERROR: (earthly exporting to oci image format) failed to parse nima/frontend:: invalid reference format
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = failed to parse nima/frontend:: invalid reference format
```

What I'm wrongly doing? Do you have any advice?
Thanks

**Comment by vladaionescu** [comment]
Hi @tafax - there was an issue with build args before FROM command, which is going to be fixed in the next release: https://github.com/earthly/earthly/pull/531.

As a temporary workaround, you can move the ARG declaration just after `FROM DOCKERFILE`.

I've close this issue since fix is upcoming - but feel free to reopen if you encounter problems.
