### ISSUE TITLE
Timings difficult to see with solarized dark terminal font

### ISSUE THREAD

**Issue by jazzdan** [earthly/earthly#548]
This is a bit of a silly problem, but bear with me. :D

When I run `earth --verbose` to see what the timings for the various steps are I am greeted with something that looks like this:

<img width="490" alt="Screen Shot 2020-12-02 at 10 53 06 AM" src="https://user-images.githubusercontent.com/452453/100896603-c9c30880-348c-11eb-9a29-2b7bf6ef446b.png">

I quickly realized that there must be some hidden text there, so I highlighted it with my cursor and the timings were revealed!

<img width="359" alt="Screen Shot 2020-12-02 at 10 53 18 AM" src="https://user-images.githubusercontent.com/452453/100896687-e2332300-348c-11eb-9c78-0aa05de0ecff.png">

If I switch my terminal theme to solarized light everything looks just fine

<img width="707" alt="Screen Shot 2020-12-02 at 10 55 55 AM" src="https://user-images.githubusercontent.com/452453/100896790-0131b500-348d-11eb-933c-3a10ec275c28.png">

Would it be possible to change the color of the timing information so that it shows up clearly in solarized dark? I think it's relatively popular as far as terminal themes go. :D

Thanks so much for the quick turnaround time on timings!

**Comment by vladaionescu** [comment]
Yeah - I can see how this can be a problem :smile: 

Fix will go out with the next release.
