### ISSUE TITLE
Need a more flexible, less dangerous installation method

### ISSUE THREAD

**Issue by chbarts** [earthly/earthly#56]
The method proposed to install this software is both not flexible and potentially dangerous.

**Comment by vladaionescu** [comment]
An alternative is to download the binary yourself from the releases page and place it in your bin.

**Comment by chbarts** [comment]
If the simple and straightforwards way works, why do you suggest the dangerous and complicated one?

**Comment by idelvall** [comment]
>If the simple and straightforwards way works, why do you suggest the dangerous and complicated one?

Why you think is "dangerous" and "complicated"?

**Comment by chbarts** [comment]
It's complicated because just downloading a file is the simplest possible method of installing something. It's dangerous because a script can do strange things, especially when run in an arbitrary environment; your script doesn't know how my machine is set up, so it doesn't know how not to be dangerous.

**Comment by idelvall** [comment]
I see, but for lots of people (me included) running a command in the console is much preferable than downloading, copying and changing permissions.

About the dangerous part, running a script is as dangerous as running a manually downloaded binary, that can also do strange things (in a much obfuscated way), don't you think?

**Comment by chbarts** [comment]
Sorry, I didn't check the username I guess.

I still think the script is more dangerous, both because it could be partially downloaded (which would lead to the shell running some unknown, inconsistent script which gets cut off at an unpredictable point) and because installation is inherently more, I don't know, "touchy-feely" with various parts of the filesystem, whereas the binary itself is more likely to stick to its task. Ultimately, I trust Vlad, which is why I'm even commenting here; what I don't trust *that* far is the network connection and Vlad's knowledge of how my directory structure is set up.

**Comment by dashwav** [comment]
I think this would be a very nice feature. At the very least I think a [Homebrew](brew.sh) package would be very helpful in terms of adoption. Brew can be used to install packages in a very consistent and safe manner while also installing any dependencies needed as well. With brew for linux now being fairly stable this would allow for an easy install on about 50% of developer workstations.

As a personal note I am much more willing to try out new software if I see it has a brew package as there are very few barriers to getting it working on my workstation (brew manages dependencies, path, bin, etc).

I would also be willing to help with the development of the formulae should this be a path the maintainer is willing to take.

**Comment by vladaionescu** [comment]
I've been meaning to do better installer, haven't gotten around to it. Go for it @dashwav - brew package makes sense.

**Comment by tipok** [comment]
Hi, i've added a PR in the homebrew repo  [#53992](https://github.com/Homebrew/homebrew-core/pull/53992)

**Comment by vladaionescu** [comment]
Thanks - I left a couple of comments on it.

**Comment by tipok** [comment]
Thank you, added to the PR
