### ISSUE TITLE
Proposal: Shared artifact and image caching

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#574]
This allows things like:

* Shared caching. CI is allowed to write to the cache. Developers get read-only cache.
* Cloud-based caching for CIs like GH Actions, Circle etc.
* Cache-aware storage of artifacts and images (eg issuing `earth --artifact github.com/foo/bar+target/my-artifact` essentially downloads the readily built artifact if the CI has already built it).

Details TBD

**Comment by JensRantil** [comment]
Are you thinking that this would be a file-based cache? That is, the interface is a shared disk such as NFS?

**Comment by vladaionescu** [comment]
No.. this will be either an Earthly-specific protocol, or something based on BuildKit primitives.

**Comment by cosminci** [comment]
We use Jenkins with dynamically provisioned workers in AWS. It's reasonable to believe all CI systems will eventually migrate away from persistent worker nodes which sit idle most of the time. :+1: for remote / shared cache as it enables caching for these use cases and between the workers themselves.

**Comment by vladaionescu** [comment]
Abandoned for now. We might revisit later, but details are too vague to keep this open as is.

**Comment by ruffsl** [comment]
@vladaionescu , is this still on the drawing board or has the status of this changed elsewhere? I really like this:

> Shared caching. CI is allowed to write to the cache. Developers get read-only cache.

But haven't had much luck in finding CI platforms natively support such abstractions:

- https://github.com/orgs/community/discussions/44567
