### ISSUE TITLE
Proposal: LOCALLY

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#580]
This proposal builds upon a previous (now abandoned) version described in https://github.com/earthly/earthly/issues/167

## Background

Not everything a build system does is suitable for a container. There are certain tasks which are either too cumbersome for a container or Earthly just doesn't support them yet and may never will, for build repeatability reasons.

Because of the above, many Earthly users end up wrapping Earthly in other scripts (bash or Makefile) to be able to complete their development workflow.

### Use-cases

* In general, wrap common development commands that can only run on the host
* docker-compose up commands
* Watch type of commands, where mounting the source code is necessary - so it’s best done via a docker run
* Commands interacting with local config / secrets - example: grabbing local AWS config or grabbing the local maven credentials
* Situations where using the host docker daemon is necessary / preferred

## Proposal

An "escape hatch" is provided to be able to execute commands on the host system rather than in a container. Targets that execute on the host are marked as `FROM LOCAL`.

The intended use of `FROM LOCAL` is for **development commands only** and not for use in CI. To make this distinction for the user, a new *strict* mode is introduced (default: off) in which `FROM LOCAL` commands are not allowed. A warning is displayed for cases where strict mode is off but the build includes `FROM LOCAL`.

### Example

```Dockerfile
some-target:
  FROM LOCAL
  RUN docker-compose up
```

### Notes

* Executes commands directly on the host machine
* The current directory used is the directory in which the Earthfile is defined (not the directory it is called from)
* If the `FROM LOCAL` target is a remote target (referenced from github), then the current directory used is a directory under `~/.earthly/tmp/<unique-id>/github.com/bla/bla/deep/dir`, where the remote git dir is cloned into.
* No caching, no layers, no `SAVE IMAGE`
* `SAVE ARTIFACT` can be used to expose files to regular targets. Regular (containerized) targets can reference the artifact in the usual way - this results in builds that partly execute on the host, and partly in containers.
* Ordering of commands are guaranteed - eg `BUILD +one` and `BUILD +two` on consecutive lines, will build and output sequentially, guaranteed
* `COPY`, `LABEL`, `CMD`, `ENTRYPOINT` don’t work in this context (we throw an error)
* Because `FROM LOCAL` targets interact with the local system, perhaps we turn off any parallelization when executing these. (More reason for the user to avoid these for anything heavy-duty)
* Add a warning: this command would not work in `--strict` mode. Encourage Earthly used in CI to be executed with `--strict` flag turned on.

### TODO

* `WITH DOCKER` - decide if allowed.
  * Pro: reuse --compose etc
  * Cons: Two ways to do one thing
  * Possible alternative: allow user to use `WITH DOCKER --local` - which simply uses the host docker daemon (`/var/run/docker.sock`) but does not support volume mounts and also network may behave differently.

**Comment by alexcb** [comment]
We just merged https://github.com/earthly/earthly/pull/725 into our main branch which implements a new `LOCALLY` keyword to support this.

Here's an example:

```
step1:
    LOCALLY
    RUN whoami
    RUN cat /proc/1/cgroup | head -n 1

step2:
    FROM alpine:latest
    RUN whoami
    RUN cat /proc/1/cgroup | head -n 1

both:
    BUILD +step1
    BUILD +step2
```

then when you run `earthly +both`, one should see something similar to:

```
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
      busybox:1.32.1 | --> Load metadata linux/amd64
       alpine:latest | --> Load metadata linux/amd64
              +step1 | --> FROM busybox:1.32.1
              +step2 | --> FROM alpine:latest
              +step1 | [██████████] resolve docker.io/library/alpine:latest@sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378 ... 100%
              +step1 | [██████████] resolve docker.io/library/busybox:1.32.1@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f ... 100%
              +step2 | --> RUN whoami
      +step1 *local* | --> RUN whoami
      +step1 *local* | alex
              +step2 | root
              +step2 | --> RUN cat /proc/1/cgroup | head -n 1
      +step1 *local* | --> RUN cat /proc/1/cgroup | head -n 1
      +step1 *local* | 12:cpuset:/
              +step2 | 12:cpuset:/docker/6efd922b36cf848c95e746e75dec582bfeb24fc7c4fbb6c2c9d9ab245c59f4da/buildkit/uezzasd9bcuc3wol6am9h1lkl
              output | --> exporting outputs
              output | [██████████] sending tarballs ... 100%
=========================== SUCCESS ===========================
```

**Comment by rulatir** [comment]
Why does step1 say `FROM busybox:1.32.1`? Does this mean the step is not **truly** performed on bare metal, and instead precious seconds are taken to spin up a "pretend local" busybox container and upload potentially huge context?

My main interest in this feature was about performance. Earthly's DSL is great. I wouldn't have spent the last month writing an in-house build system from scratch if I could have a build system with a DSL this elegant, but capable of working directly in the local environment without docker's performance penalty. I understand that optimization for a tight code-build-debug cycle is not a design goal of Earthly, but I was hoping that `FROM LOCAL`/`LOCALLY` might bring improvements in this area as a side effect.

**Comment by alexcb** [comment]
Good catch @rulatir , we're using `busybox:1.32.1` in our implementation detail in order to maintain a compatible dependency graph that we feed into buildkit; technically the only thing busybox executes is the `true` command; while the actual command from the Earthfile gets executed in the local baremetal system. I'll work on the output to see if we can omit that from the logs as it's rather confusing to see it being pulled in.

If you're interested in trying this feature out before it hits our next release, you can make use of the `./earthly` script in the root of our repo. We would love any additional feedback.

**Comment by rulatir** [comment]
> technically the only thing busybox executes is the `true` command; while the actual command from the Earthfile gets executed in the local baremetal system

What really matters is whether the busybox spin-up and execution of the `true` command are synchronous, i.e. "awaited" for before the building of the `LOCALLY` step can complete. If this is the case, then we still have a slow container spin-up on the critical path. Can we avoid that?

I'm not entirely sure I understand the "compatible dependency graph" consideration. Is it because the nodes in the graph must be Docker images? If that's the case, how do you represent _different_ build outcomes with _the same_ `FROM busybox` image that results from spinning up _the same_ base busybox image, executing _the same_ `true` command, and committing (if I understand correctly how this works)?

**Comment by alexcb** [comment]
> because the nodes in the graph must be Docker images

That's correct. Theoretically it would be possible to remove this constraint; however, at this time it's a much bigger refactor of the buildkit code than we wish to take on. None of the `LOCALLY` `RUN` commands are cached, so they should all be executed.

If you're interested in how I made it work under the hood it's best to look at my PRs in https://github.com/earthly/earthly/pull/725 and https://github.com/earthly/buildkit/pull/24

I also was able to omit the busybox output in https://github.com/earthly/earthly/pull/731

**Comment by alexcb** [comment]
We merged additional support for copying local files and directories from a LOCALLY target into a container in https://github.com/earthly/earthly/pull/758

This PR also allowed us to remove the dependency on calling `true` under `busybox` as we now create a fake empty snapshot for cases where no files are copied.
