### ISSUE TITLE
Proposal: Allow save artifact commands after push commands

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#586]
### Background

**Outputting only at the end is limiting**. The principle of “first perform all the build steps, and only after they complete successfully, perform outputting + pushing” is limiting for certain use cases. Examples:
  * `RUN --push` and then `SAVE ARTIFACT` (eg a terraform backup)
  * A case where an artifact publishing tool auto-increments version number on publish, but then that number needs to be used in other places too

### Proposal

Currently the following is an error in Earthly:

```
RUN --push ...
RUN ...
```

The proposal is to allow this.

### How it works

* If `earth --push` flag is provided, everything executes as expected.
* If no push flag is provided to `earth`, such a build would fail from the get-go, explaining why it would not be able to complete the build.

**Comment by dchw** [comment]
With the addition of allowing `SAVE ARTIFACT` after `--push`, allowing `RUN --push` to affect the state of later `SAVE IMAGE --push`, and `RUN --no-cache`, it seems like almost all use cases have been satisfied.
