### ISSUE TITLE
`earth --help` does not really document what `--server` does

### ISSUE THREAD

**Issue by JensRantil** [earthly/earthly#590]
The help text says

> API server override for dev purposes (default: "https://api.earthly.dev") [$EARTHLY_SERVER]

What does the API server do? It does not seem to be documented in https://docs.earthly.dev. How does it differ from `--buildkit-host`?

**Comment by alexcb** [comment]
Thanks for the report @JensRantil , the `EARTHLY_SERVER` is only meant for internal development purposes which is used to access our [experimental secret store](https://github.com/earthly/earthly/blob/main/secret-readme.md), it's not related to the `buildkit-host` in any way.

This flag should have been hidden from our help text, which I've opened a PR to do.

**Comment by JensRantil** [comment]
Excellent! That makes sense. Thanks!
