### ISSUE TITLE
Error while creating mount source path '/tmp/ssh-agent.sock.1000' 

### ISSUE THREAD

**Issue by GeertJohan** [earthly/earthly#61]
When I use `earth` in my default shell/terminal it always results in this error:
```
$ earth ./dexterity-api/dex/+generate
buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
buildkitd | Settings do not match. Restarting buildkit daemon with updated settings...
buildkitd | Is docker installed and running? Are you part of the docker group?
Error: buildkitd new client: buildkitd new client (own): maybe start buildkitd: maybe restart: docker run earthly/buildkitd:v0.1.1: 80d0ea1166ef829ef485f42ae43760ba86c1ac13bd00da4d30efeb08bec2c203
docker: Error response from daemon: error while creating mount source path '/tmp/ssh-agent.sock.1000': mkdir /tmp/ssh-agent.sock.1000: file exists.
: exit status 125
```

From my env vars:
```
SSH_AUTH_SOCK=/tmp/ssh-agent.sock.1000
```

I found a quick fix is to `unset SSH_AUTH_SOCK` and then run `earth ..`. But this will probably cause trouble down the road when I want to let Earthly checkout a private git repo.

**Comment by GeertJohan** [comment]
This has been the case on both v0.1.0 and v0.1.1

**Comment by vladaionescu** [comment]
Hi @GeertJohan - can you give me details about your environment? OS distribution version, ssh agent version?

**Comment by GeertJohan** [comment]
Ubuntu 19.10

> $ sudo apt show ssh
> Package: ssh
> Version: 1:8.0p1-6build1

**Comment by vladaionescu** [comment]
It seems that this happens when the ssh auth sock file is a symlink. Earthly should resolve the symlink and mount the file it is pointing to.

A workaround for this is to `export EARTHLY_SSH_AUTH_SOCK=$(realpath "$SSH_AUTH_SOCK")`

**Comment by alexcb** [comment]
This fix has been released under https://github.com/earthly/earthly/releases/tag/v0.2.1

**Comment by alexcb** [comment]
v0.2.1 introduced a macOS-specific bug; this has been fixed in https://github.com/earthly/earthly/releases/tag/v0.2.2
