### ISSUE TITLE
Support FROM DOCKERFILE -f

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#619]
@rulatir requests support for -f in https://github.com/earthly/earthly/issues/615#issuecomment-743977844

* Should be able to specify the Dockerfile to use.
* `-f` should work the same as the `FROM DOCKERFILE` path: it can either be a path within the build context or be an artifact path.

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by vladaionescu** [comment]
I'll add this to the roadmap as this has been requested quite a bit.

**Comment by vladaionescu** [comment]
This will go out with the next release.

The syntax is

```
FROM DOCKERFILE -f <local-dockerfile-path-relative-to-current-earthfile> <local-build-context-path-relative-to-current-earthfile>
```

or

```
FROM DOCKERFILE -f +target/path/to/some.Dockerfile +another-target/path/to/build/context
```

Or any combination of the above.

**Comment by vladaionescu** [comment]
This has now been released.

**Comment by n-rodriguez** [comment]
> This has now been released.

awesome!
