### ISSUE TITLE
"Error: parser failure: assignment to entry in nil map" when combining FROM with EXPOSE

### ISSUE THREAD

**Issue by bearbytes** [earthly/earthly#64]
I'm using earth to create a Docker image in 2 recipes.
The first stage compiles the source code, the second sets up a run environment and copies over the artifacts.

I boiled it down to this simple example:
```
FROM alpine

build:
  RUN touch hello.txt
  SAVE ARTIFACT hello.txt

run:
  FROM ubuntu
  COPY +build/hello.txt .
  EXPOSE 8080
  SAVE IMAGE hello-image
```

Running `earth +run` fails with the following error:

```
Error: parser failure: assignment to entry in nil map
```

If i comment either the `EXPOSE 8080` or `FROM ubuntu` commands, the command works again, so there seems to be an issue when using both commands in a recipe.

**Comment by vladaionescu** [comment]
I can indeed reproduce this. Will take a look.

**Comment by vladaionescu** [comment]
Thanks for reporting. This is now fixed on master. You can build the master yourself like this:

Linux
```
earth --artifact github.com/earthly/earthly+earth/earth ./earth
```

Mac
```
earth \
--build-arg GOOS=darwin \
--build-arg GOARCH=amd64 \
--build-arg GO_EXTRA_LDFLAGS= \
--artifact github.com/earthly/earthly+earth/earth ./earth
```

**Comment by vladaionescu** [comment]
This is now in the latest release `v0.1.2`
