### ISSUE TITLE
WITH DOCKER - possible regression in v0.4.2

### ISSUE THREAD

**Issue by visciang** [earthly/earthly#676]
Issue seen in `v0.4.2`, it works as expected in `v0.4.1`.

It seems the loaded image (`WITH DOCKER --load external-image:latest=+external-image`) is not available in the docker-compose "context".

To reproduce the issue:
https://github.com/visciang/issue-earthly-docker-compose

```
$ earthly -P +test
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
        earthly/dind | --> Load metadata (linux/amd64)
             context | --> local context .
               +base | --> FROM earthly/dind
               +base | [          ] resolve docker.io/earthly/dind@sha256:210c526a401e2f4529a207a0510c2882393a[██████████] resolve docker.io/earthly/dind@sha256:210c526a401e2f4529a207a0510c2882393a4ca2027dcf874b6820fbdf1de894 ... 100%
             context | [██████████] transferring .: ... 100%
               +test | *cached* --> COPY docker-compose.yml .
               +test | *cached* --> WITH DOCKER (install deps)
               +test | *cached* --> WITH DOCKER (docker-compose config)
external-image:latest | --> Load metadata (linux/amd64)
external-image:latest | WARN: (Load metadata (linux/amd64)) pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: authorization failed
```

**Comment by agbell** [comment]
Thanks for finding this @visciang.

I can reproduce the issue. ``--load`` is not required in this case, it will load regardless.  Nevertheless the same issue is encountered without the load in v0.42.

**Comment by vladaionescu** [comment]
Thanks for the report @visciang. It seems that this no longer reproduces on the main branch. `v0.4.3` (just released) should fix this for you.

**Comment by visciang** [comment]
Tested right now on "the real thing" and it works as expected.
Thank you @vladaionescu !
