### ISSUE TITLE
Invalid ENV declaration should return an error

### ISSUE THREAD

**Issue by cirego** [earthly/earthly#69]
If I do the following in my `build.earth` file:

```
ENV ${CODE_SRC}=/go/src/<project>

protobuf:
    COPY --dir api ${CODE_SRC}/backend
```

Then running `earth +protobuf` results in the files being copied into `/backend`:

`+protobuf | --> COPY [api] /backend`

I have worked around this by specifying the full path in the copy command:

```
ENV ${CODE_SRC}=/go/src/<project>

protobuf:
    COPY --dir api /go/src/<project>/backend
```

**Comment by cirego** [comment]
I see the same behavior with the `WORKDIR` command as well.

**Comment by vladaionescu** [comment]
I believe the issue is purely in the syntax. You should use:

```Dockerfile
ENV CODE_SRC=/go/src/<project>

protobuf:
    COPY --dir api $CODE_SRC/backend
```

**Comment by vladaionescu** [comment]
Depending on your needs - I think an ARG would be more appropriate fit for this. ENV is mainly meant for env vars that remain as part of the image, should you issue a `SAVE IMAGE` command.

```Dockerfile
ARG CODE_SRC=/go/src/<project>

protobuf:
    COPY --dir api $CODE_SRC/backend
```

**Comment by cirego** [comment]
Thanks for the quick reply! So it's the `{}` that's causing it to fail? I can fix the syntax, thank you!

We call into scripts that expect this ENV var to be set, but using ARG is definitely preferred. Thanks for the tip!

Also, thanks for the awesome build tool! I'm loving it so far!

**Comment by vladaionescu** [comment]
> So it's the {} that's causing it to fail?

Looks that way. Both in the declaration and in the use of it. (Also, no `$` in declaration).

We should make the system return an error on invalid declaration. I'll leave this ticket open for addressing this.

**Comment by cirego** [comment]
> (Also, no `$` in declaration).

Sorry, that was a transcription error because I didn't want to copy my exact `build.earth` file. Thanks for your help!

**Comment by JosemyDuarte** [comment]
Hi @vladaionescu! I would like to help with this for the Hacktoberfest. Could I work on this? Any hint on where to look at?

**Comment by agbell** [comment]
Hi @JosemyDuarte ,
Take a look at this PR https://github.com/earthly/earthly/pull/71. It is close to a solution so you could start from there.
