### ISSUE TITLE
Proposal: Ability to drop to an interactive shell via Earthfile

### ISSUE THREAD

**Issue by dchw** [earthly/earthly#693]
Introduce a new command that triggers the interactive debugger as a step. Once the shell session is complete; aggregate all changes made in the container and continue execution (including the modifications).

Here are the options I have thought of for syntax:

```Dockerfile
my-target:
    FROM alpine:latest
    INTERACTIVE SHELL
   ...
```

```Dockerfile
my-target:
    FROM alpine:latest
    DEBUG
    ...
```

## Use-cases:

* Explore problematic containers that otherwise build fine with Earthly
* Debug at any state
* Allow manual modification for development and/or testing while creating an Earth target
* Enables a repl-like development cycle

## Alternatives:

* Right now, to get similar effects, you would need to insert a failing command (I usually use `RUN breakhere`); and then include the interactive debugging mode CLI argument. This is cumbersome and annoying; plus it does not allow for continuation after the fact (since something has already failed).
* Build the image and explore it post-build using tools like `dive`. This lets you see the state of the filesystem at a given point; but its not easy to run commands at a given layer. Additionally; we are encumbered more by the lack of good layer descriptions in  our built images right now.

**Comment by vladaionescu** [comment]
Another possible syntax could be

```
RUN --interactive /bin/sh
```

Then you could also run arbitrary programs directly. Like `RUN --interactive python` or `RUN --interactive node`.

Possible extension: in interactive mode, also allow bind-mounting any local folder. This could enable watch mode use-case for front-end developers.

**Comment by leighst** [comment]
Was this added ?
