### ISSUE TITLE
WSL ERROR: read-only file system

### ISSUE THREAD

**Issue by Dyhr** [earthly/earthly#70]
Hello, I have set up earthly to run on Windows with WSL, and I am trying to use a specific image for compiling Unity projects, but I get this error:

```
+base | ERROR: (FROM gableroux/unity3d:2019.2.11f1-windows) failed to copy: write /tmp/earthly/buildkit/runc-overlayfs/content/ingest/7e1cdf26cfc0f911031b2bd7d6ad7596fe77a38778389fe3f282b2354d40abc6/data: read-only file system
Error: solve side effects: build error group: solve: failed to solve: rpc error: code = Unknown desc = failed to copy: write /tmp/earthly/buildkit/runc-overlayfs/content/ingest/7e1cdf26cfc0f911031b2bd7d6ad7596fe77a38778389fe3f282b2354d40abc6/data: read-only file system
```
My `build.earth` simply looks like this:

```
FROM gableroux/unity3d:2019.2.11f1-windows
WORKDIR /app

build:
        RUN echo "Hello world"`
```

**Comment by vladaionescu** [comment]
Thanks for the report! It looks like this is tied to windows guest support.

**Comment by Dyhr** [comment]
It's not a windows image though, so are you sure that windows guest is the issue?

**Comment by vladaionescu** [comment]
Ah you're right. The `-windows` part in the label fooled me. Then it's some other issue - will need to look into it.
