### ISSUE TITLE
support for referencing generated earthfile targets

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#719]
Similar to our support for referencing generated dockerfiles (e.g. https://github.com/earthly/earthly/edit/main/examples/tests/gen-dockerfile.earth ) we had a request to do this with Earthfile. Here's an example:

```
FROM alpine:3.11
WORKDIR /test

gen-earthfile:
    RUN echo "FROM alpine:3.11" > Earthfile
    RUN echo "" >> Earthfile
    RUN echo "mytarget:" >> Earthfile
    RUN echo "    RUN echo hello world" >> Earthfile
    SAVE ARTIFACT ./*

testa:
    BUILD +mytarget FROM +gen-earthfile

    # or perhaps this syntax:
    BUILD +gen-earthfile/mytarget

    # or break it up into two commands
    LOAD +gen-earthfile
    BUILD +mytarget

testb:
    FROM +gen-earthfile/mytarget
```

using `BUILD +mytarget FROM +gen-earthfile` seems odd since when we want to do `FROM +mytarget FROM +gen-earthfile` it seems confusing with the multiple FROMs; using `LOAD +gen-earthfile; BUILD +mytarget` could introduce a case where the generated earthfile's targets conflict with the parent Eathfile's targets, so that leaves me leaning towards a `BUILD +gen-earthfile/mytarget` syntax.

**Comment by alexcb** [comment]
Here's a rather contrived example of a work-around to perform something similar (using earthly-in-earthly):

running `earthly -P +eine` will run a python script that generates a new Earthfile, then shells out to a containerized version of earthly which is invoked via our '/usr/bin/earthly-buildkitd-wrapper.sh' script:

```
FROM alpine:latest
RUN apk add wget
eine:
    FROM github.com/earthly/earthly:main+earthly-docker
    RUN apk add python3
    RUN echo "import subprocess" > /myscript.py
    RUN echo "open('Earthfile', 'w').write('FROM alpine:latest\n\nmytarget:\n    RUN echo hello\n')" >> /myscript.py
    RUN echo "subprocess.check_call(['/usr/bin/earthly-buildkitd-wrapper.sh', '+mytarget'])" >> /myscript.py
    RUN cat /myscript.py
    RUN --privileged python3 /myscript.py
```

However this limitation doesn't allow pushing the generated targets.

**Comment by vladaionescu** [comment]
Perhaps this can be a little more general, to allow either `BUILD`, `COPY` or `FROM` to reference a generated build context (not just the Earthfile, but also the files around the Earthfile that can be used to copy from).

Maybe something like this:

```
BUILD --context=+something/* +target
COPY --context=+something/* +target/artifact ./
FROM --context=+something/* +target
```

**Comment by vladaionescu** [comment]
BTW re workaround:

> ```
> eine:
>    FROM github.com/earthly/earthly:main+earthly-docker
> ```

We also have a released Docker image for this, to help with the build speed: `FROM earthly/earthly:v0.4.5`

**Comment by alexcb** [comment]
this is not something we want to do in the end; generally static build graphs are easier to optimise.
