### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#722]
The following issues remain:

- [x] Not clear which architecture buildkit is being run as. Best if we print the output of `uname -m` at the beginning of the logs.
- [x] The platform each target executes as is not very obvious (only shown once per target). We should show this for every RUN command to improve its visibility.
- [x] `WITH DOCKER` does not work. Some network-related error prevents dockerd to start. This could be related to the Docker for Mac preview and may fix itself in a later version of Docker.
- [x] `--platform` should be automatically propagated between projects. Currently this behaves like build args (they do not cross project boundaries unless explicitly passed); however, this behavior is not very useful for the platform flag. With this change, perhaps there should be a way to tell buildkit to use the default platform of the system, in order to be able to undo a platform override for sub-branches of the build.
- [x] Get the Buildkite CI agent to run tests and examples on M1

CC @dchw

**Comment by dchw** [comment]
You know I want to talk you out of more shelling out; why is using the `runtime` arch in the buildkit binary not acceptable here too? Or whatever the manifest says it is?

Crazy idea: add an API endpoint of some kind to it that we can query for statistics and other debug info.. like this?

**Comment by vladaionescu** [comment]
> You know I want to talk you out of more shelling out; why is using the runtime arch in the buildkit binary not acceptable here too? Or whatever the manifest says it is?

Oh - for this I was thinking of placing the `uname -m` in our buildkit [`entrypoint.sh`](https://github.com/earthly/earthly/blob/main/buildkitd/entrypoint.sh). That way we don't actually have to modify buildkit itself for this.

I like the API endpoint idea - might require significant work though.

**Comment by dchw** [comment]
> Oh - for this I was thinking of placing the uname -m in our buildkit entrypoint.sh. That way we don't actually have to modify buildkit itself for this.

Great idea; I am down for that

> I like the API endpoint idea - might require significant work though.

Yep. Hence the crazy idea... someday maybe

**Comment by vladaionescu** [comment]
This is ready to graduate to Beta status on the next release.

**Comment by rizkyramadhan** [comment]
I just tried installing earthly on m1, after running these command: 

`brew install earthly/earthly/earthly && earthly bootstrap`

I got this

```
    buildkitd | Is docker installed and running? Are you part of the docker group?
Error: bootstrap new buildkitd client: docker not available
```

Yes, I have docker desktop installed.
