### ISSUE TITLE
Good First Issues?

### ISSUE THREAD

**Issue by kevinkjt2000** [earthly/earthly#724]
I was looking at ways that I could contribute to this amazing project, but it seems that many of the good first issues were completed during hacktoberfest. Where would someone new start currently?

**Comment by agbell** [comment]
Hi @kevinkjt2000,

That is great, we are happy to have you.  I've cleared the assignees from some of the first-issue tickets that look abandoned. Does that help.  Feel free to jump on our slack channel to chat more about how you can contribute.

**Comment by kevinkjt2000** [comment]
When I get a minute I'll totally jump in Slack and introduce myself. I absolutely love what Earthly is doing! <3
