### ISSUE TITLE
Cannot build image FROM scratch

### ISSUE THREAD

**Issue by austenadler** [earthly/earthly#73]
Earthly seems to always try pulling images and it won't allow me to build from scratch.

This Dockerfile works:
```
FROM scratch
WORKDIR /
```

This earthly build file fails:
```
FROM scratch
t:
  WORKDIR /
```
With error:
```
buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: parse: apply implicit FROM +base: apply build +base: earthfile2llb for +base: parse: apply FROM scratch: resolve image config for scratch: docker.io/library/scratch:latest: not found
```
This will also fail if `FROM scratch` is listed under a target.

How can I build an image from scratch?

**Comment by vladaionescu** [comment]
Indeed this is a limitation. Nothing that can't be fixed however - I'll look into this.

**Comment by vladaionescu** [comment]
Ok - added support for it as part of #74. It will be in the next release. In the meantime, you can build the earth binary from source:

Linux
```
earth --artifact github.com/earthly/earthly+earth/earth ./earth
```

Mac
```
earth \
--build-arg GOOS=darwin \
--build-arg GOARCH=amd64 \
--build-arg GO_EXTRA_LDFLAGS= \
--artifact github.com/earthly/earthly+earth/earth ./earth
```

---------

Note that even with this, there is currently a limitation in that you cannot use `RUN` until you have a shell (`/bin/sh`) copied into the container. This limitation can be addressed in the future, however: you'd be able to `RUN [...]` using the exec-form.
