### ISSUE TITLE
Proposal: Flow control structures (IF and FOR)

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#779]
# IF / IF ELSE

## Use-cases

* Ability to switch between FROM <something> and LOCALLY based on a build arg. This allows the user to reuse CI setup (FROM alpine) in their development workflow (LOCALLY). A common set of instructions are used (eg RUN go download, RUN go build etc), but the execution can be switched between container and local via an IF.
* With the new UDC proposal, it it harder to rely on bash if’s alone. The decision of whether to run a UDC or not cannot be controlled via a bash if. In this context first-class support for IF is necessary.
* This kind of optional use of secrets is clunky to use: https://github.com/earthly/earthly/blob/main/examples/tests/Earthfile#L8-L15. In order to turn the use of a secret on, the entire path of the secret needs to be specified as part of a build arg (like this https://github.com/earthly/earthly/blob/main/.github/workflows/ci.yml#L72). It would be much nicer if we could use an IF with a much simpler build arg like DO_DOCKER_LOGIN=true.

## Proposal

```
IF <run expression>
	RUN ...
	COPY ...
	EXPOSE ...
END
```

```
IF <run expression>
	RUN ...
	COPY ...
ELSE
	COPY ...
	RUN ...
END
```

```
IF <run expression>
	RUN ...
	COPY ...
ELSE IF <run expression>
	COPY ...
	RUN ...
END
```

## Example 1 (optional docker login in our integration tests)

```
ARG DO_DOCKER_LOGIN=false
IF $DO_DOCKER_LOGIN
  ARG DOCKERHUB_USER_SECRET=+secrets/earthly-technologies/dockerhub/user
  ARG DOCKERHUB_TOKEN_SECRET=+secrets/earthly-technologies/dockerhub/token
  RUN --secret USERNAME=$DOCKERHUB_USER_SECRET \
    --secret TOKEN=$DOCKERHUB_TOKEN_SECRET \
    docker login --username="$USERNAME" --password="$TOKEN"
END
```

## Example 2 (ability to run build locally)

```
ARG LOCAL=false
IF $LOCAL
	LOCALLY
ELSE
	FROM +code
END
RUN go build ...
```

## Example 3 (use bash comparisons)

```
FROM +something
IF \
	[ "$var" = "abc" ] && \
	[ -f ./some-file ] && \
	curl ...| \
	grep ....
	FROM +something-else
END
```

## Notes
* Don’t interpret true / false. Just run and look at exit code.
* Possibly add `--no-cache` in the future. Current workaround: `RUN --no-cache` above to evaluate.
* Think more about `IF +target` (similar to `TRY +target`)
* Nested IF's are allowed

## Open questions
* What happens with SAVE ARTIFACT ... ... AS LOCAL ... in a LOCALLY target? Resolution: Support this. AS LOCAL dest is the actual dest.

# FOR ... IN ....

## Use-cases
* Iterate through a list of things to build / handle. Eg a list of cpp files to compile, a list of protobuf packages to generate code for. In most cases, this can be achieved via a bash for, however. (Question: any example of a situation where this cannot be achieved through a bash for?)
* Reduce repetition. For our +examples target, what if it were defined as a FOR loop of invoking the target +all of each subdirectory under ./examples. See example 2 below. In a monorepo layout, this might also be used as a way to automatically detect new services that are added to the build.
* Together with the UDC proposal #581, it helps to reuse a UDC in a for loop, since a bash for would not be able to call a UDC.

## Notes

* IFS is hard. Different shell has different behavior with it. Add `--delimiter="\n"` or `--sep="\n"` option, which defaults to what bash does: "\n\t ".
* Don’t use any escape char (bash doesn’t use it). User can still change the delimiter.

## Example 1 (perform the same action over a number of files)

```
FOR file IN $(ls cpp/src)
	RUN clang cpp/src/"${file}" -S -O3 -o build/"${file}.o"
	SAVE ARTIFACT build/"${file}.o"
END
```

## Example 2 (reduce repetition)

```
examples:
	COPY --dir ./examples ./examples
	FOR example IN $(ls ./examples)
		BUILD "$example"+all
	END
```

# WHILE

## Use-cases

* What’s a good use-case for this that would not be covered by a `FOR ... IN ...`?

## Pitfalls

* The user may be tempted to use `WHILE` for a busy-wait loop - eg `WHILE <something is not ready> RUN sleep 1`. This ends up creating a ton of layers for no good reason.

## Resolution

Don't implement `WHILE` until there's a solid use-case for it.

**Comment by jazzdan** [comment]
`FOR` will be super useful if you can pass a dynamic list to iterate over to it. For example, I'd love to be able to run a command that lists all of my typescript files, then `RUN` `eslint` on each of them. That way if one file changes I only run `eslint` on the file that changed, not on the whole directory structure.

**Comment by vladaionescu** [comment]
Implementation for this is complete. Will go out with the next release in experimental phase. To enable, use

```
VERSION --for-in 0.5
```
