### ISSUE TITLE
Cargo-Chef with Earthly caching issue

### ISSUE THREAD

**Issue by bhansconnect** [earthly/earthly#786]
[Cargo-Chef](https://crates.io/crates/cargo-chef) is a tool for being able to cache rust build dependencies. Since, sadly, rust does not have a nice way to tell it to go and download all dependencies. Chef is made with docker containers in mind. Its general process is:
1) prepare - Generate a recipe in a container with the full source
2) cache - Load the recipe into another container and use it to build dependencies
3) build - Load the build dependencies from the cacher and complete your build

If you modify your code without changing a dependency, step 1 will run again, but produce the same recipe. As such, step 2 will notice the recipe is the same and simply used the cached image with dependencies in it. Finally, step 3 will run again.
In the case you do modify a dependency, the recipe will change and step 2 will rerun.

[Naively copying](https://github.com/bhansconnect/earthly-rust-chef/blob/main/Earthfile%20-%20Suggested) the equivalent Dockerfile into an Earthfile does not work as expected. With every single change, Earthly will rerun step 2, even if it generates the same recipe in step 1.
[A workaround](https://github.com/bhansconnect/earthly-rust-chef/blob/main/Earthfile#L16) to at least make this partially work is to make the prepare script only depend on the `Cargo.toml` files and to generate fake `main.rs` and `lib.rs` files. This is not terrible, but it is quite tedious for sizable projects. Also, all of the copy and run operations to move these different directories take quite a long time to generate. Lastly, if a change is made to a `Cargo.toml` file that does not modify the recipe, it will still invalidate all caching.

For a repo with a sample project I set up: https://github.com/bhansconnect/earthly-rust-chef

It would be really nice if copying a new version of an artifact that has the same sha would cause caching to be kept.
Otherwise, it would be nice if there was some sort of copy operation that went faster by grouping more things together.
I believe it is the cost of caching every individual copy operation that makes this slow.

**Comment by vladaionescu** [comment]
Thanks for the detailed explanation and sample project. Super useful! We'll work out a solution for this.

**Comment by bhansconnect** [comment]
Just an extra note: For the chain of copies being slow for me, I think I may be hitting this bug related to zfs and caching layers: https://github.com/moby/moby/issues/31247

**Comment by vladaionescu** [comment]
I don't think that that zfs bug applies - underneath Earthly uses a docker volume for the cache and that volume is provided as ext4 by Docker.

**Comment by agbell** [comment]
Hi @bhansconnect I am going to look into this later this week and see if I can figure out what's happening.

**Comment by agbell** [comment]
@bhansconnect 
Thanks for putting together this example.  I believe this does work the way you desire it to work.  It will not run subsequent steps if the steps have been run before with that same input.  

I recorded a video using your example, to make sure I understand. 
https://share.descript.com/view/8vZ3u9ODlpA
Take a look and let me know you get this behavior as well.

**Comment by agbell** [comment]
The second example I showed is in #809  if you'd like to try it and see if behaves similarly for you.

**Comment by bhansconnect** [comment]
So I was looking into this more and the issue definitely seems to be device specific in some way, but I am not sure how. My laptop (ubuntu 20.04 with zfs) fails to cache things properly with my rust example. That being said, your c++ example works on my laptop. On my raspberry pi (ubuntu 20.04 with ext4), both examples work correctly.

I am not sure the file system matters at all, but it is one of the things that I would expect might have an effect. I really don't know enough about the underlying systems to guess what is causing the caching to fail on my laptop. Any ideas what might be happening or debug logs I should look at?

**Comment by agbell** [comment]
Interesting, does your rust example work with docker if you use buildkit? 

```
DOCKER_BUILDKIT=1 docker build .
```
We are using buildkit to do the caching, so it SHOULD work equivalently to docker build with buildkit.

**Comment by bhansconnect** [comment]
`DOCKER_BUILDKIT=1 docker build .` crashes the first time and then after that it works as expected for me. Haha.

It looks like I am hitting this bug: https://github.com/moby/buildkit/issues/1758
Maybe it is manifesting differently through earthly and just breaking caching somehow.

Anyway, I guess I am fine as just writing this off as zfs related issues, buildkit seems to have a couple of bugs related to zfs.
Luckily for me, the CI server has ext4 as the filesystem and caching works perfectly fine.

**Comment by agbell** [comment]
Wow, you really hit an edge case. Thanks for diving into it.

**Comment by nrdxp** [comment]
Just thought I'd post a workaround I'm using for this atm:
```
mock:
    COPY Cargo.toml Cargo.lock .
    ARG CRATES=$(tomlq -r .workspace.members[] Cargo.toml)
    FOR crate IN $CRATES
      COPY --if-exists $crate/Cargo.toml $crate/*.rs $crate
    END
    RUN for i in $CRATES; do mkdir -p $i/src && touch $i/src/main.rs; done
```
Some of the crates are actually lib crates so the `main.rs` isn't strictly correct, but it doesn't seem to affect `cargo chef` negatively so far, so I think it works fine. If I could somehow the loops to a single `COPY` command, it wouldn't be so bad.

**Comment by adamgordonbell** [comment]
We now have lib/rust, which does a better job of caching then cargo-chef, especially if you have a persistent cache for the layers generated. 

See https://earthly.dev/rust

Closing this, but if its still a blocker and still occuring, we can reopen.

**Comment by Boscop** [comment]
@adamgordonbell Does the Rust lib also work when requiring rustc nightly, and for fullstack Rust projects (WASM frontend that also needs npm deps)?

In other words, what's the best way to do this but with maximum caching? :)
```Earthfile
VERSION 0.8

FROM rustlang/rust:nightly-alpine

builder:
    RUN apk update && apk add --no-cache bash curl npm libc-dev binaryen

    RUN npm install -g sass

    RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/leptos-rs/cargo-leptos/releases/latest/download/cargo-leptos-installer.sh | sh

    RUN rustup target add wasm32-unknown-unknown

    WORKDIR /work
    COPY . .

    RUN npm install

    RUN cargo leptos build --release -vv

    SAVE ARTIFACT /work/target/release/my-app /app/
    SAVE ARTIFACT /work/target/site /app/site
    SAVE ARTIFACT /work/Cargo.toml /app/

docker:
    FROM alpine:latest

    WORKDIR /app

    COPY +builder/app/my-app .
    COPY +builder/app/site ./site
    COPY +builder/app/Cargo.toml .

    ENV LEPTOS_SITE_ROOT=./site
    ENV LEPTOS_SITE_ADDR="[::]:8080"
    EXPOSE 8080

    CMD ["/app/my-app"]

    SAVE IMAGE --push ghcr.io/Boscop/my-app:latest
```
