### ISSUE TITLE
Then linux-arm64 release binary is actually the darwin-arm64 binary

### ISSUE THREAD

**Issue by bhansconnect** [earthly/earthly#789]
The title pretty much describes the issue.

On the [release page](https://github.com/earthly/earthly/releases/tag/v0.5.1), the darwin-arm64 and the linux-arm64 binaries are the same. They both look to be compiled for Mac and not for linux.

**Comment by vladaionescu** [comment]
Just checked - this is confirmed.

**Comment by vladaionescu** [comment]
I removed `earthly-linux-arm64` from the release for the time being.

**Comment by vladaionescu** [comment]
This is now fixed in the latest release https://github.com/earthly/earthly/releases/tag/v0.5.2
