### ISSUE TITLE
Improve logs (introduce a progress-bar for tty devices)

### ISSUE THREAD

**Issue by brandonkal** [earthly/earthly#84]
Running the Go example, earth floods the terminal with lines like this:

```
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 11%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 11%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
+base | sha256:61b11419476186415e86da00c53c938fd32dc5904a889e1c3d40e238d69d168e 12%
```
Though it is a lot more of that than I've included here. I would expect this as a progress bar replacing the line on update rather than drawing a new line.

`go build` is silent on success so this is a lot messier.

**Comment by vladaionescu** [comment]
Makes sense, Brandon. We need to improve this.

(I believe those specific lines are from the progress of pulling some docker image - this can be made less verbose.)

**Comment by brandonkal** [comment]
Yes that is from pulling the image. My internet connection is slow so I get a higher amount of those lines.
With a tty, a simple wget-like progress bar would be better.
Without a tty, one solution is to filter out duplicate lines (that at least reduces it down to 100 lines for each pull).

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/pull/143 changes the behaviour to only print out the progress every 5 seconds.

I agree that a tty progress bar would be nice to implement one day, so maybe we should leave this issue open?

**Comment by Gituser143** [comment]
Hey @vladaionescu! Can I work on this issue?

**Comment by vladaionescu** [comment]
Sounds good @Gituser143. This is where progress is printed BTW: https://github.com/earthly/earthly/blob/master/builder/solver_monitor.go#L178. Keep in mind that there may be multiple progress bars ongoing at a time and that the printing itself is being worked on in parallel: https://github.com/earthly/earthly/issues/338.

CC @MadhavJivrajani

**Comment by Gituser143** [comment]
Thank you @vladaionescu! I'll get to it...

**Comment by Gituser143** [comment]
@vladaionescu I'm running into some small issues while trying to build from source. I was able successfully build the binary using the command `earth +all`, but when I try using the earthly binary I just built to run the go example, I come across this issue:

![image](https://user-images.githubusercontent.com/44526455/94899659-52372400-04b1-11eb-9b6f-c6a947c9313e.png)

That file `earth-prerelease` doesn't exist. Am I doing something wrong here?

**Comment by Gituser143** [comment]
@vladaionescu I'm having a few some small issues with the progress bar. My implementation is kinda like [this](https://github.com/Gituser143/earthly/blob/6178029c2e7191e636bde8194b521e2dc3a6ffc8/builder/solver_monitor.go#L158). I'm testing these out with the go example and since values aren't really updating frequently, it moves from 0 to 100 pretty quick.

Can you give me some sort of feedback on what I can change (or if I'm doing something wrong)?

**Comment by Gituser143** [comment]
@vladaionescu I've implemented a simple progress bar. It's declared [here](https://github.com/Gituser143/earthly/blob/94055707077b6bdb83bb35f8a87af0067cf176b3/builder/solver_monitor.go#L160) and values are updated like [this](https://github.com/Gituser143/earthly/blob/94055707077b6bdb83bb35f8a87af0067cf176b3/builder/solver_monitor.go#L186). Let me know if I can open a PR so that you can see the changes and tell me what changes I'll have to make.

My overall implementation looks kind of like this:

```go
var on sync.Once
progressBar := pb.New(100)
for _, vs := range ss.Statuses {
  ...  
  progress := int(0)
  if vs.Total != 0 {
    progress = int(100.0 * float32(vs.Current) / float32(vs.Total))
  }
  if vs.Completed != nil {
    progress = 100
  }
  if vm.shouldPrintProgress(progress) {
    ...
    on.Do(func() {
      vm.console.Printf("%s\n", vs.ID)
      progressBar.Start()
    })
    progressBar.SetCurrent(int64(progress))
  }
}
progressBar.Finish()
```

**Comment by vladaionescu** [comment]
It's a good start, however you probably need a separate progress bar for each of the items in `ss.Statuses`. These are multiple activities taking place in parallel and the relevant progress bars need to be updated in parallel. Feel free to open a PR even if it's WIP.

**Comment by vladaionescu** [comment]
This has been implemented and will be in the next release.
