### ISSUE TITLE
How I could effectly cache the docker step?

### ISSUE THREAD

**Issue by Mdsp9070** [earthly/earthly#841]
I have this sample Earthfile: https://www.github.com/cciuenf/lovelace_bot/tree/main/Earthfile

But obviously it does not cache anything that's docker resulted...

I'm trying to build a better one, to speed up CI, but I don't know where to start and where to improve.

Could you please give me any suggestions?

**Comment by agbell** [comment]
Hi @Mdsp9070,
Does it cache steps when you rerun locally but just not in CI?

I think you may want to look at using the explicit cache:
https://docs.earthly.dev/guides/shared-cache

That will require setting up a docker hub account, and pushing to it at the end of your build, purely for caching purposes.

**Comment by Mdsp9070** [comment]
Thanks for the answer @agbell! No, actually, when Earthfile enter on the "With DOCKER" statement, it ignores the the "FROM earthly/dind:alpine" and tries to install docker and docker compose "manually".

Also, this "manual" installation does not caches...

Yeah! Last day I was reading the docs! I'll give it try!

**Comment by vladaionescu** [comment]
Hi @Mdsp9070 - it looks like the chain is `+unit-test` -> `FROM +test-setup` -> `FROM +setup-base` -> `FROM hexpm/elixir:$ELIXIR-erlang-$OTP-alpine-3.12.0`. So your base image used in the `WITH DOCKER` test is not actually `earthly/dind`.

**Comment by Mdsp9070** [comment]
@vladaionescu, exactly! My doubt is how and if it's possible to use both images! Obviously I can't use 2 `FROM` statements, however with cache I could "use" both images, right?

**Comment by vladaionescu** [comment]
You could try to install docker in the image you are already using. If it's alpine-based, it could be as easy as `apk install docker`. If it's debian-based, it might be a little more involved. You can take a look at this script which Earthly uses to automatically install docker: https://github.com/earthly/earthly/blob/main/buildkitd/docker-auto-install.sh#L81. If you do the installation as early as possible (before any `COPY` command), the cache will be efficient.

Either that, or go the other way and install Elixir and Erlang on top of `earthly/dind`.

**Comment by Mdsp9070** [comment]
Indeed! I chose to go with `earthly/dind` and then install elixir! CI are blazing fast now! Thank you all!
