### ISSUE TITLE
Support marking dependencies explicitly

### ISSUE THREAD

**Issue by benjamin-wright** [earthly/earthly#858]
First off, thanks for making Earthly, it's such a neat project!

I'm trying to figure out a good way of sharing node modules in a monorepo, pushing and pulling from a private NPM registry. There may be a better way of doing this, but here's one of my Earthfiles to illustrate what I'm thinking:

```
FROM node:10.15.3-alpine
WORKDIR /src

deps:
  COPY ../dependency-module+publish/ /markers/dependency-module

  RUN --secret NPMRC_FILE=+secrets/NPMRC_FILE printf "$NPMRC_FILE" > ~/.npmrc
  COPY package.json package-lock.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./.eslintrc ./.eslintrc
  COPY ./lib ./lib

lint:
  FROM +deps
  RUN npm run lint

  SAVE ARTIFACT package.json

unit:
  FROM +deps
  RUN npm run test

  SAVE ARTIFACT package.json

publish:
  FROM +deps

  COPY +lint/ /markers/lint
  COPY +unit/ /markers/unit

  RUN npm run patch
  RUN npm publish
```

And my `depenedency-module` has the earthfile:

```
FROM node:10.15.3-alpine
WORKDIR /src

deps:
  RUN --secret NPMRC_FILE=+secrets/NPMRC_FILE printf "$NPMRC_FILE" > ~/.npmrc
  COPY package.json package-lock.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./lib ./lib

publish:
  FROM +deps

  RUN npm run patch
  RUN npm publish

  SAVE ARTIFACT package.json
```

The problem I'm hacking around is that the output of my dependency module is created by pushing to the private registry, which means I don't have a sensible artifact to reference from the parent module. Instead, I'm saving package.json (a relatively small file) and copying that into a random `/markers` folder just to force Earthly to recognise the dependency.

Also, because I need to push the dependency module to the registry BEFORE running the `npm install` in the parent module, I can't use `RUN --push npm publish` or it'll publishing everything at the end AFTER all the `npm install`s. That's why I've got the same hack for the lint and unit tests.

What I'm proposing is a simple concept (I'm hoping similarly easy to implement...) to explicitly mark dependencies, so that I can indicate to Earthly that one target is dependent on another without having to manufacture a dummy artifact.

```
FROM node:10.15.3-alpine
WORKDIR /src

deps:
  DEPENDS ON ../dependency-module+publish

  RUN --secret NPMRC_FILE=+secrets/NPMRC_FILE printf "$NPMRC_FILE" > ~/.npmrc
  COPY package.json package-lock.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./.eslintrc ./.eslintrc
  COPY ./lib ./lib

lint:
  FROM +deps
  RUN npm run lint

unit:
  FROM +deps
  RUN npm run test

publish:
  FROM +deps

  DEPENDS ON +lint +unit

  RUN npm run patch
  RUN npm publish
```

Thanks again for your great work! 😁

**Comment by vladaionescu** [comment]
Hi @benjamin-wright - it seems that your use-case is covered by `WITH TRY --before` (a future command we're planning on adding - see [this proposal](https://github.com/earthly/earthly/issues/587)). Can you confirm that that would indeed address your problem?

**Comment by benjamin-wright** [comment]
Hi @vladaionescu - almost, but I think the caching In my use case is a bit different;

For the proposed `WITH TRY --before` you have tests, and environment setup and teardown. You want the caching to be conditional on the tests, and to have no caching on the setup and teardown at all:
- if the tests are cached then you do nothing
- if the tests are not cached then you ALWAYS do both the setup and teardown, and run the tests

In my use-case I have two projects A and B, and A depends on B.

- if A is cached and B is cached then do nothing
- if A is not cached and B is cached, only build A
- if A is not cached and B is not cached, wait for B to build, then build A
- if A is cached and B is not cached, wait for B to build, then rebuild A

So in my use-case I really just want to mimic the behaviour of a COPY from project B, but for cases where there is no artifact to copy.

Does that make sense? Thinking about it, I don't know if a better alternative would be to add a `--no-dangling` option to the `BUILD` command? So you could have...

```
deps:
  BUILD ../dependency-module+publish --no-dangling

  RUN --secret NPMRC_FILE=+secrets/NPMRC_FILE printf "$NPMRC_FILE" > ~/.npmrc
  COPY package.json package-lock.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./.eslintrc ./.eslintrc
  COPY ./lib ./lib
```

The critical thing is that `RUN npm install` doesn't happen until / unless there is a valid PUSHed build for `../dependency-module+publish`

**Comment by vladaionescu** [comment]
Ah yes - it is quite different. You have an interesting use-case actually and indeed there should be an easy way to do the right thing in Earthly.

`RUN --push` would actually execute every time as it runs with no-cache. So even if that executed at the right time, it wouldn't help for your use-case.

I'll need to think about this a bit more and figure out the implications.

**Comment by vladaionescu** [comment]
Just to repeat the Slack idea for posterity: `EVAL "COPY $(cat dependencies) ."` would help for @jazzdan's issue. This could work similar to a [bash eval](https://linuxhint.com/bash_eval_command/).

**Comment by jclangst** [comment]
Similar goal. The copy solution from @benjamin-wright is very clever. I also like the idea of a more purposeful method to invalidate the cache. I have a couple of ideas for enhancing the  proposed `DEPENDS ON` syntax.

- Change the name to `CACHE KEY [<target-ref>[/<artifact-path]]...`. If the value of the referenced object(s) change, the line has the same effect as `RUN --no-cache` in that all subsequent steps operate with no cache
- If no artifact is specified, it should use the final image hash from the referenced target (`LOCALLY` targets not supported)
- If artifacts are specified, perform a value comparison over the artifact file or directory

I think that this adds the right level of control and is a bit more literate than `COPY` or `DEPENDS ON`

**Comment by vladaionescu** [comment]
Closing in favor of a new EVAL construct.
