### ISSUE TITLE
Slack invite page does not work

### ISSUE THREAD

**Issue by flupke** [earthly/earthly#876]
https://earthly.dev/slack

![image](https://user-images.githubusercontent.com/188962/111897401-0dcc2000-8a20-11eb-869e-aa24a145913b.png)

The [link in the README](https://join.slack.com/t/earthlycommunity/shared_invite/zt-ix9rtuv8-DUFl8uxe5bFULxyCGGbqJQ) does not work either:

![image](https://user-images.githubusercontent.com/188962/111897475-5daae700-8a20-11eb-841f-5dc1c0cbe4a5.png)

**Comment by agbell** [comment]
Hi, Looks like our redirect is broken.  We are looking into it.
This is the link:
https://join.slack.com/t/earthlycommunity/shared_invite/zt-n5vw7fw6-7inWcey3_UNkx0FOm3bQBA

**Comment by agbell** [comment]
redirect is working. Readme update to follow

**Comment by agbell** [comment]
The links have been updated. I did not find a link in the readme that went directly to slack. @flupke did you find it in an old revision of the readme?
