### ISSUE TITLE
Why are my stdout messages not being streamed?

### ISSUE THREAD

**Issue by impredicative** [earthly/earthly#899]
Is there any reason why earthly is not streaming my application's stdout messages as they happen? This makes earthly much worse than just using docker (which does reliably stream stdout). What do I need to do to reliably see stdout logs immediately as my application prints them?

Verbose mode (`-V`) doesn't help at all with this either, although no such mode should even be necessary for it.

**Comment by vladaionescu** [comment]
Hi @impredicative - do you have a specific example that you can share to help us with debugging? We're not aware of this being an issue.

**Comment by vladaionescu** [comment]
Is it a single line being updated constantly? Or multiple lines being added?

We need something to go on to figure out a way to reproduce this.

**Comment by impredicative** [comment]
Batches of lines are being printed with sleeps in between. It is a long running Python application that is just using `print()`.

**Comment by impredicative** [comment]
This kind of problem doesn't manifest on its own. There is some strange buffering going on in the earthly code.

**Comment by impredicative** [comment]
Eventually the messages are displayed. The delay seems to be random, and can be many minutes. The delay seems to vary greatly from one run to another.

**Comment by axzfkdpmrzrheue** [comment]
> Python application that is just using print()

@impredicative `print` could delay a flush. Use `logging`.
