### ISSUE TITLE
Required ARGs

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#904]
Some UDCs (or even targets) could benefit from strictly required ARGs - ARGs that must be passed in, in order for the command (or target) to work.

This helps eliminate cases where the user is chasing their tail trying to figure out what's wrong when an ARG is unexpectedly set to `""` when declared as `ARG something` and no value is provided on the call itself.

Sytanx suggestion:

```
ARG --required something
```

Required ARGs can never have a default value.

CC @jazzdan

**Comment by alexcb** [comment]
This might be a good first issue if anyone wants to take it on. We would need a new struct for ARG options under https://github.com/earthly/earthly/blob/main/earthfile2llb/flags.go

then, under `func (i *Interpreter) handleArg(ctx context.Context, cmd spec.Command) error {`, one would have to reference the struct to parse the opts. then if the required flag is set, check the value is not empty.

**Comment by alexcb** [comment]
this has been released and is available under `v0.6.0`.
