### ISSUE TITLE
Usage Question: Exposing Ports - Running a temporary service

### ISSUE THREAD

**Issue by MatthiasScholzTW** [earthly/earthly#917]
# Summary

How to use `earthly` to run some build steps as a service?
This would require exposing ports on the local development machine.

# Background

I am currently evaluating `earthly` as a build and local development ecosystem to provide developers a consistent experience without the need to install build dependencies locally. It seems `earthly` is a great fit so far.

One use case I can not figure out how to make it work to fully support a local development environment:
For frontend development we make use of Storybook. A tool which provides a web service in order to check your component appearance manually. Of course this is not the TDD approach nevertheless it provides a convenient way to check and diagnose problem since it provides a way to embed the component with additional eventing support.

In order to run this service I wrote this step:

```
storybook:
  FROM +src
  COPY .storybook .storybook
  COPY storybook-static storybook-static
  EXPOSE 6006
  RUN npm run storybook
```

It runs the storybook service, but of course the exposed port is not exposed to the host system.
Maybe I missed a configuration option to make this happen, or it is a use case (currently) not supported by `earthly`.

A workaround I can currently only think of is building a container and executing this container afterwards.
Unfortunately this would drop lead to some scripting aside of `earthly` which I want to avoid.

Any suggestion will be appreciated, thanks!

# Disclaimer

This use case might not be in the usage scope of earthly.
Since it is intended to be a build tool.
Nevertheless it seems very close in order to support this
and would fit well in the hybrid world of supporting local development environment.

**Comment by alexcb** [comment]
Thanks for the question @MatthiasScholzTW 

You're on the right track with the workaround you thought of. We're currently working on a feature to run code locally (via the LOCALLY target), which will avoid having to write a wrapper around earthly.

The LOCALLY feature is currently experimental; however the following should work with the latest (v0.5.9)

here's a quick example I put together with running a simple flask app:

```
baseflaskcontainer:
    FROM python:3.8-alpine
    RUN pip install flask
    
myflaskcontainer:
    FROM +baseflaskcontainer
    WORKDIR /code
    COPY --dir src .
    ENV FLASK_APP "/code/src/server.py"
    CMD ["flask", "run", "--host=0.0.0.0"]
    SAVE IMAGE myflaskcontainer:dev

dev:
    LOCALLY
    RUN earthly +myflaskcontainer
    RUN docker run --rm -p 5000:5000 myflaskcontainer:dev
```

The hacky part with the above example is the `RUN earthly +...` which will run a second instance of earthly. We're currently working on removing that requirement, and once it's done, we will eventually be able to do something like this instead:

```
dev:
    LOCALLY
    WITH DOCKER --load +myflaskcontainer
        RUN docker run --rm -p 5000:5000 myflaskcontainer:dev
    END
```

**Comment by MatthiasScholzTW** [comment]
Thanks a lot for the quick reply!

I adapted the workaround you suggested with the help of the example you provided and it works in my context as well. :)
Looking forward to the new feature release.

For reference this is how it looks like now:
```
storybook:
  FROM +src
  COPY .storybook .storybook
  COPY storybook-static storybook-static
  EXPOSE 6006
  CMD ["npm", "run", "storybook"]
  SAVE IMAGE storybook:dev

run-storybook:
  LOCALLY
  RUN earthly +storybook
  RUN docker run --rm -p 6006:6006 storybook:dev
```
