### ISSUE TITLE
bootstrap tries (and fails) to get earthly bash completions 

### ISSUE THREAD

**Issue by kidd** [earthly/earthly#923]
Hi. Very promising project! I'm eager to give it a go
It looks like `earthly bootstrap`  tries to find bash completion files.

```
$ wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64
$ mv earthly-linux-amd64 ~/bin/earthly
$ chmod +x ~/bin/earthly
$ earthly bootstrap                                                                                                    
Error: open /usr/share/bash-completion/completions/earthly: permission denied
```

**Comment by vladaionescu** [comment]
Hi @kidd - can you give us some more context about your operating system?

I *think* you just need to do `sudo earthly bootstrap` for `earthly` to have permission to install that.

**Comment by kidd** [comment]
Thanks for the response!

I'll try later with sudo, but it might be interesting to drop the sudo requirement, if it's for non-essential things like autocompletion.

**Comment by vladaionescu** [comment]
Yeah, that might be good for the future. Currently we do start a privileged container to run buildkit. We might be able to rely on rootless buildkit in the future, though, and that will relax the requirements.

**Comment by kidd** [comment]
Just for posterity, in an ubuntu 20.04 it failed until I ran with sudo.
NixOS could run `bootstrap` without sudo though.

Not sure about the details, and now it's too late to try again I guess.

Anyway, now it's installed in both. :)
