### ISSUE TITLE
Output shows up misaligned

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#96]
Sometimes, when the output has some sort of progress bar, earthly does not display it correctly due to the prefix (target name) that it needs to print for every line of the output. This needs to be handled better by Earthly.

Relevant [TODO](https://github.com/earthly/earthly/blob/master/conslogging/conslogging.go#L93) in the code.

#### Example

![Screenshot from 2020-07-08 16-37-18](https://user-images.githubusercontent.com/446771/86980734-82cd2300-c139-11ea-92dc-29c67ba084b3.png)

**Comment by vladaionescu** [comment]
Anything remaining to be done for this @alexcb?

**Comment by alexcb** [comment]
thanks for the poke, this was fixed in https://github.com/earthly/earthly/pull/102
