### ISSUE TITLE
change git protocol from string to new type

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#961]
This might be a nit; but the only thing I would do in addition here is maybe enumerate the protocols to make it clearer down the line. Like:

```
type gitProtocol string

const (
	auto gitProtocol = "auto"
	ssh gitProtocol = "ssh"
        ...
)
```

This would ensure that git protocols stay on the rails? At the very least I would move them into a constants list and name them, the type just helps them only get used where they should be used.

_Originally posted by @dchw in https://github.com/earthly/earthly/pull/960#discussion_r623376019_

**Comment by JosemyDuarte** [comment]
This one seems like a good first issue. Before considering contributing just a couple of clarifying questions: 

1. Do you want `gitProtocol` to be private to `buildcontext` package? Meaning, from [`main.go`](https://github.com/earthly/earthly/blob/aaffd2cc84bf7cb7a9cd7943602ecc44e46b2701/cmd/earthly/main.go#L2863) we will keep using Strings, or what would be the idea?

2. I guess `ssh` is not a feasible name for a variable without renaming [current ssh import](https://github.com/earthly/earthly/blob/aaffd2cc84bf7cb7a9cd7943602ecc44e46b2701/buildcontext/gitlookup.go#L16) or using another name for the variable. How would you proceed in this regard?

**Comment by alexcb** [comment]
@JosemyDuarte That's great if you're willing to tackle this :raised_hands: 

1. I would be inclined to keep it as a private type and continue to pass in protocol as a string to `func (gl *GitLookup) AddMatcher(name, pattern, sub, user, password, suffix, protocol, keyScan string) error {`. Then inside that function we could parse the string value and convert it into a `gitProtocol` type. Keeping it as a string outside this package allows us to continue to define it as a string when we parse the yaml into the `GitConfig` structure. 
I don't think we have any public methods that export the configured protocol; if we do, then the extra complexity might be warranted.

2. How about calling it something like `sshProtocol`, `autoProtocol`, `httpProtocol`, and `httpsProtocol`?

Let us know if you run into any troubles.

Cheers,
Alex

**Comment by JosemyDuarte** [comment]
Perfect. I agree with both ideas. I'll try to have a PR before the end of the week. Thanks!
